### ISSUE TITLE
tab key in database block should jump to next cell

### ISSUE THREAD

**Issue by gotjoshua** [toeverything/blocksuite#1002]
as of (https://blocksuite-git-20230203-example-toeverything.vercel.app/)
hitting tab key tabs the text instead of jumping to the next cell in the row (as expected)

**Comment by joebeijing** [comment]
I found that this conflicts with some of the existing logic:
1. When the cursor is positioned on a Title column, pressing the Tab key should indent one row. If the current row cannot be indented, there will be no response.

2. If the cursor is positioned on a non-Title column, pressing the Tab key will automatically move to the cell on the right side and activate it. However, for fields without input boxes such as Progress field, Check box field, etc, We need a selected state for the cell, I will reach out to the design team to address this.

**Comment by joebeijing** [comment]
In addition, if the up and down arrow keys are pressed, they will move up and down in the same column, similar to the left and right movements of the Tab key. 
However, we need to handle a case where when a Block type such as a Database, Image, or Code Block is at the end of a Page, clicking on the blank space at the end of the Page with the cursor will default to adding a new empty row. When moving down in a Database, it should also be possible to add a new row at the end. Although this can be done using Block Hub, the functionality may not be very intuitive.
And it is important to note that Text Frames in Edgeless do not have blank spaces at the end and therefore do not require any additional processing.

**Comment by zqran** [comment]
Has been achieved by #2665.
