### ISSUE TITLE
Block Hub does not fully respect dark mode

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1024]
fixed at https://github.com/toeverything/blocksuite/pull/946

Text changes colour and becomes unreadable - background colour also needs to respect colour mode.

![Image](https://user-images.githubusercontent.com/4605025/216878488-87c907a1-4891-4ecc-801c-4df5c24232fd.png)

**Comment by thorseraq** [comment]
https://github.com/toeverything/blocksuite/pull/946
