### ISSUE TITLE
https://github.com/toeverything/blocksuite/pull/1056

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1040]
Recored gif is attached.
![2023-02-07 12 23 30 pm](https://user-images.githubusercontent.com/22443345/217148258-bad46ad9-9a6b-4ce2-b65b-515a8b82ac5d.gif)

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/blocksuite/issues/978

**Comment by himself65** [comment]
I'm working on this

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/blocksuite/commit/ee3ee83f6584e9726d59d873a9419cf6c811e8f7
