### ISSUE TITLE
Minify Lit html literal and optimize bundle size

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#1041]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/41265413/217165616-29e1b157-4d68-488e-a6ff-58415824d5d9.png">

see: https://lit.dev/docs/v1/tools/build/

**Comment by doodlewind** [comment]
Hi, BlockSuite is shipping ESM-only packages with only `tsc` transpiled, it doesn't release `dist` bundled artifacts at the moment (see more reasons behind this at https://github.com/toeverything/blocksuite/discussions/756#discussioncomment-4713457).

I'm not sure if it worth the effort adding the bundle step, it may be better to handle the minify part in application build tools. Also, the majority size in the current playground bundle should be Quill, so to optimize bundle size, switching to `packages/virgo` (our Quill alternative) may deliver more significant results.

**Comment by doodlewind** [comment]
Closing as not planned since this may not make too much sense before we add perf benchmark metrics.
