### ISSUE TITLE
Edgeless mode offset

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#1067]
https://user-images.githubusercontent.com/14026360/217407967-0b4de50a-4a5a-4681-98e2-958ff7d3c6b3.mp4

P.S. put the window to your second screen

**Comment by himself65** [comment]
On different screens that have multiple resolution

**Comment by himself65** [comment]
Related https://github.com/toeverything/blocksuite/issues/389

**Comment by doodlewind** [comment]
Also fixed by #1239
