### ISSUE TITLE
it takes a long time for a Code Block to load when inserted into the text

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1079]
![Image](https://user-images.githubusercontent.com/22443345/217713836-15905ef6-9652-4d10-948f-9e2040721341.png)

**Comment by himself65** [comment]
the block services could be loaded once editor has initialized.

**Comment by lawvs** [comment]
Can also load only a common subset of popular languages for faster load times.

ref https://github.com/highlightjs/highlight.js/#es6-modules--import
