### ISSUE TITLE
GitHub merge queue stuck

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#1101]
Upstream: https://github.com/orgs/community/discussions/46757#discussioncomment-4908050

I will disable the merge queue if the bug cannot be fixed in the next business day

**Comment by himself65** [comment]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/14026360/217915398-8b077676-0805-475f-842e-3a1ec82d5148.png">

<img width="835" alt="image" src="https://user-images.githubusercontent.com/14026360/217915457-9414e3ba-3dca-4da2-b33a-610e0906eab9.png">

**Comment by himself65** [comment]
https://github.com/orgs/community/discussions/46757#discussioncomment-4926252

**Comment by doodlewind** [comment]
Closing as not-planned at the moment.
