### ISSUE TITLE
Support `shift` + `enter` for consecutive line break in code block

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1117]
Pressing enter twice will move the cursor out of the code block, so it's inconvenient to input this piece of content at the moment:

```
// two empty line...


```

And this is by design for now. @joebeijing do we have some better strategy on this?

**Comment by joebeijing** [comment]
Still suggest to keep this feature, however we can adjust it to skip out of a block of code by pressing Enter twice, while pressing Shift + Enter will keep it within the block.  @doodlewind How do you think?

**Comment by lawvs** [comment]
This feature is naturally completed :)
