### ISSUE TITLE
Unable to navigate left in slash menu

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#1124]
In addition to "up" + "down" support from keyboard input I would expect to be able to go "left" and navigate the categories. Currently "left" key closes the menu.

![Image](https://user-images.githubusercontent.com/4605025/218046989-64ea6986-78cd-4316-adfc-c1b81f45aac7.gif)

**Comment by lawvs** [comment]
fixed in https://github.com/toeverything/blocksuite/pull/1130
