### ISSUE TITLE
Code block copy does not function as expected

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#1128]
1) Copy paste to the right of the code block I would expect to copy the whole block - but it does not function

2) When copying content from inside the code block it will paste as a code block - I would expect this to only copy the data/string.

![Image](https://user-images.githubusercontent.com/4605025/218044452-5c1285f4-f11b-40d1-9498-1e17b23cf3c8.gif)

**Comment by Himself65** [comment]
please refactor the code with popper.js. the bug will be fixed

**Comment by thorseraq** [comment]
Updated the code block copy and paste behavior：

- Use menu copy button

    - Paste inside the code block, perceptually copying only the text

    - Paste outside the block, perceptually copying the block and inserting a new block after the current block

- Use cv shortcut keys

    - Behavior inside and outside the code block are the same, copy only the text
