### ISSUE TITLE
Format size metrics for real-world use case

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1176]
Due to the nature of CRDT that serializes all historical changes in binaries ([y-protocol](https://github.com/yjs/y-protocols) based) and the extra meta data that are being carried per-block, we need to have a baseline metrics about the real-world binary size, especially when compared with plain-text formats.

**Comment by pengx17** [comment]
No need to have code built in. We can run this ad-hoc script in console to get a preview: https://gist.github.com/pengx17/9b838a0d4afb3b7ac1fb11dd83cf7c01
