### ISSUE TITLE
Image block popup doesn't follow scroll

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1214]
The expected effect is that the menu is at best aligned top-bottom with the border.

![Image](https://user-images.githubusercontent.com/22443345/217264079-db020266-9558-429d-a2ca-921c705bf5d3.png)

**Comment by joebeijing** [comment]
I can reproduce this issue in the test environment.
![Image](https://user-images.githubusercontent.com/22443345/220814824-a637342b-d752-42ae-b9d6-868892dbe399.png)

**Comment by doodlewind** [comment]
Not reproduced in latest playground.
