### ISSUE TITLE
Too large space between image content and the text below

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1215]
I'm guessing this is to reserve space for the Caption, but it shouldn't still be taking up space without the Caption.

![Image](https://user-images.githubusercontent.com/22443345/217262817-c928322c-2c4a-4c8d-a3f0-fe1c870c6408.png)

**Comment by doodlewind** [comment]
> Fix in [blocksuite](https://github.com/toeverything/blocksuite/pull/1240/commits/0b4f03a196fd5a8b056f9c321cd3c94795d87cb1)

@QiShaoXuan please add things like `Close #1215` in PR description next time, this forms bi-directional links between the issue and the PR.
