### ISSUE TITLE
Embed selection rect doesn't follow window resize or scroll

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#1235]

**Comment by Innei** [comment]
https://user-images.githubusercontent.com/41265413/219311532-13f2be03-f48f-40f0-bd8e-b840ac385fa3.mov

https://user-images.githubusercontent.com/41265413/219311607-4fec7668-93ab-49d6-96b7-7b755511970a.mov

**Comment by fundon** [comment]
It will be fixed in #1223.

Both models exist at the same time should not be the expected behavior. See https://github.com/toeverything/blocksuite/pull/1223#issuecomment-1432619074
