### ISSUE TITLE
poor performance with HMR

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#1244]
The HMR feature is incredibly useful. It has saved me a lot of time, especially when adjusting styles.

But I encountered a minor issue during the usage.

If you use the slash menu several times, there is a delay when HMR is activated.

Related to https://github.com/toeverything/blocksuite/pull/621

/cc @fi3ework 

<img width="1073" alt="Screenshot 2023-02-16 at 7 29 06 PM" src="https://user-images.githubusercontent.com/18554747/219353116-51414bff-8298-4bbd-9c52-9984e31ee283.png">

https://user-images.githubusercontent.com/18554747/219352156-348b7989-d189-4f2e-8e31-f20575b95bb7.mov

**Comment by lawvs** [comment]
Also occurs when clicking the language button in the code block.


https://user-images.githubusercontent.com/18554747/220293931-c2a6109d-9645-401c-b839-546fe54aaf3c.mov

**Comment by lawvs** [comment]
I believe it is related to extending `LitElement`

See https://github.com/toeverything/blocksuite/pull/1361

**Comment by doodlewind** [comment]
We've made the HMR command opt-in, so this issue has been mitigated and is not of major concern.
