### ISSUE TITLE
Edgeless selection rect doesn't follow viewport update

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1249]
To reproduce:

1. Create and select a shape.
2. Move the whiteboard (panning or zooming).

The selection rect will be out of sync.

This could be easily fixed by updating the selection rect on `signals.viewportUpdated`.

https://user-images.githubusercontent.com/7312949/219507346-88756c8a-2361-4f22-b311-a2c6ff40433b.MOV

**Comment by lzlme** [comment]
I'm trying to fix this bug, then I found that the setting for the selection width comes from:
```
return {
  // ...
  width: rect.width + (isSurfaceElement ? 0 : PADDING_X) * zoom + 'px'
  // ...
}
```
I noticed that the value of `isSurfaceElement` is always `true` when I zoom, so the value of `width` is always equal to `rect.width`. So, I would like to know what is `surfaceElement` ?
