### ISSUE TITLE
Edgeless selection rect doesn’t follow undo/redo

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1250]
This is similar with #1249 but just triggered by performing undo/redo.

https://user-images.githubusercontent.com/7312949/225053721-d0741d49-bcc8-4088-b9a7-98c07b59f760.mov

**Comment by donglixiaoche** [comment]
@doodlewind @alt1o is there any working on this issue? if no, i'd love to have a try

**Comment by alt1o** [comment]
> @doodlewind @alt1o is there any working on this issue? if no, i'd love to have a try

That's very nice. No one is working on this issue.

**Comment by donglixiaoche** [comment]
> > @doodlewind @alt1o is there any working on this issue? if no, i'd love to have a try
> 
> That's very nice. No one is working on this issue.

copy, so i'm going to work on it. leave a comment here to avoid duplicate working.

**Comment by donglixiaoche** [comment]
@doodlewind for this issue, if a undo case a selected shape object deleted, and then, if we use redo to recreate this shape object, do we need to reselect this shape object either?

**Comment by regischen** [comment]
@donglixiaoche yes, need to reselect this element. 
by the way, are you still working on it?

**Comment by donglixiaoche** [comment]
@regischen previously i dicussed with @doodlewind, seems like this work requires more wokrs than i thought. i thought we should make selection status works like cursor, and share them between multiple clients. i'd love to continue, but seems like we need some product design first

**Comment by donglixiaoche** [comment]
> @donglixiaoche yes, need to reselect this element. by the way, are you still working on it?

or do you think if i can help to design this feature? need some investigation, it may take some time, and also i may need some help about the architecture of this whole blocksuite project

**Comment by Flrande** [comment]
This issue is waiting for the reconstruction related to selection.
cc @doodlewind
