### ISSUE TITLE
Remove redundant re-render on mouse move

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1258]
Currently BlockSuite will re-render the block tree components on mouse move (this is triggered by `requestUpdate`). But due to the setup of `model` property in Lit block components, the `hasChanged` guards are not functioning properly.

We need a more fine-grained mechanism to incrementally update the affected block components.

**Comment by lawvs** [comment]
Setting the `hasChanged` to always return true is not a correct approach, as it leads to recalculating the template every time the parent node renders the current component.

Adding listeners to the model is a better option, but it is not a long-term solution.

Is there a way to adjust the model to an Immutable model, so that Lit can automatically update on property changes?

```ts
  // set `hasChanged` always return true is incorrect!!
  @property({ hasChanged: () => true })
  model!: PageBlockModel;

  @state()
  private _disposableGroup = new DisposableGroup();

  override connectedCallback() {
    super.connectedCallback();
    this._disposableGroup.add(
      this.model.propsUpdated.on(() => this.requestUpdate())
    );
    this._disposableGroup.add(
      this.model.childrenUpdated.on(() => this.requestUpdate())
    );
  }

  override disconnectedCallback() {
    super.disconnectedCallback();
    this._disposableGroup.dispose();
  }
```

**Comment by pengx17** [comment]
> Is there a way to adjust the model to an Immutable model, so that Lit can automatically update on property changes?

I think one solution may be to use smaller lit components, instead of using rendering functions? E.g. for `DefaultPageBlockComponent`, it has several big rendering functions in `render`:

```js
  render() {
    const { page, selection } = this;
    const { viewport } = selection.state;

    const childrenContainer = BlockChildrenContainer(this.model, this, () =>
      this.requestUpdate()
    );
    const draggingArea = DraggingArea(this._draggingArea);
    const selectedRectsContainer = SelectedRectsContainer(
      this._selectedRects,
      viewport
    );
    const selectedEmbedContainer = EmbedSelectedRectsContainer(
      this._selectedEmbedRects,
      viewport
    );
    const embedEditingContainer = EmbedEditingContainer(
      page.readonly ? null : this._embedEditingState,
      this.slots,
      viewport
    );
    const codeBlockOptionContainer = CodeBlockOptionContainer(
      page.readonly ? null : this._codeBlockOption
    );

    return html`
      <div class="affine-default-viewport">
        <div class="affine-default-page-block-container">
          <div class="affine-default-page-block-title-container">
            <div
              data-block-is-title="true"
              class="affine-default-page-block-title ${!this._titleContainer ||
              this._titleContainer.innerText === ZERO_WIDTH_SPACE
                ? 'affine-default-page-block-title-empty'
                : ''}"
            ></div>
          </div>
          ${childrenContainer}
        </div>
        ${selectedRectsContainer} ${draggingArea} ${selectedEmbedContainer}
        ${embedEditingContainer} ${codeBlockOptionContainer}
      </div>
    `;
  }
```

The `BlockChildrenContainer` etc calls will effectively make the render function return a big template, but I think it maybe optimized by converting them into lit components?

**Comment by pengx17** [comment]
Ah, it seems that we have already utilized the built-in directive 'repeat' with keys to avoid list re-rendering. However, one significant issue is that we may have overused the hasChanged prop in '@property'. After we removed `hasChanged` in #1550 , re-rendering issue is much alleviated.
