### ISSUE TITLE
Support Whiteboard with basic usability

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#1268]
## Features
* https://github.com/toeverything/blocksuite/issues/496
* https://github.com/toeverything/blocksuite/issues/374
* #1282

## New element support
* https://github.com/toeverything/blocksuite/pull/1104

## Phasor support
* https://github.com/toeverything/blocksuite/pull/837
* https://github.com/toeverything/blocksuite/pull/809
* https://github.com/toeverything/blocksuite/pull/808
* https://github.com/toeverything/blocksuite/pull/775
* https://github.com/toeverything/blocksuite/pull/746
* https://github.com/toeverything/blocksuite/pull/740
* https://github.com/toeverything/blocksuite/pull/664

**Comment by doodlewind** [comment]
Closing in favor of our next goal #1282
