### ISSUE TITLE
Edgeless frame content overflow

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1288]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/7312949/220001695-ec9b8ac1-b09a-45be-bc3b-9a3274cbe05f.png">

**Comment by zqran** [comment]
And,

<img width="117" alt="image" src="https://user-images.githubusercontent.com/15389209/220064472-559d0596-397f-40d7-ae1c-c74f326614d3.png">
