### ISSUE TITLE
Shifted selection box position for shape element

### ISSUE THREAD

**Issue by lzlme** [toeverything/blocksuite#1293]
I have the same problem with `https://blocksuite-toeverything.vercel.app/?init` and local build attempts, but it works fine in `app.affine.pro`.

https://user-images.githubusercontent.com/117659326/220044440-f9f51173-c8bb-4097-aad3-f9fc35440579.mov

**Comment by doodlewind** [comment]
I had a bit trouble reproduce this. Is this only happens on pages that contains vertical scroll bar?

**Comment by lzlme** [comment]
> I had a bit trouble reproduce this. Is this only happens on pages that contains vertical scroll bar?

Yes, when I build locally, select "Empty Editor" or some other example, then switch editor mode to edgeless, and a vertical scroll bar will appear.
I found that it's a css problem, adding `display: block` to `.affine-surface-canvas` or adding `display: flex` to `.affine-edgeless-surface-block-container` will fix it.
How about I create a PR ?

**Comment by doodlewind** [comment]
This may be fixed by #1299 in our latest master, could you give it another try?

**Comment by lzlme** [comment]
> This may be fixed by #1299 in our latest master, could you give it another try?

No solution yet. I have tried the following:
- macbook pro with m1 pro: reproduced
- macbook air 2017: reproduced
- lenovo windows laptop: reproduced
- thinkpad windows laptop: reproduced
- windows desktop (2k monitor): reproduced
But:
- macbook pro with **external 4k monitor**: normal, can't reproduce.

I wonder if the problem is with the external monitor ? Can you try using only the built-in screen of your macbook?

**Comment by lzlme** [comment]
> This may be fixed by #1299 in our latest master, could you give it another try?

Still not working, I tried multiple devices (different OS, different versions, different browsers), some can reproduce but some cannot.

**Comment by lzlme** [comment]
@doodlewind 
This problem was fixed in passing by #1381.
But, let's dig a little deeper, #1381 only superficially fixes the problem, but it doesn't solve the root problem. It only sets the overflow to `hidden`, but it doesn't consider why there is content overflow.
The real reason is that the `.affine-surface-canvas` and its container `.affine-edgeless-surface-block-container` are both `height: 100%`, and their computed heights are same, but the canvas has two key default styles `display: inline; vertical-align: baseline;`, so there is a **descender space** inside the`.affine-edgeless-surface-block-container`, which causes an overflow and triggers the vertical scroll. So the correct root solution is to add `display: block;` to `.affine-surface- canvas`.
[StackOverflow - Why is there a vertical scroll bar if parent and child have the same height?](https://stackoverflow.com/questions/36974514/why-is-there-a-vertical-scroll-bar-if-parent-and-child-have-the-same-height)
