### ISSUE TITLE
Support ```[lang] to add code block with language

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#1314]
Feature request:

When typing ```ts , a code block is generated, and its default language is typescript.

**Comment by lawvs** [comment]
Using markdown to create a code block is supported in blocksuit, but it needs extra space to trigger convert now

https://user-images.githubusercontent.com/18554747/220298722-51d8ea45-bbc9-4e58-958d-06ab3e679e1c.mov

**Comment by zqran** [comment]
Yes, but my point is: "When typing **```ts** , a code block is generated, and its **default language is typescript**"

**Comment by zqran** [comment]
I implemented it, but there is one point that needs to be discussed:

For example, when I input ` ```ts `, the default language of the generated code block is: `ts`, and the corresponding language name in the language list is `TypeScript`.

Is there a mapping required for `ts` => `TypeScript`, also used in other languages.
