### ISSUE TITLE
Unable to use tab key when editing in code block

### ISSUE THREAD

**Issue by kvsur** [toeverything/blocksuite#1317]
![https://d2y5h3osumboay.cloudfront.net/1dutmzlbbrqqoorae9lwtfwyzkoh](https://d2y5h3osumboay.cloudfront.net/1dutmzlbbrqqoorae9lwtfwyzkoh)
﻿After keydown， it look like this：

![https://d2y5h3osumboay.cloudfront.net/dt9ipypxasl9dffbaceqh1higl7u](https://d2y5h3osumboay.cloudfront.net/dt9ipypxasl9dffbaceqh1higl7u)

﻿
﻿Whole Code Block offset 😅

Here is my device:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/13591479/220348469-f0e03d0c-06f7-4fc1-bea8-b20336106aa3.png">
<img width="323" alt="image" src="https://user-images.githubusercontent.com/13591479/220348572-22a52eae-82a4-40ca-9e60-3b6636494523.png">

**Comment by lawvs** [comment]
Thanks for your feedback! We have fixed the issue you reported in  https://github.com/toeverything/blocksuite/pull/1295
