### ISSUE TITLE
Fix `getDefaultPageBlock` typing issue and support edgeless mode

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#1341]
The `getDefaultPageBlock` function has an unsafe type. It returns `DefaultPageBlockComponent | EdgelessPageBlockComponent | null`, but is typed as `DefaultPageBlockComponent`.

This will break edgeless mode, so we need to design a new API to get `DefaultPageBlockComponent` and distinguish between page and edgeless mode.

https://github.com/toeverything/blocksuite/blob/dd801b5d28d82ba3f5786892e5b4538a903cd9c8/packages/blocks/src/__internal__/utils/query.ts#L132-L144

**Comment by zqran** [comment]
Can it be distinguished by the `flavor` attribute? just like:

```ts
export function getDefaultPageBlock(model: BaseBlockModel) {
  assertExists(model.page.root);
  const page = document.querySelector(
    `[${ATTR}="${model.page.root.id}"]`
  ) as NonShadowLitElement;

 // check default page
  if (!_checkDefaultPageBlock(page)) {
    throw new Error(
      'Failed to get default page block, page id: ' + model.page.root.id
    );
  }
  return page;
}

function _checkDefaultPageBlock(
  page: NonShadowLitElement
): page is DefaultPageBlockComponent {
  return 'flavour' in page;
}
```

**Comment by lawvs** [comment]
> Can it be distinguished by the flavor attribute?

Thank you very much for your suggestion. The method you proposed is correct.

However, we have heavily relied on this function in our project, and many features depend on this flawed function. Therefore, we cannot simply replace it with a correct version at the moment.

I believe designing a function that is intuitive and easy to use and gradually replacing it is a better option.
