### ISSUE TITLE
heavy page hangs

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#1354]
<img width="468" alt="Screenshot 2023-02-24 at 3 52 06 PM" src="https://user-images.githubusercontent.com/27926/221122702-ece27458-ebc8-44f0-85c8-7747bc857028.png">

<img width="631" alt="Screenshot 2023-02-24 at 4 03 36 PM" src="https://user-images.githubusercontent.com/27926/221125105-29339e8d-5600-4a13-af7b-e9e0e2b5424e.png">

**Comment by doodlewind** [comment]
Should be fixed by #1397
