### ISSUE TITLE
When select cross block range, delete not work correctly after some operation.

### ISSUE THREAD

**Issue by Saul-Mirone** [toeverything/blocksuite#1364]
1. Select a cross block range.
2. Use `tooltip` to add bold style for selected text.
3. Press `delete`, only some parts of the selected text will be deleted.

https://user-images.githubusercontent.com/10047788/221338521-9e058822-2b55-4cf9-a4db-300ea48cbf46.mp4

**Comment by Flrande** [comment]
cc? @lawvs

**Comment by doodlewind** [comment]
I think the screen recording was not uploaded successfully 🥶

**Comment by Saul-Mirone** [comment]
> I think the screen recording was not uploaded successfully 🥶

I've reuploaded it.

**Comment by Saul-Mirone** [comment]
I also noticed that this issue cannot be reproduced in virgo playground.
