### ISSUE TITLE
Remove title padding top

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#1371]
https://affine-next.vercel.app/preview/Welcome-to-AFFiNE-Alpha-Downhills

![6875DD4F-7DAF-4E96-B417-400E57837569](https://user-images.githubusercontent.com/14026360/221349377-aacc5ce8-0b37-4934-845b-3610b2f9263d.jpeg)

**Comment by zqran** [comment]
Isn't it `margin-top`?

**Comment by himself65** [comment]
typo

**Comment by zqran** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/15389209/221351287-07506708-17dd-4753-a4c1-2f819e3212e6.png">

After updating the `margin-top`, the title may be covered by the debug-menu, does the BlockSuite playground need to add some styles?
