### ISSUE TITLE
Cursor doesn't go to the end of the line for line-breaks

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/blocksuite#1382]
This is how it currently works:

https://user-images.githubusercontent.com/70709113/221417206-e658b6d3-e711-495b-8f60-27945bbf5eeb.mp4

as you can see, the cursor does not go to the end of the line. This is how I expect it to work:

https://user-images.githubusercontent.com/70709113/221417243-281820ae-9813-4830-9576-aeb22f4f095d.mp4

**Comment by Flrande** [comment]
It seems that this problem has been fixed. : )
