### ISSUE TITLE
Select using triple-click to select entire paragraph

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/blocksuite#1383]
How it currently works:

https://user-images.githubusercontent.com/70709113/221417325-7bae0ee6-5840-4a88-89bf-4805ed025cda.mp4

How I expect it to work:

https://user-images.githubusercontent.com/70709113/221417342-4191647d-978f-4cd4-ba00-5148128f3e48.mp4

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/2037
