### ISSUE TITLE
After selecting the image, the bounding box will scroll along with the page.

### ISSUE THREAD

**Issue by luke358** [toeverything/blocksuite#1391]
https://user-images.githubusercontent.com/48149577/221463232-b9485130-c77e-483b-9c72-a7ec1dbddbe9.mov

**Comment by luke358** [comment]
https://user-images.githubusercontent.com/48149577/221463810-11812ef0-a76d-4a60-ac0c-3cdb68c53de8.mov

**Comment by luke358** [comment]
https://user-images.githubusercontent.com/48149577/221463901-783af870-4f0f-4733-88b8-dfbddef4a1db.mov

And if scaled, the background color will not disappear.

**Comment by fundon** [comment]
This should be fixed in #1300. 

Did you test on the latest version?

**Comment by luke358** [comment]
> This should be fixed in #1300.
> 
> Did you test on the latest version?

Yeah,It's latest.I have only found this problem on Image so far.

**Comment by doodlewind** [comment]
Closed as not reproduced during housekeeping
