### ISSUE TITLE
Cannot delete code block when using select all shortcut

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#1394]
In a code block, use cmd+A to select the block, you cannot press the backspace key to delete the block.
In addition, the blue selection still exists after deletion.

https://user-images.githubusercontent.com/102217452/221497872-48130817-2e7b-45e5-8e75-a8f2cc25cdea.mov

**Comment by lawvs** [comment]
I believe this issue has already been fixed. Please feel free to reopen if you can reproduce it.
