### ISSUE TITLE
Unable to start the react next.js example

### ISSUE THREAD

**Issue by awmleer** [toeverything/blocksuite#1398]
复现方式：

1. clone 这个 repo
2. 进入目录 `packages/react/examples/next`
3. `pnpm install`
4. `pnpm dev`

然后打开 Next.js 启动的页面，会看到这样的报错：

<img width="936" alt="image" src="https://user-images.githubusercontent.com/16526078/221530725-c8a57199-7a2c-4bac-983e-9307580e978b.png">

**Comment by himself65** [comment]
I'm working on this
