### ISSUE TITLE
blocksuite workspace API in non browser environment

### ISSUE THREAD

**Issue by pengx17** [toeverything/blocksuite#1430]
When working with Blocksuite/Octobase, there are several interfaces the users could interact with the "data" for usage outside of AFFiNE
- in AFFiNE / Blocksuite, users have the option to export to HTML/Markdown and have access to yDoc instance and export yDoc binary.
- with Octobase public API, users can get the yDoc binaries and blobs by giving the correct tokens

However, there are some _limitations_ of each right now:
- data exporter in AFFiNE / Blocksuite can only work in the browser environment
- Octobase public API only provides raw data for Blocksuite

These _limitation_ is not a big deal if the content in AFFiNE is only to be used in AFFiNE app. We also want to have an open platform that allows the user to use AFFiNE to render a snapshot of the data onto other media, such as their personal blogs.

What we can do here is to have a set of APIs that allows the user to fetch their blocksuite data in their desired format (such as markdown) via API.

There is a unofficial library [affine-reader](https://github.com/pengx17/affine-reader) that could part of the job. However, I believe some of the functionalities should be prebuilt in blocksuite, such as converting yDoc into Markdown in a headless environment.

There is also [affine-ghost](https://github.com/tzhangchi/AFFiNE-ghost/blob/master/tests/index.spec.ts) which can import documents into app.affine.pro with Playwright. We may consider this use case as well.

cc @doodlewind

**Comment by doodlewind** [comment]
The usage of `@blocksuite/store` under Node environment is actually supported since #2178, and we'll open new issues for further extension-related development.
