### ISSUE TITLE
Support dragging and dropping single or multiple images from outside the browser into the editor for adding

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1447]
This is a very natural way to add local images to the AFFiNE editor. We hope it can be supported based on feedback from the community.

**Comment by himself65** [comment]
I think this is a feature that is related to BlockSuite. even though affine could do this, but

**Comment by darkskygit** [comment]
I put some thoughts about implementation details:
1. we should provide a more general drag scheme that allows the accept any content(file/text/image/any others) and the display of its insertion position through DragIndicator.
2. allow to register some handler, accept specific types of content, and process the dragged-in content to decide whether to insert it into the position specified by the indicator
3. write a handler that accept the drag-in image, and inserts an image block after processing (I think this part can be implement in affine)

**Comment by doodlewind** [comment]
This will be handled by @Saul-Mirone since it requires some architecture-level design to make it extensible.
