### ISSUE TITLE
Support selecting multiple blocks by holding down the Shift key

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1453]
This allows selecting related blocks in one go, based on the starting block where the cursor is located and the final block where the click occurs.

**Comment by fundon** [comment]
The native behavior is to select the text. Is this text(native) or block.

**Comment by doodlewind** [comment]
@fundon if we are already under block level selection, it will be great if shift + click can select more blocks.

**Comment by fundon** [comment]
* native selection
* block selection

**Comment by doodlewind** [comment]
Closed by #2280
