### ISSUE TITLE
Support cursor with format in virgo

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#1456]
Due to the lack of support for quill in cursor marks, we utilized `quill.on` to achieve our need for inline code escaping. 

However, this solution caused several issues, it caused the status of quill and Ytext to be out of sync.

As a result, we hope that the virgo can support cursor marks.

This is similar to the concept of a Mark in prosemirror

Related to https://github.com/toeverything/blocksuite/issues/415 https://github.com/toeverything/blocksuite/issues/1319 https://github.com/toeverything/blocksuite/issues/1184

**Comment by doodlewind** [comment]
Sounds fair! Added into #1219 roadmap

**Comment by doodlewind** [comment]
Closed since we've landed Virgo fixing the issues mentioned above.

**Comment by lawvs** [comment]
Virgo resolves this issue by not inheriting any existing styles during input. 

However, this causes problems when users want to maintain the previous formatting while entering text.
