### ISSUE TITLE
Refactor default selection manager

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1480]
We should consider re-organize its code structure, since the maintainability is concerning.

Before refactoring lands, recent features, optimizations and non-incremental fixes on selection manager may better be postponed.

/cc @fundon @lawvs @Himself65 

Progress
* #1494 
* #1496 
* #1500 
* #1502
* #1503 
* #1506 
* #1507 
* #1511 
* #1512 
* #1519

**Comment by fundon** [comment]
Here are some of my thoughts:

1. Binary search may not be needed, use `document.elementFromPoint` instead of
2. Block cache may not be needed either
3. Grouping dom manipulations into a single file
4. For view updates, execute `requestUpdate` all at once after batching

**Comment by lawvs** [comment]
I intend to extract the `CodeBlockOption` and `EmbedEditingState` from both the `selection-manager` and `default-page-block`.

These two parts should be controlled internally by the corresponding block.

![Screenshot 2023-03-05 at 2 42 32 AM](https://user-images.githubusercontent.com/18554747/222923322-72599ed0-b60e-4037-8d70-a435ac271623.png)

**Comment by doodlewind** [comment]
> I intend to extract the `CodeBlockOption` and `EmbedEditingState` from both the `selection-manager` and `default-page-block`.
> 
> 
> 
> These two parts should be controlled internally by the corresponding block.
> 
> 
> 
> ![Screenshot 2023-03-05 at 2 42 32 AM](https://user-images.githubusercontent.com/18554747/222923322-72599ed0-b60e-4037-8d70-a435ac271623.png)
> 
> 

Sounds fair, is there ongoing PR?

**Comment by doodlewind** [comment]
Considered completed in 0.5
