### ISSUE TITLE
Hovering the frame selection over a shape will cause the shape to move along with it

### ISSUE THREAD

**Issue by PerfectPan** [toeverything/blocksuite#1485]
The problematic code is https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/page-block/edgeless/mode-controllers/default-mode.ts#L196.

https://user-images.githubusercontent.com/24316656/222885279-3b548953-b1b2-4045-aeb7-e9606bc4c273.mp4

The shape element should not move when the selected state is inactive.

However, using frame selection over two elements is not currently supported in this mode. We can only select one element at a time. So, it may be better to solve the problems together.

**Comment by doodlewind** [comment]
Should be closed by #1488, thanks for your feedback!
