### ISSUE TITLE
Move `Slot.disposableListener` to `disposableGroup.addListener`

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#1518]
Based on our current use cases, I recommend renaming `Slot.disposableListener` to `disposableGroup.addListener` to improve ease of use. `addListener` is just an optional name and any better suggestions are welcome.

```ts
const _disposableGroup = new DisposableGroup();

// Before
disposableGroup.add(
  Slot.disposableListener(this, "mouseover", (e) => {
    this.hoverState.emit(true);
  })
);

// After
disposableGroup.addListener(this, "mouseleave", (e) => {
  this.hoverState.emit(false);
});

```

/cc @doodlewind

**Comment by doodlewind** [comment]
Semantically we should add a `Disposable` to `DisposableGroup`, so the `add` method sounds accurate - open to some sugar here! But the `disposableListener` has just been removed, so we won't have the `listener` concept in our slot API.
