### ISSUE TITLE
regression on reading experience in mobile comparing to `0.4.0-20230217095654-a561b36`

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#1528]

**Comment by himself65** [comment]
https://user-images.githubusercontent.com/14026360/223281577-3429e746-1a63-430e-adb1-7ce2537f0a77.mp4

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/blocksuite/commit/00f385e45c34cc1278daa93b953aae75827eca44
