### ISSUE TITLE
Cursor line appears at unexpected position

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/blocksuite#1606]
as I grab the green one downward, the cursor line with the colour of red one appears at the upper position
![110d0cd9-3f7f-4a47-9602-bfa30401e64f](https://user-images.githubusercontent.com/121489905/223930795-e17e639b-4d67-4b08-864e-ef85bab4bf60.jpeg)

**Comment by JackiePengp** [comment]
yes, i just realized the video didn't upload successfully, will edit it right away

**Comment by joebeijing** [comment]
Can not repoduce it
