### ISSUE TITLE
Should not need to press enter twice to exit Quote format

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1645]
The expected behavior is that pressing Enter in an empty line within a Quote will exit the Quote mode just like the recored video.

https://user-images.githubusercontent.com/22443345/224267256-60692cc5-7414-4ec8-8d44-abb2601dbc25.mp4

**Comment by lawvs** [comment]
Does https://github.com/toeverything/blocksuite/pull/1624 meet the requirements?

**Comment by Flrande** [comment]
Fixed in #1624
