### ISSUE TITLE
Broken example links in README.md

### ISSUE THREAD

**Issue by suica** [toeverything/blocksuite#1667]
The following links seem to be broken:

- [Nightly Playground](https://blocksuite-toeverything.vercel.app/?init) ([🔗 source](https://github.com/toeverything/blocksuite/blob/master/packages/playground/src/main.ts))
- [The SimpleAffineEditor Example](https://blocksuite-toeverything.vercel.app/examples/basic/) ([🔗 source](https://github.com/toeverything/blocksuite/blob/master/packages/playground/examples/basic/index.html))

**Comment by doodlewind** [comment]
Can you visit the https://blocksuite-toeverything.vercel.app/?init playground?

**Comment by suica** [comment]
@doodlewind Now it works perfectly : )
