### ISSUE TITLE
code block index gap miscalculation

### ISSUE THREAD

**Issue by HavanaLee** [toeverything/blocksuite#1675]
<img width="549" alt="屏幕截图 2023-03-12 193058" src="https://user-images.githubusercontent.com/44768938/224541733-7ca33ed2-ef76-4862-ac11-e5779d68be49.png">

when i use affine doc

**Comment by HavanaLee** [comment]
<img width="691" alt="屏幕截图 2023-03-12 193532" src="https://user-images.githubusercontent.com/44768938/224541966-556937e6-86d5-49f2-bf36-38504cf483e3.png">

devtools [error message](javascript:;)

**Comment by doodlewind** [comment]
Thanks for your report! This should be fixed by #1692
