### ISSUE TITLE
Paste in code block can't delete the selection

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#1676]
Is this expected behavior?

https://user-images.githubusercontent.com/15389209/224551850-c86bf91f-703e-4d05-b3f3-bd0aad9472b9.mov

In my opinion, the following way is more intuitive:

https://user-images.githubusercontent.com/15389209/224552175-651ebe97-2eb4-4937-8765-99f39b2f782c.mov

**Comment by doodlewind** [comment]
I think the latter one should be expected, this looks like a regression after switching to virgo.

**Comment by zqran** [comment]
This has been fixed in #1687.
