### ISSUE TITLE
There are three scenarios where Balloon Toolbar does not appear when selecting a Block

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1677]
1. Clicking on the Drag Handle to select a Block
2. Clicking on the icon in front of a List to select a Block
3. Deleting a Code Block below will select that Code Block.

**Comment by lawvs** [comment]
There is a new scenario that needs to be dealt with now

See https://github.com/toeverything/blocksuite/pull/2037

**Comment by doodlewind** [comment]
Closing this since 1 is fixed and 3 is a non-goal. We'll track 2 in #3461
