### ISSUE TITLE
Support keyboard operation to move Block up or down

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#1686]
This is a supplement to a very small editing operation, with the aim of ensuring the functional scope of mouse and keyboard operations are as equal as possible.

(1) Shortcut key format
⌘/ctrl + ⌥/Alt + ↑  Move Up
⌘/ctrl + ⌥/Alt + ↓  Move Down

(2) Slash Commands
Add Move Up and Move Down to the Action in the Slash Commands, and place these two options at the top of the Action area.

(3) Add corresponding explanations in the shortcut key instructions
This is located at the end of Keyboard Shortcuts, with attention given to distinguishing between Mac and Windows.
![CleanShot 2023-03-13 at 6 20 35@2x](https://user-images.githubusercontent.com/22443345/224674877-ea3137c9-5c2a-47c6-83a0-cb1af815a0f7.png)

Additionally, the cursor remains at the original position of the manipulated Block after it has been moved.

**Comment by adityash1** [comment]
@doodlewind can i work on this ?

**Comment by doodlewind** [comment]
@adityash1 sure, feel free to give it a try.
