### ISSUE TITLE
Support bookmark block

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1707]
This is used as a card-like-view for bi-directional links and subpage links.

This is not assigned yet. We may reassign according to our progress.

**Comment by joebeijing** [comment]
[Internal doc](https://toeverything.feishu.cn/wiki/wikcnPaZqsirXqTF4ZxQc25NMNd)

**Comment by doodlewind** [comment]
Closing in favor of https://github.com/toeverything/blocksuite/issues/2574
