### ISSUE TITLE
Support dragging block outside of frame in whiteboard

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1709]
This would allow:

* [x] Dragging blocks (with drag handle) out of the frame, inserting it into a new frame.
* [x] Dragging blocks (with drag handle) out of the frame, inserting it into an existing frame.

**Comment by joebeijing** [comment]
@fundon

**Comment by fundon** [comment]
@joebeijing Does it support selecting multiple blocks and moving them, just like Page mode?

**Comment by joebeijing** [comment]
@fundon This is indeed something that needs support. However, currently in Edgeless, it is not possible to select multiple blocks at once. Once the support for selecting multiple blocks is available, for example, through keyboard shortcuts, it can be dragged out. So, we can leave this issue for later.

**Comment by fundon** [comment]
In Edgeless, the space is too small and there are several selections, frame, block, text.

**Comment by joebeijing** [comment]
Yes, it's currently not possible to select multiple blocks by dragging outside of the editing area, but in the future you can use some shortcuts, such as holding down the ⌘ or Shift key and clicking on a block with the mouse to select a specific block.

**Comment by doodlewind** [comment]
@joebeijing I think this will be mainly handled by @alt1o soon 👀

**Comment by doodlewind** [comment]
Landed in https://github.com/toeverything/blocksuite/pull/1736
