### ISSUE TITLE
the scaling label font of the whiteboard global toolbar is not consistent with the editor

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#1733]
I found that the scaling label font of the whiteboard global toolbar is not consistent with the editor. Does this detail need to be unified? @joebeijing @alt1o  If so, is the default font configured in the editor global

before consistent

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/5910926/225586075-3b408195-4c22-4c05-b721-cc5ba99cd33a.png">

after consistent

<img width="1561" alt="CleanShot 2023-03-16 at 18 12 24@2x" src="https://user-images.githubusercontent.com/5910926/225585557-d701320d-ae50-42a7-b27b-3d5f68dc3f38.png">

**Comment by tzhangchi** [comment]
It is just appear in blocksuite playground  https://blocksuite-toeverything.vercel.app/?init=empty

**Comment by joebeijing** [comment]
This requires consistency in font and size on both sides. @alt1o said he will add the default font for whole BlockSuite in next pr

**Comment by tzhangchi** [comment]
Thanks，look forward to it @joebeijing @alt1o
