### ISSUE TITLE
Flaky `should focus on empty code blocks created by the slash menu` test case

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1758]
Recent related CI failure:

* https://github.com/toeverything/blocksuite/actions/runs/4454755357/jobs/7824148446
* https://github.com/toeverything/blocksuite/actions/runs/4453722142/jobs/7822439909
* https://github.com/toeverything/blocksuite/actions/runs/4447196796/jobs/7808442824

@Flrande any idea?

**Comment by Flrande** [comment]
I will try to fix it.
