### ISSUE TITLE
Override placeholder in database block

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#1773]
I think this should be hidden

![image](https://user-images.githubusercontent.com/14026360/226199690-631aab5e-da55-43be-9cdd-95de39f7529e.png)

**Comment by zqran** [comment]
Can we add an property(e.g. `showTooltip: boolean`) to `ParagraphBlock` to control whether to display tooltip?

**Comment by doodlewind** [comment]
> Can we add an property(e.g. `showTooltip: boolean`) to `ParagraphBlock` to control whether to display tooltip?

Block components only receive `model` and `host` properties, the `host` can be used for similar context-like purpose. If you want to override placeholder in database container, I think on solution is to create a new `host` in database block, override its flavours to `affine:database`, and in this case its children paragraphs can adapt to it based on this host `flavour` property.
