### ISSUE TITLE
Support autocomplete brace/bracket in code block

### ISSUE THREAD

**Issue by VictorNanka** [toeverything/blocksuite#1800]
Autocompleting the closing braces or brackets in code block like

- ""
- ''
- ()
- {}
- []

It will enhance the user experience and improve the accuracy and speed of writing code.

**Comment by doodlewind** [comment]
@VictorNanka if you select part of the code, we have already supported the autocompleting by pressing `" ' { [`:

https://user-images.githubusercontent.com/7312949/227082137-96704fa1-f68b-4b21-a758-a38ec9642d73.mov

@joebeijing for regular input inside code block, does this require autocomplete? It's common in code editors if the code block language is not plain text.

/cc @lawvs

**Comment by joebeijing** [comment]
I think this requirement is reasonable and can be considered as a follow-up requirement. @lawvs Thanks
