### ISSUE TITLE
Hope that AFFiNE supports quickly enter the editing state when switching between different Text components

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1809]
Just like what we could do in FigJam, after entering the editing state of a Text component, switching between multiple Text components can quickly enter editing state. However, if it is a Text component and a component of another type, entering the editing state requires clicking on the Text component again after clicking on the other component.

**Comment by doodlewind** [comment]
@joebeijing please add an extra "story" label for similar requirement issues (only required in BlockSuite since it haven't enabled issue form), thanks!
