### ISSUE TITLE
After using keyboard shortcuts or slash commands to modify the style of a block or text, editing the content after formatted text should inherit the previous formatting

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1818]
Recorded video is attached

https://user-images.githubusercontent.com/22443345/226873872-8bc9bc26-15ec-4b36-9c1d-37010df61781.mp4

Note:
If I using Markdown syntax such as **xxx**, editing the content after formatted text should not inherit the previous formatting

**Comment by Flrande** [comment]
There is an issue here: in the scenarios mentioned above, we cannot distinguish whether we have selected all the characters in a line using the mouse or have selected the entire block using the slash-menu or shortcut selection. They all result in the same data change.

**Comment by Flrande** [comment]
You can test in https://blocksuite-git-fork-flrande-fix-block-format-0322-toeverything.vercel.app/
