### ISSUE TITLE
Slash menu doesn't support dark mode when embedded

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1851]
AFFiNE overrides the dark mode style, and the default `@blocksuite/editor` package only contains some basic styles. So the dark mode support for slash menu is missing in https://blocksuite-docs.vercel.app/getting-started.html:

AFFiNE:

<img width="800" alt="Screenshot 2023-03-24 at 18 03 46" src="https://user-images.githubusercontent.com/7312949/227491464-a4bf9968-4cb8-4bcd-ab19-1522dde6260d.png">

Embedded BlockSuite:

<img width="800" alt="Screenshot 2023-03-24 at 18 04 29" src="https://user-images.githubusercontent.com/7312949/227491609-f8c2d8e7-28a7-4466-a2a4-35b1138efae1.png">

**Comment by Rogue-striker** [comment]
can i work on this?

**Comment by Flrande** [comment]
> can i work on this?

Sure, feel free to work on it!

**Comment by Alex-Programer** [comment]
How's going? I'm very expect it.

**Comment by Alex-Programer** [comment]
> can i work on this?

How's going? I'm very expect it.

**Comment by adityash1** [comment]
Tested it. It's working fine now.  Issue can be closed now.

![Image](https://user-images.githubusercontent.com/65771169/229881754-2ffb892a-e686-4dca-9623-7af0f65d9d6a.png)

**Comment by lawvs** [comment]
It is now functioning properly. Feel free to reopen this issue if the problem occurs again.
