### ISSUE TITLE
Incorrect indentation when deleting list item

### ISSUE THREAD

**Issue by lzlme** [toeverything/blocksuite#1881]
https://user-images.githubusercontent.com/117659326/228162013-c7b77b6a-9bfe-45a0-a71b-7100a97b3576.mov

https://user-images.githubusercontent.com/117659326/228162061-0e1d5167-5bd9-45ab-9947-028826465b8c.mov

**Comment by zuoxiaodong0815** [comment]
@doodlewind I think the behaviour is normal, so I'm going to roll back the relevant code
