### ISSUE TITLE
Need to press ctrl+enter twice to exit the code block and enter the next line, is it a bug or a feature?

### ISSUE THREAD

**Issue by Zeng1998** [toeverything/blocksuite#1886]
```
"```"
"enter"
"ctrl+enter"
"ctrl+enter"
```

**Comment by joebeijing** [comment]
Thank you for your feedback.
Currently,  if you use "shift + Enter", the text will wrap at the end of the line without exiting the code block. 
And Pressing "Ctrl + Enter" twice which is equal to "Enter" will exit the code block and enter the next line.
Are you sure that you cannot exit the code block by pressing Ctrl + Enter? Could you provide more details about this, such as the browser and operating system being used?

**Comment by Zeng1998** [comment]
I see. Currently `ctrl+enter` is equal to `enter`, that is, `enter`/`ctrl+enter` twice will exit the code block. It is not a bug. 

Of course, my habit is to press `ctrl+enter` once to exit the code block directly. In other words, `enter` is to get  a newline in the code block, and `ctrl+enter` is to exit the code block.

**Comment by joebeijing** [comment]
Got it.  We will continue to pay attention to this type of feedback.

**Comment by lawvs** [comment]
> Of course, my habit is to press ctrl+enter once to exit the code block directly. In other words, enter is to get a newline in the code block, and ctrl+enter is to exit the code block.

In many text editors, using `Ctrl/Cmd+Enter` is for inserting a line below, which I believe is a more intuitive operation. (But it is a bug that Ctrl+Enter can not insert an **empty** line in a code block.)
