### ISSUE TITLE
Sub command of `pnpm dev` fails due to invalid environment variable setup on Windows

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#189]
When I try to use "pnpm dev" command in windows system, it throws the following error
<img width="377" alt="image" src="https://user-images.githubusercontent.com/102217452/200793300-f50f60f8-5286-4b66-a796-77fe4dde611f.png">

**Comment by JimmFly** [comment]
I'll handle this myself

**Comment by lawvs** [comment]
In general, if you want to compatible with Windows, you can add [cross-env](https://github.com/kentcdodds/cross-env) to fix it.

**Comment by doodlewind** [comment]
@JimmFly welcome to give it a try! 😀

**Comment by JimmFly** [comment]
I'll try my best

> 



> @JimmFly welcome to give it a try! 😀
