### ISSUE TITLE
Hope that typing "2. + Space" could generate numbered list "2." instead of "1."

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1909]
Now, no matter what number is typed before a dot and a space, it will always generate a numbered list starting with "1.".

**Comment by doodlewind** [comment]
Expected effect:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/7312949/234747384-66dfb328-1b39-441a-aae8-334638aa4f9c.png">
