### ISSUE TITLE
Support loading state for paste event

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#1938]
### Description

When pasting a large amount of content, a loading state is needed.
When there are a large number of images in the clipboard, it may take more than 10 seconds to process, and there is no UI prompt. If you press command + v repeatedly, it may result in duplicate pasting.

![shot-2023-03-27-12 03 16](https://user-images.githubusercontent.com/24713927/227838033-1961a85c-962d-4feb-9c13-03bd3e677598.gif)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
I think this would be considered as no recent plan to support. Reasons:

* It would be hard to tell where a paste operation is "large" or "small". Most of the pasted content should be small, but having toasts on all pasting operations will be disturbing.
* It's quite verbose in JavaScript to make the pasting computation non-blocking, and async pasting doesn't work well in Firefox (https://stackoverflow.com/questions/55456041/how-to-allow-async-programmatic-copy-to-clipboard-functionality-in-firefox).
* Lags also exists on heavy content in other SOTA rich text editors (like https://tiptap.dev/examples/book), but as long as the perf is decent, this looks acceptable.
* In the next refactoring (#4191) on content import/export, there should be perf gain. So IMHO that should be the better approach to go.

/cc @Saul-Mirone @zuoxiaodong0815
