### ISSUE TITLE
Cursor lost in the first render

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#1967]
Preview: https://affine-storybook.vercel.app/?path=/story/blocksuite-editor--empty

https://user-images.githubusercontent.com/14026360/230424912-2273f013-4e7d-49a5-aabf-4c562530f0f6.mp4

**Comment by Flrande** [comment]
`editor-container` does not automatically focus by default.

https://github.com/toeverything/blocksuite/blob/bc4231bd877373c0b68dfa0b618efec71ff83e87/packages/editor/src/components/editor-container.ts#L41

**Comment by doodlewind** [comment]
So @Flrande how about updating affine to enable `autofocus`?

**Comment by Flrande** [comment]
> So @Flrande how about updating affine to enable autofocus?

https://github.com/toeverything/AFFiNE/pull/1844
