### ISSUE TITLE
Press and hold the space, the cursor will run to the front

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#1970]
https://user-images.githubusercontent.com/27926/230520387-e3aa1b74-506d-43ae-aa90-a443aa699324.mov

**Comment by Flrande** [comment]
Do you use Windows?

**Comment by fundon** [comment]
```
Mac 13.3
Chrome 111.0.5563.146 (Official Build) (x86_64)
```

**Comment by zuozijian3720** [comment]
Same issue on my computer, Mac M2 Chrome

**Comment by Flrande** [comment]
Can it still be reproduced in the latest playground?

**Comment by zuozijian3720** [comment]
> Can it still be reproduced in the latest playground?

No more, my case looks fixed.
