### ISSUE TITLE
Need to handle single click and long press operations in active state of Connector

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#1974]
After drawing a Connector, it remains in the active state. It is necessary to differentiate between long-press and single-click operations. If a component is single-clicked, it will immediately switch to Select mode and select the component. If it is long-pressed, it will continue drawing the Connector. If the whiteboard is clicked blankly, there is no response, similar to the operation in FigJam.

**Comment by doodlewind** [comment]
Closing as resolved since after #3886 landed, the behavior between dragging and clicking on the connector are both supported:

https://github.com/toeverything/blocksuite/assets/7312949/6e1b22ba-887a-44e8-a625-a4a0804cbc90
