### ISSUE TITLE
After deleting characters, retyping appears with extra character

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#199]
After the first line is selected, press backspace, and then enter a character will appear strange.
![selectBUG](https://user-images.githubusercontent.com/102217452/201041762-170408fc-00b6-4841-b68f-5be18880866f.gif)

**Comment by JimmFly** [comment]
Looks like this bug is fixed, I will close this issue.

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/issues/574

**Comment by himself65** [comment]
> Looks like this bug is fixed, I will close this issue.

NO, it isn't

**Comment by doodlewind** [comment]
This is fixed by #209 indeed, I suggest next time @thorseraq could write `Closes #xxx` in PR desc instead of `#xxx`, this will explicitly close the issue, instead of only having a weak ref.

@Himself65 we can open other issues for more cursor behavior inconsistencies in list blocks.

**Comment by thorseraq** [comment]
> This is fixed by #209 indeed, I suggest next time @thorseraq could write `Closes #xxx` in PR desc instead of `#xxx`, this will explicitly close the issue, instead of only having a weak ref.
> 
> 
> 
> @Himself65 we can open other issues for more cursor behavior inconsistencies in list blocks.
> 
> 

I will take care next time
