### ISSUE TITLE
After selecting multiple lines, editing only modifies the first line

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#200]
After selecting multiple lines, editing only modifies the first line
![delete](https://user-images.githubusercontent.com/102217452/201042543-edb3ab08-7b8f-45bc-b932-0599be2fc3ab.gif)

**Comment by himself65** [comment]
I have fixed this bug. I will open the pr today

**Comment by JimmFly** [comment]
> I have fixed this bug. I will open the pr today

Cool, that sounds great to me. Thank you for your information.
