### ISSUE TITLE
There is an extra blank space at the top of the Text component

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2004]
![CleanShot 2023-04-10 at 11 51 55@2x](https://user-images.githubusercontent.com/22443345/230822797-fd8d3eec-f2bd-43d4-901a-7cbfeaddd1bc.png)

**Comment by alt1o** [comment]
Currently, the block is not rendered in the center of the container, so there is an offset at the first/end block.

**Comment by doodlewind** [comment]
This may be non-trivial, @QiShaoXuan please feel free to discuss and we can reconsider its priority accordingly.

**Comment by doodlewind** [comment]
Closed by #2354
