### ISSUE TITLE
Cannot be re-edited after selection

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#201]
This may be related to [issue#196](https://github.com/toeverything/blocksuite/issues/196), and the behavior of re-editing after selecting text is not as expected. I need to delete it write new instead of adding after these texts.
![delete](https://user-images.githubusercontent.com/102217452/201043659-bc60ee64-4792-4d40-9cd5-f40f4955aae7.gif)

**Comment by LuciNyan** [comment]
I can't reproduce it. Does this issue still exist? 🤔

**Comment by JimmFly** [comment]
> I can't reproduce it. Does this issue still exist? 🤔

Looks like this bug is fixed, I will close this issue, thanks for letting me know.
