### ISSUE TITLE
Switch to block level database fields

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2013]
This came from the discussion with @Saul-Mirone.

Initially we have the concept of `tag` that is attach-able for blocks, so we have page-level APIs to operate on tags. But due to product design changes, the tag concept has been weakened and we gradually replaced their fields and APIs as regular table-orientated data structure (`ext:cells` and `ext:columns`). In this case, having these fields inside the database block, rather than containing them on the page block, could make more sense.

From another perspective, this is about managing database states like Virgo and Phasor, since they both attach state manager to partial Yjs data structure.

For cross page references, we can assume using the referenced page follow the `Page -> PageBlock -> DatabaseBlock` structure, which is still acceptable and could reduce the ad-hoc setup in `Page` APIs.

If this got confirmed, we need to ship this before rolling out the first version of database block.

/cc @Himself65 @darkskygit @zqran @Flrande

**Comment by Saul-Mirone** [comment]
This should be closed since https://github.com/toeverything/blocksuite/pull/2053 has been merged.
