### ISSUE TITLE
Feature Request: support select all in text-block using double(triple) click

### ISSUE THREAD

**Issue by promer94** [toeverything/blocksuite#2036]
Currently, double click text-block would only select the current word.

https://user-images.githubusercontent.com/15878786/231360591-b6983ef4-5380-47c6-a104-542adee2091c.mp4

It might be better if it could select the whole text content like notion

https://user-images.githubusercontent.com/15878786/231360887-a47698e9-7090-44aa-8d81-6fb61b733c8b.mp4

**Comment by doodlewind** [comment]
Thanks for your feedback! Alternatively for now you can click the drag handle to select single block :)

In BlockSuite, word-level selection is done by overriding browser events, recognizing double click and partially select text by `Intl.Segmenter`. So this is highly controllable but not documented and public yet. From engineering perspective, it may make sense to have this behavior pluggable together with our SelectionManager. I hope to document the related patten behind this.

/cc @Saul-Mirone @Flrande
