### ISSUE TITLE
The Macbook touchbar flashes when selecting text on Chrome

### ISSUE THREAD

**Issue by Sevichecc** [toeverything/blocksuite#2039]
In Firefox (V.113.0b1 (64-bit)), it doesn't flash:

https://user-images.githubusercontent.com/91365763/231402211-4c329779-c8eb-49b5-b350-2f41434a57b7.mp4

In Chrome (V.111.0.5563.146), it flashes like this: 

https://media.kongwoo.icu/1861f85b8e828a6cac9b1509182b185286af3a8b95e8f153ebfee0942a230b50.mp4

**Comment by doodlewind** [comment]
I guess this is related to how our Virgo rich text editor renders the text, will be great if @Flrande can explain about this.

**Comment by Flrande** [comment]
Will it flashes when you input?

**Comment by fourdim** [comment]
Unfortunately, we cannot fix it on the blocksuite side.
Please trace it here: https://bugs.chromium.org/p/chromium/issues/detail?id=952267
