### ISSUE TITLE
Using Ctrl+p & Ctrl+n to moving menu items in slash menu popover

### ISSUE THREAD

**Issue by gyuannn** [toeverything/blocksuite#2052]
### Description
![CleanShot 2023-04-13 at 11 12 50](https://user-images.githubusercontent.com/23186536/231639938-7ad060d8-1a37-46c3-b011-bbf31e072ef4.gif)

This feature exists in the cmdk of Affine, but it cannot be used in the editor.
I read the source code and found this comment.
```
// Abort when press modifier key to avoid weird behavior
// e.g. press ctrl + a to select all or press ctrl + v to paste
```
If AFFINE also has an AI Copilot, might need to press Ctrl + A to select all, instead of close the slash menu popover. 
<img width="853" alt="CleanShot 2023-04-13 at 11 28 12@2x" src="https://user-images.githubusercontent.com/23186536/231641533-999d7172-bcf9-4b20-921e-6d40bd3c61b1.png">

**Comment by lawvs** [comment]
@joebeijing Could you have a look?

**Comment by joebeijing** [comment]
After discussion, we agree with that, this shortcut can be added to maintain consistency with Quick Search.
