### ISSUE TITLE
Example demonstrating `@blocksuite/store` usage

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2071]
Based on the [docs](https://block-suite.com/workspaces-and-pages.html), it's now easy to reuse only `@blocksuite/store` to build a block-based app. Steps:

* Define some custom block flavours.
* Listen to the `page.rootAdded` event slot, bind the `page.root` to framework component.
* Listen to the `model.propsUpdated` and `model.childrenUpdated` event slot, update the UI framework component.
* Call APIs like `page.addBlock` and `page.updateBlock` to manage state.

This example can be as simple as a todo list (no rich text) with no styling support. For this usage, we can define `ContainerBlock` and `TodoBlock` with the components you are familiar with. Using any popular framework can be acceptable (React, Vue...)

We have `packages/playground/examples` Vite environment that can be used as new example entry. The newly added example can also be added into our documentation for reference.

**Comment by DataDaoDe** [comment]
Hey I would be interested in trying to do this. I think I'm probably going to need some guidance though. I've been trying to figure out how blocksuite works over the last couple days (trying to get an inline math block working like in notion), and its been pretty slow going and difficult to figure out whats going on (for me at least :). I think I need to start somewhere simpler to figure out the internals of how things are working. This seems like a better place to start.

**Comment by doodlewind** [comment]
@DataDaoDe thanks for your interest! I'm working on adding more documentation explaining how things work. Welcome to open discussion thread or join our [Discord](https://discord.com/invite/9vwSWmYYcZ) for reaching out 😀
