### ISSUE TITLE
Support editor-level view-only mode

### ISSUE THREAD

**Issue by pionxzh** [toeverything/blocksuite#2105]
Use case: 
As a user with limited editing permissions, I would like to be able to access a live collaboration page where I can view changes made by other users in real-time, without the ability to make edits myself.

This feature would be particularly useful for scenarios where users need to observe and review the collaborative work of others, such as in a team setting where some members have more editing privileges than others. The view-only mode would provide a safe and controlled environment for all users to participate in collaborative editing.

**Comment by doodlewind** [comment]
This is supported by `page.awarenessStore.setReadonly(page, true)`, which is a model-level lock without affecting UI logic. But there are minor issues in #3750 that will be addressed recently.
