### ISSUE TITLE
Cursor behaves unexpectedly in quote block when Enter is pressed and undo

### ISSUE THREAD

**Issue by SkyeSun** [toeverything/blocksuite#2123]
# Demo

https://user-images.githubusercontent.com/16323946/232418624-bbc253a9-eb41-440f-9e8f-ca31a5c17b63.mov

# Step to reproduce
1. Add a `Quote` block.
2. Type any character.(unnecessary)
3. Press Enter.(x2)
4. Type any character.
5. Press Enter.
6. Undo.

# Result
The cursor will fallback one character after undo. If we put more empty lines before current editing line, the number of fallback characters will be the same as the total number of empty lines before current line in this quote block.

# Expected
The cursor should always be at the position when we pressed Enter after undo.

# Environment
- OS: Mac OS Monterey (Version 12.3)
- Browser: Chrome (Version 112.0.5615.49)

**Comment by SkyeSun** [comment]
It seems that this is not a `quote` block problem, more like a `rich-text` problem. Because it can also reproduced in plain `rich-text`.


https://user-images.githubusercontent.com/16323946/232425344-1ada5571-7d6d-4bee-88ba-e0fdfd6b6057.mov

## Step to reproduce
1. Press `Shift` + `Enter`.
2. Type any characters.
3. Press `Enter`.
4. Undo.

**Comment by zuozijian3720** [comment]
Seems this bug is because ZERO_WIDTH_SPACE has only one cursor position, but is counted as two.

https://github.com/toeverything/blocksuite/blob/64520c8a7a824c28dbb26b00333e6e135fd9ba29/packages/virgo/src/virgo.ts#L204-L224
