### ISSUE TITLE
Changes from spell checker are not been tracked by editor

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#2134]
https://user-images.githubusercontent.com/50035259/232543231-88996776-4584-466d-a3ff-d1751d692063.mp4

related to https://github.com/toeverything/blocksuite/issues/2129

**Comment by zuozijian3720** [comment]
I discovered that Grammarly does not trigger the 'beforeinput' event, but it trigger the 'input' event.
The fix for this bug can be a difficult job.

**Comment by zuozijian3720** [comment]
<img width="742" alt="image" src="https://user-images.githubusercontent.com/17165520/233297040-bac1fd83-c23b-40ad-9f41-7460ee5576df.png">
It seems that Grammarly uses execCommand('insertText') to implement replacement, which would result in different behavior in Chrome and Safari.

In Safari, execCommand triggers the 'beforeinput' event（there are also bugs）, but Chrome does not.

### In Safari

![Kapture 2023-04-20 at 16 09 49](https://user-images.githubusercontent.com/17165520/233302391-d92aaecd-6d44-41eb-9acc-1c86c25acd9a.gif)
