### ISSUE TITLE
Emoji gets partially deleted when pressing backspace

### ISSUE THREAD

**Issue by pionxzh** [toeverything/blocksuite#2138]
Pressing backspace will partially delete some emoji characters.
For example: 
🙅‍♂️ (no_good_men) will become 🙅 (no_good_woman)
🏳️‍🌈 will become 🏳️‍

This is a common problem for editors as the length of the string characters and the visual letters are not aligned.
```js
'🌷'.length === 2
'🙅‍♂️'.length === 5
'🏳️‍🌈'.length === 6
```

I noticed this by deleting the gear emoji in the playground.
```
⚙️ Serve as E2E test entry.
 ^
```

**Comment by ijklmopffs** [comment]
Hey, I'd be willing to work on this

**Comment by lawvs** [comment]
@ijklmopffs  Thank you for your willingness to work on this. Feel free to ask any questions or let me know how I can help.

**Comment by ijklmopffs** [comment]
alright. can we connect on discord or telegram

**Comment by lawvs** [comment]
When the emoji is in the middle of the text, the issue can still be reproduced.

https://user-images.githubusercontent.com/18554747/233011439-5db1280b-87d5-461c-aef0-331ce04d6a7d.mov
