### ISSUE TITLE
blobOptionsGetter shouldn't have a default to API

### ISSUE THREAD

**Issue by pionxzh** [toeverything/blocksuite#2147]
When I import markdown by:

```js
const contentParser = new ContentParser(page)
const pageBlockId = page.addBlock('affine:page')
const frameId = page.addBlock('affine:frame', {}, pageBlockId)
contentParser.importMarkdown(markdown, frameId)
//             ^^^^^^^^^^^^
```

If there are any image element, it will automatically call `workspace.blobs` (the `BlobStorage`) to store the blob.

But the default value of `_blobOptionsGetter` caused the parser to send a request to `/api/workspace/{workspace_id}/blob` to persistent the blob on the server, which shouldn't be enabled by default.

See 

https://github.com/toeverything/blocksuite/blob/c673f6637d9d0fc32147b931b37c1e4932cbc027/packages/blocks/src/__internal__/content-parser/parse-html.ts#L468

https://github.com/toeverything/blocksuite/blob/c673f6637d9d0fc32147b931b37c1e4932cbc027/packages/store/src/workspace/workspace.ts#L35-L37

## Current workaround
```diff
const workspace = new Workspace({
    id: workspaceId,
    providers: [],
+   blobOptionsGetter: () => undefined,
})
```

**Comment by doodlewind** [comment]
Closed by #2169
