### ISSUE TITLE
Wrong line break occurs during real-time collaboration

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#217]
I try to do real time collaboration in blocksuite. When I join the workspace, I press enter on the first line and a weird block appears. I think this is a bug and hopefully someone can fix it.

https://user-images.githubusercontent.com/102217452/203756249-16b750fb-f18f-4a76-bf71-2a71bc5327e2.mov

**Comment by JimmFly** [comment]
<img width="1347" alt="898b2c704b47289fb4d0f2a14792d5e0" src="https://user-images.githubusercontent.com/102217452/203756529-4747c876-56be-4753-8b8d-f0c971930b04.png">

**Comment by JimmFly** [comment]
Maybe I can try to handle it?

**Comment by JimmFly** [comment]
> Maybe I can try to handle it myself?

Oh, I might not be able to handle this for some reason, can someone help me?

**Comment by himself65** [comment]
I think the bug is the same as when I `Y.applyUpdate` directly https://github.com/toeverything/blocksuite/pull/318

**Comment by himself65** [comment]
I think the reason is the state doesn't sync fully between users
