### ISSUE TITLE
Support gantt chart view in database block

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2172]
Originally posted by @Jersyfi in https://github.com/toeverything/AFFiNE/discussions/2031

/cc @joebeijing

**Comment by joebeijing** [comment]
This should be included in our Database view plan, but with a lower priority than our planned Kanban view.

**Comment by tmlmt** [comment]
I believe that AFFiNE can really make a difference with all other tools by making a smooth integration of planning / task management. For instance:
- On Azure DevOps, it is nearly impossible to show any kind of timeline from a backlog of task
- On Miro, it requires a lot of manual steps to turn a bunch of sketched ideas into an organized set of tasks (in a table, or Gantt chart for instance). Let alone the follow-up of progress that you can really facilitate with the integration with your system of database.

Thumbs up for this Feature Request 👍

**Comment by doodlewind** [comment]
This should be a new view in database (like @3283), /cc @zzj3720

**Comment by doodlewind** [comment]
Tracked in #5385
