### ISSUE TITLE
Add Node environment compatibility test

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2176]
For now some imports from `@blocksuite/blocks` are fragile to become incompatible with Node (e.g., `@blocksuite/blocks/content-parser` and `@blocksuite/blocks/models`). Since BlockSuite is published in a bundle-less way (running `tsc` only), we can't track such case in our build process.

So, it will be good to add CI checks in `playground` that imports these package entries in Node:

* `@blocksuite/store`
* `@blocksuite/blocks/content-parser`
* `@blocksuite/blocks/models`

And check no error is thrown. This helps ensuring our Node compatibility. And we can remove the `@blocksuite/react` after this is shipped, because this package was mainly used for validating this.

**Comment by himself65** [comment]
I think it's not SSR because we electron also use this, so it should be `node.js` side

**Comment by himself65** [comment]
Related https://github.com/toeverything/blocksuite/issues/2175
