### ISSUE TITLE
testing: Create JSX runtime for scaffolding blocks for testing

### ISSUE THREAD

**Issue by colelawrence** [toeverything/blocksuite#218]
Inspired by the conversations in #206.

Design a JSX interface that allows us to create JSX code that looks near identical to the snapshot strings we get for jest snapshot.

See related: [Test: jsx snapshot parse text format #154](https://github.com/toeverything/blocksuite/pull/154)

**Comment by doodlewind** [comment]
Closing this since we have implemented `assertStoreMatchJSX` and we are going to use #535 for debug persistence. Also, #332 is so far convenient enough for debugging.
