### ISSUE TITLE
Emoji gets partially deleted when delete backward

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#2180]
Related to https://github.com/toeverything/blocksuite/issues/2138

Press the `Delete` key in Windows or `Fn+Backspace`/`Contrl+D` in Mac

https://user-images.githubusercontent.com/18554747/233277676-71b482bf-04e3-49fb-89d3-2a2db35c17d4.mov

**Comment by lzlme** [comment]
@lawvs Semantically speaking, it should be called `delete forward` instead of `delete backward`, I will fix this right away.
