### ISSUE TITLE
Refactoring `edgeless-page-block` to simplify logic and improve maintainability

### ISSUE THREAD

**Issue by alt1o** [toeverything/blocksuite#2193]
Currently, the `edgeless-page-block` has become overly complex due to the mixture of various states, making it difficult to maintain. To address this issue, we propose a three-part refactoring plan:

- State Management: we will separate the states into three categories:
  - CRDT: graphical data
  - Whiteboard state: zoom, offset, selection, pointer, etc.
  - View state: view rendering

- Component Composition for Edgeless: we will refactor the `edgeless-page-block` by breaking it down into smaller components that can be composed together. For example, we will create a separate toolbar component that can be used based on the specific use case
  - Try to minimize the use of `customElement` for internal components. This will prevent the unintended introduction of unknown elements to the user.

- Rich State API: we will enhance the State API by providing additional functionalities such as `sendToFront` and `zoomTo`, to offer more flexibility and convenience in managing the states.

**Comment by doodlewind** [comment]
I suggest restart this part after the host refactoring (#2320)
