### ISSUE TITLE
Refactor `@blocksuite/phasor` for standard canvas rendering

### ISSUE THREAD

**Issue by alt1o** [toeverything/blocksuite#2194]
- Provide a standardized CRUD API for element operations. Currently, for each new type of Element added, a separate set of APIs needs to be created.
- Ensure accurate element schema types are provided.
- Ensure consistent bounds returned when calling `setBound` for different types of elements. Currently, the bounds returned by `Connector` do not include line width, while bounds returned by `Shape` do include it.

```[tasklist]
- [ ] https://github.com/toeverything/blocksuite/issues/2318
```

**Comment by doodlewind** [comment]
Generally LGTM
