### ISSUE TITLE
After adding an existing page as a linked page, the title should not be editable directly inline under Chinese pinyin input method

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2244]
https://user-images.githubusercontent.com/22443345/233840539-dc2a86c4-b971-4a28-accd-43c7925942ee.mp4

Moreover, after editing, i can not delete or add line breaks.

**Comment by lawvs** [comment]
Close by https://github.com/toeverything/blocksuite/pull/2232
