### ISSUE TITLE
After dragging the database, the number/text column data is lost

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#2284]
After dragging the database, the number/text column data is lost:

https://user-images.githubusercontent.com/15389209/234295283-bbe524ba-705d-42fd-b76c-ff87e6ac0688.mov

**Comment by zqran** [comment]
@fundon What happens when dragging and droping the `database` block?

**Comment by fundon** [comment]
@zqran In the video, the children of the model in the database have two blocks.

**Comment by zqran** [comment]
> @zqran In the video, the children of the model in the database have two blocks.

@fundon Thanks! This problem is related to virgo, not caused by dragging.
