### ISSUE TITLE
Database has redundant popup tooltip on the "New Record" button

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2296]

**Comment by zqran** [comment]
@hwangdev97 Can this behavior be optimized?


https://user-images.githubusercontent.com/15389209/234573577-8fd5a2ba-49ca-4221-ab1e-0ec2200e1ee4.mov

**Comment by doodlewind** [comment]
So I'd consider current implementation as by-design. Feel free to reopen or continue further discussion here!

/cc @joebeijing
