### ISSUE TITLE
Support copy, cut and paste in database block

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/blocksuite#2309]
## Reasons
the `deleteModelsByRange` is unable to handle a block that does not contain `text`

https://github.com/toeverything/blocksuite/blob/d59a6838f82de93a37bacdd952b1175c1bf78b06/packages/blocks/src/page-block/utils/container-operations.ts#L94

`json2Block` method has not processed the database.
# Principles
Do not introduce database concept in the utility methods of the internal functions.
## Solution
Ignore the delete text case tempoarily (cut or paste will not remove selection)
`deleteModelsByRange` will no longer throws an exception when model does not contain text. 
Please make sure to add TODO marks and comments in appropriate places.
Paste
Add `json2Block` implement to database block
Copy
Refactor `getBlockClipboardInfo` (add BlockRange as parmeter)
Refactor `block2Json` and implement `block2Json` in database block
## References
See https://github.com/toeverything/blocksuite/blob/d59a6838f82de93a37bacdd952b1175c1bf78b06/packages/blocks/src/__internal__/clipboard/page-clipboard.ts#L32-L82

**Comment by doodlewind** [comment]
@zqran given the current status, I think the clipboard support for database support would need your help mainly. This can count for a great piece of UX improvement!

**Comment by zqran** [comment]
Ok, I think we should confirm the specific operation details, and then I can implement it.

/cc @joebeijing

**Comment by zqran** [comment]
related to: #2470

**Comment by joebeijing** [comment]
After our last discussion, I added the information to the[ internal doc](https://toeverything.feishu.cn/wiki/YEvswCd83ipwr6kqGQ9cyRoynJf#PHXDd0VCwoIUm3xKiMWc68h1nFd). Please take a look. @zqran
