### ISSUE TITLE
Support new frame element in edgeless

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2325]
The new frame element should not be confused with the legacy frame block. Frame elements can be used to "group" visual contents inside in edgeless mode.

Previous goal:

<del>It can be simply understood as the presentation effect of Miro's presentation based on frames. We will invest more design into it and create even greater highlights.</del>

Related: https://github.com/toeverything/blocksuite/issues/2196

**Comment by xell** [comment]
Reopen it as being planned in milestone 0.7

**Comment by joebeijing** [comment]
Note：Supporting presentations is also within the scope of this issue.

**Comment by regischen** [comment]
> Note：Supporting presentations is also within the scope of this issue.

need details about presentation. @joebeijing 
also need design about frame. @hwangdev97

**Comment by hwangdev97** [comment]
> > Note：Supporting presentations is also within the scope of this issue.
> 
> need details about presentation. @joebeijing also need design about frame. @hwangdev97

You can find the frame design on [this file](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=5459%3A115287&mode=design&t=kmREHt8SPLLwh0I8-1)

**Comment by joebeijing** [comment]
> > Note：Supporting presentations is also within the scope of this issue.
> 
> need details about presentation. @joebeijing also need design about frame. @hwangdev97

The details of this part will be provided as soon as possible, and we will discuss it with others.

**Comment by hwangdev97** [comment]
we update the presentation mode's design for frame, you can check this feature on following file:
![shot-2023-07-28-18 45 36@2x](https://github.com/toeverything/blocksuite/assets/24713927/eaf3c477-5772-4063-9635-f9b86b8f8148)

[The figma link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=10095%3A167771&mode=design&t=62OYbkyUiyR6eSKN-1)

**Comment by houjoe0829** [comment]
PRD：[Internal Doc](https://toeverything.feishu.cn/wiki/EnSSwrTd0iCObBkTZ7FchoTmnob?from=from_copylink)
