### ISSUE TITLE
The style under edit mode and exported HTML are different

### ISSUE THREAD

**Issue by BedBear** [toeverything/blocksuite#2326]
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/8636635/234622041-3cce5b07-3e8c-450f-82ff-293adf86844d.png">

website：
[blocksuite-toeverything.vercel.app](https://blocksuite-toeverything.vercel.app/?init=AAMAAw8H14mb2wurAagBAAIBAQoBBhQBAQhipgEBAEIMAQLQAY4BSBoCAQgYAQJkCCaEAQEDwgECiwEAAQPGAQKOAT4BA3oCggGSAgIWAiIBAsoDApIDigEBAsgBApABngECCgKUBwEC%2FggChgmkAgISAooBAhICmgEBAvIFAroFnAICCgK0BAIMAhABAvwHAoQIrgUCOgKEAwEC7gkCtgmEAwKMAQK4AQECygYCkgaCAQIiAsoyAK8CJwAHACgAIQAoAScAKAgnACgBJwEEAKEAJwAoAScAoQAnACgBJwAoAQgAoQAnASgKJwAoAScAKAAnAAgAoQAEACcAKAEnACgAJwAoAIgAoQAEACcAKAEnACgAJwAoAIgAoQAEACcAKAEnACgAJwAoAIgAoQAEAIYAhACGAIQAJwAoAScAKAAnAIgAoQAEACcAKAEnACgAJwCIAKEABACGAIQAhgCEACcAKAEnACgAJwCIAKEABACGAIQAhgCEAIYAhACGAIQAJwAoAScAKAAnAIgAoQAEAIYAhACGAIQAhgCEAIYAhAAnACgBJwAoACcAiAChAAQAhgCEAIYAhAAnACgBJwAoACcAiAChAAQAhgCEAIYAhAAnACgBJwAoACcAiACoAAQAhgCEAIYAhACo4xesFnNwYWNlOm1ldGFwYWdlc2lkdGl0bGVjcmVhdGVEYXRlc3VicGFnZUlkc3NwYWNlOm1ldGF2ZXJzaW9uc2FmZmluZTpjb2RlYWZmaW5lOnBhcmFncmFwaGFmZmluZTpwYWdlYWZmaW5lOmxpc3RhZmZpbmU6ZnJhbWVhZmZpbmU6ZGl2aWRlcmFmZmluZTplbWJlZGFmZmluZTpzdXJmYWNlYWZmaW5lOmRhdGFiYXNlc3BhY2U6cGFnZTAxNTcyMDM3MjA3OjBzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dGl0bGVXZWxjb21lIHRvIEJsb2NrU3VpdGUgUGxheWdyb3VuZHNwYWNlOnBhZ2UwMTU3MjAzNzIwNzoxc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5zcGFjZTpwYWdlMDE1NzIwMzcyMDc6MnN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp4eXdocHJvcDpiYWNrZ3JvdW5kZWxlbWVudHMwaWRpbmRleHR5cGV4eXdoc2hhcGVUeXBlcmFkaXVzZmlsbGVkZmlsbENvbG9yc3Ryb2tlV2lkdGhzdHJva2VDb2xvcnN0cm9rZVN0eWxlc3BhY2U6cGFnZTAxNTcyMDM3MjA3OjNzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dFRoaXMgcGxheWdyb3VuZCBpcyBkZXNpZ25lZCB0bzpzcGFjZTpwYWdlMDE1NzIwMzcyMDc6NHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0cHJvcDpjaGVja2Vk8J%2BTnSBUZXN0IGJhc2ljIGVkaXRpbmcgZXhwZXJpZW5jZS5zcGFjZTpwYWdlMDE1NzIwMzcyMDc6NXN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0cHJvcDpjaGVja2Vk4pqZ77iPIFNlcnZlIGFzIEUyRSB0ZXN0IGVudHJ5LnNwYWNlOnBhZ2UwMTU3MjAzNzIwNzo2c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRwcm9wOmNoZWNrZWTwn5SXIERlbW9uc3RyYXRlIGhvdyBCbG9ja1N1aXRlIHJlY29uY2lsZXMgcmVhbC10aW1lIGNvbGxhYm9yYXRpb24gd2l0aCBsaW5rbG9jYWwtZmlyc3RsaW5rIGRhdGEgb3duZXJzaGlwLnNwYWNlOnBhZ2UwMTU3MjAzNzIwNzo3c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRDb250cm9sbGluZyBQbGF5Z3JvdW5kIERhdGEgU291cmNlc3BhY2U6cGFnZTAxNTcyMDM3MjA3OjhzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dFlvdSBtaWdodCBpbml0aWFsbHkgZW50ZXIgdGhpcyBwYWdlIHdpdGggdGhlIGNvZGU%2FaW5pdGNvZGUgVVJMIHBhcmFtLiBUaGlzIGlzIHRoZSBkZWZhdWx0IChvcHQtaW4pIHNldHVwIHRoYXQgYXV0b21hdGljYWxseSBsb2FkcyB0aGlzIGJ1aWx0LWluIGFydGljbGUuIE1lYW53aGlsZSwgeW91J2xsIGNvbm5lY3QgdG8gYSByYW5kb20gc2luZ2xlLXVzZXIgcm9vbSB2aWEgYSBXZWJSVEMgcHJvdmlkZXIgYnkgZGVmYXVsdC4gVGhpcyBpcyB0aGUgInNpbmdsZS11c2VyIG1vZGUiIGZvciBsb2NhbCB0ZXN0aW5nLnNwYWNlOnBhZ2UwMTU3MjAzNzIwNzo5c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRUbyB0ZXN0IHJlYWwtdGltZSBjb2xsYWJvcmF0aW9uLCB5b3UgY2FuIHNwZWNpZnkgdGhlIHJvb20gdG8gam9pbiBieSBhZGRpbmcgdGhlIGNvZGU%2Fcm9vbT1mb29jb2RlIGNvbmZpZyAtIFRyeSBvcGVuaW5nIHRoaXMgcGFnZSB3aXRoIGNvZGU%2Fcm9vbT1mb29jb2RlIGluIHR3byBkaWZmZXJlbnQgdGFicyBhbmQgc2VlIHdoYXQgaGFwcGVucyFzcGFjZTpwYWdlMDE1NzIwMzcyMDc6MTBzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dE5vdGUgdGhhdCB0aGUgc2Vjb25kIGFuZCBzdWJzZXF1ZW50IHVzZXJzIHNob3VsZCBub3Qgb3BlbiB0aGUgcGFnZSB3aXRoIHRoZSBjb2RlP2luaXRjb2RlIHBhcmFtIGluIHRoaXMgY2FzZS4gQWxzbywgZHVlIHRvIHRoZSBQMlAgbmF0dXJlIG9mIFdlYlJUQywgYXMgbG9uZyBhcyB0aGVyZSBpcyBhdCBsZWFzdCBvbmUgdXNlciBjb25uZWN0ZWQgdG8gdGhlIHJvb20sIHRoZSBjb250ZW50IGluc2lkZSB0aGUgcm9vbSB3aWxsIGJvbGRhbHdheXNib2xkIGV4aXN0LnNwYWNlOnBhZ2UwMTU3MjAzNzIwNzoxMXN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0SWYgeW91IGFyZSB0aGUgb25seSB1c2VyIGluIHRoZSByb29tLCB5b3VyIGNvbnRlbnQgd2lsbCBiZSBsb3N0IGFmdGVyIHJlZnJlc2guIFRoaXMgaXMgZ3JlYXQgZm9yIGxvY2FsIGRlYnVnZ2luZy4gQnV0IGlmIHlvdSB3YW50IGxvY2FsIHBlcnNpc3RlbmNlLCB5b3UgY2FuIG9wZW4gdGhpcyBwYWdlIHdpdGggdGhlIGNvZGU%2FcHJvdmlkZXJzPWluZGV4ZWRkYiZyb29tPWZvb2NvZGUgY29uZmlnLCB0aGVuIGNsaWNrIHRoZSBpbml0IGJ1dHRvbiBpbiB0aGUgYm90dG9tLWxlZnQgY29ybmVyIHRvIGluaXRpYWxpemUgdGhpcyBkZWZhdWx0IGNvbnRlbnQuc3BhY2U6cGFnZTAxNTcyMDM3MjA3OjEyc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRBcyBhIHBybyB0aXAsIHlvdSBjYW4gY29tYmluZSBtdWx0aXBsZSBwcm92aWRlcnMhIEZvciBleGFtcGxlLCBmZWVsIGZyZWUgdG8gb3BlbiB0aGlzIHBhZ2Ugd2l0aCBjb2RlP3Byb3ZpZGVycz1pbmRleGVkZGIsd2VicnRjJnJvb209aGVsbG9jb2RlIHBhcmFtcywgYW5kIHNlZSBpZiBldmVyeXRoaW5nIHdvcmtzIGFzIGV4cGVjdGVkLiBIYXZlIGZ1biFzcGFjZTpwYWdlMDE1NzIwMzcyMDc6MTNzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dEZvciBhbnkgZmVlZGJhY2ssIHBsZWFzZSB2aXNpdCBsaW5rQmxvY2tTdWl0ZSBpc3N1ZXNsaW5rIPCfk40KBQIFSgEICxBLAAwODA4PCwwGCwwKIAsMBgsMCwwGCwwJDwgBAgVEAAlGAAlLAgwGCwxJAB8LDAYLDEkADCELDAYLDEkADBsLDAYLDEkADIYBBAsEEAsMBgsMSQAiCwwGCwxJAC0EBQSpAwsMBgsMSQCQAQQJBCUECQQsCw0GCwxJAIwBBAUEmgIEBgQHCw0GCwxJALUCBB0EoQELDQYLDEkAoAEEJgQ7Cw0GCwxJAB8EEQQDPwEAAAQBAAAIAQAABAEAAAIBAAASAQAABgEAAAYBAAAGAQAABgEAAAUBAAAFAQAABQEAAAUBAAAFAQAABQEAACsAQQEAAgEAAQBBAQACAQACAQACAQACAQACAQACAQACAQACAQACAQACAQACAkFdAbwBAHcFcGFnZTB7Qnh73uIIoAB1AH0BfQF9An0BfQF9AX0BfQF9AXcMMTU3MjAzNzIwNzowdwthZmZpbmU6cGFnZXcMMTU3MjAzNzIwNzoxdw5hZmZpbmU6c3VyZmFjZXcMMTU3MjAzNzIwNzoydwxhZmZpbmU6ZnJhbWV3DVswLDAsNzIwLDQ4MF13Iy0tYWZmaW5lLWJhY2tncm91bmQtc2Vjb25kYXJ5LWNvbG9ydwwxNTcyMDM3MjA3OjJ3ATB3AmEwdwVzaGFwZXcNWzAsMCwxMDAsMTAwXXcEcmVjdH0AeXccLS1hZmZpbmUtcGFsZXR0ZS10cmFuc3BhcmVudH0EdxstLWFmZmluZS1wYWxldHRlLWxpbmUtYmxhY2t3BXNvbGlkdwwxNTcyMDM3MjA3OjN3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DDE1NzIwMzcyMDc6M3cMMTU3MjAzNzIwNzo0dwthZmZpbmU6bGlzdHcIYnVsbGV0ZWR5dwwxNTcyMDM3MjA3OjR3DDE1NzIwMzcyMDc6NXcLYWZmaW5lOmxpc3R3CGJ1bGxldGVkeXcMMTU3MjAzNzIwNzo1dwwxNTcyMDM3MjA3OjZ3C2FmZmluZTpsaXN0dwhidWxsZXRlZHl3DDE1NzIwMzcyMDc6NnczaHR0cHM6Ly9tYXJ0aW4ua2xlcHBtYW5uLmNvbS9wYXBlcnMvbG9jYWwtZmlyc3QucGRmfncMMTU3MjAzNzIwNzo3dxBhZmZpbmU6cGFyYWdyYXBodwJoMncMMTU3MjAzNzIwNzo3dwwxNTcyMDM3MjA3Ojh3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DDE1NzIwMzcyMDc6OHh%2BdwwxNTcyMDM3MjA3Ojl3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DDE1NzIwMzcyMDc6OXh%2BeH53DTE1NzIwMzcyMDc6MTB3EGFmZmluZTpwYXJhZ3JhcGh3BXF1b3Rldw0xNTcyMDM3MjA3OjEweH54fncNMTU3MjAzNzIwNzoxMXcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNMTU3MjAzNzIwNzoxMXh%2Bdw0xNTcyMDM3MjA3OjEydxBhZmZpbmU6cGFyYWdyYXBodwR0ZXh0dw0xNTcyMDM3MjA3OjEyeH53DTE1NzIwMzcyMDc6MTN3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DTE1NzIwMzcyMDc6MTN3IFdlbGNvbWUgdG8gQmxvY2tTdWl0ZSBQbGF5Z3JvdW5kdzFodHRwczovL2dpdGh1Yi5jb20vdG9ldmVyeXRoaW5nL2Jsb2Nrc3VpdGUvaXNzdWVzfncNWzAsMCw3MjAsNzI1XQHXxM3tBQ8DADEABAAEAAIAFAAnACkAIwBqACkApAIAvgEAgwIAvAIA)

Use this export function：
<img width="474" alt="image" src="https://user-images.githubusercontent.com/8636635/234622915-ab366c02-04bb-4733-95ab-e175cacb7e69.png">

**Comment by donglixiaoche** [comment]
anyone working on this issue? i'm glad to give this a try. @zuoxiaodong0815

**Comment by doodlewind** [comment]
> anyone working on this issue? i'm glad to give this a try. @zuoxiaodong0815

Would be great if you can give it a try, thanks!

**Comment by donglixiaoche** [comment]
> > anyone working on this issue? i'm glad to give this a try. @zuoxiaodong0815
> 
> Would be great if you can give it a try, thanks!

copy, glad to do, leave a comment here to avoid duplicate works.

**Comment by Flrande** [comment]
> copy, glad to do, leave a comment here to avoid duplicate works.

I have assigned you. :)

**Comment by water-in-stone** [comment]
I recently started using Affine and encountered the same issue. Please assign it to me, and I will submit a PR to address it.

**Comment by water-in-stone** [comment]
@Flrande PTAL

**Comment by doodlewind** [comment]
Closed by #3893, @water-in-stone thanks for the help!
