### ISSUE TITLE
edgeless palette dark mode black color

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#2339]
add an inside 0.5px border for black color in the panel as well as white in light mode

![Image](https://user-images.githubusercontent.com/110808979/234752044-50e7cfbe-7a2f-4022-ae75-3f84fedc1c30.png)

![Image](https://user-images.githubusercontent.com/110808979/234752264-3c0955be-2c49-4886-98cf-2541544bf500.png)

**Comment by JimmFly** [comment]
close by https://github.com/toeverything/blocksuite/pull/2496
