### ISSUE TITLE
Click to add a paragraph block at the end of the page

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#2360]
> 1. When the last block is not paragraph block, we need to provide the ability for users to add a paragraph block. Ex, in notion, you can always click to add a paragraph block at the end of the page.

Quote link: https://github.com/toeverything/blocksuite/issues/2305#issuecomment-1527075100

**Comment by rottenpen** [comment]
> When the last block is not paragraph block, we need to provide the ability for users to add a paragraph block. Ex, in notion, you can always click to add a paragraph block at the end of the page.
I think this pull request supported the feature. https://github.com/toeverything/blocksuite/pull/2391  
And I will work for the other one

**Comment by lawvs** [comment]
I believe this issue has been fixed in https://github.com/toeverything/blocksuite/pull/878
