### ISSUE TITLE
Use the shortcut key to exit the database block

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#2361]
> 2. When cursor in database block, we need to provide hotkeys for users to exit the block and insert a paragraph block if needed. For example if we have a database block appended by a image block.

Quote link: https://github.com/toeverything/blocksuite/issues/2305#issuecomment-1527075100

**Comment by joebeijing** [comment]
Exiting a Database is actually similar to a List. One can consider a Database as a list view. When there are indent levels in the last empty line, pressing Enter while on that line will reduce the indent level until it becomes the root node. Pressing Enter again will turn that line into regular Body Text.

https://github.com/toeverything/blocksuite/assets/22443345/da85cf2c-ac9d-4829-8817-84461ddade93
