### ISSUE TITLE
Database support pop-out multiline/expandable  text

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/blocksuite#2379]
See SeaTable or Coda.io:

- Option could be called "Multiline", "Expand-Text", "Longform" or something similar.
- Gives the ability to write multiple lines of text in a pop-out box.
- Also gives the ability to add check-boxes or other rich-text format material (see: Collabee or Coda.io as examples of this)

The use-case for this is; if I have a simple kanban board or task list table, and I don't want to overcomplicate the table by cross-referencing between tables, but instead include a checklist or list of sub-tasks on a in a single row (my main task), this tool gives the option to do so.

SeaTable, Collabee, Coda.io, and other table tools give the option for this. Contrarily, some table tools like Larksuite don't give this option and it limits the functionality of the tables.

**Comment by doodlewind** [comment]
This is solved together with #2401. You can now add multi lines of rich text in database title (using `shift` + `enter` for line break), both in a popup or in-place.

https://github.com/toeverything/blocksuite/assets/7312949/7f2785a1-b83d-42ce-a09b-014bec051043

Try this in our [latest playground](https://blocksuite-toeverything.vercel.app/) or just wait for new beta / stable release of AFFiNE would be good.

Thanks for you sponsorship and we'll keep rolling out features to fulfill your needs. Cheers!
