### ISSUE TITLE
Database conditional formatting

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/blocksuite#2380]
Similar to spreadsheet software conditional formatting:

Use-case is: 
- I have a list of tasks
- I set due dates on those tasks
- Tasks past the due date should turn light red, to darker, brighter red as the due date continues on.

There may be other use-cases for conditional formatting, but the request is for the ability to program colours on field entries based on rules set by the user.

**Comment by doodlewind** [comment]
Tracked in #5385
