### ISSUE TITLE
Support multiple editor instances on same page

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#2396]
We might have a use case. The editor is in page mode on the left side, and the right side is in edgeless mode. There will need multiple editors.

Demo: https://affine-demo-git-dev-himself65.vercel.app/

![image](https://user-images.githubusercontent.com/14026360/236135309-496dbd41-0ea9-4141-bace-e5a22481babc.png)

**Comment by zzj3720** [comment]
I'd like to try this, seems like it will require quite a few code changes.
