### ISSUE TITLE
​Split the document by setting  divider and switch to the whiteboard, where it can be divided into multiple freely arranged blocks

### ISSUE THREAD

**Issue by aiyou9** [toeverything/blocksuite#2407]
### Description

​freestyle of the bidirectional transform between page and whiteboard, now, I only show the single direction, but anthor direction of    whiteboard to page, may be more difficult and need to discuss more.

### Use case

![image](https://user-images.githubusercontent.com/15712822/236214388-9321d7c1-e771-452e-92b4-a90a8d49ff0c.png)
![image](https://user-images.githubusercontent.com/15712822/236215294-e2a97f7d-9bc6-42fb-9210-42743e6fb77b.png)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
I think it's a great idea! /cc @joebeijing for evaluation from the product team side.

**Comment by aiyou9** [comment]
so, based on #2408 and #2407, Affine may create a templet market of binding styles in Affine for users to create the format output of docx files. just like https://typeset.io/formats/ for SCI papers. in company, it also has some value in work communication. So, as a user, I expect to have a wonderful experience for working in Affine.

**Comment by aiyou9** [comment]
> so, based on #2408 and #2407, Affine may create a templet market of binding styles in Affine for users to create the format output of docx files. just like https://typeset.io/formats/ for SCI papers. in company, it also has some value in work communication. So, as a user, I expect to have a wonderful experience for working in Affine.

this is a good way for creating Revenue.

**Comment by joebeijing** [comment]
Thank you very much for your feedback. We have discussed this internally, and while it is an interesting concept, we still have some concerns. Using a block with actual meaning to serve as a dividing operation and visual clue for Edgeless text frames could lead to many unmanageable functional logics. However, we are more inclined to use purely visual effects to mark the content of different blocks under various frames in page mode.

**Comment by joebeijing** [comment]
Related with https://github.com/toeverything/blocksuite/issues/2478

**Comment by aiyou9** [comment]
no problem, all depends on software development and User experience

**Comment by aiyou9** [comment]
base on divider, more and more app created by ai like 
1-MD Video
project page: https://github.com/lqomg/mdvideo
homepage:  https://mdvideo.wvovw.com/
2-slidev
https://github.com/slidevjs/slidev
