### ISSUE TITLE
Support changing the key of  /  in Chinese input method 

### ISSUE THREAD

**Issue by aiyou9** [toeverything/blocksuite#2416]
![QQ录屏20230505184033](https://user-images.githubusercontent.com/15712822/236439195-e7ea4c4a-bc4e-4b1d-a789-f6419b85963a.gif)

![image](https://user-images.githubusercontent.com/15712822/236437945-4d7b7b67-298e-4a12-9f47-853e12603031.png)
 this maybe a good way to use / in chinese without changing the input method to english input method

**Comment by lawvs** [comment]
After the merge of #2539, the symbol '、' can trigger the slash menu and work properly.
