### ISSUE TITLE
Support Up/Down to move selected-block

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#2425]
<img width="709" alt="Screenshot 2023-05-06 at 3 21 46 PM" src="https://user-images.githubusercontent.com/27926/236609608-8052627b-c2c6-4587-b226-c9880d312c2c.png">

**Comment by joebeijing** [comment]
When selected, do you want to use the directional keys to select the next block or to move the selected block? Related with https://github.com/toeverything/blocksuite/issues/2425

**Comment by fundon** [comment]
@joebeijing Here is just moving the block-level cursor, so that means selecting the next block.

**Comment by joebeijing** [comment]
> @joebeijing Here is just moving the block-level cursor, so that means selecting the next block.

Cool, that make sense.

**Comment by doodlewind** [comment]
Supported after #3653 (or its following PRs)
