### ISSUE TITLE
Cursor move to the wrong position when pressing up/down with minimized Canvas

### ISSUE THREAD

**Issue by zzj3720** [toeverything/blocksuite#2428]
https://user-images.githubusercontent.com/17165520/236660040-3840a213-3121-4619-b193-056fba7d9182.mp4

**Comment by rottenpen** [comment]
Same in vscode. 
https://user-images.githubusercontent.com/12029924/236686198-86acbad7-17da-4d07-b7bc-3800364c3f03.mp4
