### ISSUE TITLE
Delay on filtering code block language list

### ISSUE THREAD

**Issue by Simon-He95** [toeverything/blocksuite#2430]
### Description

当输入一些搜索条件，然后删除时，到最后一个输入被删除时，存在一个明显的延迟
![屏幕录制2023-05-06 20 47 33](https://user-images.githubusercontent.com/57086651/236625274-3e1cc441-5bf3-4757-a869-d9322d346b3a.gif)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
This seems like because of the tons of list items appended to the menu

**Comment by himself65** [comment]
I think the approaches here are:
1. use the virtual list
2. add a transition state like `is loading`

**Comment by viju-sharma** [comment]
Hey, Can you please assign it to me?

**Comment by doodlewind** [comment]
> Hey, Can you please assign it to me?

Sure, feel free to open PRs for this!
