### ISSUE TITLE
Unable to update whiteboard shape border color

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2434]
This happens before dragging existing shape. After the shape is dragged, the color can be updated.

<img width="690" alt="image" src="https://user-images.githubusercontent.com/7312949/236715198-f6236594-2ce1-446e-b946-1dbec3d0906f.png">

(from Azure)

**Comment by alt1o** [comment]
It may be beneficial to provide further details about the specific version in question, as I have not encountered this bug in the affine master branch.

**Comment by doodlewind** [comment]
Not reproduced in latest canary
