### ISSUE TITLE
Support aligning multiple selected items on whiteboard

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2436]
Expected effect (in pre-alpha live demo):

<img width="800" alt="image" src="https://user-images.githubusercontent.com/7312949/236720377-835820de-a259-462b-8949-de8735c26c19.png">

(from Azure)

**Comment by xell** [comment]
Is it a bug or a feature?

**Comment by regischen** [comment]
> Is it a bug or a feature?

feature
