### ISSUE TITLE
Unable to directly bring item to top or bottom in whiteboard

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2439]
Currently, user has to adjust layer index by one step each time.

(from Azure)

**Comment by alt1o** [comment]
Curious about this question. As our current functionality only supports bringing items to the top or bottom, and does not offer the ability to adjust layer index by step.

**Comment by doodlewind** [comment]
Current status is the opposite

**Comment by xell** [comment]
So it seems to be a feature request?

**Comment by doodlewind** [comment]
The PR requires some refactoring according to the review, so this may not be in this week's beta /cc @xell
