### ISSUE TITLE
Support adding text above the shape

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2441]
In whiteboard, when shape overlaps with current text (frame actually), the shape will always be put on top of the text. This is by design since we put all the canvas content inside one top `SurfaceBlock` layer, but makes user confused about our text feature. Since **it's not supported to put a piece on top of the shape**. It was understood as a bug (from Azure).

![image](https://user-images.githubusercontent.com/7312949/236724991-4619bd8b-7a17-4d37-b652-e4e7f2cf06b5.png)

/cc @joebeijing for related product design (UX to differentiate adding text block and adding canvas handwriting style text element)

**Comment by joebeijing** [comment]
Please refer to [Internal link](https://toeverything.feishu.cn/wiki/wikcnP7za5C8FCOvC1msgPqncQe#MMkoduY0IoY4aSxsFRVcNFw6nRc) for Product details，and this part also requires work from the design team, mainly because new component menu options need to be added. CC @Svaney-ssman
