### ISSUE TITLE
Refactor BlockHub to support multiple editor 

### ISSUE THREAD

**Issue by zzj3720** [toeverything/blocksuite#2445]
Currently multiple BlockHubs overlap in multi-editor scenarios.

https://user-images.githubusercontent.com/17165520/236748767-0717f057-8e2d-4f65-a5d2-e1b96764320d.mp4

Should we move it to the corresponding editor-container, or make sure there is only one BlockHub?

**Comment by doodlewind** [comment]
With the current pattern, it should up to the application level to control the `createBlockHub` API call, and we have no recent plan in revamping this widget. So this is considered a wont fix.
