### ISSUE TITLE
Cant select text when clicking on blank area in edgeless

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#2447]
https://user-images.githubusercontent.com/27926/236778893-b4eff20e-8648-4f3a-b466-22bc156d98f5.mov

**Comment by ShortCipher5** [comment]
Not very consistently reproduced, but still seems to be an issues in the latest version (v0.5.x-staging-36871e1d9667667718c6bee7891d507142cc5f19)

![Select](https://github.com/toeverything/blocksuite/assets/4605025/4d25299e-fe4b-465c-b406-4ff614dc4470)

**Comment by joebeijing** [comment]
Can not reproduce it in the latest beta.
