### ISSUE TITLE
Support row-level database selection after clicked on row-level drag handle

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2468]
An example would be kind of similar with GitHub project:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/7312949/237052378-91f3e4a3-7cb8-47c6-a9f4-e0c37c825c24.png">

**Comment by hwangdev97** [comment]
The design part:
<img width="554" alt="shot-2023-05-15-11 31 52@2x" src="https://github.com/toeverything/blocksuite/assets/24713927/4f9aef7a-7d0e-4829-9e0d-607e204d7b3d">


Add new color for selection background color
`primaryColor04` : `rgba(84, 56, 255, 0.04)`


And the border:
```
 border: 2px solid var(--primaryColor);
 border-radius: 2px;
```
