### ISSUE TITLE
Unreliable `tryUpdateFrameSize`

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2475]
Currently, the `tryUpdateFrameSize` method is used to update `xywh` of frame blocks, setting the block model size using the DOM size. This runs on `firstUpdated` of the edgeless mode, and every time a user inputs (`keydown`) on doc mode.

This is unreliable since:

1. This potentially lead to inaccurate zoomed frame size.
2. The frame size can also be wrong when user resize the browser viewport and input something, which will update the frame size according to the (incorrect) resized width under the page mode.

So further refactoring is required for fixing related bugs.

**Comment by QiShaoXuan** [comment]
I think we need add a flag on the fram block to tag has it be handle by user self, if not, we chould change it size automaticaly, or it should be maintained it size.
Otherwise user changes a frame block's size by himself, but after input someting, it is confusing that block's size is also changed

**Comment by doodlewind** [comment]
This can be closed by #3424 since we don't have architectural issue under the hood now.
