### ISSUE TITLE
The database search should not display a clear button when no keywords are entered

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2497]
![CleanShot 2023-05-10 at 6 15 55@2x](https://github.com/toeverything/blocksuite/assets/22443345/5bfc0d13-bbf3-4f07-bec2-4668cd77f19a)
CC @hwangdev97

**Comment by hwangdev97** [comment]
I think this is right

**Comment by hwangdev97** [comment]
cc @zqran
