### ISSUE TITLE
Database column drag and drop optimization

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2498]
Expected behavior:

1. When hovering over the drag-and-drop button or after activating drag-and-drop, the mouse cursor could turn into a hand gesture
2. Long-pressing the column header for a period of time can directly activate drag and drop
3. The mouse position during drag and drop should remain consistent with the position when drag and drop was activated

**Comment by doodlewind** [comment]
The long press one may require more effort, this issue could be closed after others 2 ones are fixed.
