### ISSUE TITLE
Support sub-rows in database block

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2500]
![CleanShot 2023-05-10 at 6 43 04@2x](https://github.com/toeverything/blocksuite/assets/22443345/94f904df-59dd-4c93-b30f-1334fb9b46f4)
The sub-rows after conversion do not meet expectations, I am currently unable to convert to get sub-rows, nor can I generate sub-rows using the Tab key.
<img width="553" alt="CleanShot 2023-05-10 at 6 44 04@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/213dcede-f6cc-4696-a09b-2a359ef9a7b5">

**Comment by doodlewind** [comment]
Tracked in #5385
