### ISSUE TITLE
Support full-width display for database block

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2517]
- The default is still to align with the standard width of the editing area.
- It supports manually switching between standard width and full width.
- There is no such option in Edgeless mode because it always displays in alignment with the width of the editing area.

**Comment by hwangdev97** [comment]
The full-width database design is complete:

![image](https://github.com/toeverything/blocksuite/assets/24713927/2eadbc4e-d7f9-4e1c-b92c-763b0874774f)


[internal link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=2830%3A75722&t=dB9IqGYM6UvleJoq-1)


cc @zqran

**Comment by doodlewind** [comment]
Related to #2515

**Comment by doodlewind** [comment]
Reopened since the support is not landed yet due to underlying support.

**Comment by doodlewind** [comment]
Tracked in #5385
