### ISSUE TITLE
Optimizing the line weight icon in edgeless mode

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#2518]
<img width="552" alt="shot-2023-05-11-10 02 10@2x" src="https://github.com/toeverything/blocksuite/assets/24713927/fd76357a-df4e-4f59-af86-259f0462c070">

Icons with varying line thickness and color are very similar, so I suggest changing the icons to make them easier to distinguish.

**Comment by Svaney-ssman** [comment]
Please check the newest design in [figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=4700-109884&t=wGW1FeD8ayrMYJtE-4) @Flrande 
<img width="536" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/a38c9a8d-c660-4b3b-8354-aa1c6b5a6997">

**Comment by doodlewind** [comment]
Let @Flrande to temporarily assigned this before we have new members 👀
