### ISSUE TITLE
Add same level list block before first list block

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#2522]
<img width="442" alt="Screenshot 2023-05-11 at 11 08 36 AM" src="https://github.com/toeverything/blocksuite/assets/27926/401510ee-9b07-4510-a45d-7aef0bb4c466">

Currently, when I want to insert a list block of the same level in front of the first list block, it is expected that `sdf` should become the first list block.

**Comment by doodlewind** [comment]
Closing since this following process (based on my understanding) works as expected:

https://github.com/toeverything/blocksuite/assets/7312949/7ec2f0e8-3c1c-4cd1-8590-b6305b9f1a6a

But feel free to re-open if it's not the case you proposed!
