### ISSUE TITLE
When the divider is entered through the command, the page turns black.

### ISSUE THREAD

**Issue by BedBear** [toeverything/blocksuite#2547]
<img width="570" alt="image" src="https://github.com/toeverything/blocksuite/assets/8636635/4fbd269d-1a8e-474e-95b2-4f832c8bfaa1">

npm packages
`
"@blocksuite/blocks": "^0.0.0-20230510195934-c3adecb7-nightly",
"@blocksuite/editor": "^0.0.0-20230510195934-c3adecb7-nightly",
"@blocksuite/store": "^0.0.0-20230510195934-c3adecb7-nightly",
`

**Comment by doodlewind** [comment]
Sorry for the regression! We'll handle this at the earliest opportunity.

**Comment by doodlewind** [comment]
We've temporally hidden the divider entry in #2599, and we are unable to reproduce this for the moment.
