### ISSUE TITLE
Database interactions - horizontal scrolling

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#2549]
User experience for scrolling horizontally and adding columns can be improved.

Difficult to interact with anything off-screen.

![image](https://user-images.githubusercontent.com/4605025/237557903-da171584-fa95-49c2-a1d6-f2ef802bcafb.gif)

**Comment by zqran** [comment]
This issue has been fixed by #2487, after the Affine client updates the BlockSuite version, you can see the scroll bar when you move the mouse over the database body.
