### ISSUE TITLE
The keyboard shortcut for Selecting All  inside the Text component in Edgeless is different from that in Page

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2556]
Expected effect：
Whether in Page or Edgeless mode, the action of Selecting All should select the entire block instead of just the text inside the block.

**Comment by QiShaoXuan** [comment]
If no frames are activated, Select All should select all frames

**Comment by doodlewind** [comment]
Related to #2706

**Comment by doodlewind** [comment]
Supported in latest playground

https://github.com/toeverything/blocksuite/assets/7312949/d4f061df-0e69-4526-9a2c-e9dd415a3bda
