### ISSUE TITLE
The Divider option should not be displayed in the block dropdown menu of the Balloon Toolbar

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2577]
![CleanShot 2023-05-15 at 5 15 46@2x](https://github.com/toeverything/blocksuite/assets/22443345/4b13bd06-41bc-4a7e-abca-8dd36de1262c)

**Comment by xell** [comment]
Because the Deivider is obviously different from other items, which are all kind of turning-into, @joebeijing might have to propose a new arrangement for it instead of just removing it.

**Comment by joebeijing** [comment]
> Because the Deivider is obviously different from other items, which are all kind of turning-into, @joebeijing might have to propose a new arrangement for it instead of just removing it.

This is the conversion feature of the Balloon Toolbar, which is not quite suitable for non-text blocks to appear here, including future ones such as Bookmark and Embed Web. However, they will definitely be available in the Block Hub.

**Comment by xell** [comment]
> > Because the Deivider is obviously different from other items, which are all kind of turning-into, @joebeijing might have to propose a new arrangement for it instead of just removing it.
> 
> 
> 
> This is the conversion feature of the Balloon Toolbar, which is not quite suitable for non-text blocks to appear here, including future ones such as Bookmark and Embed Web. However, they will definitely be available in the Block Hub.

Understandable. So @doodlewind can simply remove it from the toolbar to close this issue
