### ISSUE TITLE
When the search box is expanded in the database, the interface experiences is shaking

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2579]
https://github.com/toeverything/blocksuite/assets/22443345/c2005d86-4ea3-4b7f-a69a-873176342dd9

The New Record button has shifted slightly to the right.

**Comment by hwangdev97** [comment]
I think part of the reason here is due to the inadequate width of the editing area, but specific reasons still need to be verified and checked with @zqran

**Comment by zqran** [comment]
> I think part of the reason here is due to the inadequate width of the editing area, but specific reasons still need to be verified and checked with @zqran

Yes, that's why.
