### ISSUE TITLE
Unable to drag and drop images to rearrange them

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2580]
https://github.com/toeverything/blocksuite/assets/22443345/3e35964b-8a1c-4eec-abe4-1dae036f444c

It should be equivalent to clicking the drag handle to drag and rearrange the images.

**Comment by doodlewind** [comment]
Also reported in #4023, we should plan for the support. /cc @Saul-Mirone to confirm if our event dispatcher infra is ready for this.

**Comment by water-in-stone** [comment]
I am experiencing the same issue. Kindly assign the bug to me, and I will submit a pull request.

**Comment by water-in-stone** [comment]
I misunderstand the context of this issue. Please offer more information about it. @houjoe0829

**Comment by water-in-stone** [comment]
It's better if you can offer video instead of text.

**Comment by houjoe0829** [comment]
> It's better if you can offer video instead of text. @houjoe0829

This is similar to the operation in our other similar tools. When you long-press an image, you can drag it to adjust its position, as shown in this screenshot example.

https://github.com/toeverything/blocksuite/assets/22443345/987614e3-9048-484d-94a4-30dd81e08216

**Comment by xell** [comment]
I understand that the operation of moving elements via long click is, at least in macOS and iOS, a system predefined action, by which not only image but also characters are valid targets (see the screenshot in Pages.app). However, considering we now have a new version of drag handle, I suggestion to postpone this function in the future. When it's ready we'll consider implementations exactly like that, i.e. for both images and other selection contents.


https://github.com/toeverything/blocksuite/assets/132558/1eb1c92e-02fa-4e6d-862e-622dcc02c634

**Comment by water-in-stone** [comment]
LGTM. Kindle notify me once the updated version of drag handle is released.

**Comment by water-in-stone** [comment]
> I understand that the operation of moving elements via long click is, at least in macOS and iOS, a system predefined action, by which not only image but also characters are valid targets (see the screenshot in Pages.app, in which I intentionally use it to show the universal characteristic of this operation). However, considering we now have a new version of drag handle, I suggestion to postpone this function in the future. When it's ready we'll consider implementations exactly like that, i.e. for both images and other selection contents.
> 
>  CleanShot.2023-08-31.at.09.21.43.mp4

LGTM. Kindle notify me once the updated version of drag handle is released.

**Comment by xell** [comment]
> LGTM. Kindle notify me once the updated version of drag handle is released.

You could try it in [internal version](https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-internal.20230830180443-13323bc) .

**Comment by lawvs** [comment]
Closed in https://github.com/toeverything/blocksuite/pull/4741
