### ISSUE TITLE
scaling in edgeless mode incorrect

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#259]
https://user-images.githubusercontent.com/14026360/205673464-2309834e-8f7d-4edd-8f51-50b64aef73b9.mov

**Comment by doodlewind** [comment]
Could not reproduce on latest master, any prerequisites?

**Comment by himself65** [comment]
> Could not reproduce on latest master, any prerequisites?

Still looking for a way to reproduce🤔

**Comment by himself65** [comment]
I think this has been fixed during development of edgeless mode
