### ISSUE TITLE
Once a page has been deleted, it should not be searchable even if it's being @-mentioned

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2592]
![CleanShot 2023-05-16 at 11 47 12@2x](https://github.com/toeverything/blocksuite/assets/22443345/f7d32fa5-a77d-4f25-991c-5cad45a0bb8c)

**Comment by doodlewind** [comment]
Related to #3059

**Comment by doodlewind** [comment]
This is not fixed, should be kept tracking in #3059
