### ISSUE TITLE
Database supports right-click menu

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2606]
Options
- Insert row above
- Insert row below
- Insert left column
- Insert right colum
- Delete row
- Delete column
- Delete database

**Comment by zzj3720** [comment]
Currently, we support right-clicking on row and column header to bring up a pop-up menu, as follows
<img width="857" alt="image" src="https://github.com/toeverything/blocksuite/assets/17165520/4b5adef8-4954-44fa-8b33-876f64fdf54e">
<img width="863" alt="image" src="https://github.com/toeverything/blocksuite/assets/17165520/009cb08a-3975-478d-b1af-29b4ab916455">
Do we need more?

**Comment by houjoe0829** [comment]
For the right-click menu, it is already sufficient.
