### ISSUE TITLE
Support rotating shapes in edgeless mode

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2608]
It would be better to support the rotation of all elements except for Note, such as Text, Shape, Pen, images, and so on, on the whiteboard.

**Comment by fundon** [comment]
@joebeijing Need a rotating cursor style.

For cross-platform, a unified set of styles may be required, such as resize, hand.

**Comment by joebeijing** [comment]
> @joebeijing Need a rotating cursor style.
> 
> For cross-platform, a unified set of styles may be required, such as resize, hand.
> 
> https://mac-cursors.netlify.app/

@xell Could you take a look at this? a rotating cursor style.

**Comment by xell** [comment]
A rotation cursor shape was sent to the developer and it can be previewed in the https://github.com/toeverything/blocksuite/pull/2931 now.
