### ISSUE TITLE
The exit logic of the code block does not meet expectations

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2609]
The current actual effect is that the cursor exits the Code Block when pressing Enter in blank lines at the end of the Code Block. With the current effect, the cursor exits the Code Block too easily, which should be different from the behavior of Quote.

https://github.com/toeverything/blocksuite/assets/22443345/8ffc72ad-90e6-4676-a99d-f52d1a7bd432

Expected  effect:
- While adding blank lines at the end of the Code Block, followed by two empty lines(excluding the first line), pressing the Enter key again will cause the cursor to exit the Code Block and delete the last two empty lines
- Using the shortcut keys Ctrl/⌘/Shift + Enter repeatedly could add empty lines without the cursor exiting the Code Block.

**Comment by fourdim** [comment]
We should reconsider this behaviour. My suggestion is to use Ctrl/⌘/Shift + Enter to exit the code block. Pressing the Enter solely will just add new lines to the code block. This is more intuitive.

**Comment by doodlewind** [comment]
@fourdim this sounds very reasonable! PR welcome :)

**Comment by houjoe0829** [comment]
This is not the expected result. We have discussed this with @HeJiachen-PM  before and we need to support the use of the Enter key to exit Code Block, List, Quote and other blocks. We can also support Shift + Enter, but the visibility for users is poor.

**Comment by doodlewind** [comment]
No, I insist current behavior LGTM
