### ISSUE TITLE
Console error on repeating range selection

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#261]
I did a quick search and it seems that this is introduced by #209 @thorseraq 

This doesn't affect usability, so it's tolerable and doesn't have top priority for now.

https://user-images.githubusercontent.com/7312949/205709268-0eef7a22-f565-45b4-bd36-b1c9e5154f57.mov

**Comment by lawvs** [comment]
@thorseraq plan to fix this issue on https://github.com/toeverything/blocksuite/pull/246

**Comment by lawvs** [comment]
#246 there are still some bugs that need to be dealt with.

https://user-images.githubusercontent.com/18554747/209496795-4398db5c-866e-4add-9a52-362375c04d27.mov

**Comment by thorseraq** [comment]
OK! Will look through this problem

**Comment by thorseraq** [comment]
This unstable native selection behavior is improved by #588

**Comment by doodlewind** [comment]
Closing this since it does not reproduce after #588. Thank @thorseraq for improving our stability!
