### ISSUE TITLE
The bullet points will break the boundary of the doc if users continue typing and retracting the bullet point

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/blocksuite#2629]
![image](https://github.com/toeverything/AFFiNE/assets/121489905/ed0d771b-88a5-47ce-999a-534840805d77)

**Comment by doodlewind** [comment]
Fixed in latest playground

<img width="470" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/2bc5bbdf-2113-49ce-a024-2a472696a79a">
