### ISSUE TITLE
The words in the front are indented forward as I continuously type

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/blocksuite#2631]
![111](https://github.com/toeverything/blocksuite/assets/7312949/5633897e-f96d-4763-abf7-a4ae806031ff)

**Comment by doodlewind** [comment]
This works as expected in code block, or you can use the wrap code option:

<img width="1026" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/dffa01a9-f3b6-4b90-9ae9-9d5701af2d76">

**Comment by doodlewind** [comment]
Seems to be a Windows-specific issue related to incorrect line offset.

**Comment by xell** [comment]
Closed as not being able to reproduced in neither virtual nor real Windows environments.
