### ISSUE TITLE
The database separator line is not displaying correctly

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#2639]
![image](https://github.com/toeverything/blocksuite/assets/50035259/0395a3eb-2925-4f72-bd5b-808a3dfa5f87)

**Comment by hwangdev97** [comment]
I think this is an issue with the dark mode, and we will address it during the dark mode optimization in this iteration.

**Comment by zqran** [comment]
![Image](https://github.com/toeverything/blocksuite/assets/15389209/7e993bf0-7982-4a88-a337-2b3665b90059)


Closed because this question no longer exists.
