### ISSUE TITLE
If blockHub is open, clicking the blockHub icon in the row does not respond

### ISSUE THREAD

**Issue by imyuanx** [toeverything/blocksuite#2644]
If blockHub is open, clicking the blockHub icon in the row does not respond
I not sure this rule is a feature or bug, but I feel confused about this rule.
I think we can toggle blockHub when we clicking the blockHub icon in the row, not just open.
If this proposal is accepted, I can provide a PR.
<img width="1440" alt="image" src="https://github.com/toeverything/blocksuite/assets/50652358/2e55d733-b025-433c-9f33-d670bf6a427b">

**Comment by imyuanx** [comment]
### Preview

https://github.com/toeverything/blocksuite/assets/50652358/a7bdad04-89ab-4551-a5b3-449be3275794

**Comment by doodlewind** [comment]
Its nice to have, would be great if you can try for a fix!
