### ISSUE TITLE
To-do lists can turn into database table entries immediately​

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/blocksuite#2660]
### Description

In Quire.io, when a user is on the List mode, when they type an entry, after pushing enter, the line immediately is entered as a task in the software.
When they press enter again, it becomes another task.
If they push the tab key, it becomes a sub-task to the task above it.

These tasks can be viewed in a kanban board, with the subtasks populated within each card.

Affine would benefit from a similar feature, this is very useful for creating and assigning tasks to teams that are in high volume environments and don't want to refactor notes and assign work later on. (ie. for teams with no time or people to review meeting minutes.)

### Anything else?

quire.io task list & sub-task list feature is very slick.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for this feature request! /cc @joebeijing for related planning that turns list items into database.

**Comment by joebeijing** [comment]
We have currently supported the conversion to this method. Does this solve your problem?  @SolarDesalination 
https://github.com/toeverything/blocksuite/assets/22443345/ffce547f-722d-4115-9ad0-e6364c19e3a9

**Comment by SolarDesalination** [comment]
@joebeijing that's really slick, I've never seen anything like that before.

It solves the part of operationalizing a to do list into an action item list, and I will definitely use this. 

There's a second part of it though which is, I would ideally like each line in the editor, once flagged as a to-do item (or having a certain attribute attached to the line item if not the checkbox but something else), that it would sync between the list and the table. So if I updated the list, it will update the table, and vice versa. Sort of like the row becomes a bi-directional synchronized cell from the table to the line of text. I don't know if it's feasible at the moment but that would allow me to create a to do list, track the to do list in a table, and see it get completed from a kanban/table and the list at the same time. 

I could have a meeting list to my leadership and it would be updated in real time when my development team finished tasks in the table.

Maybe I should mark this issue as complete and then create a new one for the more fanciful part of the request?

**Comment by joebeijing** [comment]
Thank you again for your support and feedback. The new task system for AFFiNE is indeed in our roadmap, but it hasn't started yet. We will create an issue to keep track of it. You can click here to follow the progress. https://github.com/toeverything/AFFiNE/issues/2662
