### ISSUE TITLE
Unable to paste in image caption input

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#2663]
There seems to be a bug where the image caption feature doesn't support pasting.

When I try to paste text into the image caption, it replaces the image instead of adding the text.

https://github.com/toeverything/blocksuite/assets/24713927/afd07362-8f31-4d40-a05f-dbb66fa2485f

**Comment by lawvs** [comment]
I think this issue also related to https://github.com/toeverything/blocksuite/issues/2495
