### ISSUE TITLE
Add Email Field for Database Block

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2669]

**Comment by water-in-stone** [comment]
Please assign this issue to me, I will submit a pull request.

**Comment by houjoe0829** [comment]
> Is implementation still needed? If so, please assign this issue to me , I will submit a pull request.

Sorry, currently this is not in the current iteration and there are no design resources involved yet. Please be patient and wait a bit, thank you very much.

**Comment by doodlewind** [comment]
Tracked in #5385
