### ISSUE TITLE
Add Phone Field for Database Block

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2670]

**Comment by water-in-stone** [comment]
Is implementation still needed? If so, please assign this issue to me , I will submit a pull request.

**Comment by houjoe0829** [comment]
> Is implementation still needed? If so, please assign this issue to me , I will submit a pull request.

This is also not within the scope of this iteration. There are currently no design resources available for it, thank you.

**Comment by doodlewind** [comment]
Tracked in #5385
