### ISSUE TITLE
Add Note Field for Database Block

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2672]
- By default, a note icon is displayed. 
- Clicking on the icon will open a pop-up window displaying the content in the Note block. 
- The Note block is a Block Editor block without a title.

**Comment by houjoe0829** [comment]
Note field is different from 'multi-line text' and is a complete block editor.

**Comment by doodlewind** [comment]
After discussion with @zzj3720, this sounds reasonable and we will consider related support.

**Comment by doodlewind** [comment]
https://github.com/toeverything/blocksuite/assets/7312949/738c9e2c-25a8-4018-b7cd-c93a6b29ce13

Currently this can be considered as supported. The popup window has landed, and the block text field inside the popup supports rich text editing.
