### ISSUE TITLE
The select column of database supports keyboard operation

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#2681]
Such as:

1. `ArrowDown`/`ArrowUp` keys to switch options.
2. `Enter` key to select option.

/cc @joebeijing

**Comment by zqran** [comment]
This feature relies on the cell-level selection of the Database. 
Relate to: #2665

**Comment by joebeijing** [comment]
Whether it is a select or multi-select field, users could use arrow keys and Enter key for selection and confirmation.
