### ISSUE TITLE
Support holding Shift+Down to select next line

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/blocksuite#2684]
### What happened?

On the linux version, when my text cursor is on a line, and I have text on another line below it, the expected use is that when hold the shift key and push down, that the next line of text is also highlighted. The current editor doesn't enable a shift-down text cursor highlight function.

Using Linux version.

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
This is a common issue on both platforms

**Comment by doodlewind** [comment]
This is partly supported if you are using block level selection:

https://github.com/toeverything/blocksuite/assets/7312949/1e5f4498-5227-4278-a838-34a78e8db4bf

But for the shift+down support under native text selection,  /cc @Saul-Mirone to tell if this is a low-hanging fruit.

**Comment by Saul-Mirone** [comment]
> This is partly supported if you are using block level selection:
> 
>  Screen.Recording.2023-08-16.at.13.06.39.mov 
> But for the shift+down support under native text selection, /cc @Saul-Mirone to tell if this is a low-hanging fruit.

I don't think there're any low-hanging fruit for now. We can roughly support the feature  since we already have the <kbd>ArrowDown/ArrowUp</kbd> supported. However there're a lot of edge cases for keyboard navigation, we still need to polish and test every edge cases.
