### ISSUE TITLE
Allow page width adjustments

### ISSUE THREAD

**Issue by nooz** [toeverything/blocksuite#2685]
### Description

Enable simple page width adjustments, at least (Normal / Wide) options,  as a LOT of screen space is currently wasted on larger screens
![pagewidth](https://github.com/toeverything/AFFiNE/assets/1309131/33d79df0-a58a-4d39-83e0-7841af02e13a)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nooz** [comment]
just for comparison, here is Notion's page width style
<img width="1916" alt="notion" src="https://github.com/toeverything/blocksuite/assets/1309131/11abef8f-c882-484d-b6b7-34cf2a58b796">

**Comment by nooz** [comment]
and Trilium
<img width="1913" alt="trilium" src="https://github.com/toeverything/blocksuite/assets/1309131/0ca2bb78-349e-4fe4-b0dd-4d5078b3242e">

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/blocksuite/issues/2517

**Comment by doodlewind** [comment]
Supported in AFFiNE

<img width="962" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/65c9391f-0f05-4105-b1da-039be48c3f5d">
