### ISSUE TITLE
After I press Enter on the linked page, the line break appears at the top.

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#2687]
After I press Enter on the linked page, the line break appears at the top.

When I press the left and right keys, it will appear correctly below.

![shot-2023-05-22-09 42 49](https://github.com/toeverything/blocksuite/assets/24713927/b8ea9872-48d8-44b7-abfd-bcd3d8e67b29)

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/blocksuite/issues/2006

**Comment by Flrande** [comment]
fixed in #3659
