### ISSUE TITLE
add color selection in the Shape dropdown menu in Edgeless Toolbar

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2690]
![CleanShot 2023-05-22 at 12 46 54@2x](https://github.com/toeverything/blocksuite/assets/22443345/4a79919b-6c94-41b2-a63f-d12028c3ff56)

**Comment by doodlewind** [comment]
Closing since we have switched to new toolbar in https://github.com/toeverything/blocksuite/issues/3139
