### ISSUE TITLE
Grouping complex list items as database will result in bizarre outcomes

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#2697]
In the following screencast, please refer to the first part "Reference" to compare the strange outcomes.

https://github.com/toeverything/blocksuite/assets/132558/fb231071-a7a8-4162-8928-7192de5cdfcc

**Comment by zqran** [comment]
Since the selected blocks have different parents, should they be converted to Database in this case? /cc @joebeijing

**Comment by zqran** [comment]
This function is related to `Sub-row`, and it will be fixed when `Sub-row` is implemented. /cc @joebeijing

**Comment by zqran** [comment]
I think the function of flattening the list is now implemented.

https://github.com/toeverything/blocksuite/assets/15389209/64f8b883-d9e3-4a6e-a160-30841500cdf2

**Comment by joebeijing** [comment]
Note: According to previous discussions, for the conversion of content with hierarchy, the hierarchy needs to be canceled first before converting to a Database. Once sub-row support is available, the conversion with hierarchy can be done.

**Comment by zqran** [comment]
Closed because it is now supported.
