### ISSUE TITLE
Add a state for when the database is empty

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2727]
When deleting the last row, maintain the state of an empty database. At this point, consider keeping the "New Record" option permanently displayed for the database.

This is different from the previous conclusion in https://github.com/toeverything/blocksuite/issues/2704

**Comment by hwangdev97** [comment]
looks like: 
![image](https://github.com/toeverything/blocksuite/assets/24713927/2c123cc2-2e96-475e-90c5-96006d649c55)
