### ISSUE TITLE
The UI of the checkbox field in Database needs to be optimized

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2729]
<img width="293" alt="CleanShot 2023-05-24 at 3 45 35@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/a78f8f25-29c0-4abf-8eec-c2eb654ec8c3">

**Comment by zqran** [comment]
closed by: https://github.com/toeverything/blocksuite/pull/3240
