### ISSUE TITLE
Add support for the "[" character in the auto-completion and enable the conversion to add Linked page

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2730]
- After selecting text, typing "[" should automatically add it before and after the selected text
- [[Selected text]] should automatically be converted to a Linked page with the title "Selected text".

From @hwangdev97

**Comment by fourdim** [comment]
Just for reference: We use `@AffineReference:(id)` internally See: https://github.com/toeverything/blocksuite/commit/f0dac47eabde3496fd8fadde5820029dbb2ebc52 .
Consider use this design instead in the future.

**Comment by houjoe0829** [comment]
> > After selecting text, typing "[" should automatically add it before and after the selected text
> 
> The automatic completion of parentheses feature has been completed.
> 
> > [[Selected text]] should automatically be converted to a Linked page with the title "Selected text".
> 
> The automatic conversion of selected text into a linked page requires a more detailed product design. Do we need to create a new page for the user?

yes, If [[selected text]] is completed, we need to create a new page for the user.
