### ISSUE TITLE
Doesn't working Ctrl + Z over edgeless mode​

### ISSUE THREAD

**Issue by callmehanu** [toeverything/blocksuite#2732]
### What happened?

Trying to undo some pen traces, I noticed that  undo shortcut doesn't work en edgeless mode. 
I'm on Linux using the latest beta.

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Closing since we've fixed #2648, which will be released in our next beta client. You can checkout https://blocksuite-toeverything.vercel.app/?init for preview.
