### ISSUE TITLE
Selecting the database from a non-editing zone and across a block does not produce the expected result

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2764]
1. If multiple rows are selected, it should select multiple rows of the database, but in reality, it selects the content in the block of the header column.

2. If the entire database is selected, it should select multiple databases, but in reality, it still selects the content in the block of the header column.

https://github.com/toeverything/blocksuite/assets/22443345/30338ccd-51f6-46ed-942c-d3222690a99b

**Comment by doodlewind** [comment]
I think it's better for the drag handle to avoid selecting inner row content of the database block, it will make things more complicated. Always making the drag handle selecting the database block as a whole may make more sense.

But this conflicts with the "drag block into or out of database row" feature, may require more thoughts.

**Comment by joebeijing** [comment]
I have an idea that when selecting a database from a non-editing zone across blocks, the entire database should be automatically selected, and the drag handle could handle the selection and dragging of individual rows within the database. When selecting the database from outside the database, the database should be treated as a single block.
How do you think?

**Comment by zqran** [comment]
closed by: #2773
