### ISSUE TITLE
Support exporting attachment with markdown and HTML

### ISSUE THREAD

**Issue by purpleden** [toeverything/blocksuite#2772]
### What happened?

Exported using both methods, desktop client not exporting images/videos/attachments etc - just the main text

![image](https://github.com/toeverything/AFFiNE/assets/33729019/cec3e99e-b579-4881-92fa-3f882207f2c5)

Table export not working:
![image](https://github.com/toeverything/AFFiNE/assets/33729019/97f1ebf6-3553-4eea-93aa-bf321f95d087)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Supported in latest client.
