### ISSUE TITLE
Add new page buttons in block-hub

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/blocksuite#2779]
![internal link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=3112-66162&t=przHuzetmHYDUWoG-0)

![Image](https://user-images.githubusercontent.com/53252747/241190540-3a3a86e3-01e8-420f-8ce2-352375396f02.png)

**Comment by doodlewind** [comment]
Closing since the revamped design of block hub is raised by TBD
