### ISSUE TITLE
Unable to operate on bookmark using enter and tab

### ISSUE THREAD

**Issue by darkskygit** [toeverything/blocksuite#2782]
### What happened?

![84322991-fa39-42c3-8625-06e2c15e4dbb](https://github.com/toeverything/AFFiNE/assets/25152247/9034b1ad-5860-4eb1-8b90-013f2e075e33)
in this dialog, cannot use enter to close the dialog
and unable to move focus to save button using tab key

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by QiShaoXuan** [comment]
fixed: https://github.com/toeverything/blocksuite/pull/2818/commits/de56538ffd5ba4d098a32eab216e56add4b3950d
