### ISSUE TITLE
Unable to load bookmark preview content

### ISSUE THREAD

**Issue by darkskygit** [toeverything/blocksuite#2783]
### What happened?

![23qboMtaVI](https://github.com/toeverything/AFFiNE/assets/25152247/574dbe73-f0ea-4d99-b5a7-d74e5c4a7887)
website title, description, favicon etc.

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by QiShaoXuan** [comment]
fixed: https://github.com/toeverything/blocksuite/pull/2871/commits/9555106902f2bf084d08a40d5af6579bda89b8c1
