### ISSUE TITLE
Editor crash after zooming during input canvas text

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2784]
To reproduce:

1. Input canvas text and keep the editing state.
2. Zoom out.

https://github.com/toeverything/blocksuite/assets/7312949/66761df8-27e8-4a4a-bee6-16bce60b6b69

<img width="1294" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/1031a012-cc2d-4301-8962-c792c86f9586">

@Flrande seems that this is something to do with the grid manager 😥

**Comment by Flrande** [comment]
Can you reproduce it in newest commit?

**Comment by doodlewind** [comment]
Not reproduced locally, cheers :)
