### ISSUE TITLE
Unable to paste text from Tencent QQ

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#2787]
Version: AFFiNE 0.5.4-beta.2
OS: Windows 10 22H2

In Tencent QQ, the text is stylized and can not be paste to the editor.

To reproduce:

https://github.com/toeverything/blocksuite/assets/59462000/c8e2861e-2131-4bd1-aa1e-d0fe34e70659

**Comment by lawvs** [comment]
Could you attempt to access the console by pressing `Ctrl+Shift+I` and furnish us with the error logs?

**Comment by fourdim** [comment]
![image](https://github.com/toeverything/blocksuite/assets/59462000/e6ccf524-7cbe-46ff-9516-00863986f5b6)
Here are the logs, but none of them related to the paste operation.
