### ISSUE TITLE
Multi-level headings are displayed without distinction.

### ISSUE THREAD

**Issue by IndifferentArea** [toeverything/blocksuite#2792]
### What happened?

Hey! I just heard about AFFINE, it's a really amazing production! 

But when I was trying it online it seems that there is no distinction displayed but block width between multi-level headings, I think distinction of font size is a basic feature for an editor supporting `md` syntax. (and better with small mark!)

![image](https://github.com/toeverything/AFFiNE/assets/74698401/3353238a-8832-489a-aff6-4567e5a3bb32)

Is it a bug or just unsupported feature? 

Forgive me for my poor English plz.

### Version

app.affine.pro

### What browsers are you seeing the problem on?

Microsoft Edge

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
I think different heading are styled, wondering how to reproduce this?

![image](https://github.com/toeverything/blocksuite/assets/7312949/60b085d6-e5bb-4b63-a937-7a2f18f51dc3)

**Comment by IndifferentArea** [comment]
Maybe I didn't explain it clearly, I mean I tried it online, and three `ds` is proceeded by different number of `#`s.

**Comment by doodlewind** [comment]
@Svaney-ssman could you please take a look about it our current heading margin and font size works as expected? Thanks!

**Comment by zqran** [comment]
@IndifferentArea, are you using the web version of Affine(https://app.affine.pro/)?

**Comment by IndifferentArea** [comment]
> @IndifferentArea, are you using the web version of Affine(https://app.affine.pro/)?

@zqran Yeah

btw, I remember adding issue in AFFINE, was it relayed here?

**Comment by zqran** [comment]
This is because the web version of Affine has not been updated, you can use the client version(https://affine.pro/download or https://github.com/toeverything/AFFiNE/releases) to get the latest features.

> btw, I remember adding issue in AFFINE, was it relayed here?

This issue appears here because @Himself65 transferred this issue from toeverything/AFFiNE. You can see above.

**Comment by IndifferentArea** [comment]
Got it. Thx

**Comment by Svaney-ssman** [comment]
> @Svaney-ssman could you please take a look about it our current heading margin and font size works as expected? Thanks!

This is a bug, the design is supposed to be the same as in blocksuite.
