### ISSUE TITLE
The Fit to screen, Zoom in and Zoom out icons could not be seen when edgeless mode.

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#2795]
![edgeless-mode-zoom-icons](https://github.com/toeverything/blocksuite/assets/99816898/8b21f118-2c6e-460e-95c4-d9bc0280716b)
![edgeless-mode-zoom-icons-didn't-show](https://github.com/toeverything/blocksuite/assets/99816898/fed18339-c056-49c6-b198-746caaad963d)

**Comment by donteatfriedrice** [comment]
@doodlewind  How can I add label to this issue and contribute to this repository? It seems that I don't have the write auth to this repo. It is my first time to try to contribute to an open source repo. I appreciate the time you look at this comment. Thanks!

**Comment by doodlewind** [comment]
Hi @donteatfriedrice, the common practice is to fork this repo (.e.g., to *github.com/donteatfriedrice/blocksuite*) and open pull request to upstream. We'll continue the code review regarding the PR. Otherwise one maintainer would have to grant everyone write access so as to contribute, which doesn't make sense.

**Comment by donteatfriedrice** [comment]
> Hi @donteatfriedrice, the common practice is to fork this repo (.e.g., to _github.com/donteatfriedrice/blocksuite_) and open pull request to upstream. We'll continue the code review regarding the PR. Otherwise one maintainer would have to grant everyone write access so as to contribute, which doesn't make sense.
> 
> Would love to see your fix!

OK. Thanks for your reply!

**Comment by donteatfriedrice** [comment]
fix by #2699.
