### ISSUE TITLE
Incorrect UI text on `HTML` spelling

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#2798]
On import modal Html should be HTML.

<img width="453" alt="Screenshot 2023-05-26 at 16 34 30" src="https://github.com/toeverything/AFFiNE/assets/4605025/1e8421be-7b91-40e8-a9f9-e231ada9231b">

**Comment by doodlewind** [comment]
> can i be assigned to fix this typo?
> 
> edit: my bad just came across docs that mentioned i can just submit a PR. there is no practice of issue assignment here :)

Sure, PR welcome :)
