### ISSUE TITLE
Pressing enter at the middle of parent list also indents its children 

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/blocksuite#2801]
### What happened?

See attached gif. When pushing enter in the middle of a line, the output creates a bunch of sub-points and the text dissappears.
Linux version, latest Beta.

![Peek 2023-05-27 20-01](https://github.com/toeverything/AFFiNE/assets/51060565/d3a56137-0d84-4c3e-812c-b4ce4fb87d1e)

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for your report and it's a good catch!

I found a simpler reproduction:

https://github.com/toeverything/blocksuite/assets/7312949/85d99272-3243-4d92-aa24-4073b45a7432
