### ISSUE TITLE
Support edge cases of cursor keeping

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2805]
For example, when cursor is at the start. of the first paragraph block, pressing  `ArrowLeft` should locate the cursor to the page title.

**Comment by tillkwl** [comment]
If this is still due Id like to work on fixing this

**Comment by doodlewind** [comment]
@tillkwl surely welcome!

**Comment by tillkwl** [comment]
#2973

**Comment by doodlewind** [comment]
@Saul-Mirone seems here are regressions about pressing arrow keys in page block title.

**Comment by doodlewind** [comment]
Closing since we've supported `ArrowDown` from the page title.
