### ISSUE TITLE
In title line, press key DownArrow will create a new line

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#2807]
https://github.com/toeverything/blocksuite/assets/41265413/a7da4fe3-c4db-44b8-937a-d0849c97b0d5

**Comment by tillkwl** [comment]
Hello, I've looked into this issue and I think I understand what might be causing it. If it's alright, I'd like to work on fixing this. If anyone has any additional insights or suggestions, they would be greatly appreciated. I'll keep this thread updated on my progress.
