### ISSUE TITLE
tooltips should not perform any action when hover over

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#2814]
The interaction should not be there, and there is no relevant explanation. I suggest removing "lean more"

![Image](https://github.com/toeverything/blocksuite/assets/24713927/0c6ab320-ea08-4860-b4b2-b1d7b359d83a)

**Comment by zqran** [comment]
The relevant documentation is here:
[internal link](https://toeverything.feishu.cn/wiki/wikcnSQ16ZxsWMikiI4gc3HO2jb?comment_id=7215515813378211844&comment_anchor=true).

**Comment by xell** [comment]
@joebeijing please see if there's inconsistency on PRD and/or need to change the content.

**Comment by joebeijing** [comment]
@xell 
This is the effect I was originally hoping for.
https://github.com/toeverything/blocksuite/assets/22443345/2f909577-e4da-4dfb-933d-dd67b705f70b

After discussing with @hwangdev97 , he believes that the current implementation of Hovertips may not be able to achieve a smooth effect similar to what we wanted. He suggests changing it to a Toast form instead, where users can always click, but a message will appear when they encounter Blocks which cannot be converted. The drawback of this approach is that the logic that uses after-the-fact validation only give users negative feedback when they are unable to convert.

If we ignore this negative impact, we can simply show a prompt to the user when they are unable to click on certain elements. The message should read: "Unable to be grouped as Database. There are blocks that cannot be converted. **View all**"
And Clicking on "View all" will open an FAQ of which blocks cannot be converted to the Database.

**Comment by joebeijing** [comment]
Currently, block types such as code blocks, databases, and references cannot be grouped as Databases. We need an FAQ to explain this, and after changing to the Toast form, users should be directed to this FAQ.  @ShortCipher5  Can you have a look?  As we have previously discussed it in the internal doc.
