### ISSUE TITLE
put import feature into web worker

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#2816]
Currently it will block the UI thread and make our affine very laggy

**Comment by himself65** [comment]
I would suggest to use https://www.npmjs.com/package/async-call-rpc

**Comment by doodlewind** [comment]
The plan is to use the new transformer API (#3165) to support the format importer, which is supported to be compatible without DOM. Based on this plan, it's a non-goal to port current `ContentParser` to web worker.
