### ISSUE TITLE
Cursor position with code block

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#2822]
It seems that there are some problems with the key down events of code block.

1. When the cursor is in the last code line, user press arrowdown, the cursor would not move to next block.
2. When cursor is at the block before code block, then press arrowdown, it will focus on the whole code block, not the first code line of this code block.
3. When cursor is at the block after code block, then press arrowup, it will focus on the whole code block, not the last code line of this code block.

https://github.com/toeverything/blocksuite/assets/99816898/c6ef4257-1331-403c-bcef-391a48fe3335

**Comment by doodlewind** [comment]
This is fixed by #3408 (or ongoing PRs about selection refactoring). Cheers!
