### ISSUE TITLE
Long title in bookmark block results in incorrect display

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#2823]
Please see the screenshot:

<img width="687" alt="CleanShot 2023-05-29 at 15 07 17@2x" src="https://github.com/toeverything/blocksuite/assets/132558/5486e699-e4ff-455b-8b4c-e1dd69978340">

**Comment by QiShaoXuan** [comment]
fixed: https://github.com/toeverything/blocksuite/pull/2818/commits/2f89d6f778e96f85ac797391b80cad92626fef02
