### ISSUE TITLE
Dragging head columns in database block unexpectedly selects rows below

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#2829]
This is by design? The UX is not very good.

https://github.com/toeverything/blocksuite/assets/41265413/52441b4e-75b1-4056-845b-46b0506ff70b

**Comment by zqran** [comment]
Where are you using database? BlockSuite or Affine?

**Comment by Innei** [comment]
> Where are you using database? BlockSuite or Affine?

BlockSuite Playground

**Comment by zqran** [comment]
https://github.com/toeverything/blocksuite/assets/15389209/28e2cc2d-a7a8-4767-a435-117b6ca7237b

I can't reproduce it in https://blocksuite-toeverything.vercel.app/?init=database.

**Comment by Innei** [comment]
Okay, I just tried it again, and there's a precondition for reproducing the problem.

https://github.com/toeverything/blocksuite/assets/41265413/23dae6ec-150b-447d-8992-eb15d5b8d369

Select any database block and then drag and drop the table header.
