### ISSUE TITLE
When press `Enter` twice in code block, the cursor always move to next block and clear the new line end of the code block

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#2830]
As a rule of thumb, two carriage returns in code block should not eliminate styling

https://github.com/toeverything/blocksuite/assets/41265413/bc571910-ead1-4bd5-8a84-c56bd1782281

**Comment by doodlewind** [comment]
The expected behavior is what #2609 wants to improve, let's track it there and this is also a help wanted one!
