### ISSUE TITLE
Cursor can't move to next line in code block, if the initial cursor is the last character of the last line

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#2831]
https://github.com/toeverything/blocksuite/assets/41265413/b2bd2db2-66d3-44ca-a623-2010e9ca515c

**Comment by Flrande** [comment]
![20230529175716_rec_](https://github.com/toeverything/blocksuite/assets/50035259/af2eeb69-ccd2-44cd-8bfe-d0c74ee0e309)

I can't reproduce it. Can you log the range?

**Comment by Innei** [comment]
> ![20230529175716_rec_](https://user-images.githubusercontent.com/50035259/241704817-af2eeb69-ccd2-44cd-8bfe-d0c74ee0e309.gif)
> 
> I can't reproduce it. Can you log the range?

This is a fixed reproduction path, first, create a multi-line code block, then click on the block outside the code block, then click again into the code block to reproduce the issue.

https://github.com/toeverything/blocksuite/assets/41265413/f7cd79d0-d583-4167-b789-b294be18b3da
