### ISSUE TITLE
In multi-level lists, using the backspace key display wrong style and broken list structure

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#2835]
https://github.com/toeverything/blocksuite/assets/41265413/ff3efa7c-7d7c-42d4-b41a-43d5f5eec85d

**Comment by doodlewind** [comment]
Not reproduced in latest playground, cheers!

https://github.com/toeverything/blocksuite/assets/7312949/218bb440-db58-4070-8c45-bd3b8d0668c8
