### ISSUE TITLE
Modifier text characters like `#` causes unexpected conversion of quote block

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#2836]
https://github.com/toeverything/blocksuite/assets/41265413/8887aadb-00ba-442a-a23a-24f245063e32

**Comment by doodlewind** [comment]
Good catch! I this we can ignore the modifier of `#` (and other ones) in quote block. Help wanted!

**Comment by donteatfriedrice** [comment]
It seems that after pressing space, the quote block will transfer to h1 block
https://github.com/toeverything/blocksuite/assets/99816898/5953aefa-0413-4d0f-a038-1e98fb34e5d5

**Comment by donteatfriedrice** [comment]
It seems that after pressing space, the quote block will transfer to h1 block


https://github.com/toeverything/blocksuite/assets/99816898/bae31ae6-7aaa-4364-9a2d-eaeaa504764c

**Comment by donteatfriedrice** [comment]
It seems that after pressing space, the quote block will transfer to h1 block


https://github.com/toeverything/blocksuite/assets/99816898/e2dc9934-c88f-419a-99cc-a2b33f12f898

**Comment by donteatfriedrice** [comment]
Seems like this doesn't just happen with quote block, it also happens with other paragraph blocks like test, h1, h2, etc...
Maybe the # is recognized as markdown header syntax...

https://github.com/toeverything/blocksuite/assets/99816898/0cf54c33-5905-4281-ab98-5d87a3a848fc

**Comment by donteatfriedrice** [comment]
> Good catch! I this we can ignore the modifier of `#` (and other ones) in quote block. Help wanted!

Do You mean does not match the space hot key when in quote block (like code block)?
