### ISSUE TITLE
Add meta field indicating page data source

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/blocksuite#2841]
Add a marker to indicate where a page was created. In future, we may plan to create a page filter to find all data from an imported source, such as importing from Notion.

**Comment by doodlewind** [comment]
@zuoxiaodong0815 could you please elaborate about this? For example, providing some real world data source examples will help us to understand what this task indicates. Thanks!

**Comment by doodlewind** [comment]
Also, please add `feat`, `story` and `mod:*` labels for your newly created issues.

**Comment by doodlewind** [comment]
Closing since this is not of high priority FTM and is better to define outside of BlockSuite.
