### ISSUE TITLE
Deleting the last/only object (in Edgeless) breaks page mode

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#2846]
After deleting the last object/frame in Edgeless mode, the Page mode breaks: it's empty and you cannot type or insert from Block Hub anything to it. You can only turn to Edgeless mode again to add something to recover the Page mode.

![feedback (1)](https://github.com/toeverything/blocksuite/assets/132558/9d2f6a4f-9772-48bd-97e3-70506461960c)

**Comment by doodlewind** [comment]
What is the expected behavior here @joebeijing 🤔?

**Comment by regischen** [comment]
> What is the expected behavior here @joebeijing 🤔?

I think the final solution should be when there is no frame block in edgeless page, user can click content area to create a new block in Page mode.

**Comment by regischen** [comment]
if there needs a transition solution that user cannot delete the last frame block in edgeless mode. I'll work on it.

**Comment by joebeijing** [comment]
Agreed with that @regischen, because the whiteboard needs to be able to achieve a state where there are no Note(Text frame). When the last Note is deleted, switching to the Page Mode and clicking in the editing area should allow for the addition of a blank line with a single click.  /cc @doodlewind
