### ISSUE TITLE
Number column in Database can not input .(dot, decimal) or ,

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#2847]
I can not type .(dot, to express decimal fraction like "3.1415") or ,(comma, like "123,555") in Number field in Database.

https://github.com/toeverything/blocksuite/assets/132558/b1e3ccd6-22c7-4de1-b654-e442d76f966d

**Comment by zqran** [comment]
@joebeijing  Because `33.` is not a legal number, it is impossible to be absolutely WYSIWYG for numbers. We need to confirm the relationship between the input content and the final display content.

**Comment by joebeijing** [comment]
It is suggested to not add too many constraints at the beginning, and only ensure the input of integers and decimals to meet the general scenarios.

- Do not support comma as decimal point for now
- Overall, do not block the input of various information, but automatically remove the non-standard parts when losing focus.

For example, if only "33." is entered, the extra format will be cleared and become "33" after losing focus; if "33,333" is entered, it will become "33" after losing focus; if "33.33.333" is entered, it will become "33.33" after losing focus.
/ cc @xell @HeJiachen-PM
