### ISSUE TITLE
No bookmark preview by slash menu

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#2848]
If using slash menu to create a bookmark, the preview can not be automatically generated. (You need to click Reload to load it).

However, if you convert an inline link to a bookmark, there's no problem.

https://github.com/toeverything/blocksuite/assets/132558/cba16cb5-51ae-41e9-8a10-2c29480e0cbe

**Comment by QiShaoXuan** [comment]
fixed: https://github.com/toeverything/blocksuite/pull/2871/commits/9555106902f2bf084d08a40d5af6579bda89b8c1
