### ISSUE TITLE
​In the tips placeholder, the highlight icon will make it look like it can be clicked

### ISSUE THREAD

**Issue by rottenpen** [toeverything/blocksuite#2851]
### Description

<img width="477" alt="image" src="https://user-images.githubusercontent.com/12029924/234734689-a1640688-3e98-4cc6-a057-e501cb16e3c7.png">

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Currently, this area is working as intended. Our goal is to indicate that it is clickable when it is hovering, without being too distracting and taking editors' attention away from their work.

**Comment by doodlewind** [comment]
Closing as working as expected, cheers!
