### ISSUE TITLE
Cannot switch to insert mode in the situation of renaming a column header of a database

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#2856]
In renaming of a column header of a database, while the whole header is selected, clicking in the header cannot switch to insert mode to type new characters.

https://github.com/toeverything/blocksuite/assets/132558/32a5d4ed-e1bc-4500-abae-352e33866e28

**Comment by zqran** [comment]
Closed, fixed by #2859

**Comment by zqran** [comment]
Closed, fixed by https://github.com/toeverything/blocksuite/pull/2859
