### ISSUE TITLE
Support using tab to indent multiple highlighted list lines with different indent levels

### ISSUE THREAD

**Issue by SolarDesalination** [toeverything/blocksuite#2862]
### What happened?

- I have multiple lines of text, 
- I click and drag to select those lines of text
- once selected/highlighted, I push the tab key.

Expected outcome after pushing tab:
- all lines of highlighted text should indent on the editor. Pushing shift tab should unindent all lines of highlighted text.

Current outcome:
- multiple lines of highlighted text don't indent when pushing tab key.

Using Linux app.

### Version

app.affine.pro

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
For now if you selects on multiple list item under same level, things should work:


https://github.com/toeverything/blocksuite/assets/7312949/4a100878-0997-48d8-a079-39a433ec1afb

But unindent them may not work, which requires more further detailed improvements.
