### ISSUE TITLE
After clicking Reload in the Bookmark dropdown menu, there is no response and the dropdown menu does not disappear

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2865]
The expected outcome is that after clicking, the dropdown menu should disappear and the process of loading the content to be captured should begin.

https://github.com/toeverything/blocksuite/assets/22443345/c93ab917-8b1e-460d-ae2e-377f56a566b8

**Comment by QiShaoXuan** [comment]
fixed: https://github.com/toeverything/blocksuite/pull/2871/commits/cddb82ef746b12c479d44dde08d57bc254282c5b
