### ISSUE TITLE
When creating a Bookmark, an empty state Bookmark should not be inserted

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2867]
![CleanShot 2023-05-30 at 2 33 51@2x](https://github.com/toeverything/blocksuite/assets/22443345/e6e86fc1-f4ce-4205-8a9d-0f98583d8a20)

**Comment by QiShaoXuan** [comment]
fixed: https://github.com/toeverything/blocksuite/pull/2871/commits/5eee76c849c1e48ba29d1674f8b334fd4c790ae0
