### ISSUE TITLE
When editing the Bookmark, it is recommended to pre-select all the contents in the Title

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2868]
Expected effect
![CleanShot 2023-05-30 at 2 53 41@2x](https://github.com/toeverything/blocksuite/assets/22443345/f765d00c-4122-4908-a77d-6f2f6c9f9f80)

**Comment by QiShaoXuan** [comment]
fixed: https://github.com/toeverything/blocksuite/pull/2871/commits/a617821236fff072d5cdc469552a8c50e00ecfb8
