### ISSUE TITLE
Some keyboard shortcuts for the whiteboard are not working

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2870]
Refer to [internal shortcuts list](https://toeverything.feishu.cn/wiki/Aop6wmBAyiVLSzkkyRXc6UT0nfd#WZOZdkrYPocukhx0ukWcy80tn8f).

The keyboard shortcuts are not working in Edgeless
- Zoom in
- Zoom out
- Zoom to fit
- Zoom to 100%

**Comment by doodlewind** [comment]
@fundon I think this is also one possible low hanging fruit that deserves being shown up on your radar, thanks!
