### ISSUE TITLE
Missing cursor when pressing arrow key to navigation if use `/` to convert current block type in edgeless

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#2874]
And maybe into the wrong style, the heading block is overflowed the text frame

https://github.com/toeverything/blocksuite/assets/41265413/e36578a4-30ea-4811-81f8-c2698bcaf60c

**Comment by doodlewind** [comment]
https://github.com/toeverything/blocksuite/assets/7312949/4b5c7a15-f1db-484e-aa81-71c55bdd9d85

Things just work in latest playground (possibly thanks to #3693), cheers!
