### ISSUE TITLE
Support cmd + backspace to remove all list indents

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2891]
If I have a nested list in this format:

``` md
* title
  * hello
    * world
```

And now I want to have "hello world" in the same line:

``` md
* title
  * hello world
```

The current editor requires deleting at the beginning of the `world` line for multiple times:

https://github.com/toeverything/blocksuite/assets/7312949/8a5388e4-3acd-49e6-9175-f06ae111b836

But it will be much better if we support  cmd + backspace that simply removes all the indents:

https://github.com/toeverything/blocksuite/assets/7312949/7525fbdb-8217-4d53-aa04-19a75af06173

**Comment by d4nnyp73** [comment]
Hey, I want to start contributing to open Source projects and would like to try solving this issue!

could you please assign it to me?
I would try to make it work within the next week.

Thank you !

**Comment by doodlewind** [comment]
Sure, feel free to give it a try, thanks!

**Comment by smallnine9** [comment]
Does we have function that can detect whether a model has indent ?

**Comment by smallnine9** [comment]
So does we have function that can clear indent at one time?
I just try to using handleLineStartBackspace in while but it seems that there was async update problem

**Comment by doodlewind** [comment]
Maybe `moveBlock` can do the trick?

**Comment by Saul-Mirone** [comment]
#3749 implements only part of the issue, still need some improvements.

**Comment by Flrande** [comment]
> #3749 implements only part of the issue, still need some improvements.
> 
> \cc @smallnine9 @lawvs @doodlewind

What improvements do you mean? I found that it breaks `option + delete`. (#4804)
