### ISSUE TITLE
Occasional lag on keyboard input and mouse click

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#2892]
This shows up *occasionally* during editing. See this screen recording:

https://github.com/toeverything/blocksuite/assets/7312949/7de63176-7b91-4816-a26d-4e6c11b0a574

When typing to "full", **this word doesn't show up on screen until a delay about a second**. But before and after that, the text editing remains smooth.

This doesn't only happen on rich text. When clicking with drag handle, or sometime scrolling when the window gets focus, the same lag happens. Another example:

https://github.com/toeverything/blocksuite/assets/7312949/783c0e77-5a59-48ed-8113-b5828642e7d9

The first time the drag handle got clicked, the UI took about 5s to respond (the mouse has moved away to prove this). But after this, further operations are just responded in time.

**Comment by doodlewind** [comment]
DB file test case attached here:

[test-canary.db.zip](https://github.com/toeverything/blocksuite/files/11607444/test-canary.db.zip)

**Comment by Flrande** [comment]
It seems more like a performance issue specific to the client-side, but I'm not entirely sure. It may require a detailed analysis of the main process and working status during this period by performance testing tools.

**Comment by doodlewind** [comment]
Closed by https://github.com/toeverything/AFFiNE/pull/2589
