### ISSUE TITLE
​forward delete at the end of block to merge

### ISSUE THREAD

**Issue by youkq95** [toeverything/blocksuite#2921]
### Description

When editing contents across blocks, someone might want to merge the content of two blocks by:
1. back delete from the starting of the second block, or
2. forward deleted from the ending of the first block.

Now on the affine PC desktop can do it the first way, but not in the second way. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
This sounds very interesting! For macOS users, the only key for deleting content is `Backspace`, which deletes content backward. So deleting content forward was not specifically supported. Hope for PRs that makes this happen!

For anyone interested in this, see #2552 that demonstrates how hotkey binding works.

**Comment by Alkaidcc** [comment]
fixed in #2552 @youkq95

**Comment by doodlewind** [comment]
Closed by #2552, thanks @Alkaidcc for helping clean up our backlog!
