### ISSUE TITLE
Incorrect canvas text cursor jump offset in edgeless mode

### ISSUE THREAD

**Issue by smallnine9** [toeverything/blocksuite#2922]
https://github.com/toeverything/blocksuite/assets/35493996/e6b18305-3872-4891-abda-fb883cca8a75

**Comment by smallnine9** [comment]
Another `mod:cursor` issue.
I found that `awareness.setLocalRange` doesn't work in edgeless mode.
https://github.com/toeverything/blocksuite/blob/3854a14cc6c3c4e8fcf98b2e00602df1844e42ac/packages/store/src/awareness.ts#L132

**Comment by doodlewind** [comment]
This is a follow up from #2791

**Comment by doodlewind** [comment]
This is fixed in latest playground (possibly closed by #3734 since we've reimplemented the way how cursor locates).
