### ISSUE TITLE
performance issues related to hard drive while typing normally

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#2924]
「Hey guys, I just started using Affine rn but I'm experiencing some performance issues related to my hard drive while typing normally, my HDD is about 2 years old and definitely not the best but I don't have any issues with other programs. does anyone else have the same issue? 
same with the whiteboard :/
I tried 0.5.4 which is the stable version and in the video it was 0.7.0-canary.5, the most recent one
both had the same issue」

**Comment by doodlewind** [comment]
Thanks for notifying! This will be tracked in standalone ones.

**Comment by doodlewind** [comment]
Follows #2892
