### ISSUE TITLE
The loading effect of bookmarks needs to be optimized

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2930]
- Use "Loading" instead of "Embedding".
- Dynamic UI that indicates the ongoing process is needed. Currently, it is only static text.

**Comment by Svaney-ssman** [comment]
here is the design: [figma link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=4257-88394&t=4nxzzh16kcDd6lPq-4l) @QiShaoXuan
