### ISSUE TITLE
Support filter in database

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2933]
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/blocksuite/issues/4395
- [ ] https://github.com/toeverything/blocksuite/pull/3065
```

**Comment by joebeijing** [comment]
PRD：[Internal doc](https://toeverything.feishu.cn/wiki/G2DowRoAeiQ9Z6khm1kcULrcnbs)

**Comment by doodlewind** [comment]
The sort part continues in #3294 and this is closed since we have shipped the filter part. Thanks @zzj3720 for the feat!
