### ISSUE TITLE
Support modifying tag color for the "Select" field in database

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2934]

**Comment by hwangdev97** [comment]
The sub-menu appear as follows:

<img width="655" alt="shot-2023-06-05-18 19 20@2x" src="https://github.com/toeverything/blocksuite/assets/24713927/18222f61-f45b-45b2-a1c6-cf61c4916a65">

@zqran cc @doodlewind

**Comment by zqran** [comment]
> The sub-menu appear as follows:
> 
> <img alt="shot-2023-06-05-18 19 20@2x" width="655" src="https://user-images.githubusercontent.com/24713927/243325082-18222f61-f45b-45b2-a1c6-cf61c4916a65.png">
> @zqran cc @doodlewind

Get!
