### ISSUE TITLE
Support toggling for headings and list blocks

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2945]
PRD：[Internal doc](https://toeverything.feishu.cn/wiki/Ds3BwBM1ViKxC8kmDaTcHrt0nFc)

**Comment by houjoe0829** [comment]
In terms of implementation priority, Lists > Headings.

**Comment by lawvs** [comment]
## Caveats

- Undo/Redo
- Collaboration
- Copy/Paste
- Update or rerender

**Comment by xell** [comment]
@lawvs please see the [internal figma design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=5659-121035&mode=design&t=wLNBCRWgYINIigeE-4) for the details.
