### ISSUE TITLE
After pasting a link to generate a bookmark, undoing should not restore it to the loading state.

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2946]
https://github.com/toeverything/blocksuite/assets/22443345/c32c5ae7-4870-4fff-9ab3-753a7471c339

The expected outcome is to return to the link state directly after undoing.

**Comment by QiShaoXuan** [comment]
fixed here in passing: https://github.com/toeverything/blocksuite/pull/2980
