### ISSUE TITLE
Support attachment block

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2952]
Attachment preview is not within the scope of this task.

**Comment by Svaney-ssman** [comment]
[internal doc](https://toeverything.feishu.cn/wiki/X8Bkwj9triEVqbkxMImc7e3Hnwd)

**Comment by Svaney-ssman** [comment]
[internal figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=6306-131013&mode=design) @joebeijing

**Comment by doodlewind** [comment]
This is closed by #3622, we'll track new related issues after new canary releases.
