### ISSUE TITLE
Lose cursor in edgeless mode after undo

### ISSUE THREAD

**Issue by smallnine9** [toeverything/blocksuite#2957]
https://github.com/toeverything/blocksuite/assets/35493996/93a6d5ea-0fcb-4fce-ac28-908386a4fe9a

**Comment by doodlewind** [comment]
What's the previous action before losing cursor? Was that an undo operation?

**Comment by smallnine9** [comment]
yes

**Comment by smallnine9** [comment]
https://github.com/toeverything/blocksuite/assets/35493996/e6332a02-fed3-4d59-b7d8-658ed977e7e3

Use undo twice it will be normal, maybe it's a issue realted to y.js, do you have any idea about this issue?

**Comment by doodlewind** [comment]
Fixed by #3693 (or following selection refactoring)
