### ISSUE TITLE
The row data is lost after converting the title column type in the database

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#2960]
For example, after changing the content of title column from `rich text` to `list`:

https://github.com/toeverything/blocksuite/assets/15389209/96781732-4d87-4dfe-b998-15e1eacdf802

**Comment by doodlewind** [comment]
I think we should not allow changing the type of the title column. /cc @joebeijing

**Comment by joebeijing** [comment]
> I think we should not allow changing the type of the title column. /cc @joebeijing

Yes, we do not allow modification of the field type of the title column. However, the format of the Block can be adjusted, and this is something that we cannot prevent.

**Comment by zqran** [comment]
I mean modify the content format of the title column.

**Comment by doodlewind** [comment]
Not reproduced after #2401 landed, cheers!
