### ISSUE TITLE
Optimization for dragging and dropping to create copies

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2963]
related with https://github.com/toeverything/blocksuite/issues/1811

Adding some optimization options
- To display a double-arrow mouse cursor when holding down the Option key, similar to how Figma handles it, to indicate that a copy is about to be created.
- Disabling the display of component menu while dragging.

**Comment by alceil** [comment]
Can I take a dab at this? @houjoe0829  @doodlewind

**Comment by doodlewind** [comment]
Sure, feel free to give it a try!

**Comment by alceil** [comment]
Hey @doodlewind Im confused on how to setup the project locally and cant see anything about in the docs either. Can you point me to resources or help me set it up locally?

**Comment by doodlewind** [comment]
@alceil see https://github.com/toeverything/blocksuite/blob/master/BUILDING.md
