### ISSUE TITLE
Toast that appears after clicking the "Copy" button of Bookmark is incorrect

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2966]
https://github.com/toeverything/blocksuite/assets/22443345/ea5b1dfd-979a-4184-8008-6ab9e956ee92

- It should be “Copied original link to clipboard“
- The Button's name should be “Copy original link” CC @Svaney-ssman

**Comment by Svaney-ssman** [comment]
Here is the menu design: [figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/AFFiNE-2023?type=design&node-id=3823-84301&t=CUwRd6eDnoaZ8IV7-4) @QiShaoXuan
