### ISSUE TITLE
​Database not properly exported in any mode in AFFiNE Stable Release June 1st Version

### ISSUE THREAD

**Issue by NLBRT** [toeverything/blocksuite#2970]
### What happened?

Title is self-explanatory.

When the DB is exported as PDF, the scrollable parts cannot be used and it displays the editing options per the app for no reason.
When exported in HTML/MD, only the first column of data is shown. 

Preview of the exported file in PDF:
![image](https://github.com/toeverything/AFFiNE/assets/93070290/e680119c-f819-430d-8acb-f797a03a4968)
Preview of the exported file in HTML:
![image](https://github.com/toeverything/AFFiNE/assets/93070290/f610846a-c3eb-406f-9a42-8acbc82729cd)
Preview of the exported file in MD:
![image](https://github.com/toeverything/AFFiNE/assets/93070290/d73b9db3-ff78-4350-98cd-c015a35cefe2)

This issue can be easily reproduced in the Stable Release of June 1st. Here's the original table in-app for reference: 
![image](https://github.com/toeverything/AFFiNE/assets/93070290/9738e3fa-138c-4d4c-a1fb-b38e85847a08)

P.S: Apologies for the use of profane language in the examples

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zuoxiaodong0815** [comment]
About the PDF/PNG case, because it haven't render all columns, we just only export part columns. So I think this case is not a problem which we maybe not to fix this case.

About the markdown/html case, this is really a problem. We will fix this case.  @zqran @NLBRT

**Comment by NLBRT** [comment]
I realised the former. However, what's with the editing buttons on the exported file?

**Comment by zuoxiaodong0815** [comment]
@NLBRT It('the editing buttons on the exported file')is a bug. I have create a issue https://github.com/toeverything/blocksuite/issues/3453

**Comment by doodlewind** [comment]
We'll track the remaining part in https://github.com/toeverything/blocksuite/issues/3568
