### ISSUE TITLE
Uncaught Error: val does not exist

### ISSUE THREAD

**Issue by Adonis0123** [toeverything/blocksuite#2971]
When I paste the using， i got this error
![image](https://github.com/toeverything/blocksuite/assets/46788304/5cd8a304-18dd-4a5a-8922-1b0f188b47fd)

**Comment by doodlewind** [comment]
I'm a bit confused by the description. Could you elaborate how to reproduce this? Thanks.

**Comment by Adonis0123** [comment]
> I'm a bit confused by the description. Could you elaborate how to reproduce this? Thanks.

@doodlewind I'm sorry for not describing the problem clearly，You can reproduce this problem by following my steps.

1.  Open [The SimpleAffineEditor Example](https://blocksuite-toeverything.vercel.app/examples/basic/)
2. Copy a piece of Markdown text on the editor
3. Drag a paragraph of text to sort

Then, I get the same error in my code

![image](https://github.com/toeverything/blocksuite/assets/46788304/6d6d455e-05fe-4011-a3d1-ce1ad9e7aff2)

this is my test markdown text

This playground is designed to:
📝 Test basic editing experience.
⚙️ Serve as E2E test entry.
🔗 Demonstrate how BlockSuite reconciles real-time collaboration with [local-first](https://martin.kleppmann.com/papers/local-first.pdf) data ownership.
Controlling Playground Data Source
You might initially enter this page with the ?init URL param. This is the default (opt-in) setup that automatically loads this built-in article. Meanwhile, you'll connect to a random single-user room via a WebRTC provider by default. This is the "single-user mode" for local testing.
To test real-time collaboration, you can specify the room to join by adding the ?room=foo config - Try opening this page with ?room=foo in two different tabs and see what happens!

**Comment by joshirakesh** [comment]
Hello @doodlewind, I've been investigating this issue and believe I've found a potential fix. As it seems no one else is currently working on this, I'm prepared to address it. I've already identified and tested the fix, and am ready to submit a PR for your review. Looking forward to your feedback.
