### ISSUE TITLE
Cannot remove the first line using delete or forward delete

### ISSUE THREAD

**Issue by AlessioGr** [toeverything/blocksuite#2976]
https://github.com/toeverything/blocksuite/assets/70709113/c5110f66-6ad7-458f-96e2-8db9a3d15e2c

Try deleting the first line using delete or forward-delete while your cursor is in the first line. It does not work - but it does work in other editors like notion.

I'm expecting it to work with **both** delete and forward-delete

**Comment by doodlewind** [comment]
Thanks for you feedback! I'm just not sure what is the expected behavior here, since we need to keep at least one paragraph block for focusing the cursor. Perhaps moving the cursor to title at this case could make more sense?

**Comment by karti16** [comment]
@doodlewind In notion deleting the last paragrap moves cursor to the title. In Obsidian it doesn't. It has to be decided to move cursor to title or just leave as it is now. Well moving cursor to title make sense to me.
