### ISSUE TITLE
The cursor appears to be incorrect when selecting multiple blocks and inputting text

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#2982]
```
- 1|23
- 456
- 78|9

Press 'a'

---

Expected 

- 1a|9

but got

- 1|a9
```

https://github.com/toeverything/blocksuite/assets/18554747/782aac82-008a-42cc-8e35-ce381598bf4f

**Comment by doodlewind** [comment]
Great to see your involvement back here! Just kindly reminds that it's best to add the `bug` (or `feat`/`refactor`... label :)
