### ISSUE TITLE
Cannot select parent list block when shift-click.

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#2988]
Steps to reproduce:
1. Create a list block with subtree.
2. Select child list items through clicking list icon.
3. Press down shift key and click parent list block.

https://github.com/toeverything/blocksuite/assets/99816898/4d0aacd9-80b9-4ac9-b55f-fcf3465c295b

But it can be seen that, when clicked the sibling of parent list block, it worked well.

**Comment by doodlewind** [comment]
Supported after the #3734 selection refactoring, cheers!
