### ISSUE TITLE
Renaming database title causes text to write back to front

### ISSUE THREAD

**Issue by purpleden** [toeverything/blocksuite#3012]
### What happened?

Renaming 'Database text' causes text to write back to front

![image](https://github.com/toeverything/AFFiNE/assets/33729019/d4d11348-a9e2-4f0e-8d1b-1424d83f1aaa)

![image](https://github.com/toeverything/AFFiNE/assets/33729019/a34c9075-c48f-44ed-91fc-0c4278dffeb4)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zqran** [comment]
> I double clicked the title 'Title' and then started typing. The cursor seems to default to the left of the text, instead of the right

Sorry, I still can't reproduce it, can you provide a reproduction video?

**Comment by doodlewind** [comment]
Seems that according to the description, this doesn't reproduce on latest master. Feel free to reopen if more related info can be provided (reproduction recording, browser version, etc.).
