### ISSUE TITLE
Unable to scroll database in edgeless mode

### ISSUE THREAD

**Issue by purpleden** [toeverything/blocksuite#3013]
### What happened?

Switching to edgeless mode, the table block cannot be expanded (it could in previous builds)

Normal view:
![image](https://github.com/toeverything/AFFiNE/assets/33729019/0203e960-1579-4208-b13c-756ab7546353)

Unable to expand:

![image](https://github.com/toeverything/AFFiNE/assets/33729019/0f1fb9d0-60e3-4028-9018-0c1f9fa7f435)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zqran** [comment]
@purpleden How to reproduce? Can you provide the steps to reproduce, or a video?

**Comment by doodlewind** [comment]
@zqran I think this is related to the horizontal scrolling with database block.

**Comment by zqran** [comment]
@doodlewind  In the Edgelesss mode, we can view the content by dragging the scroll bar of the database with the mouse.

**Comment by doodlewind** [comment]
> @doodlewind In the Edgelesss mode, we can view the content by dragging the scroll bar of the database with the mouse.

Make sense, so I gotta closing this since this is by design and is usable FTM. But we are open to new related issue regarding improving the scrolling UX of database.

**Comment by zqran** [comment]
@purpleden 
Which version of client are you using? It cannot be reproduced in the latest version of client (0.7.0-canary.11).
