### ISSUE TITLE
Latex editor & viewer feature

### ISSUE THREAD

**Issue by Gintasz** [toeverything/blocksuite#3014]
### Description

Add a quick latex viewer & editor like in obsidian:
https://github.com/joeyuping/quick_latex_obsidian

### Use case

taking notes while studying content with math involved

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Thank you very much for your feedback. This is in our future plans, but we have not started working on it yet. Please stay tuned for updates.

**Comment by DataDaoDe** [comment]
This would be huge. Having some way to enter math equations is what's keeping me from being able to use blocksuite as of right now. I'd be glad to help out any way I could to get this implemented.

**Comment by himself65** [comment]
I think you can add a custom block like the bookmark block

**Comment by JiantingFeng** [comment]
What is the status? Any update?

**Comment by houjoe0829** [comment]
> JiantingFeng

We haven't started working on this requirement yet. It is not expected to be supported in the short term. Please continue to stay updated. Thank you again for your attention.

**Comment by mon-jai** [comment]
Maybe [MathQuill](https://mathquill.com/) could be integrated?

**Comment by DataDaoDe** [comment]
Personally. I think pure Latex better. The autocompletion usually just makes it more difficult/time consuming. And most people writing math are going to be used to latex in my experience.

**Comment by DataDaoDe** [comment]
I think that would be okay as long as you offer both. The thing is, If you don't allow for a pure latex editing mode, you end up with tons of tedious trial and error to get the function you want, or worse, you can't enter the function you want or you've enter the 90% of the equation and then can't get the autocomplete to do what you want. This can be extremely frustrating. I will say though I'm speaking from the perspective of someone in mathematics. This is probably not the case for high school students or other many other disciplines where equations remain relatively simple and straightforward.

**Comment by doodlewind** [comment]
The inline latex is supported in #5909, try https://try-blocksuite.vercel.app/?mode=page&exampleSpec=latex to see the effect (typing `$a + b$` then pressing space).

Note that this is only supported as an extension example based on the framework, require some more time to further land it in AFFiNE.
