### ISSUE TITLE
Unable to insert a block in a newly created page through dragging

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#3018]
Steps to reproduce:
1. Create a new page.
2. Drag a block to insert into the page.

https://github.com/toeverything/blocksuite/assets/99816898/31bb30cb-baed-4e7f-b8d8-4fd767faab55

**Comment by doodlewind** [comment]
Not sure if this relates to the editor lifecycle, seems there can be an easy fix :)
