### ISSUE TITLE
Support upload multiple images in edgeless mode

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#3022]
<img width="1371" alt="image" src="https://github.com/toeverything/blocksuite/assets/5910926/27e66a0e-33b6-456f-8bc8-5adc175a6a2c">

**Comment by donteatfriedrice** [comment]
I am not sure what the effect this feature is expected to achieve.

I have gave a simple try, the logic is to add all the images embed blocks to a single frame based on the code before. It seems that the previous code already contains the logic of uploading multiple images, but forget to process the frame size (options) according to the uploading images.

Does this feature need to add each image embed block to a separate frame ?

The effect is as pr #3025 shown.
