### ISSUE TITLE
Would it be better to remove the icon from the link?

### ISSUE THREAD

**Issue by zzj3720** [toeverything/blocksuite#3042]

**Comment by joebeijing** [comment]
Firstly, the issue in your recording is actually a bug. I have created an issue to follow up on it. https://github.com/toeverything/blocksuite/issues/3043

Secondly, regarding the identifier for the links, it is currently not possible to remove it, but we will consider adding an option in the future for users to decide on it themselves. https://github.com/toeverything/blocksuite/issues/3044
