### ISSUE TITLE
Adding link to a text with different formats should not display multiple links

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3043]
https://github.com/toeverything/blocksuite/assets/22443345/a8e46cbf-db9c-4455-908f-82494c915630

**Comment by doodlewind** [comment]
This relates to how Virgo represents rich text. /cc @Flrande to see if we can remove the selected bold style here on converting, so as to keep the integrity of the link?

**Comment by water-in-stone** [comment]
@Flrande Can you assign this issue to me? I will submit a pull request.

**Comment by Flrande** [comment]
> @Flrande Can you assign this issue to me? I will submit a pull request.

Sure, looking forward to your PR!

**Comment by Flrande** [comment]
Will be fixed in #4787
