### ISSUE TITLE
Is it possible to consider integrating UI/prototyping tools in the future?

### ISSUE THREAD

**Issue by Avey777** [toeverything/blocksuite#3045]
efer to：
https://github.com/penpot/penpot

**Comment by joebeijing** [comment]
We will consider adding features related to the prototype or UI elements in the future, although we don't have any short-term plans for it. We will keep this issue open and continue to track it.

**Comment by doodlewind** [comment]
It's a non-goal to provide official support for third party graphics editing. Instead, the support of standardized third-party block protocol is in plan.
