### ISSUE TITLE
Move `ClipboardManager` to blocks package

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#305]
We can migrate ClipboardManager to `BlockHost.clipboard`. This solves the problem of calling clipboard APIs from the `blocks` package and aligns more with our goal to build more editor modes as "block container" in `@blocksuite/blocks`. Ultimately the `@blocksuite/editor` package will be mainly a thin wrapper of different block containers (default page block, edgeless page block, mobile page block, etc.).

Also, this resolves the `OpenBlockInfo` conflicts.

It's a nice-to-have improvement. We can wait until the next housekeeping cleanup after our December release if we have a decent workaround.

cc @DiamondThree @zuoxiaodong0815

**Comment by DiamondThree** [comment]
So, should we now migrate to the past or keep the status quo rather? I don't know if relocating to the past will cause some other problems, for example, the previous call place will fail,  Maybe need @zuoxiaodong0815 to tell me.

**Comment by doodlewind** [comment]
> So, should we now migrate or keep the status quo rather? I don't know if relocating will cause some other problems, for example, the previous call site will fail, Maybe need @zuoxiaodong0815 to tell me.

Our discussion estimated that it may take a few days for the migration, so it would be fine to postpone this task for now.

**Comment by DiamondThree** [comment]
ok, I get

**Comment by doodlewind** [comment]
Closed by #1687
