### ISSUE TITLE
Could select all short-cut (cmd+A) support to select text (native range) firstly when first time be pressed? 

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#3075]
Currently, when user presses cmd+A will directly select whole block, and can only delete the block. 
Could the short-cut supports to select all text firstly, thus user can delete the text only and reserve the block?
If user wants to select whole block, can press cmd+A again.

https://github.com/toeverything/blocksuite/assets/99816898/318e4db8-6b7c-443c-9621-1eb3b6a98806

**Comment by doodlewind** [comment]
/@joebeijing how do you think if we make the first cmd-A to select text content under native selection, instead of block-level selection?

**Comment by joebeijing** [comment]
We have discussed this internally and the differences between the two options are relatively small. In most scenarios, either option would work. Therefore, we have decided to keep the current design for now, which prioritizes selecting the entire block. However, we will continue to monitor user feedback on this issue. Thank you for your input.

**Comment by donteatfriedrice** [comment]
> We have discussed this internally and the differences between the two options are relatively small. In most scenarios, either option would work. Therefore, we have decided to keep the current design for now, which prioritizes selecting the entire block. However, we will continue to monitor user feedback on this issue. Thank you for your input.

Got it, thanks!
