### ISSUE TITLE
Autoscroll does not activate when adding blank lines or blocks using Block Hub

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3078]
https://github.com/toeverything/blocksuite/assets/22443345/b75d37ad-c9cc-44fe-b41f-b21eb5efd9bc

**Comment by water-in-stone** [comment]
I have replicated this issue locally, please assign this issue to me.

**Comment by water-in-stone** [comment]
@doodlewind @regischen PTAL

**Comment by water-in-stone** [comment]
@Saul-Mirone PTAL
