### ISSUE TITLE
Notes in the Edgeless mode should support quick splitting into multiple ones

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#3083]
<img width="672" alt="CleanShot 2023-06-13 at 17 51 40@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/a986eec0-3465-4425-9393-ffab1b130a41">

**Comment by hwangdev97** [comment]
The design team has already come up with basic prototype styles, but there are some details that we need to discuss with @HeJiachen-PM  and confirm over dinner tonight, and then sync over to your side: 

![shot-2023-06-14-14 13 08](https://github.com/toeverything/blocksuite/assets/24713927/40df0a78-4cb1-431e-86c6-06283533fa18)

**Comment by doodlewind** [comment]
This will be tracked in #3136
