### ISSUE TITLE
Mouse behavior in edgeless breaks when database block exists

### ISSUE THREAD

**Issue by blurname** [toeverything/blocksuite#3087]
just try to drag the cavnas https://blocksuite-toeverything.vercel.app/?init=database&mode=edgeless

I track it to this commit https://github.com/toeverything/blocksuite/commit/35ef95f8b4b4b6e2d4d65e68062c7c0a7a3cd6fd#diff-2d2ed51352dd2de8e64d274ac87323e78c961d72863c8845c23ab5d46631c76bR194
since the return value is `true`

**Comment by doodlewind** [comment]
Thanks for the feedback! We are aware of this issue and a fix should be on the way.

**Comment by zqran** [comment]
May be fixed by: #3088
