### ISSUE TITLE
Bugs about the database and bookmark blocks inserted from Block Hub in Edgeless mode

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3091]
The bugs are multi-folds:

- The newly inserted Database block seems not fully visible, and the "+ new record" button is mispositioned.
- The newly inserted Bookmark block is blank.
- Clicking or moving the blocks will make them disappear.

https://github.com/toeverything/blocksuite/assets/132558/e507fcdf-14c1-499a-b42a-4b60f35a0887

**Comment by doodlewind** [comment]
Need standalone issues for each of these list items, otherwise we can't close this one by standalone PRs.

**Comment by doodlewind** [comment]
I would consider opening one monolithic "Bugs about X" issue with N actual sub-entries as an anti-pattern.
