### ISSUE TITLE
Newly inserted Database block is not fully visible and the "+ new record" button is mispositioned

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3092]
See #3091 for detailed description.

**Comment by xell** [comment]
@zqran @doodlewind It seems to remain unsolved glitches: the content on the top-right corner isn't fully visible and clicking will still make it disappear. Should we open another issue or reopen this one?


https://github.com/toeverything/blocksuite/assets/132558/0cfc05b4-d1a8-41f0-81fc-dd7c3a1bc3b1

**Comment by doodlewind** [comment]
> 

This should be tracked in #3094

**Comment by xell** [comment]
See also https://github.com/toeverything/blocksuite/issues/3112
