### ISSUE TITLE
Unable to keep newly added database block from block hub in edgeless mode

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3094]
See detailed description in #3091:

> Clicking or moving the blocks will make them disappear.

This should be related the logic that automatically tries to remove empty frame.

**Comment by regischen** [comment]
so in order to solve this issue, we allow empty database block exists
? But empty frame block still doesn't allowed

**Comment by doodlewind** [comment]
How about just adding one empty row in database block?
