### ISSUE TITLE
Input using Chinese IME under block level selection creates redundant character

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3104]
https://github.com/toeverything/blocksuite/assets/22443345/a53d38c7-2939-4d75-83f0-cd21a4afaf10

**Comment by doodlewind** [comment]
@Saul-Mirone here seems to be a regression. The pre-refactored version supports direct input under block level selection.

**Comment by Saul-Mirone** [comment]
The removal of this feature is by design. It's not possible to support IME input with this pattern.
