### ISSUE TITLE
how can I limit title length and update title text

### ISSUE THREAD

**Issue by Adonis0123** [toeverything/blocksuite#3106]
I am a freshman to BlockSuite. when i create i title like this

```
 const blockId = page.addBlock('affine:page', {
      title: new Text('title'),
    })
```
how can i limit title, and update it

I have tried
```
  const block = page.getBlockById(blockId )
 page.updateBlock(block, {
      title: new Text('new title'),
    })
```

then got some error. can you help me? thank you very much!

**Comment by Flrande** [comment]
If you want to limit the length of the title, you can use our encapsulated `VirgoInput` component or refer to it to implement your own.

This code should be of assistance.
https://github.com/toeverything/blocksuite/blob/589a346c39544c64b3246afb60136ca62932a03c/packages/blocks/src/database-block/table/components/column-type/select/select-option.ts#L90-L94

> then got some error. can you help me? thank you very much!

What kind of error did you encounter? Screenshots or error logs would help me assist you better. Currently, the `default-page-block` only [initializes the title once](https://github.com/toeverything/blocksuite/blob/9927a75adbf11c05975324fb3a19fa48b129d86b/packages/blocks/src/page-block/default/default-page-block.ts#L370). (Perhaps this could be an area for improvement. I believe we could open an issue for this. What are your thoughts? @doodlewind) Therefore, your code may not work. If you want to directly modify the value of the title, you can try the following code.

```typescript 
const block = page.getBlockById(blockId)
const text = block.title
text.replace(0, text.length, 'new title') // you can find API for `Text` in [text-adapter.ts](https://github.com/toeverything/blocksuite/blob/579ae3dfffb540ab60d3b47ee440dcd998547dbe/packages/store/src/text-adapter.ts)
```

**Comment by doodlewind** [comment]
Closing since this is not a development task, but feel free to continue further discussion here, though :)

**Comment by Adonis0123** [comment]
> If you want to limit the length of the title, you can use our encapsulated `VirgoInput` component or refer to it to implement your own.
> 
> This code should be of assistance.
> 
> https://github.com/toeverything/blocksuite/blob/589a346c39544c64b3246afb60136ca62932a03c/packages/blocks/src/database-block/table/components/column-type/select/select-option.ts#L90-L94
> 
> > then got some error. can you help me? thank you very much!
> 
> What kind of error did you encounter? Screenshots or error logs would help me assist you better. Currently, the `default-page-block` only [initializes the title once](https://github.com/toeverything/blocksuite/blob/9927a75adbf11c05975324fb3a19fa48b129d86b/packages/blocks/src/page-block/default/default-page-block.ts#L370). (Perhaps this could be an area for improvement. I believe we could open an issue for this. What are your thoughts? @doodlewind) Therefore, your code may not work. If you want to directly modify the value of the title, you can try the following code.
> 
> ```ts
> const block = page.getBlockById(blockId)
> const text = block.title
> text.replace(0, text.length, 'new title') // you can find API for `Text` in [text-adapter.ts](https://github.com/toeverything/blocksuite/blob/579ae3dfffb540ab60d3b47ee440dcd998547dbe/packages/store/src/text-adapter.ts)
> ```

thank you very much, have a nice day!!!

**Comment by Flrande** [comment]
> I have learned how to replace the title, but I find VirgoInput too complicated to use and I am unable to export it. Is it possible to use the following code instead, which is more beginner-friendly?

`addBlock` is an API used for updating the block field. To utilize this API, it is necessary to customize your own block. As for this functionality, the relevant technical infrastructure is still being continuously improved.
