### ISSUE TITLE
Unable to sync subdoc manually

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#3108]
manually call `workspace.doc.getMap('spaces').get('space:740740879:0').load()` won't work for the received client

https://github.com/toeverything/blocksuite/assets/14026360/8137f482-00e1-4de1-95b6-55921ae74a43

**Comment by Saul-Mirone** [comment]
This should be completed in favour of https://github.com/toeverything/blocksuite/pull/3082
