### ISSUE TITLE
Delete after undo in edgeless mode will loss cursor.

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#3124]
In edgeless mode, press backspace to delete some text, then perform undo operation, and press backspace again to delete text, the cursor will be lost.

Steps to reproduce:
1. Edgeless mode.
2. Press backspace to delete some text.
3. Press cmd+z to undo.
4. Press backspace continuously again.

https://github.com/toeverything/blocksuite/assets/99816898/d7097204-0de3-418f-96a9-10f419e94228

**Comment by doodlewind** [comment]
Fixed by #3693
