### ISSUE TITLE
Support new edgeless toolbar

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3139]
Related: https://github.com/toeverything/blocksuite/issues/3097

**Comment by doodlewind** [comment]
I'd close this and continue future progress in upcoming PRs. Any plan on related optimizations @donteatfriedrice?

**Comment by donteatfriedrice** [comment]
> I'd close this and continue future progress in upcoming PRs. Any plan on related optimizations @donteatfriedrice?

I am working on adding overlay to note and shape tool. Currently, I can add a simply shape overlay like strokeRect, roundRect, and it can follow with the cursor. But there are still some problems I need to figure out,  like adding complex overlay to note tool , handle the wheel event when we still have a overlay... I think I can make a draft pull request tonight.
