### ISSUE TITLE
The caret will be at wrong position after transforming paragraph block to another type and input new character.

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#3152]
Steps to reproduce:
1. Input in a paragraph block, like text, h1, h2...
2. Transform block type to another paragraph type using slash menu (type '/' )
3. Input new character.

https://github.com/toeverything/blocksuite/assets/99816898/295a0f7e-8c5d-4ff7-a3c8-7d671e418d94

It seems like this problem only occurs when convert type within paragraph block. 

When transform paragraph block to other flavour blocks (like list, code) or transform from other flavour blocks to paragraph, it works as expected.

**Comment by doodlewind** [comment]
Good catch! This may be related to virgo, cc @Flrande would be great to justify if this could a low-hanging fruit!

**Comment by Flrande** [comment]
I believe this is a timing-related issue, where the execution order of `slots.updated.once` in `onModelTextUpdated` comes after `vEditor.slots.emit`.

https://github.com/toeverything/blocksuite/blob/95f1ade130fc297a77a4a446d6831947b2050389/packages/blocks/src/page-block/utils/container-operations.ts#L246-L253
