### ISSUE TITLE
Table/DB support

### ISSUE THREAD

**Issue by 3Dcut** [toeverything/blocksuite#3159]
### Description

simple tables with filter or sorting

### Use case

sort pages, collect items and information

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for your feedback! A basic implementation of table (named *DatabaseBlock* in AFFiNE) is shipped in BlockSuite:

<img width="947" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/bca8e21a-c3cd-40dd-adc6-619259fc33b3">

So I'd close this as complete. For further specific feature requests regarding database block, feel free to open new issues.
