### ISSUE TITLE
Pen-Support

### ISSUE THREAD

**Issue by 3Dcut** [toeverything/blocksuite#3160]
### Description

most notetaking-apps dont support touchscreen or pens.

 

### Use case

The posibillity to use handwriting or annotade pdf would make AFFiNe much stronger

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
<img width="770" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/efbc235b-d290-46e6-ae11-2f531ac9fb5d">

This is implemented in current BlockSuite edgeless mode, feel free to give it a try :)
