### ISSUE TITLE
Support moving range selected text blocks by drag handle

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3162]
Just like this

https://github.com/toeverything/blocksuite/assets/22443345/b34aef52-6314-438b-9035-94969d0ff9cb

This is mainly to facilitate batch dragging and processing of multiple blocks in Page or Edgeless.

**Comment by xell** [comment]
Supplementary note:

In AFFiNE, selecting contents across multiple blocks and dragging won't result in grouped movement, the drag handle can only control one of the multiple blocks and make the aforementioned selection disappear.

Please compare the following screenshot to the above example of Notion.

https://github.com/toeverything/blocksuite/assets/132558/3141c59e-ecad-45b3-a238-4db8aa88763a

**Comment by fundon** [comment]
@doodlewind No major refactoring required, need to determine the source(`native`).

**Comment by doodlewind** [comment]
Closed by #3695 and following related PRs
