### ISSUE TITLE
unhandled method array functions in yArrayProxy

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3191]
https://github.com/toeverything/blocksuite/blob/aaf4b3bdcbb0ebc92846d47f20bb6c8bba9ce819/packages/store/src/workspace/meta.ts#L106

**Comment by Saul-Mirone** [comment]
This should've been fixed.

**Comment by himself65** [comment]
In which commit? what's the change?

**Comment by Saul-Mirone** [comment]
> In which commit? what's the change?

https://github.com/toeverything/blocksuite/pull/3209
