### ISSUE TITLE
How to export HTML and save it to the server? 

### ISSUE THREAD

**Issue by tsinglemon** [toeverything/blocksuite#3194]
How to export HTML and save it to the server? Currently, the images are in local blob format, and I don't know if there is a way to upload them to the server. I understand that this editor wants to be decentralized, but is it possible to keep a complete copy of the HTML on the server as well？

**Comment by himself65** [comment]
Implement your own blob api

https://github.com/toeverything/blocksuite/blob/master/packages/store/src/persistence/blob/types.ts

example basic server: https://github.com/toeverything/blocksuite/blob/master/packages/store/src/persistence/blob/mock-server-storage.ts

https://github.com/toeverything/blocksuite/blob/2fc312f1963b6e88cfad7e43a28591542da94ce8/tests/embed.spec.ts#L337-L360
