### ISSUE TITLE
Unable to select downwards across blocks in Firefox

### ISSUE THREAD

**Issue by Systemcluster** [toeverything/blocksuite#3242]
When attempting to select text across blocks in Firefox, it is impossible to select downwards to following blocks. 

The following was recorded on https://blocksuite-toeverything.vercel.app/?init, using Firefox `115.0b9` on Windows 11.

https://github.com/toeverything/blocksuite/assets/2847328/bd0db6f3-ffb4-4e8f-9d92-e1db94c313c3

**Comment by fourdim** [comment]
Already fixed. Close as cannot reproduce it now.
