### ISSUE TITLE
Demo does not load starter contents in safari

### ISSUE THREAD

**Issue by lennardv2** [toeverything/blocksuite#3244]
When i go to https://blocksuite-toeverything.vercel.app/?init it does not how any contents in safari on osx. 

The dev console shows these errors:
```
[Error] SyntaxError: Invalid regular expression: invalid group specifier name in slot.ts:128
[Error] Unhandled Promise Rejection: SyntaxError: Invalid regular expression: invalid group specifier name in index.ts:62
```
Very promising project though 🤩

**Comment by doodlewind** [comment]
Thanks for the feedback! This should be a regression and will be investigated.

**Comment by doodlewind** [comment]
Fixed in latest playground.
