### ISSUE TITLE
In Edgeless mode, the Bookmark menu does not respond or display completely

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#3246]
<img width="1003" alt="CleanShot 2023-06-29 at 14 49 45@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/4b61b49a-21d5-410d-bcd6-e1dd6a9918f1">

@JackiePengp mentioned that clicking "More" doesn't respond. I couldn't reproduce it, but after clicking, it doesn't display completely. It shouldn't be covered by the boundary of the Note.

**Comment by doodlewind** [comment]
/cc @QiShaoXuan since it works for image:

<img width="874" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/12560465-cd1c-4805-aa77-f6354aa4dd37">
