### ISSUE TITLE
when export the file with the markdown format, and import it again, it fails to do so and the imported file's title is not consistent with the original one

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#3247]
https://github.com/toeverything/blocksuite/assets/22443345/d313454b-44ec-495e-9b73-f16490955c6e

**Comment by zuoxiaodong0815** [comment]
The reason for this issue is that after having a multiple text node on the whiteboard, the features include markdown and html were modified badly. It have not enough time to fix this issue this morning .

**Comment by zuoxiaodong0815** [comment]
Now only the first text node can be exported and must be processed together.
