### ISSUE TITLE
Database column of type number does not work

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#3249]
When using column type of number no data can be entered (even numbers)

**Comment by zqran** [comment]
How to reproduce?

**Comment by joebeijing** [comment]
> How to reproduce?

https://github.com/toeverything/blocksuite/assets/22443345/e98040be-0384-48b5-b913-9903e1db8112

Here is the recorded video using internal version.

**Comment by zqran** [comment]
It seems that the data is not saved when the focus is lost, but now it is ok when pressing Enter.

**Comment by doodlewind** [comment]
Seems to be fixed according to the feedback from operation team
