### ISSUE TITLE
In Database preview, clicking on column doesn't activate the column menu

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3251]
![CleanShot 2023-06-29 at 15 20 57@2x](https://github.com/toeverything/blocksuite/assets/22443345/dcad6559-eaa9-469a-ab32-9f8fda0535f6)

**Comment by doodlewind** [comment]
@houjoe0829 is the database preview mode still in plan, or is it replaced by the right panel?

**Comment by houjoe0829** [comment]
> @houjoe0829 is the database preview mode still in plan, or is it replaced by the right panel?

Yes, it's still on the roadmap. We will consider it in the next iteration.

**Comment by doodlewind** [comment]
The database preview feature is already disabled, so this issue is unable to be reproduced. The development of datase features are also postponed, suggest re-tracking this at the moment it gets focused.
