### ISSUE TITLE
In the hidden note section, there could be an eye icon that allows reopening the card, similar to the button on the right

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#3264]
Split from #3233

Clicking on the icon with no hidden notes will expand the sorting bar. But clicking on a hidden note will display the page, which means the user's process of clicking this button will go from disappearance to display and then to sorting, which is in line with the user's habits.

**Comment by hwangdev97** [comment]
Yes, that's right, I suggested this modification. Clicking on the eye icon will also allow the layer to be reactivated (just like the button next to it). 
![shot-2023-06-30-15 26 48@2x](https://github.com/toeverything/blocksuite/assets/24713927/e40177ee-3e66-49a5-ab18-1bc3149b7604)

However, this version will not include any updates to the index icon-related features, so splitting it to do tracking is reasonable. 👍

**Comment by doodlewind** [comment]
Supported in latest playground


https://github.com/toeverything/blocksuite/assets/7312949/4575a993-4e20-499d-8c48-9a24c4db1199
