### ISSUE TITLE
Support gallery view for database block

### ISSUE THREAD

**Issue by hhzx** [toeverything/blocksuite#3283]
### Description

I really need the Gallery feature.Looking forward to receiving support, this feature is almost one of the most important features I can manage large volumes of documents. Thank you!

### Use case

![image](https://github.com/toeverything/AFFiNE/assets/2170168/3858a3ae-740e-4ea8-af0c-c7fad277503b)
Gallery in the Notion

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Thank you very much for your suggestion. It is on our roadmap, but at the moment we don't have a specific plan for it yet.

**Comment by hhzx** [comment]
First of all, thank you for your work! I will wait for the day when it is finished. Thank~
