### ISSUE TITLE
Edgeless mode breaks in newly​ created workspace

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3287]
To reproduce:

1. Create new workspace
2. Edgeless doesn't load - have to switch to Page mode firstly
3. Draw - can't erase

https://github.com/toeverything/blocksuite/assets/7312949/4018a3f1-13f5-4ff7-bb48-961d646c3b92

<img width="400" src="https://github.com/toeverything/blocksuite/assets/7312949/e583472f-fd66-4b5a-b3d6-e623cf36f74d">

Reported by @ShortCipher5 @himself65

**Comment by regischen** [comment]
![image](https://github.com/toeverything/blocksuite/assets/58546692/b7173e26-b26b-410f-bd23-b0eb8f6172f3)
at this time, the model of page doesn't have a child block of 'affine:surface'.
So the asserts is false, then the reset doesn't run

**Comment by doodlewind** [comment]
@regischen thanks for the investigation! Need a hotfix in AFFiNE to close this 👀

**Comment by regischen** [comment]
It seems like it's not reproducing again in latest affine-internal version.
