### ISSUE TITLE
Wrong tooltip text on switching editor mode

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3291]
![img_v2_3c369caf-b215-470c-b86c-0af33cfa514g](https://github.com/toeverything/blocksuite/assets/7312949/22f79320-c502-4f26-b697-e40ae30682fa)

(Reported by @hwangdev97)

/cc @lawvs to take a look, on maybe this should be fixed in AFFiNE?

**Comment by lawvs** [comment]
Closing this issue as it cannot be reproduced.
