### ISSUE TITLE
recalulate selected rect when resize/scroll the page

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#330]

**Comment by himself65** [comment]
https://user-images.githubusercontent.com/14026360/208166018-1699954f-e135-464b-a899-4e92f48d5f7f.mov

**Comment by himself65** [comment]
https://user-images.githubusercontent.com/14026360/208190227-a6302371-2181-4f23-9707-53c6a6bbacd1.mov

**Comment by himself65** [comment]
Related: https://github.com/toeverything/blocksuite/issues/616
