### ISSUE TITLE
The position of selected rect isn't right when drag element move

### ISSUE THREAD

**Issue by regischen** [toeverything/blocksuite#3301]
![selected rect](https://github.com/toeverything/blocksuite/assets/58546692/3b3bf104-1dd1-4fb5-936b-b4fd8d0d9e42)

**Comment by doodlewind** [comment]
Duplicate of #3289. Would be best if you can get this fixed during our current housekeeping stage @regischen

**Comment by regischen** [comment]
> Duplicate of #3289. Would be best if you can get this fixed during our current housekeeping stage @regischen 

I'll take a look
