### ISSUE TITLE
Cursor shifts after undoing generated ordered list using markdown syntax

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3306]
The main issue is that when using Markdown syntax shortcuts to generate a list, the cursor is positioned in front of the space when undoing.

https://github.com/toeverything/blocksuite/assets/22443345/aeb15220-5b1e-469f-99f2-1292c15bb495

Keeping the space after undoing is expected, but the cursor should be positioned after the space.

**Comment by Flrande** [comment]
> /cc @Flrande is it a regression?

No, I think it has always been like this.
