### ISSUE TITLE
Content pasted in title wrongly appended to page body

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/blocksuite#331]

**Comment by himself65** [comment]
I think this is intentional behavior.
For example, what if you paste an image in the title area?

**Comment by himself65** [comment]
> what if you paste an image in the title area?

I think we should detect whether the paste content is plain text or other stuff like an image blob. If it's the text, paste it into the title. Otherwise paste them into the body area

**Comment by himself65** [comment]
I'm working on this now
