### ISSUE TITLE
clicking on the eraser does not work

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#3324]
![20230704165636_rec_](https://github.com/toeverything/blocksuite/assets/22443345/40bd088c-b163-45a7-a2b3-985847b6ee24)

**Comment by regischen** [comment]
Let me try in windows machine

**Comment by regischen** [comment]
@joebeijing  are you trying in the latest internal version?

**Comment by regischen** [comment]
I tried on windows in latest interval verison, and I didn't reproduce it.

**Comment by joebeijing** [comment]
Can not reproduce it now.
