### ISSUE TITLE
Redundant text block inserted on repeatedly pasting text

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3326]
While pasting content repeatedly, new blocks of the pasted content will be randomly added, and the cursor will occasionally jump to the beginning of the content. Please see the two screencasts:

https://github.com/toeverything/blocksuite/assets/132558/f6a529e5-3441-4f14-b96d-3b966ab34127

https://github.com/toeverything/blocksuite/assets/132558/9c5d13f7-dc38-4741-b96b-faf82fb66cf3

**Comment by Flrande** [comment]
> /cc @Flrande does this relate to virgo cursor?

Maybe, I will look into it later.
