### ISSUE TITLE
Cannot select a row of the Database

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#3330]
Actual effect
<img width="759" alt="CleanShot 2023-07-04 at 17 27 50@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/10ebf42d-73c8-48d1-8d64-1cad19b92772">

**Comment by doodlewind** [comment]
Would require @zqran for tracking this 👀

**Comment by zqran** [comment]
I'll fix it.

**Comment by zqran** [comment]
I checked and in fact this row is already selected. 

@joe Do you think the style of row selection is not obvious now?

**Comment by joebeijing** [comment]
> I checked and in fact this row is already selected.
> 
> @joe Do you think the style of row selection is not obvious now?

Yes, the indicator is not incorrect.

**Comment by zqran** [comment]
I think I need @hwangdev97  to confirm the style of the row when it is selected.

**Comment by hwangdev97** [comment]
In Figma file, the row selection looks like:
![shot-2023-07-05-15 52 52@2x](https://github.com/toeverything/blocksuite/assets/24713927/1cbb90a9-6063-479f-bfa7-d5da3eb514f0)
