### ISSUE TITLE
Pressing enter in database tag input doesn't flush tag input

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#3332]
https://github.com/toeverything/blocksuite/assets/24713927/a0c18999-2eec-44ed-be70-d25662ea1ef0

Just like it was shown in the video,  after pressing enter, it appears that two tags were created and some suggested words are left behind.

**Comment by doodlewind** [comment]
On pressing enter, adding a new tag named `c p ` makes sense (since before confirming in IME, that's what you actually input in the input box). But the input box should be cleared for new tag content at the moment.

**Comment by zzj3720** [comment]
It looks like the `select` action should not be triggered during the `CompositionEvent`
