### ISSUE TITLE
Bundle size significantly bloated by `highlight.js`

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#334]
In #255 we added `highlight.js` as a dependency. This leads to a significant bloat in bundle size.

Before:

```
packages/playground build$ tsc --project ./tsconfig.json && vite build
[2 lines collapsed]
│ Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
│ ✓ 273 modules transformed.
│ rendering chunks...
│ dist/index.html                  0.85 KiB
│ dist/assets/index.74233d91.css   8.83 KiB / gzip: 2.14 KiB
│ dist/assets/index.6d7e3a8c.js    965.16 KiB / gzip: 273.16 KiB
```

After:

```
packages/playground build$ tsc --project ./tsconfig.json && vite build
[2 lines collapsed]
│ Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
│ ✓ 479 modules transformed.
│ rendering chunks...
│ dist/index.html                  0.85 KiB
│ dist/assets/index.9044078f.css   12.04 KiB / gzip: 2.85 KiB
│ dist/assets/index.93f52fc6.js    2028.87 KiB / gzip: 577.41 KiB
```

@thorseraq can we optimization on this?

**Comment by himself65** [comment]
I think in this PR, I've reduced the bundle size to about 270kb

**Comment by doodlewind** [comment]
> I think in this PR, I've reduced the bundle size to about 270kb

The bundle size `@blocksuite/blocks` is intermediate, we need to also measure the size in `@blocksuite/playground`.

**Comment by thorseraq** [comment]
OK! I’ll take a survey, see if we can reduce the bundle size increased by introducing highlight.js

**Comment by lawvs** [comment]
We can further reduce the size of the highlight by registering only part of the language

See https://github.com/highlightjs/highlight.js#es6-modules--import

<img width="604" alt="Screenshot 2022-12-28 at 1 59 15 PM" src="https://user-images.githubusercontent.com/18554747/209765267-6d215f69-d5c6-414f-adbb-74315be29f93.png">
