### ISSUE TITLE
Text input before link is also wrongly recognized as link

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3347]
<img width="1113" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/0bbbc39c-2c31-4225-ba73-5f21cdb2221f">

**Comment by lawvs** [comment]
Could you explain how to reproduce this issue?

**Comment by doodlewind** [comment]
> Could you explain how to reproduce this issue?

I think @QiShaoXuan has turned to @xell for reproduction and is working on this. So it would be better to keep current assignee unless further noticed.
