### ISSUE TITLE
Selection lost after focusing on image block using arrow key

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3350]
inner feedback row id: 37

https://github.com/toeverything/blocksuite/assets/7312949/ea7d721f-802a-41e0-90a9-873f38ebfe9e

**Comment by lawvs** [comment]
I found that the video doesn't match the issue title. Could you explain it in more detail?

**Comment by xell** [comment]
it's the original screencast gif by haoxin

![20230705134634](https://github.com/toeverything/blocksuite/assets/132558/447b8d02-eea5-41ee-9ef9-9e95ab1e0b03)

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/blocksuite/issues/1163

**Comment by doodlewind** [comment]
For image block in between, navigating through keyboard works fine for now. Possibly fixed by #3408 (on related ones).

https://github.com/toeverything/blocksuite/assets/7312949/f0cf996a-6772-426d-a757-8f2e151c63cc
