### ISSUE TITLE
Unable to open link without `http` prefix in database link column

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3351]
Can open `https://google.com` but not `google.com`

<img width="1059" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/2c87e24a-6e84-4c76-a7d4-a28c8a84d4db">

**Comment by zqran** [comment]
If the user does not enter a protocol here, do you need to add `http://` by default?

@joebeijing

**Comment by doodlewind** [comment]
> If the user does not enter a protocol here, do you need to add `http://` by default?
> 
> @joebeijing

I suggest not since you can't assume whether it's `http` or `https`

**Comment by zqran** [comment]
A link in the documentation will assume it's `http://`.

https://github.com/toeverything/blocksuite/assets/15389209/d1af242e-9b69-46fc-bc58-5336be82ab13

**Comment by joebeijing** [comment]
From my perspective, it is advisable to maintain consistency with the processing in the main body of the text, so that even if there are future modifications, they can be made together. What do you think? @doodlewind @zqran

**Comment by doodlewind** [comment]
> From my perspective, it is advisable to maintain consistency with the processing in the main body of the text, so that even if there are future modifications, they can be made together. What do you think? @doodlewind @zqran


Yes, making the link opening behavior consistent with the standard link is expected.
