### ISSUE TITLE
Inconsistant result when importing notion data from markdown

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#3355]
Notion:
![image](https://github.com/toeverything/blocksuite/assets/59462000/56be1714-d0d4-4886-80c4-511765826803)
Blocksuite:
![image](https://github.com/toeverything/blocksuite/assets/59462000/99499455-267d-48f0-9b98-9b62e73bd4bb)
Source file:
[4f2e21ae-1869-4afc-8763-c5416c62c1e2_Export-d4e7bd2c-e8ee-4cf8-b6ca-8624fb8e50e3.zip](https://github.com/toeverything/blocksuite/files/11955474/4f2e21ae-1869-4afc-8763-c5416c62c1e2_Export-d4e7bd2c-e8ee-4cf8-b6ca-8624fb8e50e3.zip)

**Comment by fourdim** [comment]
As these are all edge cases, this issue will be solved after the beta release.

**Comment by doodlewind** [comment]
Closing since we've considered https://github.com/toeverything/blocksuite/issues/2872 as finished, and more related edge cases should be built using transformer (in #3165) afterwards.
