### ISSUE TITLE
Support displaying row index in database block

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3365]
This would allow better reference to a specific database row (e.g., writing `row#3` as reference), good for our inner dogfooding on table. And this should also be optional.

<img width="481" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/71f4b2c7-04be-49ab-aef6-e2c41702a8a8">

/cc @joebeijing for the initial intention and evaluation.

**Comment by joebeijing** [comment]
Got it. There are still some questions to be addressed in terms of functional design: 
For example, is this ID a relative sequence or unique? Our view adjustments, such as filtering, may affect the display and order of each row.
We will conduct some research when working on this requirement.

**Comment by doodlewind** [comment]
I think we won't design or use `row#3` syntax in editor, and having the indexes changed on filtering is expected. Our usage here is more about the following:

<img width="738" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/82d62c8a-9a29-4158-8854-b8ea2579393b">

**Comment by doodlewind** [comment]
Closing since this is not planned recently.
