### ISSUE TITLE
Support row-level drag handle for database block

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3366]
Currently the page level drag handle works for database block, which leads to tightly-coupled widget design tech debts and (arguably) confusing UX. So having a row-level drag handle that works specifically for database block may be a better option.

<img width="478" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/7feb8d94-61e1-42cf-9ef6-340e7336b266">

/cc @joebeijing for the initial intention and evaluation.

**Comment by joebeijing** [comment]
From my perspective, as long as the global drag button looks the same, it should be fine. Users don't need to learn a new drag button. Also, our Database row can be dragged to other places outside the Database. As for the specific interaction, needs @hwangdev97  to take a look.

As for whether it will be implemented globally or separately, both are OK and I have no doubts about it.

**Comment by zqran** [comment]
> So having a row-level drag handle that works specifically for database block may be a better option.

From a development point of view, this is more reasonable and can remove this hard coding (suggestion given by @zzj3720 ).

https://github.com/toeverything/blocksuite/blob/c6a947a9ab689524f9bb0f284a5677523f6e7b9e/packages/blocks/src/database-block/table/components/selection/selection.ts#L170

**Comment by hwangdev97** [comment]
I hope we use a unified drag-and-drop UI without distinctions. As for the technical side, I think any approach would be acceptable. Considering the different styles of future views in the database, there will be many details to handle in the drag-and-drop feature.

**Comment by doodlewind** [comment]
Closed by #4698, thanks for the feat @donteatfriedrice!
