### ISSUE TITLE
Support per-element selected box for multi selection in edgeless

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3367]
This allows for better recognition of whether an element is selected inside the selection box:

https://github.com/toeverything/blocksuite/assets/7312949/198aa421-7533-4b36-a349-b1ec888a5518

**Comment by doodlewind** [comment]
Require @hwangdev97 for UI design.

**Comment by hwangdev97** [comment]
updated the design 👇

1. When making multiple selections, the child elements need to have a right-angled border. 
2. Hold down `shift` to unselect.

![shot-2023-10-11-11 12 00@2x](https://github.com/toeverything/blocksuite/assets/24713927/31873776-cd7a-403a-8772-3e07b9a420e8)


[figma link](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=11525%3A18634&mode=design&t=B0ODdP5nLjVNKavz-1)

**Comment by doodlewind** [comment]
This one would be good for @SydianAndrewChen to get familiar with current codebase.
