### ISSUE TITLE
Optimize default width for shape border

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3371]
Even the "thin" border width option is (subjectively) too bold when paired with default canvas text:

<img width="485" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/960f8571-366a-40f5-add8-3cb7e22bdd38">

See excalidraw as an comparison:

<img width="448" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/7efab822-31b5-431f-9f0c-0ffec28eecc3">

Since neither can we make the shape border *thinner* or the canvas text *bolder*, this may require a bit design tweaking. Guess this requires @hwangdev97 to take a look.

**Comment by hwangdev97** [comment]
the line‘s toolbar was used in the new design ( by @Svaney-ssman ):
![shot-2023-07-06-11 08 50@2x](https://github.com/toeverything/blocksuite/assets/24713927/b6c45766-e5db-4c0c-8996-9893a824a017)

I think, the shape border also needs to use this 

The toolbar's submenu also should use the new design. And this feature, I will create a new issue to track.

**Comment by doodlewind** [comment]
Closed by #3459, thanks @donteatfriedrice for the feat!
