### ISSUE TITLE
Unable to create bookmark inside database row​

### ISSUE THREAD

**Issue by Drake42** [toeverything/blocksuite#3374]
### What happened?

While writing in a new Record in a Database, I pasted a URL, and a dialog for creating a Bookmark appeared, but clicking on it did not work. (Creating Bookmarks worked fine outside of Records/Databases).

### Distribution version

macOS x64

### Anything else?

I'm using the stable version of AFFiNE, version 0.6.2

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for the bug report! I think we are not supporting bookmark as row content for the moment (each row in current database block should be a paragraph or list), so the current decision is to hide that entry in https://github.com/toeverything/blocksuite/issues/3346 and I'd like to close this as duplicate. /cc @lawvs
