### ISSUE TITLE
Clicking on canvas using shape tool should also add new shape element

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3376]
This sources from https://github.com/toeverything/blocksuite/pull/3335#pullrequestreview-1515586545

**Comment by donteatfriedrice** [comment]
> This sources from [#3335 (review)](https://github.com/toeverything/blocksuite/pull/3335#pullrequestreview-1515586545)

I have talk about it with @hwangdev97 yesterday, and he said we could not support 'click to add shape' for now.
