### ISSUE TITLE
Shape tool style in edgeless toolbar should align with latest edited shape state

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3377]
This sources from https://github.com/toeverything/blocksuite/pull/3335#pullrequestreview-1515586545

> Also, it may also be good for the shape overlay to inherit the last shape element style edited, so that we can keeping adding "blue shape with red fill color".

**Comment by donteatfriedrice** [comment]
> This sources from [#3335 (review)](https://github.com/toeverything/blocksuite/pull/3335#pullrequestreview-1515586545)
> 
> > Also, it may also be good for the shape overlay to inherit the last shape element style edited, so that we can keeping adding "blue shape with red fill color".

The overlay has been Rough style, but the roughness level  is low for the reason, when I increase the roughness and move the pointer, the shape overlay will be flashing.

**Comment by donteatfriedrice** [comment]
show as below:

https://github.com/toeverything/blocksuite/assets/99816898/a697d72a-e4a7-4113-9dd4-20e0a53bb005

**Comment by regischen** [comment]
> > This sources from [#3335 (review)](https://github.com/toeverything/blocksuite/pull/3335#pullrequestreview-1515586545)
> > > Also, it may also be good for the shape overlay to inherit the last shape element style edited, so that we can keeping adding "blue shape with red fill color".
> 
> The overlay has been Rough style, but the roughness level is low for the reason, when I increase the roughness and move the pointer, the shape overlay will be flashing.

You can give a fixed seed option to avoid flashing

**Comment by donteatfriedrice** [comment]
> > > This sources from [#3335 (review)](https://github.com/toeverything/blocksuite/pull/3335#pullrequestreview-1515586545)
> > > > Also, it may also be good for the shape overlay to inherit the last shape element style edited, so that we can keeping adding "blue shape with red fill color".
> > 
> > 
> > The overlay has been Rough style, but the roughness level is low for the reason, when I increase the roughness and move the pointer, the shape overlay will be flashing.
> 
> You can give a fixed seed option to avoid flashing

Big thanks!!!

**Comment by donteatfriedrice** [comment]
> This sources from [#3335 (review)](https://github.com/toeverything/blocksuite/pull/3335#pullrequestreview-1515586545)
> 
> > Also, it may also be good for the shape overlay to inherit the last shape element style edited, so that we can keeping adding "blue shape with red fill color".

If keep the style of last edited shape element, and apply it with newly added shape, there may be a inconsistence with the toolbar icon, is this ok with the design? @doodlewind

**Comment by doodlewind** [comment]
> > This sources from [#3335 (review)](https://github.com/toeverything/blocksuite/pull/3335#pullrequestreview-1515586545)
> > > Also, it may also be good for the shape overlay to inherit the last shape element style edited, so that we can keeping adding "blue shape with red fill color".
> 
> If keep the style of last edited shape element, and apply it with newly added shape, there may be a inconsistence with the toolbar icon, is this ok with the design? @doodlewind

Let's postpone this FTM, but /cc @hwangdev97 for further UX design.

**Comment by hwangdev97** [comment]
The design team has already incorporated shape designs in a doodle style, but there are still many details that need further refinement.
May be, we can start refining this aspect in the next iteration cycle: 

![shot-2023-07-06-17 34 04@2x](https://github.com/toeverything/blocksuite/assets/24713927/159561ec-316c-405d-9701-b20e1da30301)

**Comment by doodlewind** [comment]
I think it's now time for @donteatfriedrice to support the handwriting style icon in shape toolbar - making the static icon here could be great!

**Comment by doodlewind** [comment]
This should be tracked in #4173
