### ISSUE TITLE
Support URL embedding block type

### ISSUE THREAD

**Issue by CameronBrooks11** [toeverything/blocksuite#3391]
### Description

-     Allow users to embed diverse online content within app pages using URL embeddings
-     Support embedding of streaming multimedia, PDFs, forms, and interactive maps
-     Allow embedding of any content or service using a URL
-     Simplify embedding process by pasting the link into the desired app page
-     Provide a "Create embed" option for easy integration
-     Enhance app flexibility and convenience by enabling direct integration of online content into workflows

### Use case

Tons of use cases: maps, videos, webpages, diagrams, etc.

### Anything else?

I know that Notion has a great feature for this.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Thank you very much for your feedback. We have planned this product requirement, but there are no detailed plans yet. However, your vote has added one more to this requirement.

**Comment by doodlewind** [comment]
This is mainly covered by the bookmark block (#2574) and attachment block (#2952), so I'd mark this as completed.
