### ISSUE TITLE
[feature]: block suggestions 

### ISSUE THREAD

**Issue by meimosor** [toeverything/blocksuite#3393]
### 1~3 main use cases of the proposed feature

1.Add mention component, such as @someone,it can used in docs
2.Add table component
3.Support for document nesting and referencing
4.Support for document space, as well as document permission management

**Comment by doodlewind** [comment]
* For mention component, we need to finish #3398.
* For table component, we already have the database block landed and it's usable.
* For document referencing, we have shipped the bi-directional link feature in 0.6.
* For permission, this involves AFFiNE cloud capabilities and would not be tracked in BlockSuite.

So I'd close this as complete, let's keep tracking these features in corresponding issues if needed.

**Comment by Tejaswgupta** [comment]
@doodlewind how do we enable mention for `users` , couldn't find anything in the docs and the playground only gives option for mentioning other pages.

<img width="2013" alt="Screenshot 2024-04-17 at 2 03 53 PM" src="https://github.com/toeverything/blocksuite/assets/41832833/1d39ef56-a2bf-4119-bdf7-13bf247085c1">
