### ISSUE TITLE
New typesettings for every block

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#3400]
Design team just update the new typesettings: 
![shot-2023-07-06-16 35 35@2x](https://github.com/toeverything/blocksuite/assets/24713927/d39dc6e9-a656-4f52-b733-7e749a19508f)

[the figma file](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=4278%3A85613&mode=design&t=VC4OziLYFXsfZPdr-1)

Developer can just follow this: 

![shot-2023-07-06-16 37 27@2x](https://github.com/toeverything/blocksuite/assets/24713927/8241f151-49f2-4e1c-800b-883e253b736d)

**Comment by hwangdev97** [comment]
I think @JimmFly  has already done some work and needs to be checked.

**Comment by doodlewind** [comment]
Closing as duplicated of #3495
