### ISSUE TITLE
The scroll speed of new edgeless note toolbar is too fast

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3404]
https://github.com/toeverything/blocksuite/assets/7312949/d5fa3063-4366-42c9-8bc4-fb452ad940a6

Also the scroll direction should be reversed.

inner feedback id: 78

**Comment by donteatfriedrice** [comment]
> Screen.Recording.2023-07-06.at.16.54.01.mov 
> Also the scroll direction should be reversed.
> 
> inner feedback id: 78

It seems that it will be too fast when scrolling with touch bar, and it will be fine with mouse wheel. I will check it.
