### ISSUE TITLE
Unable to paste in edgeless mode

### ISSUE THREAD

**Issue by wanghongqu** [toeverything/blocksuite#3415]
### Description

pageless模式下，好像不能粘贴剪贴板内容

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Could you please give the affine version and the detailed bug?

**Comment by doodlewind** [comment]
You can double click to focus on a note block, then pasting should work.

**Comment by zuoxiaodong0815** [comment]
Today, I am busy. I will take look it next week.

**Comment by zuoxiaodong0815** [comment]
@wanghongqu Now we support pasting features is that if pasting text data , you should first focus one node. If not, it will only support pasting edgeless data. Could you please give us more detail on this issue?

**Comment by doodlewind** [comment]
Closing as not reproduced.
