### ISSUE TITLE
Support exposing playwright test helpers

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3426]
Now we also need some basic test cases on the AFFiNE side; I hope we can abstract a test helper functions library to make things easier.

```ts
// example
import { getEditor, assertBlock } from '@blocksuite/playwright/editor'
import { focusDatabase } from '@blocksuite/playwright/database'
import { test } from '@playwright/test'

test('x', async ({ page }) => {
  const editor = await getEditor(page)
  await focusDatabase(page)
  await editor.type('hello')
  await assertBlock((await editor.getBlockByFlavour('affine:database'))[0], {
    // ...
  })
})
```

**Comment by zhengjitf** [comment]
A little off-topic but related things: 
It might be easier to use them if they are loaded as fixtures. 

```ts
// load helper fixture before this

test('x', async ({ page, helper }) => {
  const editor = await helper.getEditor()
  await helper.focusDatabase()
  await editor.type('hello')
  await helper.assertBlock((await editor.getBlockByFlavour('affine:database'))[0], {
    // ...
  })
})
```

And then we can add some unified logic for them, e.g. define every helper function as a test step using `test.step(...)`, which makes sense to me, it can result in a more readable report.

For this test,
https://github.com/toeverything/blocksuite/blob/90a6e5e49bb1f7a4b8d969b5b483a4b3680f39f9/tests/paragraph.spec.ts#L43-L50

AS-IS:

![image](https://github.com/toeverything/blocksuite/assets/17249775/8c6bf886-a428-48a5-a5b8-71340f4ac642)

Hope like this:

![image](https://github.com/toeverything/blocksuite/assets/17249775/b64958b5-8bea-486e-9a05-d3d6a7c4dbfa)

Do you think it is helpful?

**Comment by doodlewind** [comment]
@Saul-Mirone do you have time for related infra design recently? If we decide to go for it, we may expose a `@blocksuite/test` package, or just publish `@blocksuite/playground` with test utils.

**Comment by Saul-Mirone** [comment]
This is interesting, I prefer to provide a `@blocksutie/test` package. But I don't have enough time for now to support it. Do we have other members have some bandwidth?

**Comment by doodlewind** [comment]
This is transferred to @doouding after discussion (so does our future testing infra maintaining), an `EditorDriver` fixture will make a lot of sense. Cheers.`

**Comment by zhengjitf** [comment]
I’d like to take some of the work if you think it will help. @doodlewind @doouding

**Comment by doodlewind** [comment]
@zhengjitf thanks for your interest! But I think our current plan in to have the basic prototype of the test package in the coming week, so avoiding duplicate work may be more beneficial.

**Comment by zhengjitf** [comment]
@doodlewind Got it.

**Comment by doodlewind** [comment]
We've added test utils in #3939 to allow easier testing, but I think the test in BlockSuite should still be self-contained to make sure we fix regression in tis CI.
