### ISSUE TITLE
Database title column UI issue (in dark mode)

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#3428]
Dark mode - cannot differentiate between rows of the darkened `Title` column

![Screenshot 2023-05-12 at 11 30 57](https://github.com/toeverything/AFFiNE/assets/4605025/41a420d9-71da-4050-afdb-5f9585e78419)

**Comment by zqran** [comment]
Under version 0.7.0-canary.38, there is no problem.

Related to: [2639](https://github.com/toeverything/blocksuite/issues/2639)

<img width="672" alt="image" src="https://github.com/toeverything/blocksuite/assets/15389209/fec8be18-8700-43df-8957-fa1207015569">

**Comment by doodlewind** [comment]
Closing as fixed according to the feedback, thanks for the involvement!
