### ISSUE TITLE
Console error on right click in edgeless mode

### ISSUE THREAD

**Issue by Yukiniro** [toeverything/blocksuite#3429]
![截屏2023-07-08 17 13 39](https://github.com/toeverything/blocksuite/assets/21242087/93657702-976f-4e9c-a26b-4e1676f212ec)

I found that in normal mode, the contextmenu event uses `ctx.get('defaultState')`, but in editor mode it is `ctx.get('pointerState')`, I can imitate normal mode by using defaultState to fix it, but I noticed that the subsequent logic of editor mode will be used in `onContainerDragStart` to `defaultState`. 
```ts
if (edgelessTool.type !== 'pan' && !this._rightClickTimer) {
      this._rightClickTimer = {
        edgelessTool: edgelessTool,
        timeStamp: e.raw.timeStamp,
        timer: window.setTimeout(() => {
          this._controllers['pan'].onContainerDragStart(e);
        }, 233),
      };
    }
```
So I'm not sure whether to fix it by using defaultState or by supplementing contextmenu 's events in `pointer.ts` .

**Comment by Saul-Mirone** [comment]
I think we should provide `defaultState` for all events, I'll add the support soon.

**Comment by doodlewind** [comment]
Not reproduced in latest playground
