### ISSUE TITLE
Support mathematical input (Mathjax, KaTeX, server-side LaTeX renderer, Mathlive, etc.)

### ISSUE THREAD

**Issue by bohrium2b** [toeverything/blocksuite#3432]
### 1~3 main use cases of the proposed feature

As a student, I want to be able to take notes and use AFFiNE as a whiteboard + note taking solution. Being able to include mathematics would be great!
Also, I can imagine teachers using this for lessson plans, etc. 

### Ideas for solution

Implementing a latex editor, a la Zettlr (after typing latex in `$` signs, Zettlr automatically renders it using a LaTeX web renderer), or using a visual math editor like MathLive, if could add a math button to the editor or by typing `/math` it inserts a MathLive editor (https://cortexjs.io/mathlive/), and when users navigate away from that input box, it will automatically render using a service like KaTeX (katex.org) or Mathjax (mathjax.org). 

### what types of users can benefit from using your proposed feature

students, anyone that needs to insert math

**Comment by Flrande** [comment]
> Would the Affine team be interested in a math featureset that goes much further, and includes things like "calculating" and "graphing"?
> 
> If yes, I'd potentially be interested in implementing that.

We are advancing certain technological infrastructure to better achieve such functionalities. You can check out this [issue](https://github.com/toeverything/blocksuite/issues/3398).

**Comment by doodlewind** [comment]
We'll keep tracking this in #3014, closing this one since this comes from legacy backlog.

**Comment by helunbaodegui** [comment]
up! waiting for support
