### ISSUE TITLE
Support GPT-based auto completion

### ISSUE THREAD

**Issue by rthsvvn** [toeverything/blocksuite#3433]
blocksuite would be a perfect editor if it supports auto-completion with GPT like https://github.com/steven-tey/novel

**Comment by himself65** [comment]
Related: https://github.com/toeverything/AFFiNE/tree/master/plugins/copilot

**Comment by doodlewind** [comment]
The plan is to handled in AFFiNE as plugin, instead of maintaining standalone support in the editor. But rest assured that we'll have the extensibility to build such extension using BlockSuite.
