### ISSUE TITLE
Add number prefix to a todo item should not forcefully change it into numbered list, vice versa

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3468]
https://github.com/toeverything/blocksuite/assets/132558/45243302-280c-4de4-b799-a1407ac73249

**Comment by smallnine9** [comment]
Should we consider toggle list case?

**Comment by doodlewind** [comment]
@smallnine9 the standalone toggle list type will be deprecated (instead, we plan a comprehensive toggle support for all heading and list types). So we don't have to consider its case FTM.
