### ISSUE TITLE
Support proper labels to the input field of bookmark edit menu

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3470]
Without labels, users sometimes are difficult to decide the usage of the input fields

![CleanShot 2023-07-11 at 22 55 06@2x](https://github.com/toeverything/blocksuite/assets/132558/7bec0491-acbb-4108-af91-abd6c68bf7ee)

**Comment by Svaney-ssman** [comment]
Will re-design this menu to “Edit in place" mode, please wait for the latest version @QiShaoXuan, will let you know

**Comment by QiShaoXuan** [comment]
fixed in https://github.com/toeverything/blocksuite/pull/3486

**Comment by QiShaoXuan** [comment]
> Will re-design this menu to “Edit in place" mode, please wait for the latest version @QiShaoXuan, will let you know

Open new issue after new design completed
