### ISSUE TITLE
Coping and pasting url from Edge browser in Windows gets webpage title

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3471]
After coping url from Edge browser in Windows, pasting the url will strangely result in the webpage title instead of the url.

A limited test with other browsers in Windows or macOS has normal behavior.

https://github.com/toeverything/blocksuite/assets/132558/0fa1e4e9-a4ab-422b-bc9e-74c8daff0001

**Comment by fourdim** [comment]
Duplicate of #2787.
Already fixed in #3458.
