### ISSUE TITLE
Colon added after the text unexpectedly shows a link

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3481]
This can be confirmed both by Macs and Windows
version: latest internal

https://github.com/toeverything/blocksuite/assets/134897361/d8ba565c-4a23-4190-9f34-07c64f4e83d8

**Comment by lawvs** [comment]
I think the "column" means "colon" not the column in the database block.

https://github.com/toeverything/blocksuite/assets/18554747/c3986602-755e-497e-b608-3d5e38fdbb1b
