### ISSUE TITLE
Slash menu did not work

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3485]
https://github.com/toeverything/blocksuite/assets/134897361/e81fda4a-0074-4cd0-8600-7173d636ecf7

version: latest internal
only exist in my computer? windows

**Comment by doodlewind** [comment]
This would require @lawvs to triage.

**Comment by lawvs** [comment]
Cannot reproduce the issue. Need more detailed information or specific steps to reproduce.

**Comment by doodlewind** [comment]
Closing as not reproduced FTM, may be a cherry-pick related issue in earlier internal version.

**Comment by lawvs** [comment]
This issue can be reproduced by pressing the slash key while using CJK IME in Windows.
