### ISSUE TITLE
Unable to use block hub and its button duplicates

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#3487]
version: latest internal(0711 internal)
MacOS

1. blockhub can not be used
2. when add a new page, which will add a new blockhub button
3. all buttons on the block hub do not work.

https://github.com/toeverything/blocksuite/assets/79373028/6770b46a-0886-453e-abbf-b68ca633abd1

**Comment by doodlewind** [comment]
Seems to be an AFFiNE integration issue, require @doouding to triage.

**Comment by doouding** [comment]
Can't reproduce on latest canary [0712 internal](https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-20230712180200-1bc8d6a). Maybe check it again?

**Comment by Yipei-Operation** [comment]
the version is [internal](https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-20230712084325-770bde8) , not canary, it should be with the internal
operation side will not test canary, just internal version.
<img width="409" alt="kYJzdnqfOd" src="https://github.com/toeverything/blocksuite/assets/79373028/3c80dc74-c761-44f0-9887-881a52b51d33">

**Comment by Yipei-Operation** [comment]
also cc @himself65 for check cherry pick thing

**Comment by Yipei-Operation** [comment]
checked latest internal (0713), it has been fixed

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/AFFiNE/pull/3199, thanks to @himself65
