### ISSUE TITLE
Wrong background color on copied PNG in edgeless mode

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#3489]
version: latest internal (both 711/712 version)
system: macOS

1. when change the block color, then choose to 「copy as PNG」
2. the PNG will shown mistake: all background color is blue

https://user-images.githubusercontent.com/79373028/252936188-7db5a0e0-ae2b-47ff-a9dc-563db79ed91d.mp4

**Comment by xell** [comment]
According to @zuoxiaodong0815 , the output result directly from the code is correct, so we'll see if it's not cherry picked to the release by @alex. C.f. https://github.com/toeverything/blocksuite/issues/3293

**Comment by doodlewind** [comment]
@Yipei-Operation not sure if you think this is a fatal one?

**Comment by Yipei-Operation** [comment]
I think this is a fatal one, as 「copy as PNG」 is a common function, it is more common than exported scenes

**Comment by zuoxiaodong0815** [comment]
close by #3502
