### ISSUE TITLE
Invalid result in copied PNG with shape and note content both exists inside

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#3490]
system: MacOS
version: latest internal (711/712 version)

1. one text block under edgeless mode
2. add some shapes around the block
3. copy as png for the whole area
4. paste PNG to paper mode
5. PNG content is garbled

https://github.com/toeverything/blocksuite/assets/79373028/a1105d04-05f4-4760-b533-fb3201c62e83

**Comment by doodlewind** [comment]
@Yipei-Operation not sure if you think this is a fatal one?
