### ISSUE TITLE
Content text lost when copied as PNG with shape and text inside

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#3492]
system: all
version: latest internal (711/712)

1. under edgeless mode, 1 area has both shape block and text block
2. choose copy as PNG
3. paste to paper mode, content text has been lost with the image

https://user-images.githubusercontent.com/79373028/252938786-3c1356f3-8107-464d-ab48-ca5032ce7478.mp4

**Comment by zuoxiaodong0815** [comment]
close by https://github.com/toeverything/blocksuite/pull/3502
