### ISSUE TITLE
Inserted image size should be consistent in different viewport zoom level

### ISSUE THREAD

**Issue by zuoxiaodong0815** [toeverything/blocksuite#3499]
https://github.com/toeverything/blocksuite/assets/53252747/191b1f36-1b9f-452d-b5ec-5771024c3047

**Comment by doodlewind** [comment]
Due to the lack of edgeless maintainers this week, this has to be handed over to @doouding to take a look if time allows.

**Comment by donteatfriedrice** [comment]
> Due to the lack of edgeless maintainers this week, this has to be handed over to @doouding to take a look if time allows.

maybe i can help

**Comment by doouding** [comment]
@donteatfriedrice I just saw this. I'll close my PR.

**Comment by donteatfriedrice** [comment]
> @donteatfriedrice I just saw this. I'll close my PR.

sorry😭, i thought you were busy with other issues...

**Comment by doouding** [comment]
> > @donteatfriedrice I just saw this. I'll close my PR.
> 
> sorry😭, i thought you were busy with other issues...

Not a problem.
