### ISSUE TITLE
Hiding objects on page mode will remove background

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#3508]
This object and the colour changes are only visible in Edgeless so it doesn't seem to make much sense that if you change to "hidden from Page mode" that the formatting is lost.

https://user-images.githubusercontent.com/4605025/253146586-035b3faf-6d2c-418c-b05c-67a60e0bd976.mov

**Comment by Flrande** [comment]
It is by design to differentiate. cc @hwangdev97

**Comment by doodlewind** [comment]
Closing as by design according to current requirement.
