### ISSUE TITLE
Lagging when drawing and zooming in edgeless mode with large content count

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3513]
in latest internal 0.0.0-20230711043747-74e6fd8 

https://github.com/toeverything/blocksuite/assets/132558/ef97e86c-a879-49e6-a70d-aa5cca7e8952

**Comment by himself65** [comment]
> @xell what is the version of the app and what is the OS that has lags?

You can see the right top. So it's windows

**Comment by himself65** [comment]
![img_v2_4e5aefa2-c3a9-4617-b001-38b2f24048ag](https://github.com/toeverything/blocksuite/assets/14026360/04bb6716-3c25-4044-bcde-a4cb114a99cf)

**Comment by himself65** [comment]
The performance issue is just because there are too many elements in the editor

**Comment by doodlewind** [comment]
I reproduced this in edgeless mode using http://localhost:5173/?init=heavy (with 1000 preset blocks). Would be great if @doouding could take a look at the perf bottle neck.

**Comment by xell** [comment]
Is this issue relate with the laggy, stuttering animation of sidebar?


https://github.com/toeverything/blocksuite/assets/132558/6dac8dd2-b1cb-44bb-afdb-4a4ea231811f

**Comment by himself65** [comment]
> Is this issue relate with the laggy, stuttering animation of sidebar?
> 
>  CleanShot.2023-07-17.at.12.46.05.mp4

This still whiteboard performance issue

**Comment by pengx17** [comment]
Maybe related https://github.com/steveruizok/perfect-freehand/pull/56
