### ISSUE TITLE
Error: Cannot find block element by model: affine:paragraph id: mPMkX6IL5L

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3516]

**Comment by himself65** [comment]
[AFFiNE_5I6ydY7vZK.affine.zip](https://github.com/toeverything/blocksuite/files/12036401/AFFiNE_5I6ydY7vZK.affine.zip)

**Comment by doodlewind** [comment]
Require @doouding to justify if this is an integration issue 🤔

**Comment by doouding** [comment]
I'm on it.

**Comment by doouding** [comment]
I found the data is corrupted (some blocks are missing, but their parent blocks still reference their IDs in the children array). Possibly due to other issue or error.
I have made no progress on finding further causes, so I decided closing it.
