### ISSUE TITLE
style incorrect on code block

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#352]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/14026360/208307669-06dea1a5-15c4-4941-b650-9934abce6024.png">

**Comment by thorseraq** [comment]
I think the style has been updated in #349, are we good to mark it resolved :)

**Comment by doodlewind** [comment]
> I think the style has been updated in #349, are we good to mark it resolved :)

Thanks! Closing as resolved.
