### ISSUE TITLE
Support updating thickness by drag in edgeless mode

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3538]
https://github.com/toeverything/blocksuite/assets/134897361/ccba9c6a-4845-4cc4-8048-f77a338f7a3e

version: latest internal 
double check with mac and windows

**Comment by donteatfriedrice** [comment]
It seems that only support clicking to choose thickness by design currently.

**Comment by donteatfriedrice** [comment]
> It seems that only support clicking to choose thickness by design currently.

@doodlewind @Svaney-ssman should we support to drag to select thickness?

**Comment by xell** [comment]
I think it's rather a feature request from product side and it should be implemented.
