### ISSUE TITLE
Unable to write text and insert bookmark in pagemode

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3540]
https://github.com/toeverything/blocksuite/assets/134897361/7701dd08-ffc1-4856-96f1-a3c1d6d5683c

version: latest Internal

**Comment by doodlewind** [comment]
I found this is not reproduced in newer internal release (https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-internal.20230714053343-27fa565)
