### ISSUE TITLE
Database is expected to split on two pages in exported PDF

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#3544]
![Image](https://github.com/toeverything/blocksuite/assets/134894293/d59efc42-8177-49e0-8316-0234c724179f)

**Comment by zuoxiaodong0815** [comment]
Sorry, it calls the printing API of the browser when exporting pdf, we can just only adjust the style. However, it is not possible to control how to page. @PaxtonXuan
