### ISSUE TITLE
The image in the page mode can not be copied and downloaded

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#3545]
![Image](https://github.com/toeverything/blocksuite/assets/134894293/598d0ebe-b8bc-4d56-8238-aef1da47e501)

**Comment by doodlewind** [comment]
This is reproduced in latest internal (but not in BlockSuite playground). Require @zuoxiaodong0815 to take a look.

**Comment by ShortCipher5** [comment]
Download is working in the latest internal - but not the copy function.

**Comment by ShortCipher5** [comment]
Added video:

https://github.com/toeverything/blocksuite/assets/4605025/c81e4f6f-4fe6-4733-9ade-3a65ea174825
