### ISSUE TITLE
Edgeless toolbar upgrades

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#3550]
The pen, shape, connectors' submenu of toolbar have been redesigned, plz check the [figma link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=5143-105979&mode=design&t=aNu51fcP4YpIyhDC-4)

![Image](https://github.com/toeverything/AFFiNE/assets/110808979/235775da-e792-4f89-9cef-047a9486331f)

**Comment by doodlewind** [comment]
Closed by #4061

**Comment by xell** [comment]
I do appreciate the workloads showed in the PRs and the function implementations are great, by which I verified this issue. However, it seems the UI bugs need another issue to handle, for example ( Figma design in magenta):

<img width="1055" alt="CleanShot 2023-08-16 at 13 01 24@2x" src="https://github.com/toeverything/blocksuite/assets/132558/accbd567-dd75-4d26-895a-ebbafe6e4f0e">

**Comment by doodlewind** [comment]
@xell yes, and I think @donteatfriedrice will address this in standalone PRs. Having the functionality work and land it matches our policy.

**Comment by donteatfriedrice** [comment]
> I do appreciate the workloads showed in the PRs and the function implementations are great, by which I verified this issue. However, it seems the UI bugs need another issue to handle, for example ( Figma design in magenta):
> 
> <img alt="CleanShot 2023-08-16 at 13 01 24@2x" width="1055" src="https://user-images.githubusercontent.com/132558/260905406-accbd567-dd75-4d26-895a-ebbafe6e4f0e.png">

@Svaney-ssman will update the design, and I will update these submenu after she complete it.
