### ISSUE TITLE
code block display in wrong format

### ISSUE THREAD

**Issue by lichuan6** [toeverything/blocksuite#3559]
### What happened?

When copying from VSCode and pasting into code block, source codes display in wrong format.

<img width="797" alt="aaaaaaa" src="https://github.com/toeverything/AFFiNE/assets/74223747/8cff28d0-a3c2-4525-8428-3c7e446c54bd">

### Distribution version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for your feedback! Could you please share about the expected result? Is the indentation or spaces that are unmatched?

/cc @zuoxiaodong0815

**Comment by fourdim** [comment]
Missing space between lines. Wrong line number.
![image](https://github.com/toeverything/blocksuite/assets/59462000/c9874167-06ea-4629-a696-a51252647faa)
![image](https://github.com/toeverything/blocksuite/assets/59462000/8764b884-a6e4-4f04-b8e1-4e5b41fa4769)
