### ISSUE TITLE
Support CTRL + Del to delete one word forward

### ISSUE THREAD

**Issue by DieSchoeneWolke** [toeverything/blocksuite#3566]
### Description

Delete one word to the right like in any other program.

### Use case

I rely on this keybind a lot.

### Anything else?

https://defkey.com/what-means/ctrl-del
### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by joebeijing** [comment]
Related content：https://www.computerhope.com/jargon/c/ctrl-del.htm

**Comment by DieSchoeneWolke** [comment]
Thank you very much for taking care about this so quickly! 🥳

@lzlme @Flrande
