### ISSUE TITLE
Cannot fetch the images, videos blocked by CORS policy

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3567]
There is an issue when copying and pasting from affine official website. 

![Image](https://github.com/toeverything/blocksuite/assets/134897361/450e9282-0ae3-44b2-ae09-181ff6ffad93)

![Image](https://github.com/toeverything/blocksuite/assets/134897361/744c25d4-a51e-41f6-b406-5cc4a1433d8d)

**Comment by fourdim** [comment]
Access to fetch at 'https://app.affine.pro/api/workspace/H6vffRmJbCfA-r3kq_36_/blob/9a_9HM2vfDl0edwyQ37HEXmjKSbqnXtpxHQaZ6Uhra0=' from origin 'http://localhost:5173/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by doodlewind** [comment]
Considered resolved since we support configuring the request proxy.
