### ISSUE TITLE
Support importing image and database in markdown

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#3569]
https://github.com/toeverything/blocksuite/assets/134894293/c112d2fd-82b5-4fb5-a52a-0af47f0dee59

**Comment by zuoxiaodong0815** [comment]
We may deal with this in the next development cycle.

**Comment by doodlewind** [comment]
For the lossless importing & exporting of database, we plan the support in #3654 and the progress should be track there. Due to this change, I think it's not planned to import non-URL image from markdown.
