### ISSUE TITLE
Support smooth scrolling and transition in edgeless color picker

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#3570]

**Comment by donteatfriedrice** [comment]
@PaxtonXuan Could you please add more details about this issue like adding a video? The user can use mouse wheel to move left and right currently for the note toolbar menu in design, does use mouse wheel not work?

**Comment by hwangdev97** [comment]
from the product design side, this toolbar should support:

1. After scrolling, left and right buttons need to be displayed
2. Enlarge when hovering
3. Click should be the next page, not the next one
4. Support horizontal scrolling 

![shot-2023-07-17-16 35 29@2x](https://github.com/toeverything/blocksuite/assets/24713927/a48c38b1-2c3b-4f6e-93f9-4f0a9063dcc1)

**Comment by doodlewind** [comment]
I think this has just been supported in #4139.
