### ISSUE TITLE
Drag indicator should be visible during resizing database column width

### ISSUE THREAD

**Issue by JackiePengp** [toeverything/blocksuite#3572]
https://user-images.githubusercontent.com/121489905/253845235-16f99a23-dded-4ad8-8e06-cc4093b002f7.mp4

**Comment by xell** [comment]
As in the example of Feishu, the blue line is visible all the time when dragging.


https://github.com/toeverything/blocksuite/assets/132558/dbda9430-645f-49ba-88b2-56fb83d4e16b
