### ISSUE TITLE
The toolbar of note within the edgeless mode can only move right

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#3576]
https://github.com/toeverything/blocksuite/assets/134894293/0a99f5f2-c32a-4bff-801a-b9c8bd2d9504

**Comment by donteatfriedrice** [comment]
this issue seems to be a duplicate of #3570

**Comment by hwangdev97** [comment]
this issue is duplicated, we will use #3570  to track this problem
