### ISSUE TITLE
Copy as PNG in edgeless mode should wait until "copy to clipboard" or user will get the wrong image

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3577]
version: latest internal 
Already confirmed with Xiaodong

https://github.com/toeverything/blocksuite/assets/134897361/157112e5-6004-4176-aef8-62c4ae865176

Give hints during copying

**Comment by houjoe0829** [comment]
The suggested approach is to not block the user's operation, but if it fails, provide a toast message saying 'Failed to copy as PNG'
