### ISSUE TITLE
Support retain formatting for block slicer

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#3578]
When using Block Splitter the newly created block will not retain the formatting - such as background colour.

https://github.com/toeverything/AFFiNE-Community/assets/4605025/fc61ed76-114f-4ff4-9c25-5a2d8a29c871

**Comment by doodlewind** [comment]
I think this can be handled as an edgeless optimization in our next iteration scope.

**Comment by doouding** [comment]
This should be an easy fix.
