### ISSUE TITLE
Unable to delete the link icon by keyboard

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3581]
version: latest internal (16:37)
unless you select all, you can delete the link mark

https://github.com/toeverything/blocksuite/assets/134897361/82898602-c3a1-43a6-a73a-9c5ae3509f08

**Comment by doodlewind** [comment]
Not sure if @lawvs can reproduce this?

**Comment by doodlewind** [comment]
Closing as not reproduced in latest playground.
