### ISSUE TITLE
Support more efficient and convenient flowchart creation and editing

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#3596]
The ability similar to whiteboard tools such as Miro and Whimsical.

https://github.com/toeverything/blocksuite/assets/22443345/f6e948ab-f9d4-45d0-9391-d79df1a5115c

**Comment by hwangdev97** [comment]
[the design file](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=9999%3A163902&mode=design&t=4jB7FxFnJYo6VOXb-1)


![image](https://github.com/toeverything/blocksuite/assets/24713927/ce2134a4-684b-40c7-a1b6-8fcf16262667)

**Comment by houjoe0829** [comment]
PRD：[Internal doc](https://toeverything.feishu.cn/wiki/WZ5owDKUpi9lz1kYxkHceskynff)
