### ISSUE TITLE
Support viewer (readonly) mode in edgeless

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3597]
For sharing doc as edgeless mode (https://github.com/toeverything/AFFiNE/issues/3287), we need to provider a "view only" whiteboard view that doesn't include editing features by default.

**Comment by JimmFly** [comment]
I am looking forward to the implementation of this feature, as the pages in AFFiNE that are moved to the trash need it.

**Comment by JimmFly** [comment]
By the way, do new functions like database and tag support the readonly mode?

**Comment by doodlewind** [comment]
`page` can freeze the content at the model layer, but IMO the UI should also be adapted in this use case - requires some more design.
