### ISSUE TITLE
Workaround potential invalid block tree

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3600]
For flat list item A B, if A is dragged as child of B and B is dragged as child of A concurrently, the merged result may lead to invalid block tree structure. A workaround is required to ensure availability.

/cc @Saul-Mirone

**Comment by Brooooooklyn** [comment]
https://affine.fail/workspace/b894e768-1355-46f6-84f6-658f21a9521f/yF5m7109v8

**Comment by doodlewind** [comment]
Closing since we've landed https://github.com/toeverything/blocksuite/pull/5264 and this is not reproduced recently.
