### ISSUE TITLE
copy as PNG bug:  cropping shapes

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3630]
![Image](https://github.com/toeverything/blocksuite/assets/134897361/471eb1a5-ff19-4044-a5a5-ed34d09eca02)

**Comment by Yanxi0202** [comment]
need more details with user, perhaps is similar to this issue: https://github.com/toeverything/blocksuite/issues/3615

**Comment by zuoxiaodong0815** [comment]
This issue is same as https://github.com/toeverything/blocksuite/issues/3615
