### ISSUE TITLE
Bookmark ​popup UI is overlapped

### ISSUE THREAD

**Issue by softund** [toeverything/blocksuite#3652]
### What happened?

bookmark ​can't show complete information.
details in this link:https://community.affine.pro/c/bug-reports/book-mark-can-t-show-complete-information

### Distribution version

macOS x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xell** [comment]
> /cc @xell to add this to our cleanup backlog.

Okay and it's been also added to the housekeeping list.
