### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by tmlmt** [toeverything/blocksuite#3656]
# Description

It would be great to have an auto-generated, auto-updated Table of Content using the headings in the documents. 
Like what you can get in a Jupyter Notebook with the [Table of Content (2) nbextension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html), whose different settings (sidebar or floating window, automatic top block with the toc in it) could be used for inspiration. 
Is that something you have planned or could be planned?

# Use case

Long pages, where it would be very useful to move from one section to the other, or get more easily an idea of the page structure

# Screenshot

(From the Jupyter Notebook nbextension)
![image](https://github.com/toeverything/blocksuite/assets/10244927/0ad3b9ad-42b9-4a99-8800-4eb6f82a167c)

**Comment by doodlewind** [comment]
Thanks for the feedback! This is WIP in #3138.

**Comment by doodlewind** [comment]
Closing since we've landed #3138
