### ISSUE TITLE
Playground 中文无法输入

### ISSUE THREAD

**Issue by Aaronphy** [toeverything/blocksuite#3661]
![ccc](https://github.com/toeverything/blocksuite/assets/16236806/100719ce-ea64-4056-aae2-2b4f9bae907b)
可以解答下吗

**Comment by lawvs** [comment]
I'm very sorry, we will fix it as soon as possible. I believe this is introduced in https://github.com/toeverything/blocksuite/pull/3653

**Comment by doodlewind** [comment]
Fixed in latest playground (possibly by #3674)
