### ISSUE TITLE
Add getting started tutorial for react and next.js

### ISSUE THREAD

**Issue by neelhabib** [toeverything/blocksuite#3663]
I have tried but unable to implement the editor in Nextjs. Is there any simple way to implement in nextjs? Thanks

**Comment by himself65** [comment]
See our minimum example https://github.com/himself65/affine-minimum/blob/stable/src/components/Editor.tsx

**Comment by neelhabib** [comment]
> See our minimum example https://github.com/himself65/affine-minimum/blob/stable/src/components/Editor.tsx

Thanks. But its not straight forward. Requires other packages. I want to implement it on my existing project with redux. Is there any official docs for nextjs implementation. Thanks

**Comment by himself65** [comment]
I'm working on this.

**Comment by yunnian** [comment]
Is there any progress in the tutorial? I am also unable to use it in next.js 

error & stack：
![image](https://github.com/toeverything/blocksuite/assets/5779513/033acfa5-f6ff-49ea-87ba-dfc28dc18033) ![image](https://github.com/toeverything/blocksuite/assets/5779513/a7d5d14c-dbff-4d42-85e9-7c4a371af6e4)![image](https://github.com/toeverything/blocksuite/assets/5779513/937f9a8d-69bf-4177-80b2-7048faad5cf7)

**Comment by doodlewind** [comment]
@zuoxiaodong0815 seems that the error stack above is related to `ContentParser`, which would require you to take a look in Next.js environment if there are recent regressions. Thanks.

**Comment by zuoxiaodong0815** [comment]
> @zuoxiaodong0815 seems that the error stack above is related to `ContentParser`, which would require you to take a look in Next.js environment if there are recent regressions. Thanks.
Ok, I will look at it today later.

**Comment by yunnian** [comment]
![image](https://github.com/toeverything/blocksuite/assets/5779513/abd340d6-f28c-4046-9311-cb241c9b881c)
官方的这个get start 试了市面上的框架都没执行成功过...，不用框架也报错 ，心累

**Comment by himself65** [comment]
> ![image](https://user-images.githubusercontent.com/5779513/265233061-abd340d6-f28c-4046-9311-cb241c9b881c.png) 官方的这个get start 试了市面上的框架都没执行成功过...，不用框架也报错 ，心累

See our official binding!
https://github.com/toeverything/AFFiNE/blob/master/packages/component/src/components/block-suite-editor/index.tsx

**Comment by kaianuar** [comment]
I've followed the tutorial as well for SimpleAffineEditor and I get this error on `yarn start`

```
✘ [ERROR] Could not resolve "events"

    ../node_modules/readable-web-to-node-stream/node_modules/readable-stream/lib/internal/streams/stream-browser.js:1:25:
      1 │ module.exports = require('events').EventEmitter;
        ╵                          ~~~~~~~~

  The package "events" wasn't found on the file system but is built into
  node. Are you trying to bundle for node? You can use "platform: 'node'" to
  do that, which will remove this error.
```

I haven't seen anyone having this error, so I'm guessing I must be doing something wrong. Any advise?

**Comment by guugg** [comment]
I can run SimpleAffineEditor in react,
> However, the SimpleAffineEditor here is just a [thin wrapper with dozens of lines](https://github.com/toeverything/blocksuite/blob/master/packages/editor/src/components/simple-affine-editor.ts) that doesn't enable the opt-in collaboration and [data persistence](https://blocksuite.affine.pro/data-persistence.html) features.

**Comment by yunnian** [comment]
> > ![image](https://user-images.githubusercontent.com/5779513/265233061-abd340d6-f28c-4046-9311-cb241c9b881c.png) 官方的这个get start 试了市面上的框架都没执行成功过...，不用框架也报错 ，心累
> 
> See our official binding! https://github.com/toeverything/AFFiNE/blob/master/packages/component/src/components/block-suite-editor/index.tsx

Thanks，参照这个在react+vite环境已经成功运行，但next.js无法运行成功，想用next.js来开发 @zuoxiaodong0815 冬哥是否有在看这个问题

**Comment by guugg** [comment]
> 

```
import '@blocksuite/editor/themes/affine.css';

import { EditorContainer } from '@blocksuite/editor';
import { Workspace, Schema, Page } from '@blocksuite/store';
import { AffineSchemas } from '@blocksuite/blocks';
import { useEffect, useRef } from 'react';
import { atom, useAtomValue } from 'jotai';


const schema = new Schema();


const workspace: Workspace = new Workspace({
  id: 'test-workspace',
  schema
});


schema.register(AffineSchemas);


const page: Page = workspace.createPage({
  id: 'page0'
});


//配置
page.clear();
await page.waitForLoaded();
// Add page block and surface block at root level
const pageBlockId = page.addBlock('affine:page', {
  title: new Text(),
});

page.addBlock('affine:surface', {}, pageBlockId);

// Add note block inside page block
//在页面内添加注释块
const noteId = page.addBlock('affine:note', {}, pageBlockId);
// Add paragraph block inside note block
//在Note Block中添加段落块
page.addBlock('affine:paragraph', {}, noteId);
page.resetHistory();


const editor: EditorContainer = new EditorContainer()
editor.page = page

const workspaceAtom = atom(workspace)
const editorAtom = atom(editor)

function App() {
  const ref = useRef<HTMLDivElement>(null)
  const editor = useAtomValue(editorAtom)
useEffect(() => {
  if (ref.current) {
    const div = ref.current
    div.appendChild(editor)
    return () => {
      div.removeChild(editor)
    }
  }
},[editor])

  return (
    <div>
      <div ref={ref} id='editor-container'></div>
    </div>
  )
}

export default App
```


可以试试这个

**Comment by yunnian** [comment]
拉取上面最新代码之后with那个问题好了，但是还有其他问题，具体如下：
![image](https://github.com/toeverything/blocksuite/assets/5779513/0ee0bb12-bf16-4a5f-8669-6c2240700ee3)
先是：document is not defined 
![image](https://github.com/toeverything/blocksuite/assets/5779513/a1fafe1c-48bc-41e8-b529-de9a5ddecae3)
通过修改`/lit/src/element/shadowless-element.ts `文件，添加 `typeof document !== 'undefined'`  条件绕过，但又开始报window is not defined 
![image](https://github.com/toeverything/blocksuite/assets/5779513/7a22514c-2f7c-41fb-97db-bb03c858a118)

![image](https://github.com/toeverything/blocksuite/assets/5779513/36c9cbdb-f8d9-446b-8c66-5d4140160708)
这个看了下是字体相关的引用 有点复杂搞不定了，大神们看下怎么解决 @zuoxiaodong0815 @doodlewind

**Comment by yunnian** [comment]
I finally run it successfully in next.js !


page.tsx

```
'use client';

import dynamic from "next/dynamic";

const Test = dynamic(() => import('./test'),{ ssr: false})

export default function Home() {

  return <div>
    <Test/>
  </div>;
}

```
test.tsx

```
'use client'

import '@blocksuite/editor/themes/affine.css';

import { SimpleAffineEditor } from '@blocksuite/editor';
import { useEffect } from 'react';

const editor = new SimpleAffineEditor();
export default function Test() {
  useEffect(() => {
    document.body.appendChild(editor);
  }, []);

  return <div> </div>;
}

```

**Comment by doodlewind** [comment]
Closing since we've revamped the getting started doc in #5063 with runnable code sandbox and things should be working for now.
