### ISSUE TITLE
In the edgeless mode, if multiple elements are selected and rotated, the size will be wrong

### ISSUE THREAD

**Issue by Yukiniro** [toeverything/blocksuite#3664]
https://github.com/toeverything/blocksuite/assets/21242087/e1fbcb9b-7e26-4524-ba1b-3e17ced8cb7b

**Comment by zhengjitf** [comment]
Is it OK to update the selected rect when the rotation ends? 

https://github.com/toeverything/blocksuite/assets/17249775/0dd6ceeb-2065-4c11-8391-a6ae1eafff78

**Comment by Yukiniro** [comment]
> Is it OK to update the selected rect when the rotation ends?
> 
>  multiple-rotation.mov

Sorry, I'm not sure if this adjustment is possible. Adjusted interactions feel less common.

**Comment by zhengjitf** [comment]
> Adjusted interactions feel less common.

Yes, I agree. But I think it is an alternative solution, based on the following points from my side:
1. Consistent with selecting multiple rotated shapes.

https://github.com/toeverything/blocksuite/assets/17249775/29f403c5-a4aa-440e-b20a-680ca7088017


2. Scrolling after rotating multiple shapes also leads to updating the selected rect. (As expected?)

https://github.com/toeverything/blocksuite/assets/17249775/2bbb6b1a-fb7d-463c-b67e-7d26c016935d


3. As a reference, a similar interaction in Excalidraw.

https://github.com/toeverything/blocksuite/assets/17249775/9ffc5ae5-7f1e-49d9-b37a-6de55eb6a7bf


4. A simple solution to get rid of this issue. 😄

**Comment by zhengjitf** [comment]
Wait for any opinions. If it's supposed to follow the previous interactions, the following code changes maybe fix this issue:

https://github.com/toeverything/blocksuite/blob/29ce5d2f8ea1e5fd6432759e0958d76325850955/packages/blocks/src/page-block/edgeless/components/rects/edgeless-selected-rect.ts#L394-L395

change line 394 to:

```ts
const { currentRect } = this._resizeManager;
```

But then the item 2 mentioned above, looks like strange from my side.

**Comment by regischen** [comment]
@fundon can you take a look?

**Comment by doodlewind** [comment]
> @fundon can you take a look?

I think @fundon is being AFK for a while, so we won't explicitly assign issues he there. But would be great if any advice, suggestions or reviews can be given.

**Comment by fundon** [comment]
@zhengjitf Good job, your implementation is better and simpler than my previous PR.
