### ISSUE TITLE
Typing symbols using "Alt Gr + <number>" triggers unwanted creation of headings

### ISSUE THREAD

**Issue by tmlmt** [toeverything/blocksuite#3669]
# Description

On certain keyboards, like mine with [Danish layout](http://kbdlayout.info/KBDDA/), typing typical symbols like "@" or currency symbols ("£", "$") is done by typing `Alt Gr` + `<digit>`. When I do so on AFFiNE, it turns the text into a heading, which is an unwanted behavior. 

See screencast where I type successively "Heading" followed by `Alt Gr` + `<n>` where n goes follows the keyboard line from left to right, 1 to 0:
https://github.com/toeverything/blocksuite/assets/10244927/eb9b85e8-5178-4b0a-ba75-f2adfb6427ff

# Tested on

- Windows 10 with v0.7.0-canary.51 Desktop .exe: :red_circle: creates different heading levels and then bullet lists etc (see video)
- Windows 10 with the [AFFiNE Demo](https://app.affine.pro): on Chrome: :red_circle: creates H2s

**Comment by fourdim** [comment]
Fixed by #3662.
