### ISSUE TITLE
Table cell selection jittering

### ISSUE THREAD

**Issue by nanzm** [toeverything/blocksuite#3673]
hi guys, When I add tables and select two table cell, the borders will start to jitter.

https://github.com/toeverything/blocksuite/assets/12454813/4d3ce731-8530-42f6-a5d5-7e379455271e

**Comment by doodlewind** [comment]
Should be a known regression related to recent selection manager, /cc @Saul-Mirone @zzj3720

**Comment by zzj3720** [comment]
The issue has been resolved after completing selection refactor
