### ISSUE TITLE
Support deleting block using ctrl + D

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#3683]
In block-level selection, control + d or ctrl + d cannot delete the block.

**Comment by SebastienPingal** [comment]
As I'm working on this I'm questiionning wether it would not make more sense to make the "duplicate" feature on this shortcut.

**Comment by doodlewind** [comment]
IMO in macOS, ctrl-D should be deleting and cmd-D should be duplicating (see Notion). /cc @houjoe0829 for confirmation.

**Comment by houjoe0829** [comment]
The current Duplicate command is usually:
+ Cmd + D (Windows)
+ Ctrl + D (Mac)

It is recommended to use Ctrl + D only for deleting selected blocks on Mac. @doodlewind @JimmFly @SebastienPingal

**Comment by mukeshkuiry** [comment]
![image](https://github.com/toeverything/blocksuite/assets/99157367/9d220369-e775-419a-b863-8855908d13ec)
Are you talking about deleting the selected block after pressing ctrl + D?

**Comment by doodlewind** [comment]
@mukeshkuiry yes, and this could also apply to doc mode.

**Comment by mukeshkuiry** [comment]
Okay lemme try to do something on it.

**Comment by AliceLanniste** [comment]
@doodlewind  hi,I added ctrl+D in doc and egeless ,but it triggers browser collection.

**Comment by doodlewind** [comment]
@AliceLanniste thanks for the trying! I tested and indeed there's conflict with Chrome on Windows, so how about limit this hotkey to macOS (e.g., by using the `IS_MACOS` const from `@blocksuite/global/env`) only?

**Comment by AliceLanniste** [comment]
@AliceLanniste  I will try it
