### ISSUE TITLE
Support text color modification

### ISSUE THREAD

**Issue by TinsFox** [toeverything/blocksuite#3688]
Now there are only two basic colors, which need to be switched through dark mode. In actual use, we need to **highlight** the text or modify it to another color to highlight the label, so I think it is necessary to add the text color modification function

I haven't found this feature yet in AFFiNE (Version 0.7.0-canary.51)

<img width="881" alt="image" src="https://github.com/toeverything/blocksuite/assets/33956589/0ba8893a-0156-445f-bfce-99336433d767">

Here is an example of Notion

<img width="642" alt="image" src="https://github.com/toeverything/blocksuite/assets/33956589/142b4b75-8506-4230-a3aa-3e6e180e7320">

**Comment by doodlewind** [comment]
Thanks for the feedback! This is planned in #2315 and is WIP

**Comment by doodlewind** [comment]
Closed by #3961
