### ISSUE TITLE
Unable to resize image

### ISSUE THREAD

**Issue by youhua** [toeverything/blocksuite#3689]
1. Go to https://blocksuite-toeverything.vercel.app/starter?init=preset
2. Paste any image
3. Click on the image, the resizer is not visible.
4. Press Up/Down, the cursor didn't move as expected.

https://github.com/toeverything/blocksuite/assets/1414766/47c3b9c4-bdce-4796-8b9b-9925c829cea2

**Comment by doodlewind** [comment]
Should be regression in https://github.com/toeverything/blocksuite/pull/3653, it's in our current plan to fix them.

**Comment by doodlewind** [comment]
Fixed by #3903
