### ISSUE TITLE
Unable to select the right contents.

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3700]
![Image](https://github.com/toeverything/blocksuite/assets/134897361/cb2d4054-5502-49e2-9a72-89f124041e12)

If you only want to select part of the content, it will automatically select all

**Comment by doodlewind** [comment]
I think we should avoid testing against this latest canary, it's known to be buggy since the selection refactoring is WIP. This will be also tracked in https://github.com/toeverything/blocksuite/issues/3676 and https://github.com/toeverything/blocksuite/issues/3463.
