### ISSUE TITLE
The code copied from the code block cannot be pasted directly into vsc or terminal

### ISSUE THREAD

**Issue by TinsFox** [toeverything/blocksuite#3702]
## What happened?

After copying a code block in blocksuite, it can be pasted into blocksuite, but it cannot be pasted into other places, such as vscode, terminal.

https://github.com/toeverything/blocksuite/assets/33956589/943990f5-cf96-4174-b071-c6e08e8f776a

But he can paste on TextEdit on macOS

<img width="617" alt="image" src="https://github.com/toeverything/blocksuite/assets/33956589/58dc63e3-35f6-4d6c-b8f8-46c021483939">

**Comment by doodlewind** [comment]
Would be great if @fourdim could take a look.
