### ISSUE TITLE
cannot paste image twice

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3724]
https://github.com/toeverything/blocksuite/assets/14026360/aa9239ad-f651-4dc9-a67f-f22f9ab95f75

**Comment by zuoxiaodong0815** [comment]
Because lose focus after the first time when pasting in an empty block.

**Comment by himself65** [comment]
Not working

**Comment by fourdim** [comment]
https://github.com/toeverything/blocksuite/assets/59462000/642ef1cf-2b45-4eb1-9363-3524fa5681a9

Cannot reproduce.

**Comment by fourdim** [comment]
Relate to #3655.
https://github.com/toeverything/blocksuite/pull/3655/files#diff-549d643360b769e6f4a11960e243c3c067da6b62e694640982ba47c676b0390aR148-R151

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/assets/14026360/c91427c6-4f9b-4855-978b-4aeaecc97bb5
