### ISSUE TITLE
In database: It went flashy when I try click on the column

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3728]
https://github.com/toeverything/blocksuite/assets/134897361/cee1a4f8-9d3e-408d-bc25-91079de5fb49

[Department OKR and Progress Tracking.md](https://github.com/toeverything/blocksuite/files/12179277/Department.OKR.and.Progress.Tracking.md)
This is the document I was working on, please have a look.
Version: latest version 
windows

**Comment by doodlewind** [comment]
Closing since this is a ad-hoc cherry-pick related issue, will be solved with new picked version.
