### ISSUE TITLE
​The tooltips in the editor are blocked

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#3744]
### What happened?

upstream: https://github.com/toeverything/AFFiNE/issues/2406
![image](https://github.com/toeverything/AFFiNE/assets/102217452/1ae81028-59e4-44f3-88b5-ad52d6def582)

### Distribution version

macOS x64

### What browsers are you seeing the problem on if you're using web version?

Chrome, Other

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Yipei-Operation** [comment]
update: under {full width layout},the code block has some uiux bug,sidebar could not be shown:
<img width="735" alt="截屏2023-07-28 13 58 57" src="https://github.com/toeverything/blocksuite/assets/79373028/ef44abcb-0a1b-4b6a-b88e-7c4148e261f3">
correct case should be:
<img width="931" alt="截屏2023-07-28 13 59 55" src="https://github.com/toeverything/blocksuite/assets/79373028/1eaad6db-94b4-4734-947e-1f6aa8b307c8">
(version: 0.7.0 stable)

**Comment by doodlewind** [comment]
@xell @hwangdev97 what's the expected behavior in this case? We're working on related UI fixes.

**Comment by xell** [comment]
The tooltip should display in the opposite, i.e. left, side if there is no full room in the right side.

**Comment by doodlewind** [comment]
LGTM, so I guess @lawvs could take higher priority fixing this.
