### ISSUE TITLE
Code block toolbar blocked

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#3745]
Selecting full width layout in AFFiNE something like this happens
![image](https://github.com/toeverything/blocksuite/assets/102217452/ac68018e-12e2-45c3-88d4-53c66a6caa58)

**Comment by JimmFly** [comment]
I think they are related https://github.com/toeverything/blocksuite/issues/3744

**Comment by doodlewind** [comment]
Seems to work in latest affine.fail

<img width="609" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/74ecfd79-e3de-4f8c-ae5d-339c4328edb2">

**Comment by doodlewind** [comment]
There is still edge case in small width /cc @lawvs 

<img width="395" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/e596d785-7223-4e17-a9aa-9902455dd05f">
