### ISSUE TITLE
Editable in read only mode

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#3750]
related issue #3597 https://github.com/toeverything/AFFiNE/issues/2669

https://github.com/toeverything/blocksuite/assets/102217452/49e94600-c67c-4561-aef1-2e5043fc3105

**Comment by JimmFly** [comment]
`      setPageReadonly: (pageId: string, readonly: boolean) => {
        const page = blockSuiteWorkspace.getPage(pageId);
        assertExists(page);
        page.awarenessStore.setReadonly(page, readonly);
        console.log('page.awarenessStore.readonly', page.awarenessStore.getFlag('readonly'));
        
      },`

**Comment by doouding** [comment]
I've tried to hide all the components with editing capability in the read-only mode. But there are still some components you need to hide manually at the AFFiNE side, e.g.  `affine-block-hub` 'cause those components are not created by default.
