### ISSUE TITLE
need android support​

### ISSUE THREAD

**Issue by assassinliujie** [toeverything/blocksuite#3758]
### Description

hope it has a android client, especially for android pad

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
The support of AFFiNE client on mobile is tracked in https://github.com/toeverything/AFFiNE/issues/1581, and in BlockSuite this is tracked in https://github.com/toeverything/blocksuite/issues/2484. Closing as this is duplicated and is in plan.
