### ISSUE TITLE
Unstable E2E tests

### ISSUE THREAD

**Issue by zhengjitf** [toeverything/blocksuite#3760]
Some E2E tests could fail accidentally, but they would succeed after just running again. 
Run into this situation a few times when submitting PR.

The following is part of unstable tests:
- https://github.com/toeverything/blocksuite/actions/runs/5691125589/job/15425725648
- https://github.com/toeverything/blocksuite/actions/runs/5735216097/job/15542594843
- https://github.com/toeverything/blocksuite/actions/runs/5735329874/job/15542902746
  - `add empty Note`: wrong rect dimension assertion?

I'd like to find time to investigate it.

**Comment by himself65** [comment]
I think add some timeout should fix this

**Comment by zhengjitf** [comment]
> I think add some timeout should fix this

Some of them should be fixed by that. But feel more like a workaround and will increase test running time. If no other solution, it could be adopted.

**Comment by doodlewind** [comment]
Closing together with #3658, also we've landed some refactoring in #4100 that contains improvement for fixing some selection-related flaky tests. CI status looks better for the moment.
