### ISSUE TITLE
Infinite loop when paste image after refresh page

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3763]
See: https://github.com/toeverything/blocksuite/issues/3724#issuecomment-1656759697

**Comment by fourdim** [comment]
https://github.com/toeverything/blocksuite/assets/59462000/5becd535-ed43-4c79-9364-961d3c15f44f

This is not related to the clipbord pasting.

**Comment by fourdim** [comment]
Consider remove this dependency `dat.gui`.
https://github.com/dataarts/dat.gui/issues/193
https://github.com/dataarts/dat.gui/pull/223/files
