### ISSUE TITLE
Empty content in new default playground

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#3764]
![image](https://github.com/toeverything/blocksuite/assets/59462000/a22b33df-6a7d-457b-a0f2-9cb6659b9957)

**Comment by doouding** [comment]
Is there any infomation to reproduce this bug?

**Comment by fourdim** [comment]
I manually delete the PLAYGOUND_DB in indexeddb and it's fine now. Maybe you need to delete it on playground version changes.

**Comment by fourdim** [comment]
Goto https://blocksuite-toeverything.vercel.app/?init=preset and then goto https://blocksuite-toeverything.vercel.app/

**Comment by fourdim** [comment]
> Goto https://blocksuite-toeverything.vercel.app/?init=preset and then goto https://blocksuite-toeverything.vercel.app/

It happens not that often, you may need to try it multiple times. I'm trying to find a way to reproduce it stablely.

**Comment by fourdim** [comment]
Goto https://blocksuite-toeverything.vercel.app/?init=preset and then goto https://blocksuite-toeverything.vercel.app/
Move the pointer to init preset `ownership.` press enter to try to add a new line.
Refresh the page.

**Comment by doouding** [comment]
My bad. I found the cause of this bug is quite silly. I forgot to change the `idGenerator` from auto-increment to a multi-user compatible generator. 😢
