### ISSUE TITLE
Cursor jitter after press enter in title

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#377]
https://user-images.githubusercontent.com/14026360/208514709-03933359-add7-4f5d-8dbb-e7b1aabc28a3.mov

**Comment by doodlewind** [comment]
If you press enter on the title, this will prepend a new paragraph block into the page. But by default, there is already one empty paragraph block inside. So, in this case, it works as expected that you can navigate ⬇ two times. Just when to make sure is it what this issue is about?

**Comment by doodlewind** [comment]
Fixed by #493
