### ISSUE TITLE
Edgeless UI bugs

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3780]
There're several inconsistencies with the Figma design:

- [x] The hover background of page "Hidden" is incorrect, which should be the same as that of other buttons, for example, the "More" button.

![Untitled](https://github.com/toeverything/AFFiNE/assets/132558/98369868-c2b5-4e7e-b803-3b3a3094a201)

- [x] The activated state of the Pen tool is inconsistent with the design (left)

![Untitled](https://github.com/toeverything/AFFiNE/assets/132558/f3aba271-be61-4adc-86de-df0422275d83)

- [x] The font size of zoom percent should be scaled downward a tier, i.e. from `sm` 14px to `xs` 12px. And it would be better to use css variable instead of hard coding number to avoid future changes. 

![CleanShot 2023-08-01 at 15 24 32@2x](https://github.com/toeverything/blocksuite/assets/132558/e2e61698-1104-47f2-938c-445a7e4c1497)

- [ ] The "More" menu needs polished (left is the design layout with all the icons). By the way, the font family issue will be addressed in another issue.

![Untitled](https://github.com/toeverything/AFFiNE/assets/132558/0b9b2887-db26-4074-96f0-9bb4f19cf962)

**Comment by doodlewind** [comment]
This also requires tweaking by @DiamondThree, thanks!

**Comment by xell** [comment]
Thanks for @regischen to complete the last request of this issue, i.e. the "more menu". I reopen this until https://github.com/toeverything/blocksuite/pull/4269 is merged.
