### ISSUE TITLE
Wrong font in the More menu of toolbar in Edgeless

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3781]
The font should stick to the UI font family instead of changing with the editor.

![image](https://github.com/toeverything/blocksuite/assets/132558/8eb9e5b3-9282-491f-a8ce-d604648967ec)

**Comment by hwangdev97** [comment]
I believe not just this menu, but all aspects of the edgeless UI with font settings seem to be problematic:

![shot-2023-08-09-17 37 20@2x](https://github.com/toeverything/blocksuite/assets/24713927/715c17a4-47ab-4dd7-9bfe-50d50494700b)

![shot-2023-08-09-17 39 51@2x](https://github.com/toeverything/blocksuite/assets/24713927/d1da8b4e-f501-4897-aa6a-e63da497387a)

**Comment by doodlewind** [comment]
Could @RajeevDash007 try to fix these related menu styling issue together in the existing PR? Thanks!

**Comment by RajeevDash007** [comment]
Yup, I am on it
