### ISSUE TITLE
The prompt word of the picture function key is behind the interface.

### ISSUE THREAD

**Issue by aiyou9** [toeverything/blocksuite#3797]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/15712822/e3ea43b3-8743-40bd-8a3f-88facfc2beb6)

### Version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Require @lawvs to evaluate, the official team should take over the maintenance in this iteration. Thanks.

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/blocksuite/issues/3745

**Comment by doodlewind** [comment]
Duplicate of #3744
