### ISSUE TITLE
The "Export successfully" toast tip incorrectly pops up before the completion of export

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3799]
The toast tip should appear right AFTER the export event.

https://github.com/toeverything/blocksuite/assets/132558/d6084c9f-60ec-4869-9839-e99bdff29c44

**Comment by xell** [comment]
Furthermore, it's better to have a file link in the toast tip to open the exported file easily. As for the design @hwangdev97

**Comment by hwangdev97** [comment]
![shot-2023-08-07-16 43 47@2x](https://github.com/toeverything/blocksuite/assets/24713927/d3c7f485-f332-42cd-a4bd-985909750d10)

mark 1 : when on windows/linux show 'Folder', when on mac show 'Finder'.
mark 2: export 'PNG', replace 'file' to 'PNG'.

and I think the specific content of the text can be discussed further.

**Comment by fourdim** [comment]
Closed by https://github.com/toeverything/AFFiNE/pull/4830
