### ISSUE TITLE
`/` is not working to convert current block type in edgeless

### ISSUE THREAD

**Issue by Yukiniro** [toeverything/blocksuite#3806]
wrong:

https://github.com/toeverything/blocksuite/assets/21242087/bc2eb365-1296-48c2-8590-332611982ef6

expected：

https://github.com/toeverything/blocksuite/assets/21242087/5b90e53f-6c44-407f-b539-6f7ac99c4723

**Comment by lawvs** [comment]
It seems that due to https://github.com/toeverything/blocksuite/pull/3691

we have a test case to guard it.

https://github.com/toeverything/blocksuite/blob/604e7aed66afdb8208e8ee603f165e7c9571b9e1/tests/slash-menu.spec.ts#L402-L415

**Comment by lawvs** [comment]
I believe it will be fixed together with https://github.com/toeverything/blocksuite/issues/3658

**Comment by doodlewind** [comment]
Fixed in latest playground
