### ISSUE TITLE
Supports copying content to tables

### ISSUE THREAD

**Issue by dongjb** [toeverything/blocksuite#3818]
### Description

When I set the column type to text, I cannot copy the content into the cell.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
I can reproduce this issue. In the Database Text field, after activating the input state, I cannot paste any text information.

**Comment by zqran** [comment]
Thanks for your feedback, I'll check it out. 

By the way, the copy and paste of the database is still under development, and there will be some bugs, which will be resolved in the near future.

**Comment by zqran** [comment]
https://blocksuite-toeverything.vercel.app/starter/?init=database

Closed, it has been resolved in the playground.
