### ISSUE TITLE
Some types of blocks cannot be entered at the beginning of the next line through Backspace

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#382]
Cannot enter the Bulleted List, Numbered List, and To-do List at the beginning of the next line through Backspace

![20221220153935_rec_](https://user-images.githubusercontent.com/50035259/208610443-62aa32c3-ce60-4a71-a740-c3d618533544.gif)

**Comment by Flrande** [comment]
I can't find a way to record the keyboard while recording the screen in Windows, so it seems unclear to test GIF😢. If someone knows how to do it, I would be very grateful.

**Comment by doodlewind** [comment]
Thanks for your report, I think this could be reproduced, and we will work on it.

**Comment by Flrande** [comment]
Sorry, I'm not familiar with the collaborative approach of the open-source community at the moment. Do you mean creating a separate issue for each of the three block level types and tracking them in the current issue with a task list?🤔

**Comment by Flrande** [comment]
Great, I will try it.
