### ISSUE TITLE
Text selection is very hard

### ISSUE THREAD

**Issue by readthecodes** [toeverything/blocksuite#3829]
### What happened?

Text selection is very hard, this is really very unacceptable.

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Closing since this does not meet valid issue description. For current regression, see https://github.com/toeverything/blocksuite/discussions/3720 for details.
