### ISSUE TITLE
Cannot select from back to front occasionally.

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#3832]
https://github.com/toeverything/blocksuite/assets/59462000/8ad3ff54-0942-4567-a5be-615f60ce76d1

**Comment by doodlewind** [comment]
Fixed in latest playground.

**Comment by fourdim** [comment]
https://github.com/toeverything/blocksuite/assets/59462000/03267ab8-146f-404b-a105-d7b314b23033

**Comment by Saul-Mirone** [comment]
Fixed by https://github.com/toeverything/blocksuite/pull/3895
