### ISSUE TITLE
Symbol '、' cannot be replaced when  `_handleClickItem` execute

### ISSUE THREAD

**Issue by yuusheng** [toeverything/blocksuite#3871]
After closing #2416, AFFiNE now supports '、' to open the slash menu. But the symbol '、' didn't be replaced when executing the `cleanSpecifiedTail` function.

![Kapture 2023-08-07 at 20 24 09](https://github.com/toeverything/blocksuite/assets/64511565/d6f6b8cd-fc54-4787-88ad-cf8b75da95e0)

**Comment by lawvs** [comment]
Nice catch!
