### ISSUE TITLE
`AffineFormatBarWidget` is not removed when editor removed

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3881]

**Comment by Flrande** [comment]
Do you mean that the `affine-format-bar-widget` still exist when `block-suite-root` removed?
<img width="1354" alt="image" src="https://github.com/toeverything/blocksuite/assets/50035259/b68d859e-178c-4490-9bc6-62a6cf094c5f">

**Comment by pengx17** [comment]
It is happening in the affine `master` branch. When you editing the title and then navigate to other pages, it will show the following error screen:
![Uploading image.png…]()
