### ISSUE TITLE
Wrong position of the icon of Linked to this page

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3883]
It should align horizontally with the "Linked to this page", instead of being vertically in the whole height

![CleanShot 2023-08-03 at 09 35 04@2x](https://github.com/toeverything/AFFiNE/assets/132558/d2464daa-b159-4edf-b967-908a3bd5b350)

**Comment by JimmFly** [comment]
> @xell can you please provide me just the the page url or the file name in which I should make the changes, anyone of it will workout for me



> > @xell can you please provide me just the the page url or the file name in which I should make the changes, anyone of it will workout for me
> 
> You're welcome to contribute to the repo. And perhaps @DiamondThree or @JimmFly can help you about this.

This is Blocksuite‘s issue, and I transferred it to  Blocksuite.

**Comment by RajeevDash007** [comment]
@JimmFly can you please send me the url of this page, so that I can see the output please,
or else just say the flow to reach the destination section after entering the landing page

**Comment by JimmFly** [comment]
> @JimmFly can you please send me the url of this page, so that I can see the output please, or else just say the flow to reach the destination section after entering the landing page

https://github.com/toeverything/blocksuite/blob/ef3445a9f6f32b9481ec81f0a36458dc41c66101/packages/blocks/src/page-block/doc/meta-data/meta-data.ts#L396
It is rendered here, you can use the '@' symbol to create a page on a blank line, and then the two pages will be concatenated.

https://github.com/toeverything/blocksuite/assets/102217452/abc27dfd-1e79-486b-a3af-c0fe37713a8d
