### ISSUE TITLE
New playground entry should do the data migration

### ISSUE THREAD

**Issue by doouding** [toeverything/blocksuite#3885]
![img_v2_97261fe7-50d6-469e-985c-9e683773f77g](https://github.com/toeverything/blocksuite/assets/9301743/6f524219-fab2-4c82-93a2-7b1e7c7af370)

**Comment by fourdim** [comment]
Shell we do it in block flavours setup rather than a function to be called in the application.

**Comment by doouding** [comment]
> 

This sounds reasonable. I'll confirm it soon.
