### ISSUE TITLE
Invalid drag handle indicator position when scrolling

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#3912]
### **Description**

**What happened**: The editing hint line will remain fixed above all content and will still stay on the page when scrolling

https://github.com/toeverything/AFFiNE/assets/40333372/f9988b0e-4eb2-438a-aaf8-22be73d68380

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Reproduced in latest playground

**Comment by donteatfriedrice** [comment]
Closed by #3912 #3921
