### ISSUE TITLE
Invalid selection state in image caption

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#3913]
### **Description**

**What happened:** When we edit the caption of an image, if you try to move the cursor, it will automatically select the whole content.

https://github.com/toeverything/AFFiNE/assets/40333372/3bb4b6a3-2877-4ffa-ad6b-3efe2c7bfaca

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by RajeevDash007** [comment]
I checked this issue,
but I am not facing any problem regarding this in my machine.

**Comment by doodlewind** [comment]
@RajeevDash007 not sure which editor environment and OS are you using? This can be reproduced but I'm afraid it requires background in new refactoring selection manager to fix. /cc @Saul-Mirone
