### ISSUE TITLE
The viewport will jilter when drag from block hub and move the block to the left bottom

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#3924]
https://github.com/toeverything/blocksuite/assets/99816898/0bde1618-b179-401a-b12d-fd407d7509ec

**Comment by doodlewind** [comment]
Though the position of drag indicator can be confusing at times, but it's not reproduced:

https://github.com/toeverything/blocksuite/assets/7312949/37e3d0c4-2414-47af-8d73-c9ad3c7aa2fc

**Comment by donteatfriedrice** [comment]
This issue can now be reproduced:
I guess it would be reproduced if drag the block to the left-bottom of the page, out of center area.
And issue #3684 maybe related with this problem. 

https://github.com/toeverything/blocksuite/assets/99816898/8f741d90-bd4d-4c51-8ad8-0cc5b11be846

**Comment by doodlewind** [comment]
Closed by #4509
