### ISSUE TITLE
Import modal dialog window UI bugs (especially buttons)

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3936]
We notice that there're still bugs in the https://github.com/toeverything/blocksuite/issues/3798 , especially the UI of button and perhaps fonts.

<img width="536" alt="CleanShot 2023-08-10 at 09 39 46@2x" src="https://github.com/toeverything/blocksuite/assets/132558/46096931-c80e-4e24-853d-e0066827ec4e">

v.s. design layout:

<img width="600" alt="CleanShot 2023-08-10 at 09 40 29@2x" src="https://github.com/toeverything/blocksuite/assets/132558/549fff0d-5c5e-4e95-bca5-6d296be5a80f">

**Comment by RajeevDash007** [comment]
@xell can you please help me to get the import dialog box?

**Comment by DiamondThree** [comment]
> @xell can you please help me to get the import dialog box?

hi, you can input "@" on the page and choose import. Like this:
![20230810231235](https://github.com/toeverything/blocksuite/assets/24630517/6a095ee6-ac14-487a-ac8e-4fee118e8bfc)

**Comment by RajeevDash007** [comment]
Thank you for the assistance

**Comment by RajeevDash007** [comment]
could you provide the figma design?

**Comment by DiamondThree** [comment]
> 

https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=3104-67070&mode=design&t=aVDAtHenVzdUr2rP-0

**Comment by xell** [comment]
> could you provide the figma design?
> It would help in replecating the UI.
> @xell @DiamondThree

Because the figma design files are not open sourced, please reply my email sent to you yesterday for further details. Thanks.
