### ISSUE TITLE
The `Table View` cell still hovers while not activated

### ISSUE THREAD

**Issue by yuusheng** [toeverything/blocksuite#3963]
When moving out from a cell, the previously active cell is still staying in active style (except for the column type is `text`).
Is that a correct behavior?

![Kapture 2023-08-11 at 01 13 20](https://github.com/toeverything/blocksuite/assets/64511565/811727cc-9042-4916-8a6b-6afada3e4bc5)

**Comment by zqran** [comment]
Thanks for the feedback, the problem has been fixed and cannot be reproduced in [Playground - database](https://blocksuite-toeverything.vercel.app/starter/?init=database).
