### ISSUE TITLE
Support `Shift` + `tab` in Table View

### ISSUE THREAD

**Issue by yuusheng** [toeverything/blocksuite#3964]
I think we should support the `Tab` command in Table View. For a better writing experience!

When pressing the `Tab` key, we should focus on the next cell. And because all types of our Column Type support manipulate with a keyboard, we can focus more on what we are writing.

![Kapture 2023-08-11 at 01 23 20](https://github.com/toeverything/blocksuite/assets/64511565/4f902751-6076-46c5-8976-3698bba04ab0)

**Comment by zzj3720** [comment]
For now, you can press `Esc` to exit edit mode and press `Tab` or `Arrow Right` to move to the next cell.

**Comment by yuusheng** [comment]
> For now, you can press `Esc` to exit edit mode and press `Tab` or `Arrow Right` to move to the next cell.

In my case, after pressing `Esc` to exit edit mode and press `Tab`, the cursor will focus on the next line after the current Table View. Maybe we should focus on the next cell after the current cell instead of the next line.

**Comment by doodlewind** [comment]
I think the tab hot key support mentioned here pretty much makes sense. /cc @houjoe0829 to confirm.

**Comment by houjoe0829** [comment]
@yuusheng Hello, I would like to ask further, in which app do you use "Shift" the most to switch focus between different cells? We will also test it out.

**Comment by yuusheng** [comment]
> @yuusheng Hello, I would like to ask further, in which app do you use "Shift" the most to switch focus between different cells? We will also test it out.

Maybe Microsoft Word, Notion, or Typora. All of them support the `Tab` hotkey in Table View.

**Comment by yuusheng** [comment]
Oh! I just realized that there was a mistake in my initial statement. What I meant to say is the `Tab` key. And I said `shift` in the beginning. It might make some confusion. Sorry for that~

**Comment by houjoe0829** [comment]
We currently support switching with the "Tab" key, but not yet with "Shift + Tab". We will work on adding this feature.
Assign to  @zqran
