### ISSUE TITLE
Redundant white border in image block with transparent content

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#3972]
### **Description**

Now: There's a white border around the image when it's imported into the software

**Should: It shouldn't be appear because it's .PNG format**

<img width="924" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/c29f2b70-4e5b-4edf-be24-40bd85999df9">

**Comment by doodlewind** [comment]
Reproduced with edgeless dark mode:

<img width="1443" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/b828284c-d07a-4994-b194-3e5343eb92db">

PNG link: https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/560px-PNG_transparency_demonstration_1.png

**Comment by doodlewind** [comment]
Surely do it since this come from design team! 😈
