### ISSUE TITLE
A separator line has appeared on the toolbar.

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#3988]
![shot-2023-08-11-18 05 44@2x](https://github.com/toeverything/blocksuite/assets/24713927/6fac2d6d-3207-427b-ad2f-37f424c29b18)

![shot-2023-08-11-18 07 00@2x](https://github.com/toeverything/blocksuite/assets/24713927/6ef5dc00-a406-44c2-9753-ebce67122a61)

**Comment by doodlewind** [comment]
I guess @RajeevDash007 could give this a try?

**Comment by RajeevDash007** [comment]
@doodlewind sure

**Comment by RajeevDash007** [comment]
![Screenshot (31)](https://github.com/toeverything/blocksuite/assets/96860040/96ba9dd4-98bb-4ed9-b781-f628b172be64)
I am not facing this issue,
can you please guide me that on which page or after what action this issue is coming?
@doodlewind @hwangdev97

**Comment by doodlewind** [comment]
Not reproduced in latest playground
