### ISSUE TITLE
Apple Pencil Support

### ISSUE THREAD

**Issue by fabrastudio** [toeverything/blocksuite#3993]
### Description

Hey, I would love to see Apple Pencil support on AFFiNE. I'm not sure if this is feasible on the web, but I'm really looking forward to its potential inclusion in the hopefully soon-to-be-released iPad app.

### Use case

Using AFFiNE as my all-in-one tool for studies, personal projects, and organization is my goal. Particularly for studying, the ability to draw notes and sketches with the Apple Pencil would be incredibly beneficial.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by xell** [comment]
Thank you for the request. Although it's definitely a great idea and we'll implement the functionality in the future, now we're focusing on the fundamental usabilities, better experiences and cloud services. We will update the status of this issue when there's progress.

**Comment by doodlewind** [comment]
Closing since we now have basic iPad support since #5850, and there will be more optimizations afterwards.
