### ISSUE TITLE
Hard to drag & zoom on Windows

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#3997]
Running on Windows 11 Arm 64 simulator

See the video on internal channel

**Comment by doouding** [comment]
Still can't reproduce on Windows 11 Arm Emulator (VMware Fusion). I will try it on a physical PC when I return home this weekend.

**Comment by doodlewind** [comment]
I've verified that in Windows 11 physical device:

* Pressing mouse middle click wheel and move cursor pans the canvas.
* Pressing `ctrl` and scroll the mouse wheel zooms the canvas.

Both are working as expected.
