### ISSUE TITLE
The position of table properties toolbar is not expected

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4005]
https://github.com/toeverything/blocksuite/assets/50035259/d47629ea-98e0-46a2-8276-e7995fc31024

**Comment by RajeevDash007** [comment]
Can you specify the position of the dialog box?
so that I can make changes as per that.
like it should be in the center of the website or top left of the website?
@Flrande

**Comment by RajeevDash007** [comment]
![BlockSuite-Playground (1)](https://github.com/toeverything/blocksuite/assets/96860040/a6c7d940-6b07-4d37-a3e6-168d168810ff)
Will that be okay?

**Comment by Flrande** [comment]
I think it will be a sub dropdown like that. :)

<img width="651" alt="image" src="https://github.com/toeverything/blocksuite/assets/50035259/0a41bff3-ea31-4ff9-9716-997f9f39ae54">

However, it seems that there are still many features left unfinished at the moment. I think you can fix its positioning issue separately first.

**Comment by Flrande** [comment]
Furthermore, I believe that this type of “float” component can be developed using [float-ui](https://github.com/floating-ui/floating-ui), which could save so much time. cc @zzj3720

**Comment by zzj3720** [comment]
this will be fixed in #3991
