### ISSUE TITLE
Keep column type when create column continuously

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4006]
https://github.com/toeverything/blocksuite/assets/50035259/87f55bad-1055-4cfe-8228-ac4d2abf8df5

**Comment by zzj3720** [comment]
Maybe we should let the user choose the column type when they click the add button

**Comment by houjoe0829** [comment]
Currently, we tend to let users choose the field type when creating a new column. Each column needs the user to decide its purpose before it can be used. I will temporarily close this issue for now. If there are any other questions, feel free to reopen it.
