### ISSUE TITLE
Cell selection not updated when move column

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4007]
https://github.com/toeverything/blocksuite/assets/50035259/8b6da8ac-1fea-4a13-a2d9-c5784a8dcf2a

**Comment by zqran** [comment]
Currently, the selection area of the database table is determined according to the `[rowIndex, columnIndex]` of the cell.

/cc @zzj3720

**Comment by zzj3720** [comment]
We will fix the style update issue, but the cursor will not be implemented to follow the drag changes for now.
