### ISSUE TITLE
Run `pnpm test:store` in CI

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#402]
Currently, we only run the `pnpm test` and `pnpm build` on CI. The test cases in the store package are ignored. It would be better to run `pnpm test:store` on CI, which can be a standalone check to improve CI speed.

**Comment by himself65** [comment]
Could we add the path filter in yml that only includes the relative code

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-paths
