### ISSUE TITLE
Support dragging selected image

### ISSUE THREAD

**Issue by RajeevDash007** [toeverything/blocksuite#4023]
https://github.com/toeverything/blocksuite/assets/96860040/a20269b6-3317-4c3a-81e0-d507ea525246

**Comment by doodlewind** [comment]
Currently you can use drag handle for this:

https://github.com/toeverything/blocksuite/assets/7312949/81259ff0-4629-4284-85cb-aa82471cee0d

But it would make sense if we allow other custom blocks (bookmark, attachment) to be dragged in a universal way.
