### ISSUE TITLE
When inserting image, the card view functionality does not work

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#4034]
https://github.com/toeverything/blocksuite/assets/134894293/77dc2894-c37d-4120-801a-6fdbcfba1466

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/blocksuite/pull/4049

**Comment by lawvs** [comment]
Closed due to the unclear problem description. We will trace the missing name and size in  https://github.com/toeverything/blocksuite/issues/4271
