### ISSUE TITLE
Double clicking mid-word does not select text

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#4036]
Applies to title and body content

Cursor and selection will flash.

https://github.com/toeverything/blocksuite/assets/4605025/0e50c022-52b1-4015-baf0-02c8c8572fc1

**Comment by doodlewind** [comment]
This works in BlockSuite playground, may relate to AFFiNE integration.

**Comment by doodlewind** [comment]
Closing as not reproduced in latest internal and canary.
