### ISSUE TITLE
Connectors extension does not match with cursor

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#4037]
https://user-images.githubusercontent.com/4605025/260369519-cbd37bd2-8ed7-407a-a57e-ede28fc20c1b.mov

**Comment by regischen** [comment]
It works locally.
But in affine, I think it's because we didn't consider the container of the canvas.
I would like to add transformation between client coord and model coord to viewport class.
but the naming of the api is kind of non-trival.
I feel like the name of 
```
viewToModel(coord: IVec):IVec
modelToView(coord: IVec): IVec
clientToModel(coord: IVec): IVec
ModelToClient(coord: IVec): IVec
```
how do you think @doodlewind

**Comment by doodlewind** [comment]
I think it would be better to convert the DOM event into view coords, rather than adding a new coord system that could be confusing in maintainability.
