### ISSUE TITLE
IME input overlaps with database title placeholder

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4043]
https://user-images.githubusercontent.com/134897361/260395997-17e00453-c17d-4a20-b6ec-8c747d6348e8.mp4

both showed up in windows and mac. Only appears if you use the Chinese input, won't appear in English input.

**Comment by xell** [comment]
As for the IME's marked inline text, perhaps this may be helpful https://github.com/alacritty/alacritty/issues/1613 .
