### ISSUE TITLE
Should not display format bar on selecting bookmark and attachments

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4047]
![Image](https://user-images.githubusercontent.com/134897361/260401682-1991c2ce-4be1-4171-bdb8-89d16a9008c8.png)

**Comment by doodlewind** [comment]
Currently, the format bar appears when any block is under block level selection. To optimize this, only showing it when list, paragraph or code block includes in current selection sounds to makes sense. /cc @Flrande @Saul-Mirone
