### ISSUE TITLE
Default playground `connected` state and its relation with `provider.connect`

### ISSUE THREAD

**Issue by linonetwo** [toeverything/blocksuite#405]
https://github.com/toeverything/blocksuite/blob/10bc78ebb6f60f7d1ec9afc08c7a3eba217adf62/packages/editor/src/components/debug-menu/debug-menu.ts#L179

Currently, I have to click connect button twice to get my `provider.connect` called.

**Comment by linonetwo** [comment]
I can change it to false, or add a call to connect on init, which one do you prefer?

**Comment by doodlewind** [comment]
I think for Yjs, we don't explicitly call `provider.connect` to sync data, just attaching the provider instance to YDoc should be enough. The "disconnect" feature is designed for simulating offline state during multi-user collaboration (with DebugProvider, aka WebrtcProvider), so this is not used for initialization.

In other words, by default, we assume providers should work fine and we don't "disconnect" a page from anything, so `connected = true` looks intuitive here.

**Comment by himself65** [comment]
We connect all the providers you provided in the URL parameters by default.

Closing as this has been resolved

**Comment by linonetwo** [comment]
> We connect all the providers you provided in the URL parameters by default.

The only code related I can find is

https://github.com/toeverything/blocksuite/blob/f43765ceddc51fd36b4653ea0a8c2a0839a262d3/packages/playground/src/utils.ts#L9-L11

But anyway, I'm going to move my

```
this.#yDocument.on('updateV2',
```

to the constructor instead of the `connect` method, thanks.

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/blob/f43765ceddc51fd36b4653ea0a8c2a0839a262d3/packages/playground/src/utils.ts#L33
