### ISSUE TITLE
Refactor `PasteManager.insertBlocks`

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#406]
The current `insertBlocks` implementation ([code](https://github.com/toeverything/blocksuite/blob/572fe2c5c5/packages/editor/src/managers/clipboard/paste-manager.ts#L143-L271)) is too verbose to maintain, this should be refactored using some regular engineering approach.

cc @zuoxiaodong0815 @QiShaoXuan

**Comment by himself65** [comment]
I think there are three parts of this function:

1. Delete the selection
2. Parse the blocks into right structure
3. Insert the blocks into right position

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/blocksuite/issues/305

**Comment by doodlewind** [comment]
Closed by #1687
