### ISSUE TITLE
​Unable to copy/paste from/to table column (Text)

### ISSUE THREAD

**Issue by Mike2306** [toeverything/blocksuite#4060]
### What happened?

It is not possible to copy text into text columns in a database table (See screenshot for clarification) while it is possible in the very first column

<img width="854" alt="image" src="https://github.com/toeverything/AFFiNE/assets/28824308/418ec3a2-c7bd-418e-a1aa-2ad90b614e8e">

### Distribution version

macOS ARM 64 (Apple Silicon)

**Comment by zqran** [comment]
The [Playground - database](https://blocksuite-toeverything.vercel.app/starter/?init=database) is the latest version and cannot be reproduced.

**Comment by Mike2306** [comment]
That's true, the playground version also works for me. But the problem is reproducible in the Mac client version.

Version
App Version
0.7.2
Editor Version
0.0.0-20230717055529-79180930-nightly
