### ISSUE TITLE
Blocks selection with `⌘+aa` unexpected behavior

### ISSUE THREAD

**Issue by forehalo** [toeverything/blocksuite#4068]
the shortcut `⌘ + aa` not only triggers blocks selection but also the system one

<img width="983" alt="image" src="https://github.com/toeverything/blocksuite/assets/8281226/7136800f-b903-43e9-8ca3-a79141294776">

**Comment by doodlewind** [comment]
Seems to be an issue in internal and canary

**Comment by Saul-Mirone** [comment]
Should be fixed by https://github.com/toeverything/blocksuite/pull/4071
