### ISSUE TITLE
Inconsistent scroll/expand effects in Edgeless

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#4070]
When using the Pen tool - the expand button will move the view to show the extra colours.

When using the Note tool - the expand button will move individually through the options. 

I think these two interactions should be the same/similar. (Personally prefer the colour interaction in pen tool)

**Comment by ShortCipher5** [comment]
https://github.com/toeverything/blocksuite/assets/4605025/63012783-2174-4bef-a7a1-290a51c95638

**Comment by doodlewind** [comment]
@xell @hwangdev97 is this UX by design?

**Comment by hwangdev97** [comment]
I've chatted with @donteatfriedrice  and the correct way to do it is like the pen tool. Also, it is best to support horizontal scrolling behavior here
