### ISSUE TITLE
UI issues when editing database row properties

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#4075]
- Close `X` does not close the window
- BlockHub and Help icons are overlayed (but heading area, such as page title is not)

![Image](https://github.com/toeverything/blocksuite/assets/4605025/417d8fb4-0a8c-495e-8b1a-374351531296)

**Comment by pengx17** [comment]
`buttons` in AFFiNE may be covered by Electron's draggable region and thus button tag is added with 'no-drag' attribute. I think you may want to use standard button tag for clickable elements, or add role="button". It is not sepcific to solving this particular issue, but could also provide better a11y for the users.

**Comment by ShortCipher5** [comment]
Just to clarify "window" refers to the sidebar window - rather than the OS (Windows).

**Comment by zqran** [comment]
> - Close X does not close the window

Fixed by `0.8.0-canary.25`.  Related to https://github.com/toeverything/AFFiNE/pull/3783/commits/df0307813992841f37c736e0f1a723e5c1eb0741
