### ISSUE TITLE
Console error after using auto complete arrow and refresh

### ISSUE THREAD

**Issue by WBbug** [toeverything/blocksuite#4144]
Steps to reproduce:
- click `auto-complete-arrow` and move to create
- refresh page

the connector doesn't show and console `Error: val does not exist `

https://github.com/toeverything/blocksuite/assets/87802698/569c237b-10fe-46ce-be1a-da4d9b85ccaa

**Comment by doodlewind** [comment]
Require @regischen to take a look.
