### ISSUE TITLE
Undo is broken at inline code and link

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#415]
https://user-images.githubusercontent.com/18554747/209115410-acdefbb1-a926-4995-9fdc-40af2d599235.mov

Maybe related to https://github.com/toeverything/blocksuite/pull/148

**Comment by doodlewind** [comment]
I found this only happens when the *full* paragraph line has the inline code or link style. Bold and italics styles are not affected.

**Comment by himself65** [comment]
I think this is because the code doesn't call `page.captureSync` in the correct time

**Comment by lawvs** [comment]
> I found this only happens when the _full_ paragraph line has the inline code or link style. Bold and italics styles are not affected.

Because the link and inline code has been specially treated. If you type a character after the code or link node, the character should not be inserted into the code or link node.

See https://github.com/toeverything/blocksuite/blob/8fa558fc974755590d32e4dd3df4de0a1dde2e4d/packages/blocks/src/__internal__/rich-text/rich-text.ts#L105

**Comment by Flrande** [comment]
> Because the link and inline code has been specially treated. If you type a character after the code or link node, the character
> should not be inserted into the code or link node.

I found it when I tried to add more accurate cursor positioning for inline code. Why do we deal with it this way? Is it because when the cursor is on the "edge" of the inline code or link, the Quill data structure cannot distinguish whether the cursor is inside or outside the node?🤔

**Comment by Flrande** [comment]
As far as I know, Chrome has a bug with inline style edge [cursor](https://bugs.chromium.org/p/chromium/issues/detail?id=1249405), but you can do some workaround to it to make the user experience better.

**Comment by lawvs** [comment]
> Is it because when the cursor is on the "edge" of the inline code or link, the Quill data structure cannot distinguish whether the cursor is inside or outside the node?🤔

@Flrande Yes, it is just an editing optimization that aims to prevent text input after a link from being formatted as a code/link, particularly at the end of a line (users will have a hard time entering plain text).

There is still much room for improvement here, and if you are interested, you are welcome to contribute to its development.

You can see an example of this by deleting the corresponding code.

https://user-images.githubusercontent.com/18554747/209375347-6f763bb1-e9de-498d-920b-ea86a1f643d8.mov

And the link node is a shadow DOM so it behaves slightly differently from inline code. (It is a bug feature :)

**Comment by fundon** [comment]
See https://quilljs.com/docs/api/#text-change
If want undo/redo to behave properly, need to determine the source and ignore it when it is not the `user`.

**Comment by himself65** [comment]
I think this has been fixed in the current code, somehow

**Comment by lawvs** [comment]
This problem can still be reproduced. It is even more serious.

https://user-images.githubusercontent.com/18554747/216894171-6142a151-d6f1-42ed-8f34-303daaa50222.mov

**Comment by lawvs** [comment]
After the replacement of the quill with Virgo, this issue has been resolved.
