### ISSUE TITLE
Cannot read properties of undefined (reading 'addRow')​

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/blocksuite#4151]
### What happened?

https://github.com/toeverything/AFFiNE/assets/7054676/3209e442-385f-464e-b600-dfb5076a8818

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
The button here seems to be the UI before #4067. Not reproduced in [latest playground](https://blocksuite-toeverything.vercel.app/starter/?init=database).
