### ISSUE TITLE
Over rendering on editing single paragraph in edgeless

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#4154]
See https://github.com/toeverything/blocksuite/pull/3911#pullrequestreview-1569365874 for details.

**Comment by doouding** [comment]
It seems the over rendering are much more better now, some recent improvement on selection solved the problem.

https://github.com/toeverything/blocksuite/assets/9301743/6e62a960-fa6d-49a2-a0fd-d40ecb1ab5e1
