### ISSUE TITLE
Drag handle icon is not aligned with the all list type icons

### ISSUE THREAD

**Issue by RajeevDash007** [toeverything/blocksuite#4157]
![Screenshot (70)](https://github.com/toeverything/blocksuite/assets/96860040/cfb1f75b-7a89-44ca-a464-145cea9006bb)
![Screenshot (71)](https://github.com/toeverything/blocksuite/assets/96860040/5b397d09-e822-4ac4-8191-a1609ee82266)
![Screenshot (72)](https://github.com/toeverything/blocksuite/assets/96860040/e4bf2b7f-8a1e-4b79-a66a-cb6b59b17609)

**Comment by doodlewind** [comment]
Already closed by #4153
