### ISSUE TITLE
Deleting selected shape should also delete the attached connectors together

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4162]
https://github.com/toeverything/blocksuite/assets/22443345/c705a00b-a0bf-4768-b7db-c464fe58ec6e

**Comment by regischen** [comment]
This probably isn't considered a bug. Perhaps we might need a different type? @doodlewind

**Comment by doodlewind** [comment]
@regischen I think this looks reasonable, but your design for standalone dot support also makes sense, see this:

https://github.com/toeverything/blocksuite/assets/7312949/572d193a-96e2-48c8-ad61-47fd28d30bf8

**Comment by regischen** [comment]
Yes, It all makes sense, just I thought this represents a different choice in terms of the product. So I thought this may not technically considered a bug. Another type may good like type:imporve ?
