### ISSUE TITLE
The "add new record" button in database should not add to first row

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4164]
https://github.com/toeverything/blocksuite/assets/134897361/7ee67b63-b0c3-4024-b3d0-33488760bf6e

**Comment by Yanxi0202** [comment]
unable to meet user expectations: if you click the add new record, it should be at the bottom line.

**Comment by doodlewind** [comment]
> unable to meet user expectations: if you click the add new record, it should be at the bottom line.

Yes, and I think if a cell or row is selected, clicking this button should inserted the new row after the selected one. /cc @houjoe0829 to confirm.

**Comment by zqran** [comment]
What should I do if multiple cells are selected?

<img width="824" alt="image" src="https://github.com/toeverything/blocksuite/assets/15389209/78ab68fc-9bb1-486e-bb85-39d2a846ca06">

**Comment by xell** [comment]
> What should I do if multiple cells are selected?
> 
> <img alt="image" width="824" src="https://user-images.githubusercontent.com/15389209/261469448-78ab68fc-9bb1-486e-bb85-39d2a846ca06.png">

I think the new row could just be right after the last row of the selection.
