### ISSUE TITLE
Format bar not show in database text column

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4169]
<img width="1701" alt="image" src="https://github.com/toeverything/blocksuite/assets/50035259/6852a1dd-81f1-4d8f-b828-850a15111370">

**Comment by doodlewind** [comment]
Awaits #4313

**Comment by Flrande** [comment]
I found that it is not related #4313 and is about how we should adapt the database selection in `format-bar`. `format-bar` uses block selection and text selection to decide how it formats text and where it is rendered. However, database selection can not express the text range inside cell.

cc @doodlewind @zzj3720 @Saul-Mirone

**Comment by zzj3720** [comment]
> I found that it is not related #4313 and is about how we should adapt the database selection in `format-bar`. `format-bar` uses block selection and text selection to decide how it formats text and where it is rendered. However, database selection can not express the text range inside cell.
> 
> cc @doodlewind @zzj3720 @Saul-Mirone 

can we implement format bar for rich-text

**Comment by Flrande** [comment]
> can we implement format bar for rich-text

No, format bar needs to work with block selection as well.

Maybe we can implement another simple format bar for it, which just contains inline style formats.

**Comment by Flrande** [comment]
Continue tracking at #4597
