### ISSUE TITLE
Unable to delete the content in database

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4171]
after finishing the deleting, if you click the enter key, the deleted contents reappear. This reappearing issue also appears if you click other blank space.  Please see the video. 

https://github.com/toeverything/blocksuite/assets/134897361/c12c6740-ff4f-4f59-bb7f-78cf7137d071

**Comment by zzj3720** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/4170
