### ISSUE TITLE
Add style support for the shape of Edgeless toolbar

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#4173]
![shot-2023-08-17-14 52 17@2x](https://github.com/toeverything/blocksuite/assets/24713927/b0869e2a-1e69-4ad1-abb9-331d884a87c6)

1. add style change button on edgeless toolbar submenu

![shot-2023-08-17-14 54 04@2x](https://github.com/toeverything/blocksuite/assets/24713927/063e9249-f577-43a9-a518-70261fc6de3f)

\* The distinction between these two icons is not enough, it will be updated later

2. when style change, change sub menu's shape icon

![shot-2023-08-17-14 55 08@2x](https://github.com/toeverything/blocksuite/assets/24713927/b1656a85-b6da-4870-bed3-b924fd1530e9)

3. and the Edgeless Toolbar's main icon also needs change

![shot-2023-08-17-14 55 39@2x](https://github.com/toeverything/blocksuite/assets/24713927/2ff48a1f-84df-46bf-a969-7f9558221e3c)

[the figma link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=12278%3A63238&mode=design&t=hiEgCXDAlGXmACSP-1)

**Comment by xell** [comment]
I'd like to postpone this until Milestone 0.9 due to the heavy workload.

**Comment by doodlewind** [comment]
@donteatfriedrice we've confirmed with @xell that the animation part of toolbar should be postponed afterwards, but the static menu can be worked on.

**Comment by donteatfriedrice** [comment]
> @donteatfriedrice we've confirmed with @xell that the animation part of toolbar should be postponed afterwards, but the static menu can be worked on.

get it!
