### ISSUE TITLE
Support importing highlighted text from Notion

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4174]
It seems we only support limited stylish text when importing from notion to affine. see details here: 
this one is from Notion 
![Image](https://user-images.githubusercontent.com/134897361/261228574-5b61cb1f-835c-4f77-8a26-5ee7cb373ae3.png)

this is how it looked in AFFiNE
![Image](https://user-images.githubusercontent.com/134897361/261228734-30909593-4612-449b-a12b-73202dcef9a9.png)

**Comment by houjoe0829** [comment]
Regarding the background color mapping issue before and after migration, if a match can be found, map it directly to the same color. If there is no match, default to a yellow background.

**Comment by zuoxiaodong0815** [comment]
Background highlighting and font highlighting are converted to background highlighting.
Since notion has more colors, we choose the similar color. If have not fit color, it will be yellow color.
