### ISSUE TITLE
When a new shape is added through auto-complete, the cursor should automatically be positioned inside the new shape

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4188]
![CleanShot 2023-08-17 at 17 20 28@2x](https://github.com/toeverything/blocksuite/assets/22443345/86e39902-e1c0-4dc2-b1a9-04f64eeda4f7)

**Comment by doodlewind** [comment]
Since #4161 is fixed, there won't be content in newly added shape now. So I guess the cursor is not needed here?

**Comment by houjoe0829** [comment]
https://github.com/toeverything/blocksuite/assets/22443345/cfd6f51a-d6c3-4009-8a9d-10ebdace4033

For the New shape, it can also be focused, just like in FigJam. @doodlewind
