### ISSUE TITLE
Support hover animation for drag handle

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#4221]

**Comment by hwangdev97** [comment]
We should be done with this already? @donteatfriedrice cc @doodlewind

**Comment by donteatfriedrice** [comment]
> We should be done with this already? @donteatfriedrice cc @doodlewind

I think this feature has been fulfilled if you agree and find it acceptable.

**Comment by doodlewind** [comment]
This is considered as landed, thanks @donteatfriedrice @hwangdev97 @CatsJuice for the help involved!
