### ISSUE TITLE
Linked pages are missing hover state when the mouse hovers over them

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4222]
![CleanShot 2023-08-18 at 17 17 06@2x](https://github.com/toeverything/blocksuite/assets/22443345/a1836616-e3b6-472e-a3c9-792e8c74c8f7)

**Comment by Svaney-ssman** [comment]
> In addition, the current linked pages have too little difference from regular text, even the hyperlink style is more prominent than that of linked pages, such as hyperlinks being displayed in blue. @xell @Svaney-ssman

Need @hwangdev97 to have a look, the styles of linked page and regular text are too similar

**Comment by hwangdev97** [comment]
> In addition, the current linked pages have too little difference from regular text, even the hyperlink style is more prominent than that of linked pages, such as hyperlinks being displayed in blue.

That's by design.

A complete page doesn't need to overly emphasize link information. Doing so may reduce the overall readability. 

However, the linked page lacks a hover state.

**Comment by hwangdev97** [comment]
And the linked page has underline :
[the design file](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=4300%3A86050&mode=design&t=6zTH7t6NHMPtaGhP-1)
![shot-2023-08-21-14 34 23@2x](https://github.com/toeverything/blocksuite/assets/24713927/b766641e-4d71-4d17-9e04-8203993d25bb)
