### ISSUE TITLE
Add hovertips for shortcut keys to the Frame function

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4227]

**Comment by hwangdev97** [comment]
I believe issue #4219 has already added this feature. You can preview it at this link: 

https://blocksuite-git-feat-edgeless-frame-toolbar-add-toeverything.vercel.app/  

![shot-2023-08-21-10 00 55@2x](https://github.com/toeverything/blocksuite/assets/24713927/a24b6fd4-5581-4cfe-92ea-d13822591bc6)

However, the tooltip style is still not correct. 😇

**Comment by doodlewind** [comment]
Closed by #4219, we will track UI replication problems in new issues.

**Comment by regischen** [comment]
I guess it said the prensentation function not adding frame function 🤔

**Comment by houjoe0829** [comment]
Sorry, it's my fault, I have corrected it. @regischen @hwangdev97 
It should be for Frame.
