### ISSUE TITLE
Longpress of backspace starts deleting the main page content

### ISSUE THREAD

**Issue by RajeevDash007** [toeverything/blocksuite#4239]
When we want to delete the title of a task by long pressing backspace, it starts deleting the main page content rather than than stopping after the end of the Title.

https://github.com/toeverything/blocksuite/assets/96860040/960e1a00-7880-4c9e-b2ea-383373782429

**Comment by doodlewind** [comment]
Good catch! /cc @zzj3720 @Flrande to triage.
