### ISSUE TITLE
The `AffineReference` at line start should align with other text

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#4249]
<img width="390" alt="Screenshot 2023-08-21 at 16 32 29" src="https://github.com/toeverything/blocksuite/assets/18554747/36b0d8be-7392-449c-93f1-c4fa5ce05a35">

**Comment by Flrande** [comment]
The line begins with padding when the first node is 'embed', ensuring that the cursor can select the start of the line.

<img width="1546" alt="image" src="https://github.com/toeverything/blocksuite/assets/50035259/9deca5ba-7b7c-4bba-86d6-c5e5a13c62ca">

But we can try to decrease the padding of it.
