### ISSUE TITLE
Fit to screen doesn't center content correctly

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4254]
https://github.com/toeverything/blocksuite/assets/22443345/9ee4af44-f198-4a52-873f-cb369a1f5aff

**Comment by regischen** [comment]
can not reproduce it, which version do you use

**Comment by doodlewind** [comment]
@regischen I think here we should fit the selected content to screen, rather than the overall content:

https://github.com/toeverything/blocksuite/assets/7312949/71c5cdbf-a1c4-4eb4-a504-b70e2c3a6f1b

Current logic should only apply when nothing gets selected.

**Comment by regischen** [comment]
emm, fit to screen is supposed to display all contents to user. I'm afraid it may cause confusion.

**Comment by doodlewind** [comment]
I checked Figma and seems that current behavior is aligned. The original issue with offset is not reproduced in current playground.
