### ISSUE TITLE
[feature]: Mermaid Diagrams

### ISSUE THREAD

**Issue by shoriwe** [toeverything/blocksuite#4263]
### Mermaid
Mermaid is a tool for defining and rendering diagrams. It will level up the end user ability to document their projects and personal notes

![image](https://user-images.githubusercontent.com/25905819/204950446-1230bea8-1176-41c7-8553-4628d9521c1a.png)

[Official page](https://mermaid-js.github.io/mermaid/#/)

[Mermaid repository](https://github.com/mermaid-js/mermaid)

### Ideas for solution

Since Mermaid is made with JavaScript if could be easy to embed in the existing code base. It should be easy to adopt. Found this article with a client-side setup [https://css-tricks.com/making-mermaid-diagrams-in-markdown/](https://css-tricks.com/making-mermaid-diagrams-in-markdown/)

**Comment by doodlewind** [comment]
It's not in our plan to add official support for mermaid block, but allowing third-party extensions implementing this should be the goal. This is tracked in #3165 and is supposed to ship within 2 major versions. Hope this makes sense to you. Cheers.

**Comment by phanhavn** [comment]
Hi there,
Thank you for genius feature,
I have a question: how to preview the mermaid, My content show code only.
Thank you so much

![image](https://github.com/toeverything/blocksuite/assets/147580705/c9f4ed3a-0105-4ac2-ab37-3f350c804c06)

**Comment by v3ss0n** [comment]
Any thirdparty extensions for this?

**Comment by wada-qualia** [comment]
has anyone done a fork of affine with this functionality?

**Comment by Daniel15** [comment]
Mermaid support **is** implemented, but it doesn't seem to be documented. If you insert a new code block and select "Mermaid" as the language, it'll show a "preview" tab that lets you see the diagram

<img width="1072" height="715" alt="Image" src="https://github.com/user-attachments/assets/3d96ec0e-8d7d-4ae6-aae5-7330948063ce" />


(unfortunately there's no theming support, so no dark mode).

**Comment by techcomthanh** [comment]
@Daniel15 how do you enable Preview mode?

**Comment by Daniel15** [comment]
It worked for me out-of-the-box. As soon as I inserted a code block and selected "Mermaid" as the language, it showed a "preview" tab next to the language picker.

**Comment by techcomthanh** [comment]
> It worked for me out-of-the-box. As soon as I inserted a code block and selected "Mermaid" as the language, it showed a "preview" tab next to the language picker.
> […](#)

where did you use it. I tried on https://blocksuite.io/components/editors/page-editor.html but no Preview option
