### ISSUE TITLE
​Support toggle block

### ISSUE THREAD

**Issue by gotjoshua** [toeverything/blocksuite#4264]
### Description

As most of the competitors have will functioning toggle blocks, Affine also needs one!

### Use case

Ability to hide and show nested content blocks is crucial!

### Anything else?

We made [quite a bit of progress](https://github.com/toeverything/blocksuite/pull/1139#issuecomment-1469767945) on the prototype in block suite. Just needs the finishing touches from the team.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
The decision (and the ongoing development in #3770) is to not adding a standalone toggle block, but let headings and lists to be toggle-able. See #2945.
