### ISSUE TITLE
Clicking the right mouse button and releasing it will result in incorrect selection

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#4285]
Reproduction steps:
1. Click right mouse button.
2. Click somewhere else.
3. Move the pointer

https://github.com/toeverything/blocksuite/assets/99816898/72a28710-be1f-42f8-a7d6-cec31624954d

**Comment by Saul-Mirone** [comment]
Seems we need to check the button for `pointerDown` event.
