### ISSUE TITLE
DX: Multiple TypeScript Versions in the Project

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#4286]
I've noticed that there are several TypeScript versions present within the project. It might be beneficial to lock down the TypeScript version to a specific one. This can help reduce the space needed for the development environment and ensure consistent behavior across setups.

<img width="1258" alt="image" src="https://github.com/toeverything/blocksuite/assets/41265413/4ae14dc1-12f2-46bf-999e-ddcef286578e">

**Comment by lawvs** [comment]
This is the output result of `pnpm why`, which can help to better understand the source of these versions.

```
devDependencies:
@commitlint/cli 17.6.7
└─┬ @commitlint/load 17.6.7
  ├─┬ cosmiconfig-typescript-loader 4.4.0
  │ ├─┬ ts-node 10.9.1 peer
  │ │ └── typescript 5.1.6 peer
  │ └── typescript 5.1.6 peer
  ├─┬ ts-node 10.9.1
  │ └── typescript 5.1.6 peer
  └── typescript 5.1.6
@typescript-eslint/eslint-plugin 5.62.0
├─┬ @typescript-eslint/parser 5.62.0 peer
│ ├─┬ @typescript-eslint/typescript-estree 5.62.0
│ │ ├─┬ tsutils 3.21.0
│ │ │ └── typescript 5.1.6 peer
│ │ └── typescript 5.1.6 peer
│ └── typescript 5.1.6 peer
├─┬ @typescript-eslint/type-utils 5.62.0
│ ├─┬ @typescript-eslint/typescript-estree 5.62.0
│ │ ├─┬ tsutils 3.21.0
│ │ │ └── typescript 5.1.6 peer
│ │ └── typescript 5.1.6 peer
│ ├─┬ @typescript-eslint/utils 5.62.0
│ │ └─┬ @typescript-eslint/typescript-estree 5.62.0
│ │   ├─┬ tsutils 3.21.0
│ │   │ └── typescript 5.1.6 peer
│ │   └── typescript 5.1.6 peer
│ ├─┬ tsutils 3.21.0
│ │ └── typescript 5.1.6 peer
│ └── typescript 5.1.6 peer
├─┬ @typescript-eslint/utils 5.62.0
│ └─┬ @typescript-eslint/typescript-estree 5.62.0
│   ├─┬ tsutils 3.21.0
│   │ └── typescript 5.1.6 peer
│   └── typescript 5.1.6 peer
├─┬ tsutils 3.21.0
│ └── typescript 5.1.6 peer
└── typescript 5.1.6 peer
@typescript-eslint/parser 5.62.0
├─┬ @typescript-eslint/typescript-estree 5.62.0
│ ├─┬ tsutils 3.21.0
│ │ └── typescript 5.1.6 peer
│ └── typescript 5.1.6 peer
└── typescript 5.1.6 peer
lit-analyzer 2.0.0-pre.3
└─┬ web-component-analyzer 2.0.0-next.5
  └── typescript 4.4.4
madge 6.1.0
├─┬ dependency-tree 9.0.0
│ ├─┬ filing-cabinet 3.3.1
│ │ └── typescript 3.9.10
│ ├─┬ precinct 9.2.1
│ │ └─┬ detective-typescript 9.1.1
│ │   ├─┬ @typescript-eslint/typescript-estree 5.62.0
│ │   │ ├─┬ tsutils 3.21.0
│ │   │ │ └── typescript 4.9.5 peer
│ │   │ └── typescript 4.9.5 peer
│ │   └── typescript 4.9.5
│ └── typescript 4.9.5
├─┬ detective-typescript 9.1.1
│ ├─┬ @typescript-eslint/typescript-estree 5.62.0
│ │ ├─┬ tsutils 3.21.0
│ │ │ └── typescript 4.9.5 peer
│ │ └── typescript 4.9.5 peer
│ └── typescript 4.9.5
├─┬ precinct 8.3.1
│ └─┬ detective-typescript 7.0.2
│   ├─┬ @typescript-eslint/typescript-estree 4.33.0
│   │ ├─┬ tsutils 3.21.0
│   │ │ └── typescript 3.9.10 peer
│   │ └── typescript 3.9.10 peer
│   └── typescript 3.9.10
└── typescript 5.1.6 peer
ts-lit-plugin 1.2.1
└─┬ lit-analyzer 1.2.1
  └─┬ web-component-analyzer 1.1.7
    └── typescript 3.9.10
ts-node 10.9.1
└── typescript 5.1.6 peer
typescript 5.1.6
```

**Comment by Innei** [comment]
> 



> This is the output result of `pnpm why`, which can help to better understand the source of these versions.
> 
> ```
> devDependencies:
> @commitlint/cli 17.6.7
> └─┬ @commitlint/load 17.6.7
>   ├─┬ cosmiconfig-typescript-loader 4.4.0
>   │ ├─┬ ts-node 10.9.1 peer
>   │ │ └── typescript 5.1.6 peer
>   │ └── typescript 5.1.6 peer
>   ├─┬ ts-node 10.9.1
>   │ └── typescript 5.1.6 peer
>   └── typescript 5.1.6
> @typescript-eslint/eslint-plugin 5.62.0
> ├─┬ @typescript-eslint/parser 5.62.0 peer
> │ ├─┬ @typescript-eslint/typescript-estree 5.62.0
> │ │ ├─┬ tsutils 3.21.0
> │ │ │ └── typescript 5.1.6 peer
> │ │ └── typescript 5.1.6 peer
> │ └── typescript 5.1.6 peer
> ├─┬ @typescript-eslint/type-utils 5.62.0
> │ ├─┬ @typescript-eslint/typescript-estree 5.62.0
> │ │ ├─┬ tsutils 3.21.0
> │ │ │ └── typescript 5.1.6 peer
> │ │ └── typescript 5.1.6 peer
> │ ├─┬ @typescript-eslint/utils 5.62.0
> │ │ └─┬ @typescript-eslint/typescript-estree 5.62.0
> │ │   ├─┬ tsutils 3.21.0
> │ │   │ └── typescript 5.1.6 peer
> │ │   └── typescript 5.1.6 peer
> │ ├─┬ tsutils 3.21.0
> │ │ └── typescript 5.1.6 peer
> │ └── typescript 5.1.6 peer
> ├─┬ @typescript-eslint/utils 5.62.0
> │ └─┬ @typescript-eslint/typescript-estree 5.62.0
> │   ├─┬ tsutils 3.21.0
> │   │ └── typescript 5.1.6 peer
> │   └── typescript 5.1.6 peer
> ├─┬ tsutils 3.21.0
> │ └── typescript 5.1.6 peer
> └── typescript 5.1.6 peer
> @typescript-eslint/parser 5.62.0
> ├─┬ @typescript-eslint/typescript-estree 5.62.0
> │ ├─┬ tsutils 3.21.0
> │ │ └── typescript 5.1.6 peer
> │ └── typescript 5.1.6 peer
> └── typescript 5.1.6 peer
> lit-analyzer 2.0.0-pre.3
> └─┬ web-component-analyzer 2.0.0-next.5
>   └── typescript 4.4.4
> madge 6.1.0
> ├─┬ dependency-tree 9.0.0
> │ ├─┬ filing-cabinet 3.3.1
> │ │ └── typescript 3.9.10
> │ ├─┬ precinct 9.2.1
> │ │ └─┬ detective-typescript 9.1.1
> │ │   ├─┬ @typescript-eslint/typescript-estree 5.62.0
> │ │   │ ├─┬ tsutils 3.21.0
> │ │   │ │ └── typescript 4.9.5 peer
> │ │   │ └── typescript 4.9.5 peer
> │ │   └── typescript 4.9.5
> │ └── typescript 4.9.5
> ├─┬ detective-typescript 9.1.1
> │ ├─┬ @typescript-eslint/typescript-estree 5.62.0
> │ │ ├─┬ tsutils 3.21.0
> │ │ │ └── typescript 4.9.5 peer
> │ │ └── typescript 4.9.5 peer
> │ └── typescript 4.9.5
> ├─┬ precinct 8.3.1
> │ └─┬ detective-typescript 7.0.2
> │   ├─┬ @typescript-eslint/typescript-estree 4.33.0
> │   │ ├─┬ tsutils 3.21.0
> │   │ │ └── typescript 3.9.10 peer
> │   │ └── typescript 3.9.10 peer
> │   └── typescript 3.9.10
> └── typescript 5.1.6 peer
> ts-lit-plugin 1.2.1
> └─┬ lit-analyzer 1.2.1
>   └─┬ web-component-analyzer 1.1.7
>     └── typescript 3.9.10
> ts-node 10.9.1
> └── typescript 5.1.6 peer
> typescript 5.1.6
> ```

I know this, I want to know if it's possible to lock the version of ts to ^5 using resolutions, as peerDependencies may not actually depend on that version of ts.

**Comment by himself65** [comment]
Landed in https://github.com/toeverything/blocksuite/pull/4287
