### ISSUE TITLE
Some text is missing when exporting the playgroud page to png

### ISSUE THREAD

**Issue by dengquan** [toeverything/blocksuite#4289]
1 open url http://localhost:5173/starter/?init (Chrome 115.0.5790.170)
2 Test Operations->Export PNG
3 `As a pro tip, you can combine multiple providers! For example, feel free to open this page with` is missing in PNG.
![Welcome to BlockSuite Playground](https://github.com/toeverything/blocksuite/assets/3711119/69902830-8bb4-4ae4-9af4-f1e203eb8fa2)

**Comment by zuoxiaodong0815** [comment]
Ok, I will look at it.

**Comment by BangKk** [comment]
I tested it, this may be a bug in html2canvas. See https://github.com/niklasvh/html2canvas/issues/3109
