### ISSUE TITLE
Delete view is not set to red (css-variable) while hovering

### ISSUE THREAD

**Issue by RajeevDash007** [toeverything/blocksuite#4298]
![Screenshot (99)](https://github.com/toeverything/blocksuite/assets/96860040/79f68aec-ee83-493a-9c57-d9a7a218f0d1)
I guess, It should be set to red( css variable ) while hovering like other menu delete options

**Comment by RajeevDash007** [comment]
I have fixed it, if its needed then you may merge it or if not then you may close both the issue and PR!

**Comment by fourdim** [comment]
From an aesthetic point of view, I would like to suggest removing this delete button with this style instead.
![image](https://github.com/toeverything/blocksuite/assets/59462000/f2eba44d-e2ac-4518-9fea-beb7e143d7ab)

And double click edit in place
![image](https://github.com/toeverything/blocksuite/assets/59462000/1bfa52ac-3d0d-4cbe-af3c-750eb1f14f3a)
