### ISSUE TITLE
After copied, drawings and notes can't move or delete together at once

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4308]
https://github.com/toeverything/blocksuite/assets/134897361/2b8791b6-4aad-436e-bf30-cfd7b0853650

you need manually refresh the page to see the changes, for more details please see the video.

**Comment by regischen** [comment]
it seems werid that you don't select the text, In the video I saw the selected box is boxing the textElement.
By the way which version do you use @Yanxi0202

**Comment by Yanxi0202** [comment]
I use this version: 0.0.0-internal.20230823003802-9d6d559, I can only reproduce it in the same workspace. I tried to add a new workspace, and it can not reproduce it. 
<img width="207" alt="image" src="https://github.com/toeverything/blocksuite/assets/134897361/ed2c15ed-14e9-4d9a-8e18-b4a636d4f4d5">

**Comment by doouding** [comment]
Can you export your workspace data so that I can try to reproduce it.

**Comment by Yanxi0202** [comment]
sure, will send it to your feishu account

**Comment by doouding** [comment]
Reproduced after copy and paste operation.
