### ISSUE TITLE
After deleting contents in Edgeless, the result of undo operation will temporarily loss some elements.

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4312]
https://user-images.githubusercontent.com/142964904/262606385-e14c93a7-4124-490e-b3a8-0aa09ab66d78.mp4

**Comment by xell** [comment]
The actual bug is: if you jump to another doc and then jump back, the "lost" drawings and/or shapes will appear again.


https://github.com/toeverything/blocksuite/assets/132558/a1dd8c24-14f1-477f-b368-7a506d5d89a3
