### ISSUE TITLE
Block content overlap under edgeless mode

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4331]
https://user-images.githubusercontent.com/134897361/262896324-321e629a-fa4f-47c9-bf7d-7bb2eb8f6224.mp4

details:  when I transfer to edgeless mode, contents were covered. I guess, this was caused by the bookmark, because the whole content's position is wrong. 

version: latest internal

**Comment by doodlewind** [comment]
Have you used the block slicer in this doc before? Maybe the overlapped contents is inside another note block that overlaps?

**Comment by Saul-Mirone** [comment]
Seems we don't have this bug now. And we still don't know how to reproduce it.
