### ISSUE TITLE
Failed to export the full highlighted contents as PNG

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4335]
Original format 
![Image](https://user-images.githubusercontent.com/134897361/262901762-e28e2334-5208-4bc3-886e-c50a60cf1474.png)

after export as PNG 
![Image](https://user-images.githubusercontent.com/134897361/262901711-a1c49842-b279-43d0-af89-e084e4414f4f.png)

**Comment by fourdim** [comment]
See #4335.

**Comment by doodlewind** [comment]
Closing as duplicate of #4289
