### ISSUE TITLE
CSS won't appear in non-shadow dom in lit

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#434]
In this [commit](https://github.com/toeverything/blocksuite/commit/6219689a8ba3150899ae097bca3874e0b80d7345), we temporarily fix the issue. But it's still a thing that needs to be reminded.

Related: https://github.com/lit/lit/issues/1977

**Comment by himself65** [comment]
The reason we don't enable shadow dom is that the quill doesn't support it well.

Their sill have some related issue with quill https://github.com/quilljs/quill/issues/2961

**Comment by doodlewind** [comment]
I think this can be closed by #523
