### ISSUE TITLE
The style of connector is not reflected in its Style button of toolbar

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#4348]
No matter the style of a connector line is 'General' or 'Scribbled', the icon of the Style button is always 'Scribbled'.

Further more, a selected state should be used to tell users the current shape style.

![CleanShot 2023-08-25 at 08 08 03@2x](https://github.com/toeverything/blocksuite/assets/132558/1061ad4e-4c6a-4a84-b6db-e52ecf8e3997)

**Comment by donteatfriedrice** [comment]
It seems that the design for the change connector style button is different from two other buttonss? Should change the button below same with the two buttons above?  

<img width="623" alt="Screenshot 2023-08-25 at 13 19 11" src="https://github.com/toeverything/blocksuite/assets/99816898/23cff946-4396-4cbb-91ad-596145321233">

**Comment by xell** [comment]
> It seems that the design for the change connector style button is different from two other buttons? Should change the button below same with the two buttons above?
> 
> <img alt="Screenshot 2023-08-25 at 13 19 11" width="623" src="https://user-images.githubusercontent.com/99816898/263173067-23cff946-4396-4cbb-91ad-596145321233.png">

Good question. I'll discuss with the designers later.

**Comment by Svaney-ssman** [comment]
Yes please change all "general' and "scribbled‘ icons to these two. Which means show the one you selected: 
<img width="607" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/db330730-0236-4d5a-9960-67f5a20956e0">
<img width="695" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/e58e5ab8-6bb0-48d9-b91e-6a9808091e05">

**Comment by donteatfriedrice** [comment]
> Yes please change all "general' and "scribbled‘ icons to these two. Which means show the one you selected: <img alt="image" width="607" src="https://user-images.githubusercontent.com/110808979/264524175-db330730-0236-4d5a-9960-67f5a20956e0.png"> <img alt="image" width="695" src="https://user-images.githubusercontent.com/110808979/264524227-e58e5ab8-6bb0-48d9-b91e-6a9808091e05.png">

OK, I will update it. Thanks.
