### ISSUE TITLE
Multiple image blocks inserted after single image paste

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#435]
3 images appear after a single paste using `cmd` + `V`. Two of them are blocks.

<img width="870" alt="image" src="https://user-images.githubusercontent.com/7312949/209462595-e0a65433-2a5a-4cd9-a53c-30c9d50485cb.png">

This is a regression from #421

**Comment by himself65** [comment]
😨

**Comment by himself65** [comment]
PasteManager is called twice

**Comment by himself65** [comment]
reason is _clipboardEvent2Blocks
