### ISSUE TITLE
Support selecting block under text selection on pressing cmd-A firstly

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4355]
### **Description**

**Now:** When I type something and hit ⌘/Ctrl + A to select all the content, it weirdly highlights the whole block container, so I can't edit what I wrote.

https://github.com/toeverything/blocksuite/assets/40333372/ab4c25f4-b02e-41ca-b1c5-fde6a9c493c5

**Should:** When pressing ⌘/Ctrl + A, it should select all the content for editing, not the block container.

https://github.com/toeverything/blocksuite/assets/40333372/3c410178-a943-4568-9749-b63d5978e459

**Comment by doodlewind** [comment]
This is by design. When you are editing a single block, pressing `cmd-A` *the first time* should enter its block-level selection.

**Comment by zanwei** [comment]
What I mean is that when you select a piece of text and then use ⌘/ctrl + a to select the block, you don't edit the content, you just select the container itself

**Comment by doodlewind** [comment]
After discussion, this can be tracked as a new feature request.

**Comment by zanwei** [comment]
Based on the discussion, this can be tracked as a new feature request.

**Feature will be:**

1. The first press of mod+a selects all the text within the current block.
2. The second press selects the current block itself.
3. The third press selects all the blocks.
