### ISSUE TITLE
Unable to import Notion's original templates

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4358]
"Account info" part is Notion's template, but it can't be discerned when imported.

ps: Notion2 source file (zip.) can't be uploaded here, it can be found in Group 'Beta/ Stable internal Test',

![Image](https://user-images.githubusercontent.com/142964904/263176916-f3a41416-d2c7-4c47-9efc-85f1f3ad6540.jpg)

![Image](https://user-images.githubusercontent.com/142964904/263177164-81912b4a-38f9-4d37-8e27-07eff7601f66.jpeg)

**Comment by doodlewind** [comment]
Closing as unable to reproduce.
