### ISSUE TITLE
Drawing contents are lost after deleting content in edgeless

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4361]
Some elements lost in Edgeless. This issue still hasn't been fixed in the latest Stable version.

https://user-images.githubusercontent.com/142964904/263189358-555f008c-4717-4207-8926-4817c2f23d85.mp4

**Comment by doouding** [comment]
I think the stable version only includes the bug fixing before beta 4, so the later update with the newer version of the blocksuite will resolve this issue.

**Comment by doodlewind** [comment]
Also closing this with #4320
