### ISSUE TITLE
Inconsistency in font family CSS variable

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#4364]
In several places. We suggest to conduct a full search of `font-family` to completely fix them as much as possible.

![img_v2_54e89b1d-23a5-4c4c-be13-73cf26d0648g](https://github.com/toeverything/blocksuite/assets/132558/1ac2c360-4bd4-444d-bea9-6449251c92c8)

![image](https://github.com/toeverything/blocksuite/assets/132558/bd75e841-3e0e-49dc-9e74-523758d8ca93)

![img_v2_4314f7b9-bafc-46ac-a6ba-b447b56cc49g](https://github.com/toeverything/blocksuite/assets/132558/40f6c7c3-f418-4bd3-a54d-4b989859cdb8)

![img_v2_5d80e723-b17b-4c9c-9578-8a9079ba2b0g](https://github.com/toeverything/blocksuite/assets/132558/233c91ad-1986-4066-b6b1-500c423b8465)

**Comment by hwangdev97** [comment]
We expect that after changing the font, **only the font style inside the editing area will change**, while other UI-related content will maintain the default style. 

For example, the menus/tooltips and pop-up windows shown in the screenshot above.

Currently, in most places, the `font-family: var(--affine-font-family); ` is used, which may lead to changes in related variables. 

Therefore, under normal circumstances, this variable should be removed, and font information should be inherited only by specifying top-level variables. This variable should be used wherever UI changes are needed.

It is worth mentioning that top-level variables can be referenced within the design repository:

`fontSansFamily: 'Inter', 'Source Sans 3', Poppins, apple-system, BlinkMacSystemFont, 'Helvetica Neue', Tahoma, 'PingFang SC', 'Microsoft Yahei', Arial, 'Hiragino Sans GB', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'`

**Comment by hwangdev97** [comment]
This issue has been fixed by @lzlme  #4606
