### ISSUE TITLE
Incorrect `autoIdentifyLink` behavior

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#4371]
- Delete text should update the link
- Should not modify user input

https://github.com/toeverything/blocksuite/assets/18554747/b0496a44-c23d-4713-a6fe-e40ec1f4dfe8

@houjoe0829 Could you describe in detail how `autoIdentifyLink` should work?

**Comment by houjoe0829** [comment]
The expected effect is to directly modify (including adding or deleting) the text of the link within the body, with the modification only affecting the text of the link and not modifying the corresponding link itself.

**Comment by houjoe0829** [comment]
It is recommended to differentiate between manually typing a link and pasting a link; manually typing a link requires a space to trigger recognition, while pasting a link requires immediate recognition and a pop-up menu for converting the link to Bookmark.

**Comment by AyushAgrawal-A2** [comment]
> It is recommended to differentiate between manually typing a link and pasting a link; manually typing a link requires a space to trigger recognition, while pasting a link requires immediate recognition and a pop-up menu for converting the link to Bookmark.

Hi @houjoe0829 ,

Please clarify :-
1. On pasting link recognition, the pop-up menu to be displayed for converting link to bookmark is 
![image](https://github.com/toeverything/blocksuite/assets/54364088/5b648841-18e2-4b11-bd03-b4c394b65771)

   Notion has a separate popup asking to convert to bookmark / embed.
![image](https://github.com/toeverything/blocksuite/assets/54364088/bafb9234-d0eb-4dd3-b491-2217faa72366)


   In our link popup, convert to bookmark is just an icon and the purpose of popup may not be clear to the user.

2. If text pasted has multiple links, then no popup should be displayed

**Comment by houjoe0829** [comment]
> > It is recommended to differentiate between manually typing a link and pasting a link; manually typing a link requires a space to trigger recognition, while pasting a link requires immediate recognition and a pop-up menu for converting the link to Bookmark.
> 
> Hi @houjoe0829 ,
> 
> Please clarify :-
> 
> 1. On pasting a link, the pop-up menu to be displayed for converting link to bookmark is
>    ![image](https://user-images.githubusercontent.com/54364088/284127271-5b648841-18e2-4b11-bd03-b4c394b65771.png)
>    Notion has a separate popup asking to convert to bookmark / embed on pasting a link.
>    ![image](https://user-images.githubusercontent.com/54364088/284128591-bafb9234-d0eb-4dd3-b491-2217faa72366.png)
>    In our link popup, convert to bookmark is just an icon and the purpose of popup may not be clear to the user.
> 2. If text pasted has multiple links, then no popup should be displayed

Thank you very much. From the current implementation:
1. This does not meet expectations. After pasting the link, AFFiNE also has a similar pop-up menu for users to choose. cc @Svaney-ssman Please provide the design file link.
2. This handling is correct.

**Comment by AyushAgrawal-A2** [comment]
@houjoe0829 
![image](https://github.com/toeverything/blocksuite/assets/54364088/9a7794c4-a7c7-4e25-bcde-7bfb4cf80f0e)

I think you are referring to this menu, this is currently implemented in Affine and not part of blocksuite editor.
So no popup is to be shown on pasting a link from editor side, as this is handle in affine.

**Comment by houjoe0829** [comment]
> @houjoe0829 ![image](https://user-images.githubusercontent.com/54364088/284575378-9a7794c4-a7c7-4e25-bcde-7bfb4cf80f0e.png)
> 
> I think you are referring to this menu, this is currently implemented in Affine and not part of blocksuite editor. So no popup is to be shown on pasting a link from editor side, as this is handle in affine.

Thank you for pointing out the issue. I will ask our dev team to take a look at it. cc  @joooye34
