### ISSUE TITLE
Refactor outdated rich text operation

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4374]
related: [legacy.ts](https://github.com/toeverything/blocksuite/blob/33d15dc6e57152301426071cdc3887e871d825ea/packages/blocks/src/__internal__/rich-text/keymap/legacy.ts), [rich-text-operations.ts](https://github.com/toeverything/blocksuite/blob/33d15dc6e57152301426071cdc3887e871d825ea/packages/blocks/src/__internal__/rich-text/rich-text-operations.ts)

**Comment by doodlewind** [comment]
Consider supported after #5878, the remaining public APIs for exposing new commands would require new issues to track.
