### ISSUE TITLE
Edgeless toolbar overlaps in readonly mode

### ISSUE THREAD

**Issue by Noothan-am** [toeverything/blocksuite#4390]
### What happened?

restore and delete permanent buttons are very high from bottom in trash page, so the height needs to be reduced.

### Distribution version

Web (dev.affine.live)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Anything else?

Before

![image](https://github.com/toeverything/AFFiNE/assets/100135382/3d313613-1550-4533-b23c-5f36869b8f25)

After

![image](https://github.com/toeverything/AFFiNE/assets/100135382/4684aa07-0857-433f-b717-e94032438207)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Thanks for the report, but I think we have removed the dev.affine.live?

**Comment by himself65** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/14026360/969cbbfb-94ba-4b32-8291-59b18aa0e329)

Seems like there's a padding bottom 150px

**Comment by himself65** [comment]
I'm transfer this issue to blocksuite, since formatbar still appear in readonly mode.

https://github.com/toeverything/blocksuite/issues/4390#issuecomment-1694699963

@Noothan-am and @panugothrakesh seem like to help on this issue

/cc @doodlewind

**Comment by doodlewind** [comment]
> formatbar still appear in readonly mode.

@himself65 do you mean the main edgeless toolbar?

**Comment by doodlewind** [comment]
This is related to edgeless toolbar styling in AFFiNE integration. Would require @doouding to confirm (and fix possibly).

**Comment by doouding** [comment]
I did not hide the entire toolbar in edgeless mode, only the tools with editing functionality. And a newer bump of blocksuite is required to see the new read-only toolbar.

**Comment by doouding** [comment]
Not sure whether the entire toolbar should be hidden in read-only mode?
/cc @hwangdev97

**Comment by doodlewind** [comment]
I think having some tools in the readonly toolbar should make more sense.

**Comment by doouding** [comment]
Close by https://github.com/toeverything/blocksuite/pull/4635
