### ISSUE TITLE
Better way to implement dynamic `fill` property in svg icons

### ISSUE THREAD

**Issue by CatsJuice** [toeverything/blocksuite#4391]
### TLDR
use [`currentColor`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#currentcolor_keyword) instead!

---

### Using `currentColor` in SVG is more convenient and maintainable.

Instead of directly querying multiple SVG elements and setting inline styles for them, set `currentColor` for `fill` property, and then set `css color` directly to `SVG` element(or ancestor element), thanks to css inheritance, it should work as expected.

---

### Example

original:
```ts
@query('.brush-head-rect')
private _brushHeadRect!: SVGElement;

private _setBrushColor(color: string) {
    this._brushHeadRect.style.fill = `var(${color})`;
    this._brushMidlineRect.style.fill = `var(${color})`;
    this._brushMidlineStroke.style.stroke = `var(${color})`;
}
```
The above code can be completely removed, bind dynamic `color` style instead:

```ts
render() {
  const colorStyle = styleMap({ color: this.color })

  return html`
    <div .style=${colorStyle}>
       <!-- ..... -->
    </div>
  `
}
```

**Comment by doodlewind** [comment]
Hope @lzlme could help with this!

**Comment by lzlme** [comment]
> Hope @lzlme could help with this!

I'm gonna get it done

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/blocksuite/pull/4345
