### ISSUE TITLE
Support curve connector

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#4398]

**Comment by hwangdev97** [comment]
the design team has updated the curve connector item:
![shot-2023-08-31-16 18 40@2x](https://github.com/toeverything/blocksuite/assets/24713927/7dd29c1e-e658-4dd6-a235-e4d56a801d15)

[component's figma link](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%9B%9E-Design-System?type=design&node-id=8633%3A2&mode=design&t=Rrv0uf63UYgiTcRm-1)

![shot-2023-08-31-16 20 32@2x](https://github.com/toeverything/blocksuite/assets/24713927/9bf2e2b6-b880-46b9-8132-764efff0b4f3)

[use-case's figma link](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=7496%3A6791&mode=design&t=d9GuTtcdArN5R1qj-1)

**Comment by xell** [comment]
Summary:

- three shapes: straight line, right-angled poly line and curve
- arrow(s) at the start and/or end.

**Comment by regischen** [comment]
> Summary:
> 
> * three shapes: straight line, right-angled poly line and curve
> * arrow(s) at the start and/or end.

the arrow(s) will be tracked at #4501
