### ISSUE TITLE
Command design spec

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4407]
In the block service, we're introducing a new property named `commands`. This property will represent various operations depending on the block type. For frequently used actions like 'focus' and 'hard enter', different blocks often require distinct logic. By encapsulating these actions into commands, we can reduce the need for numerous block type checks within individual functions, such as in [legacy.ts](https://github.com/toeverything/blocksuite/blob/e7414fa16a30ab0f19e401f9f3e8f026a7dcba57/packages/blocks/src/__internal__/rich-text/keymap/legacy.ts) and [rich-text-operations.ts](https://github.com/toeverything/blocksuite/blob/e7414fa16a30ab0f19e401f9f3e8f026a7dcba57/packages/blocks/src/__internal__/rich-text/rich-text-operations.ts). This approach also simplifies the integration of third-party blocks.

see #4471

related to #4024 #4374

cc @Saul-Mirone @doodlewind

**Comment by Saul-Mirone** [comment]
Schema should only care about what happens on store level. Maybe we should put it in block spec.

**Comment by Flrande** [comment]
> Schema should only care about what happens on store level. Maybe we should put it in block spec.

Updated

**Comment by Flrande** [comment]
Infra finished in #4471 #4540
