### ISSUE TITLE
UI design of remote cursor

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#4417]
This issue focuses on the UI part of the collaboration, such as the multi cursor of users, the display of avatars, etc. Detailed design will be supplemented here later.

**Comment by Svaney-ssman** [comment]
Check design here : [Figma](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=13489-107729&mode=design&t=PP1FpkY4JgLZzbm6-4)

**Comment by doodlewind** [comment]
Unable to track this in AFFiNE kanban, use #4463 instead.
