### ISSUE TITLE
Table/Kanban View - When creating more views, there are some problems. See video

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#4421]
https://github.com/toeverything/blocksuite/assets/134894293/7ab0306d-55ef-4c46-9d18-63667258823a

**Comment by zzj3720** [comment]
It seems to be working as expected, can you provide more information?

**Comment by doodlewind** [comment]
I think this is working as expected. Rename the table view into different names and we can see the difference.
