### ISSUE TITLE
Edited frame title should not be wrapped during IME input

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4430]
https://github.com/toeverything/blocksuite/assets/22443345/bf0112de-7346-4d00-ab36-3cf36221819b

**Comment by BangKk** [comment]
On my macbook, when typing in Chinese, it looks like this: 
![image](https://github.com/toeverything/blocksuite/assets/13979818/c1b0a80e-c532-4447-9965-ae2786db4f02)
there is no space between the title and frame.
