### ISSUE TITLE
The format bar should not break cursor jumping

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#4435]
https://github.com/toeverything/blocksuite/assets/18554747/4b12c7f4-baa3-44d5-8621-292b5e369547

https://github.com/toeverything/blocksuite/blob/86653c592e02d8f7384e20f6bceab45b78a4dc4d/tests/format-bar.spec.ts#L1404-L1424

**Comment by Saul-Mirone** [comment]
The behavior will be fixed once we migrate the root content editable container. \cc @doodlewind
