### ISSUE TITLE
Invalid drag handle position after zooming the page

### ISSUE THREAD

**Issue by Tsuizen** [toeverything/blocksuite#4446]
### What happened?

![](https://raw.githubusercontent.com/Tsuizen/pic/master/affine-icon-bug.gif)

### Version

macOS ARM 64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
blocksuite editor should cleanup all floating ui when window w/h change

**Comment by doodlewind** [comment]
This is still reproduced for the new drag handle, requires @donteatfriedrice to take a look.
