### ISSUE TITLE
When entering a carriage or a space, should the first letter be capitalized automatically?

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#4447]
### Description

The first letter of space or carriage return is automatically capitalized (like lark system

### Use case

https://github.com/toeverything/AFFiNE/assets/79373028/9043d191-b612-4133-853e-0835af55a895

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
This should be supported by some external grammar checker, we have supported in #2129.
