### ISSUE TITLE
Include Zotero​

### ISSUE THREAD

**Issue by TachonFoucaut** [toeverything/blocksuite#4449]
### Description

This would be a key feature for academic people and other users that are interested with litterature.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Under current role of the team, we won't land official integration or specific block type support in the mainline codebase. For community contribution, this is suggested to wait for the extension system and snapshot importer/exporter (related to #3165 #4191).
