### ISSUE TITLE
 Can not change connector color

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4468]
### Discussed in https://github.com/toeverything/blocksuite/discussions/4442

<div type='discussions-op-text'>

<sup>Originally posted by **jjgalvez** August 30, 2023</sup>
in version 0.8.1 how do I change the connector color? If I select a connector and pick a different color nothing happens it remains black</div>

**Comment by regischen** [comment]
I think it has been fixed.
Can you guys use the latest version?

**Comment by houjoe0829** [comment]
Is this the newest version?  @regischen 
<img width="528" alt="CleanShot 2023-08-30 at 17 57 41@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/25b96286-5f39-422a-a614-d26c81c8c037">

**Comment by doodlewind** [comment]
I think we should check using the BlockSuite playground environment.
