### ISSUE TITLE
Double-click on the frame name to enter the edit state and all text should be selected by default

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4470]
https://github.com/toeverything/blocksuite/assets/22443345/a491c55e-bf5e-407f-b7f3-0ec57dbcc225

**Comment by hwangdev97** [comment]
Behavior similar to this：
![shot-2023-08-30-18 10 27](https://github.com/toeverything/blocksuite/assets/24713927/65029be7-307a-4816-9a68-3f652557a245)
