### ISSUE TITLE
Supports quick creation of new notes on whiteboard

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4474]

**Comment by hwangdev97** [comment]
![Uploading shot-2023-09-08-15.10.02@2x.png…]()
[the figma link](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=3212%3A68956&mode=design&t=oAhrTU66hw0YRmK4-1)
