### ISSUE TITLE
Quick Start use SimpleAffineEditor error

### ISSUE THREAD

**Issue by Niko030303** [toeverything/blocksuite#4480]
When i followed the developer docs to run a new simple project, it had error about `Could not resolve "@blocksuite/lit"` `Could not resolve "@blocksuite/block-std"` `Could not resolve "@toeverything/theme"` 

![image](https://github.com/toeverything/blocksuite/assets/82041918/c3a1f1fc-62c8-4e1e-94e2-6e33ff977016)

**Comment by doodlewind** [comment]
Supposed to be closed by #4482
