### ISSUE TITLE
​MarkDown export for a file export not working

### ISSUE THREAD

**Issue by OneMoonLeft** [toeverything/blocksuite#4483]
### What happened?

Tried exporting a page in a Markdown file, it only exported an empty zip file, with nothing in it
![image](https://github.com/toeverything/AFFiNE/assets/115279639/f0e74f22-f12f-4f2e-b5a9-5851ad2b6a14)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zuoxiaodong0815** [comment]
Sorry, I can't reappear it. Can you give me more details?

**Comment by OneMoonLeft** [comment]
![image](https://github.com/toeverything/blocksuite/assets/115279639/6cdb08fb-d395-4cb7-93d4-200c52d483ad)

**Comment by OneMoonLeft** [comment]
I didn't find any relevant log output i could give you, if you need anything, message me on discord, i'll be faster to respond (@[FR] Moon)

**Comment by zuoxiaodong0815** [comment]
I have seeded a message in Discord. If you look, you can contact me.

**Comment by doodlewind** [comment]
Closing as not reproduced in latest playground.

**Comment by zuoxiaodong0815** [comment]
The reason is that the display of file suffixes is not enabled in windows.
