### ISSUE TITLE
unable to copy Kanban view

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4487]
after copied, it automatically turned to table view, instead of the kanban view

https://user-images.githubusercontent.com/134897361/264519049-fa01dd82-f8fd-49b9-85bd-849a748cf5c5.mp4

**Comment by DanM3rcurius** [comment]
Copying the whole table works ok, swithcing back to Kanban view is not a big deal(issue).
I was referring to copying and pasting data into the cells. just saw it was being mentioned by Enther in the discrod that you guys are working on that feature.
I'd say this "bug" can be closed.

**Comment by doodlewind** [comment]
Thanks for the feedback, closing since this is expected.
