### ISSUE TITLE
Unable to select bullet points from the bottom to top all together.

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4488]
https://user-images.githubusercontent.com/142964904/264518787-075d78a0-ac65-402b-bf2e-e7d13a00f5be.mp4

It's ok to select all the bullet points from top to the bottom, but it's difficult to select all the bullet points from the bottom to the top.

**Comment by DanM3rcurius** [comment]
Noted. I should have been more clear. 
The bug appears when I try to copy content that is sitting in a second level bullet point.
I tried reproducing right now in the new 8.2 version and i couldn't!
Can be closed from my perspective, will keep an eye out for it though

**Comment by Flrande** [comment]
> Noted. I should have been more clear.
The bug appears when I try to copy content that is sitting in a second level bullet point.
I tried reproducing right now in the new 8.2 version and i couldn't!
Can be closed from my perspective, will keep an eye out for it though

Thanks! I will close this issue and feel free to reopen it if you encounter it again.
