### ISSUE TITLE
Import and Export - Markdown file can not be imported.

### ISSUE THREAD

**Issue by PaxtonXuan** [toeverything/blocksuite#4497]
https://github.com/toeverything/blocksuite/assets/134894293/01f43a03-9747-4165-ab85-3db154a42d25

**Comment by zuoxiaodong0815** [comment]
This feature hasn't been developed.

**Comment by doodlewind** [comment]
Closing since the markdown importing feature should only support `.md`. Exported AFFiNE content should be supported with #3654
