### ISSUE TITLE
Lost content with duplicate note action in edgeless

### ISSUE THREAD

**Issue by BangKk** [toeverything/blocksuite#4521]
What happened?

https://github.com/toeverything/blocksuite/assets/13979818/606e6be8-8abe-4ce0-b5e5-67b8eb61cc75

Distribution version
last version of playground

What browsers are you seeing the problem on if you're using web version?
Chrome 116.0.5845.110

Relevant log output
No response

Anything else?
No response

Are you willing to submit a PR?
- [x] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks the report! This should be a regression.
