### ISSUE TITLE
Need a date picker component

### ISSUE THREAD

**Issue by zzj3720** [toeverything/blocksuite#4524]

**Comment by hwangdev97** [comment]
![shot-2023-09-04-20 13 33@2x](https://github.com/toeverything/blocksuite/assets/24713927/989e3d05-dc4b-4d17-982f-aa1ec24bdf02)
[the figma file](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%9B%9E-Design-System?type=design&node-id=1430%3A11721&mode=design&t=5kwCufzY5C3gb3o6-1)

**Comment by CatsJuice** [comment]
🙋 I can help with this! @doodlewind

**Comment by doodlewind** [comment]
@CatsJuice that would be awesome! Wondering is it possible for us to support the date picker in lit (or vanilla JS like floating-ui), so that we don't have to add react into the dependency tree in BlockSuite?

**Comment by CatsJuice** [comment]
> @CatsJuice that would be awesome! Wondering is it possible for us to support the date picker in lit (or vanilla JS like floating-ui), so that we don't have to add react into the dependency tree in BlockSuite?

Yes, of course!

BTW, I wonder if we have plans to develop a  web-component library, with the aim of sharing it between `AFFiNE` and `blocksuite`. As for the current demand, I will implement it with `lit`.

**Comment by doodlewind** [comment]
> > @CatsJuice that would be awesome! Wondering is it possible for us to support the date picker in lit (or vanilla JS like floating-ui), so that we don't have to add react into the dependency tree in BlockSuite?
> 
> 
> 
> Yes, of course!
> 
> 
> 
> BTW, I wonder if we have plans to develop a  web-component library, with the aim of sharing it between `AFFiNE` and `blocksuite`. As for the current demand, I will implement it with `lit`.

I think a lit implementation in BlockSuite repo would be a good fit for now. But when it comes to reusing UI components between BlockSuite and AFFiNE, we need more discussion to decide the boundary. /cc @Saul-Mirone @zzj3720

**Comment by doodlewind** [comment]
Closing since #4680 has landed.
