### ISSUE TITLE
Support for adding inline tags

### ISSUE THREAD

**Issue by zzj3720** [toeverything/blocksuite#4525]

**Comment by mukeshkuiry** [comment]
@zzj3720 Could you elaborate, on how this is going to look?

and what does this actually tell?

**Comment by gordielachance** [comment]
I would love this feature too.  AFFiNE seems to be a perfect tool, but it lacks a good tags feature.
I mean; per-blocks tags, not per page tags as it exists for now.

I use this on [logseq](https://logseq.com/) and [workflowy](https://workflowy.com/) a lot, **to filter my content**.  See this screenshot : 


![Capture d’écran du 2023-09-18 21-06-40](https://github.com/toeverything/blocksuite/assets/4077261/84049dc9-1e80-4609-ae12-060428d33b24)

**Comment by doodlewind** [comment]
The framework capability is supported in #5909 that allows defining inline specs, but the inline tag feature is actually an AFFiNE product feature, we should track in #4838.
