### ISSUE TITLE
The image converted to a card cannot be converted back to the embedded effect

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4532]
<img width="834" alt="CleanShot 2023-09-01 at 16 55 08@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/aa9cd4a6-1d8e-466c-90f9-b3d43557ebef">

Under the expected effect, there should be an option to convert to an embedded view in the hover menu.

![CleanShot 2023-09-01 at 16 57 00@2x](https://github.com/toeverything/blocksuite/assets/22443345/d38fcef0-418d-4c18-9a00-1428d415874f)

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/AFFiNE/issues/4111

**Comment by lawvs** [comment]
I believe this issue has been fixed in https://github.com/toeverything/blocksuite/pull/4583
