### ISSUE TITLE
Long hovertips can not be fully displayed

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4533]
<img width="953" alt="CleanShot 2023-09-01 at 16 59 43@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/d53b4d08-091e-4099-aac0-ab064653c14e">

This also needs @xell  to see how to deal with it, whether it should pop out from the left when it cannot be displayed on the right.

**Comment by xell** [comment]
Duplicated with https://github.com/toeverything/blocksuite/issues/3744 .
