### ISSUE TITLE
The divider can not be selected or deleted using the keyboard

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#4547]
Other card blocks also have the same issue. (eg. image, attachment, bookmark)

https://github.com/toeverything/blocksuite/assets/18554747/054e21df-0611-407b-9d63-f3d36b36407f

**Comment by doodlewind** [comment]
It's not expected to select divider using keyboard. Deleting it with keyboard makes sense.

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/blocksuite/issues/4374

**Comment by lawvs** [comment]
There is a test case for it.

https://github.com/toeverything/blocksuite/blob/a0bbff544f6dccdb77e2209dce85de5e4f436d45/tests/selection/native.spec.ts#L771-L786

See also https://github.com/toeverything/blocksuite/pull/3948
