### ISSUE TITLE
Can not paste emoji correctly from X

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#4550]
https://github.com/toeverything/blocksuite/assets/18554747/57b8de75-452e-47b2-95db-f15a8f8b5ea3

**Comment by fourdim** [comment]
Unfortunately, there is nothing we can do.
We can find that in X:
```html
<span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">himself65</span>
<img alt="🍞" draggable="false" src="https://abs-0.twimg.com/emoji/v2/svg/1f35e.svg" class="r-4qtqp9 r-dflpy8 r-sjv1od r-zw8f10 r-10akycc r-h9hxbl">
```
The clipboard gets:

text/html
```
<span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">himself65</span>
<img alt="🍞" draggable="false" src="https://abs-0.twimg.com/emoji/v2/svg/1f35e.svg" class="r-4qtqp9 r-dflpy8 r-sjv1od r-zw8f10 r-10akycc r-h9hxbl">
```

text/plain
```
himself65🍞
```

We always treat the `text/html` format with higher priority in most blocks as it often reflects the clipboard data's original use.
Currently, we don't plan to change the priority as it seldom happens.
