### ISSUE TITLE
When dragging a shape, the shape doesn't move with the mouse scroll

### ISSUE THREAD

**Issue by CatsJuice** [toeverything/blocksuite#4561]
https://github.com/toeverything/blocksuite/assets/39363750/334b6fbd-21bd-444f-8c34-190aac6d6998

**Comment by donteatfriedrice** [comment]
This issue seems to occur not only when dragging a shape element, but also when moving other edgeless elements like Note, Connector, Brush.

https://github.com/toeverything/blocksuite/assets/99816898/67aaf3d4-8f4f-4dfe-a32c-2b1de42986f0

**Comment by doodlewind** [comment]
Considered fixed since this is not reproduced in current playground.
