### ISSUE TITLE
Missing page bottom drop area for block hub

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4564]
https://github.com/toeverything/blocksuite/assets/22443345/62c35fa7-6a5e-45b3-85fd-c58f27cd4fd4

1. The triggered area is very small, previously @lawvs  had set the triggered area to be very large.
2. An insertable hint appeared at the bottom, it should be a bug.

**Comment by zqran** [comment]
@houjoe0829 
Is it possible to insert an element when the dragged element is outside the document content area(read area)? 

<img width="977" alt="image" src="https://github.com/toeverything/blocksuite/assets/15389209/3dfea5a0-85db-40c3-89e5-7358b7149b9a">

**Comment by doodlewind** [comment]
@zqran I don't consider this as a must-have.

**Comment by houjoe0829** [comment]
@doodlewind @Saul-Mirone It is strongly recommended not to close this issue first. Doing similar security processing at the bottom is a common small detail that can make it easier for users to enter the final editing area, and areas outside the editing area can be left unprocessed (that is, the area shown in @zqran 's screenshot). Similar processing can be seen in apps such as Notion and Craft.

**Comment by houjoe0829** [comment]
As for the handling of other apps, including dragging and clicking the mouse in the bottom area of the document, it can be positioned to the last line or even create a new line.

**Comment by houjoe0829** [comment]
It has already been technically resolved.
