### ISSUE TITLE
Optimize the animation of expanding and retracting the drag handle

### ISSUE THREAD

**Issue by CatsJuice** [toeverything/blocksuite#4565]
The animation of expanding & retracting the drag handle is kind of strange, the expand/retract center should be fixed to the hovered block.

https://github.com/toeverything/blocksuite/assets/39363750/58f9c875-eeca-4d17-9e18-8e3b482e23da

**Comment by CatsJuice** [comment]
I can help with this!

**Comment by donteatfriedrice** [comment]
> I can help with this!

Thanks to optimize the animation!
