### ISSUE TITLE
When the document is too long, the connector will automatically position itself to jump to a certain location.

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4579]
https://user-images.githubusercontent.com/142964904/265405561-0b5fad04-d947-4310-9888-57bdefe45e16.mp4

In egless mode, when adding a link, the connector will be automatically linked to the center of the block, and if the zoom value is too large, the focus of the arrow will be lost on the page.

**Comment by regischen** [comment]
@Yuhang1015 it is by design, If you want to connect to edges of elements, you can put the mouse around the edges.
