### ISSUE TITLE
kanban makes page move​

### ISSUE THREAD

**Issue by omarcostahamido** [toeverything/blocksuite#4594]
### What happened?

when using a kanban database toggling the view of status off makes the entire page move a little to the right.
running affine on insider cloud deployment.

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zzj3720** [comment]
Can you provide me with a recording?
I'm guessing it might be the height change that causes the scrollbars to appear and disappear, but not sure.

**Comment by doodlewind** [comment]
Closing as not reproduced in current playground.
