### ISSUE TITLE
Request for HTTP Request Communication EXPLAIN HOW

### ISSUE THREAD

**Issue by spacewalkingninja** [toeverything/blocksuite#4612]
https://github.com/toeverything/blocksuite/pull/4596

@doouding 

**It looks like you want to implement an HTTP based provider for just an experimental purpose. It would be better if you could just clone this project and test it locally (or just fork this project).
BTW, HTTP is theoretically possible but it might be a little cumbersome.**

I want to implement an HTTP provider for PRODUCTION purposes.
I fork and test privately but now I have questions. 
It will be better than Websocket because HTTP request from what I know is master superior to websocket chan.
The question is what would I have to send to and from my MYSQL database. 

I can make the php api easy, but what would need to consist in the request cause I don't have your websocket server to test... :(

**Comment by doouding** [comment]
It's not necessary to send data to your database, but it's OK if you want to. We have our playground collaboration service deployed on Cloudflare. The code is open source too, you can check it at [collaboration-room](https://github.com/toeverything/collaboration-room).

If you want to implement your own provider, I suggest you go through the Yjs docs cause we use Yjs under the hood. You can also refer to our provider implementation https://github.com/toeverything/blocksuite/tree/master/packages/playground/apps/default/providers
