### ISSUE TITLE
The children's content was lost by using drag element to copy

### ISSUE THREAD

**Issue by BangKk** [toeverything/blocksuite#4619]
https://github.com/toeverything/blocksuite/assets/13979818/ba1b459b-1ca4-4981-998b-619cdaed475b

**Comment by BangKk** [comment]
I'd like to solve this issue.

**Comment by donteatfriedrice** [comment]
This issue not only occurs when copying and pasting after selecting the parent block using the drag handle, but also in all cases where the parent block is selected and copied. It is necessary to confirm whether all the information of the child blocks is included during the copy-paste process when only selecting parent block.

**Comment by BangKk** [comment]
> This issue not only occurs when copying and pasting after selecting the parent block using the drag handle, but also in all cases where the parent block is selected and copied. Maybe need to confirm whether all the information of the child blocks is included during the copy-paste process when only selecting parent block.

Yes, you are right. Thanks for the reminder. I'll request you to review after post the pr.
