### ISSUE TITLE
After the connector was deleted, it can't be restored on undo

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4625]
https://user-images.githubusercontent.com/142964904/265946214-3a364654-2f90-4b0a-881e-4e68648a848e.mp4

(Edgeless mode) When we delete the contents of one end of the connector connection, the connector is also deleted and cannot be restored when withdrawn.

**Comment by doodlewind** [comment]
Closing since not reproduced in latest playground.

https://github.com/toeverything/blocksuite/assets/7312949/c5942449-f55c-4dd1-8958-5b610812bc50
