### ISSUE TITLE
About the 'hasBlob' method of AttachmentBlock

### ISSUE THREAD

**Issue by yangvom** [toeverything/blocksuite#4636]
When all the file resources are uploaded to the remote server, and there are too many file resources uploaded, "ServerStorage" cannot load all the file resources into the 'list()' method, and this is not efficient and resource-intensive, then it may be the most appropriate practice to detect whether a file exists based on the 'sourceId' parameter and the 'get() ' method.

```
import type { BlobStorage } from './types.js';

/**
 * API: /api/workspace/:id/blob/:key
 * GET: get blob
 * PUT: set blob
 * DELETE: delete blob
 */
export function createSimpleServerStorage(id: string): BlobStorage {
  const localCache = new Map<string, Blob>();
  return {
    crud: {
      get: async (key: string) => {
        if (localCache.has(key)) {
          return localCache.get(key) as Blob;
        } else {
          const blob = await fetch(`/api/workspace/${id}/blob/${key}`, {
            method: 'GET',
          }).then(response => {
            if (!response.ok) {
              throw new Error(`Failed to fetch blob ${key}`);
            }
            return response.blob();
          });
          localCache.set(key, blob);
          return blob;
        }
      },
      set: async (key: string, value: Blob) => {
        localCache.set(key, value);
        await fetch(`/api/workspace/${id}/blob/${key}`, {
          method: 'PUT',
          body: await value.arrayBuffer(),
        });
        return key;
      },
      delete: async (key: string) => {
        localCache.delete(key);
        await fetch(`/api/workspace/${id}/blob/${key}`, {
          method: 'DELETE',
        });
      },
      list: async () => {
        return Array.from(localCache.keys());
      },
    },
  };
}
```

_Originally posted by @yangvom in https://github.com/toeverything/blocksuite/issues/4461#issuecomment-1708479473_

**Comment by yangvom** [comment]
> If the blob is very large, using `get` to check if the resource exists will also consume a large amount of memory and network resources. There are shortcomings in using `list` or `get` before the `has` method is implemented.

Yes, you are right, there will be such a problem.

**Comment by doodlewind** [comment]
@lawvs do we have the `has` method support here? If not, I think it could be good to support it.
