### ISSUE TITLE
the selected rect doesn't fit when zoom in

### ISSUE THREAD

**Issue by WBbug** [toeverything/blocksuite#4656]
<img width="804" alt="image" src="https://github.com/toeverything/blocksuite/assets/87802698/40a887b2-b525-47fc-90e7-014bcd0a4afc">

**Comment by doodlewind** [comment]
@hwangdev97 wondering what's the expected UI style in this case?

**Comment by hwangdev97** [comment]
The desired effect on the design side（by @Svaney-ssman ） is shown in the figure：
![shot-2023-09-08-14 21 24@2x](https://github.com/toeverything/blocksuite/assets/24713927/3648bcc5-2e0b-4124-9dfe-667c0a485fe5)

Right-angle design, every angle should have a ⭕️

**Comment by WBbug** [comment]
i see the `border-radius` was changed in this pr #4321  and wondering why this was changed, and if deleting it will have an effect on the others? @doouding

**Comment by doouding** [comment]
Yes, this would effect the style of the note selection style. I'd be better to confirm with designer first.

**Comment by WBbug** [comment]
@hwangdev97 

> The desired effect on the design side（by @Svaney-ssman ） is shown in the figure： ![shot-2023-09-08-14 21 24@2x](https://user-images.githubusercontent.com/24713927/266519795-3648bcc5-2e0b-4124-9dfe-667c0a485fe5.png)
> 
> Right-angle design, every angle should have a ⭕️

shoud it always be Right-angle when select note?

**Comment by hwangdev97** [comment]
I'm not sure what you mean by "note". 
Generally, in the Edgeless scenario, note is worth the content of the DOM from Page mode.

**Comment by hwangdev97** [comment]
If this is the note you are talking about, then a new issue will be added to the design side recently to track related changes independently. 

We will add custom height/style and other functions to it, so there is no need to consider it here.

**Comment by WBbug** [comment]
> If this is the note you are talking about, then a new issue will be added to the design side recently to track related changes independently.
> 
> We will add custom height/style and other functions to it, so there is no need to consider it here.

yes, that's what i mean. The same `edgeless-selected-rect` component is used in all three of the following cases

<img width="798" alt="image" src="https://github.com/toeverything/blocksuite/assets/87802698/d04747e1-031e-47f9-bf60-872cc4c4700e">
<img width="561" alt="image" src="https://github.com/toeverything/blocksuite/assets/87802698/fca08f35-3536-4503-8057-dd65d2b1d45a">
<img width="1217" alt="image" src="https://github.com/toeverything/blocksuite/assets/87802698/50b15e83-36d9-41a3-92f9-25092ff1f69e">

**Comment by hwangdev97** [comment]
I think the distinction here would be more reasonable. Note is rather special

**Comment by WBbug** [comment]
> I think the distinction here would be more reasonable. Note is rather special

1. so, single select note the `selected-rect` should have radius, single select shape the `selected-rect` should be right angle?
2. what should the `selected-rect` display when multiple select?
<img width="1311" alt="image" src="https://github.com/toeverything/blocksuite/assets/87802698/099ecabc-4f5b-49da-8b56-a691838f5bca">

**Comment by hwangdev97** [comment]
1. Yes, use right angle for shape, radius for note.
2. Use right angle for multiple select, too. 

Currently, notes only support left and right adjustments. After multi-selection, if there are notes, they will only support left and right adjustments. This is acceptable for the time being. 

There will be a better design solution after adjusting the note function in the future.
