### ISSUE TITLE
Incorrect presentation starting frame index for multiple selected frames

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4659]
https://toeverything.feishu.cn/minutes/obcnfw794wh4x118za54u6mj

**Comment by doodlewind** [comment]
Good catch!

**Comment by regischen** [comment]
presentation will start from the selected frame. If not, it starts from the first.

In this case，you select the frame 3.

**Comment by doodlewind** [comment]
@regischen I see, my local reproduction may have just selected the last one.
