### ISSUE TITLE
After inserting a code block, no space is found to insert the next line

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4665]
https://toeverything.feishu.cn/minutes/obcnfwobn4f7r7616etev6g7

**Comment by doodlewind** [comment]
@Saul-Mirone is this suitable to be marked as `good first issue`?

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone is this suitable to be marked as `good first issue`?

Yeah, I think it's easy to fix.

**Comment by zqran** [comment]
https://github.com/toeverything/blocksuite/blob/4af2f43d5c6345276aea25c934b24dd727d719f5/packages/blocks/src/page-block/doc/doc-page-block.ts#L526

@Saul-Mirone 
The code block has a `text` prop, so no extra paragraph is added here.
Do we need to handle code block specially? Or, can I break out of the code block?

**Comment by Saul-Mirone** [comment]
> https://github.com/toeverything/blocksuite/blob/4af2f43d5c6345276aea25c934b24dd727d719f5/packages/blocks/src/page-block/doc/doc-page-block.ts#L526
> 
> @Saul-Mirone The code block has a `text` prop, so no extra paragraph is added here. Do we need to handle code block specially? Or, can I break out of the code block?

I think we should check flavour instead of the `text` prop here.
