### ISSUE TITLE
Note position shifts during input and zooming in edgeless

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4696]
https://user-images.githubusercontent.com/142964904/266938163-333f1776-748b-4249-9866-c2f17994398c.mp4

**Comment by regischen** [comment]
@Yuhang1015  can you give a more clear video?

**Comment by Yuhang1015** [comment]
https://github.com/toeverything/blocksuite/assets/142964904/3f74c889-c72e-4aef-945e-ec45b37b20f0

**Comment by doodlewind** [comment]
Closing as not reproduced.
