### ISSUE TITLE
In edgeless mode, if kanban exceeds the length of the screen, it will jump up and down

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4699]

**Comment by zqran** [comment]
Reproduction video:

https://github.com/toeverything/blocksuite/assets/15389209/e632c48b-ab3b-4426-973d-2a9bb19f21b4

**Comment by Yuhang1015** [comment]
https://github.com/toeverything/blocksuite/assets/142964904/ae254481-fc9f-4d71-85f4-8cfef69b767f

**Comment by zqran** [comment]
It doesn’t look like it’s caused by the kanban view of the database. @regischen Please take a look.

**Comment by regischen** [comment]
closed by #4738
