### ISSUE TITLE
Support input box for canvas text

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#4717]
![shot-2023-09-12-15 28 15](https://github.com/toeverything/blocksuite/assets/24713927/97350a71-cd5c-425e-aa42-a2fb4d591b77)

The product design side updates related designs and you can view the design files.

![shot-2023-09-12-16 36 10@2x](https://github.com/toeverything/blocksuite/assets/24713927/f8968fc7-27e0-470c-9b0c-dfbf287f6d6f)

[figma link](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=8548%3A16665&mode=design&t=DkbW1QwYJvp4Rp8L-1)

**Comment by doodlewind** [comment]
Given current status, I suggest the canvas text related issues should be handed over to @doouding for maintenance, /cc @regischen
