### ISSUE TITLE
Add tests for scroll into view automatically

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4725]
Add tests for #4715 

There are three cases need to add.

### Keep pressing Enterw

When a line break occurs, the page should scroll automatically.

https://github.com/toeverything/blocksuite/assets/50035259/b2bbecdb-d2dc-4e69-86e0-382fd7a5a7d2

### Keep inputting in the end of code block (should scroll)

https://github.com/toeverything/blocksuite/assets/50035259/a2ce6824-6395-4048-855c-b48cce602aec

### Keep inputting not in the end of code block (should not scroll)

https://github.com/toeverything/blocksuite/assets/50035259/4ab8878f-4851-41c4-af3b-ca434f2c8869

**Comment by doodlewind** [comment]
Considered supported by #5045

**Comment by Flrande** [comment]
Test added in #5045 not cover all cases in this issue, just a part of them.
