### ISSUE TITLE
Flaky test cases in local environment

### ISSUE THREAD

**Issue by water-in-stone** [toeverything/blocksuite#4729]
when I run `npm run test`, many test cases failed. I think it could give rise to severe issues !!! 
 
PS: already rebase to latest branch (2023.09.13) 
![image](https://github.com/toeverything/blocksuite/assets/9940769/87401097-bd8f-46a6-b19f-a76d11ed10bb)
![image](https://github.com/toeverything/blocksuite/assets/9940769/2fcbf33a-8589-4da6-b346-0a1c0807a2de)

**Comment by Flrande** [comment]
There are a lot of flaky tests now so we retries it in [CI](https://github.com/toeverything/blocksuite/blob/master/playwright.config.ts#L33). We usually only run tests locally when debugging a specific test, and rarely run all tests locally at once.

**Comment by doodlewind** [comment]
The stability of CI has been improved in #4793, please feel free to feedback on certain flaky cases.
