### ISSUE TITLE
Support menus related to database views

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4736]
View：
- Layout
- Filter
- Sort By
- Group By
- Move Left
- Move Right
- Duplicate View

Database
- Rename
- Duplicate Database
- Delete Database

[Internal slack discussion](https://affine-pro.slack.com/docs/T03K3CD2015/F05S4CQS3C2)

**Comment by zanwei** [comment]
Design done.

View: [figma file](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=5861-20521&mode=design&t=4y4ysmuV8SGV91Ku-4)

Delete Database: [figma file](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=8639-46509&mode=design&t=4y4ysmuV8SGV91Ku-4)
