### ISSUE TITLE
Unable to display the whole database when exporting html. & md.

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4753]
![Image](https://user-images.githubusercontent.com/142964904/267887235-d804175a-f8b1-4f28-ae38-ea963677a282.gif)

After exporting the page to html and markdown, and then clicking on the file, most of the content is lost.

**Comment by zuoxiaodong0815** [comment]
This feature has not been developed yet. When doing so, it is necessary to consider exporting the database into a separate file. If there are too many database content entries in the HTML, it is also necessary to consider how to handle them.

**Comment by doodlewind** [comment]
Considered by design since HTML and MD are lossy exports.
