### ISSUE TITLE
Cursor may jump to line begin when pressing a short key

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#4761]
https://github.com/toeverything/blocksuite/assets/18554747/fdb30984-dd07-48ac-9978-aad91cd6b4aa

I suppose this is the reason for the flaky of the test below

https://github.com/toeverything/blocksuite/blob/8f0d79cf8b0aeab2d2c691e4f068965f949903f8/tests/edgeless/text.spec.ts#L87-L119

**Comment by Flrande** [comment]
duplicate of #4674
