### ISSUE TITLE
Double click editing doesn't work for shape inside hollow area

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#4764]
https://github.com/toeverything/blocksuite/assets/14026360/a95368c1-172a-4ee8-9a31-4a5631d5814e

**Comment by doodlewind** [comment]
We've further optimized hit test in #4941, but double click is still not supported for shapes under hollow area. Hope @donteatfriedrice could take a look in this iteration.

**Comment by donteatfriedrice** [comment]
> We've further optimized hit test in #4941, but double click is still not supported for shapes under hollow area. Hope @donteatfriedrice could take a look in this iteration.

I will handle it.
