### ISSUE TITLE
Some Kanban panels are lost during drag-and-drop

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#4771]
Most of the time there is a problem with the first column. In this case, the missing Kanban will be rebuilt at the end of the list as "Ungroups" and then inserted into the last column.

https://github.com/toeverything/blocksuite/assets/144991896/1b8bab87-865c-4b4b-8911-e5a0a0af78f9

**Comment by zzj3720** [comment]
The path to stable reproduction is group by multi-select column and then drag card to the ungroups

**Comment by YanxinLu0122** [comment]
still exist in beta 0.10.0



https://github.com/toeverything/blocksuite/assets/144991896/86c9e01f-60fd-4d2b-928e-80dc8eb34972
