### ISSUE TITLE
Unable to paste after clicking "copy to clipboard" in edgeless mode

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4772]
![Image](https://user-images.githubusercontent.com/142964904/268198989-90732ce8-309a-4ad1-a8bc-21f195a3edee.gif)

**Comment by YanxinLu0122** [comment]
Still exist.


https://github.com/toeverything/blocksuite/assets/144991896/b1af9f7a-9e9b-4d4f-b4f6-d3769d52a631

**Comment by Flrande** [comment]
cc? @fourdim

**Comment by fourdim** [comment]
I can reproduce it neither in blocksuite's playground nor latest AFFiNE internal.
![image](https://github.com/toeverything/blocksuite/assets/59462000/8638f387-660c-4b6c-8459-38ee190bfb5f)
Please check your version.
