### ISSUE TITLE
Unable to edit "tag" in database in edgeless mode

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4774]
![Image](https://user-images.githubusercontent.com/142964904/268217193-f9f586bc-92bb-4a55-bdb8-14f0aed21ea0.gif)

**Comment by zqran** [comment]
Which version are you using? Unable to reproduce in version (0.9.0-canary.12).

**Comment by Yuhang1015** [comment]
internal 916 test: https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-internal.20230916005708-26877ff
