### ISSUE TITLE
Content disappeared in edgeless after toggling right panel

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#4777]
https://user-images.githubusercontent.com/144991896/268220681-3766642d-f7f4-469b-83ad-c06e2a253ded.mov

**Comment by doodlewind** [comment]
Require @doouding to triage (reproduce).

**Comment by doouding** [comment]
Can't reproduce it on the latest internal version.

**Comment by doodlewind** [comment]
Closing as not reproduced.
