### ISSUE TITLE
When collaborating, if one person drags content, others can only see the empty frame being moved

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4778]
![Image](https://user-images.githubusercontent.com/142964904/268222907-64b445f2-de93-4ba7-a635-4390ed306a38.gif)

**Comment by donteatfriedrice** [comment]
duplicate of #4697

**Comment by Saul-Mirone** [comment]
Closed by https://github.com/toeverything/blocksuite/pull/4808
