### ISSUE TITLE
Require page refresh to see new image added by remote

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4779]
![Image](https://user-images.githubusercontent.com/142964904/268223059-4fd9dc20-635f-4424-aa2d-48b8382e70b1.gif)

**Comment by houjoe0829** [comment]
@Brooooooklyn  Jackie and I have also reproduced this issue. Regardless of whether it is in Page Mode or Edgeless Mode, the display of multi-person collaboration status must be refreshed first.

**Comment by houjoe0829** [comment]
For example, when Jackie uploads an image to the whiteboard, I can see the box where the image is located but not the content inside. I have to refresh first to see it.
![image](https://github.com/toeverything/blocksuite/assets/22443345/f1f9198f-f2cd-4330-b2bb-d3aed4e59b10)

**Comment by thorseraq** [comment]
Following steps can give some hints that there seems need to trigger image downloading manually on whiteboard:
1. User A uploads image in whiteboard
2. User B can see image frame, but no image
3. User B refresh page, or click the frame, then starting download image blob and image appears:
<img width="959" alt="image" src="https://github.com/toeverything/blocksuite/assets/20554850/5c2d4dce-511d-4abc-9b30-d536b9099976">

**Comment by doodlewind** [comment]
@Saul-Mirone does this relate to our blob related data flow?

**Comment by Saul-Mirone** [comment]
> @Saul-Mirone does this relate to our blob related data flow?

Maybe, but I think it's more likely about the missing structs in yjs.

**Comment by doouding** [comment]
I think this may be caused by the recent changing of the edgeless which was fixed yesterday. See https://github.com/toeverything/blocksuite/pull/4808

**Comment by doouding** [comment]
BTW, the cause of this issue is different from #4801.
