### ISSUE TITLE
Duplicate remote selection status in edgeless

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4782]
<img width="508" alt="CleanShot 2023-09-15 at 17 02 02@2x" src="https://github.com/toeverything/blocksuite/assets/22443345/a0752506-7a9f-4fac-ba01-47564f3fc7a4">

In this case, it is recommended to only display the editing cursor inside the Note. When the user exits the editing state, the cursor on the whiteboard can be displayed again.

**Comment by doodlewind** [comment]
Require @doouding to triage (reproduce).
