### ISSUE TITLE
Duplicate scrollbar caused by bookmark link view

### ISSUE THREAD

**Issue by blurname** [toeverything/blocksuite#4794]
When there is one scrollbar present, if I hover over the bookmark link at the bottom of the page and the edit-link-panel is not fully displayed, then another scrollbar appears

https://github.com/toeverything/blocksuite/assets/50226652/e02aa5ef-498b-4f3e-9b99-744a0de79ee3

**Comment by doodlewind** [comment]
Not produced locally, possibly also fixed by #4787
