### ISSUE TITLE
Redundant bookmark `edit-link-panel` components are not disposed

### ISSUE THREAD

**Issue by blurname** [toeverything/blocksuite#4795]
The video does not show my cursor, I just move it around the bookmark `asd`

https://github.com/toeverything/blocksuite/assets/50226652/2188757d-ef95-4e1f-af7e-98be29789e4e

**Comment by doodlewind** [comment]
This should be fixed by #4787, the `edit-link-panel` component is also migrated to `link-popup` that should have correct lifecycle.
