### ISSUE TITLE
Pasted note should be located to top

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4800]
![Image](https://user-images.githubusercontent.com/142964904/268550657-71bb9483-3b19-4afa-81a1-003fb3bf5b22.gif)

**Comment by doodlewind** [comment]
Seems that this only happens for the `Personal-Knowledge Management` pre loading article in AFFiNE. Since it's not urgent, can @zqran take a look on this?

**Comment by zqran** [comment]
In the 0.10.0-canary.2 version, the pasted note is already at the top.
