### ISSUE TITLE
Support auto panning when selection rect approaches viewport edge

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#4815]
I think support is needed from top to bottom, left and right.

![shot-2023-09-18-20 59 06](https://github.com/toeverything/blocksuite/assets/24713927/c91c3eef-f4fa-465c-8778-5e8a2aa77c6a)

**Comment by doodlewind** [comment]
Regarding this type of selection optimization, would be great if @donteatfriedrice could help.
