### ISSUE TITLE
Image frame doesnt get deleted

### ISSUE THREAD

**Issue by RajeevDash007** [toeverything/blocksuite#4844]
after importing an image, if we want to delete that image by using side format section, then it only deletes the image and not the whole frame.
after the deletion of the image, I guess the frame is also of no use.

https://github.com/toeverything/blocksuite/assets/96860040/84666e96-e3f1-4a20-83ad-3ee39c7b926c

**Comment by doodlewind** [comment]
Currently the image is wrapped inside a note block, so keeping the note is expected. To optimize this we have #3594 in progress.
