### ISSUE TITLE
Table view layout redesigned

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#4861]
Please [check differences in new draft](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=9441-65765&mode=design&t=za6ZfIjGpDDes4ix-4)

1. fix ’New Record', 'New Group' button
2. resize gaps between groups and title (12px > 16px)
3. 

![Image](https://github.com/toeverything/blocksuite/assets/110808979/f79ff60f-cd7e-4601-8f79-da6150b02323)

**Comment by zzj3720** [comment]
completed in #4727
