### ISSUE TITLE
Right panel UI mistakes

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#4863]
Compared to the current product, there are several mistakes:  [please check design in figma](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=9460-89444&mode=design&t=za6ZfIjGpDDes4ix-4)
1. The placeholder of an untitled record is missing
2. The placeholder of empty property is missing
3. Add a new property menu incorrect
4. Padding-top of the title area is missing
<img width="680" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/c259e7ac-0bc4-40b3-942f-163c839ecd8a">

**Comment by zanwei** [comment]
Also please note that the panel background color should use `backgroundPrimaryColor`, instead of`backgroundOverlayPanelColor`

<img width="629" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/43c1cf40-db38-4bc6-b4e5-051ad4f8e0e4">

**Comment by doodlewind** [comment]
Will be tracked in #5385
