### ISSUE TITLE
Deleting nested list item in the middle should not change the hierarchy of its siblings below

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4864]
This is mainly related to indented lists and their impact on other content.

The main purpose is to avoid changing the hierarchy of same-level content below a blank line when deleting it in the middle, which is inconsistent with common editing behavior.

How to reproduce:
1. When there is same-level content below indented content, such as "Child 2" in the screenshot.
2. Starting from the end, click the delete key to delete until it becomes a blank line.
3. Deleting again will reduce the indentation level and affect the indentation of "Child 3" below.

![CleanShot 2023-09-21 at 17 47 25@2x](https://github.com/toeverything/blocksuite/assets/22443345/a9f15bfe-ef1d-47f3-b757-af56824a58ac)

The expected effects are:

In step 2, after deleting to a blank line, clicking the delete key again will directly delete it.
In step 2, if deleting starts from the beginning, the indentation level will not be reduced, but the content will be merged into the previous line.

This is the effect I recorded in Notion：

https://github.com/toeverything/blocksuite/assets/22443345/a51068b7-2ad3-4d72-a965-2f15e1b14df3

**Comment by doodlewind** [comment]
Thanks for the detailed reproduction report! This also troubles me and should be the only major behavioral difference between our list implementation and common rich text editors.
