### ISSUE TITLE
Drag handle animation for database header

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4866]
We would like to add a new animation to the drag handle of the database header.

This is the demo for this animation
![demo](https://github.com/toeverything/blocksuite/assets/40333372/e91909ec-e323-4dee-8f5c-7024d37a91bd)

**Comment by doodlewind** [comment]
Does the drag handle already work for the database header? Haven't seen this kind of functionality yet.

**Comment by CatsJuice** [comment]
> Does the drag handle already work for the database header? Haven't seen this kind of functionality yet.

Working in #4871, there are still some interaction details to be discussed and confirmed.

**Comment by zzj3720** [comment]
Are there any other parts of this that need to be done? Can this be closed? @zanwei
