### ISSUE TITLE
​Add svg export

### ISSUE THREAD

**Issue by greedyhao** [toeverything/blocksuite#4868]
### Description

refer to https://github.com/toeverything/AFFiNE/issues/4427

quality of png is poor, can we add an option of export as svg file

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for the feedback, but I think neither the DOM nor the canvas renderer is capable of exporting content as SVG. More fine-grained needs (e.g., exporting at block level) for SVG exporting may be considered, but page level SVG exporting is a non-goal FTM.
