### ISSUE TITLE
Gif images cannot be imported

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4872]
![Image](https://github.com/toeverything/blocksuite/assets/142964904/0160dd88-d15b-4f4d-9e4e-39be16867c4c)

**Comment by fourdim** [comment]
![image](https://github.com/toeverything/blocksuite/assets/59462000/a6b30011-b1b2-4ba3-b9eb-517751a470d9)
Cannot reproduce either in the latest internal or playground.
