### ISSUE TITLE
Page jittering on adding new paragraph by enter

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#4886]
https://github.com/toeverything/blocksuite/assets/7312949/7d93ecdb-fb69-4cc7-9146-2d14b29ab8de

**Comment by Flrande** [comment]
Do you have a detailed reproduction path? I cannot reproduce it.

**Comment by zqran** [comment]
This is a style issue, the scroll bar width of `doc-viewport` is set in `Affine`.

Reproduction method: In Affine client, when the scroll bar of the page is displayed.

Related code:  https://github.com/toeverything/AFFiNE/blob/5f7f5b74ca6f235cf01fb0af811a05bb8f3cfe37/packages/component/src/theme/global.css#L220

**Comment by doodlewind** [comment]
Closing since this is the edge case related to scroll bar by design.
