### ISSUE TITLE
Table's checkbox can't add content in 0.8.0 stable

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#4893]

**Comment by Yuhang1015** [comment]
![Image](https://github.com/toeverything/blocksuite/assets/142964904/c0271702-ff66-422e-894d-ff73da84e5fc)

**Comment by Yuhang1015** [comment]
version: 0.8.0 Stable

**Comment by doodlewind** [comment]
Closing since the checkbox field is supposed to be holding checkbox only, instead of having rich text content.
