### ISSUE TITLE
Code block unexpected horizontal scrolling when click blank area on the side

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4903]
Code has incorrect indentation when closing code selection menu

https://github.com/toeverything/blocksuite/assets/40333372/bfc139d2-f999-4172-b7fa-ab71783e565d

**Comment by Flrande** [comment]
Here is a more simple reproduction.

https://github.com/toeverything/blocksuite/assets/50035259/f2dbe958-8b79-4eb9-ac59-8c7b4216179b

**Comment by zqran** [comment]
Just click outside the code-block to reproduce:

https://github.com/toeverything/blocksuite/assets/15389209/1a8579be-fdea-430d-892d-848a476c0bc7
