### ISSUE TITLE
Unable to use enter key in image caption

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4904]
Currently, the Enter key cannot be used in the caption of an image. Pressing the key will not have any response. 

The expected result is that if a line break is needed in the middle of the caption, a new text block will be created after the image, and the content after the cursor will be moved to the new text block. If a line break is needed at the end of the caption, a new blank text block will be created directly after the image.

https://github.com/toeverything/blocksuite/assets/22443345/92de8a74-9438-4273-b6f5-d1349b5f0013

**Comment by Flrande** [comment]
cc? @zqran
