### ISSUE TITLE
Attachment popup shadowed by database block

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4914]
![Image](https://github.com/toeverything/blocksuite/assets/142964904/da122ecf-2049-4bbf-a84e-4e47e8f2d15c)

When the attachment is close to the database, the "more" operation cannot be triggered because the attachment block layer is at the end.
Version: Stable 0.8.4 (draft)

**Comment by donteatfriedrice** [comment]
It seems that this issue cannot be reproduced in latest blocksuite playground.

https://github.com/toeverything/blocksuite/assets/99816898/909c02d8-3c90-418d-8499-cc13313cb953

**Comment by lawvs** [comment]
I believe this issue has been fixed.

<img width="395" alt="Screenshot 2023-10-26 at 18 09 45" src="https://github.com/toeverything/blocksuite/assets/18554747/8f382644-5fb0-44cd-a51d-a73609cc4c96">
