### ISSUE TITLE
The link page action offers pages that are on the trash in the list

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4924]
![Image](https://github.com/toeverything/blocksuite/assets/142964904/b7299ec1-4575-46b0-badd-e6184eaad68f)

When we add a link page, the article in the trash will also exist in the list.
the user's feedback: https://community.affine.pro/c/bug-reports/link-page-offers-deleted-pages
version: beta 0.9.0

**Comment by lawvs** [comment]
Duplicated of https://github.com/toeverything/blocksuite/issues/2592
