### ISSUE TITLE
Empty states of Database right panel

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4930]
Please refer [design](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=5090-16242&mode=design&t=3V1hl7djto6COaC9-4)

<img width="864" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/dcf21e8b-7330-44e6-adba-cabff65de960">

**Comment by doodlewind** [comment]
Tracked in #5385
