### ISSUE TITLE
Text exceeds the text box area

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4935]
When pasting a paragraph from an external source into Edgeless, the text overflows the text box area. However, by double-clicking the text, it will revert to the correct state

Please check to see if you can reproduce

<img width="562" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/bf8de87b-7e6f-46b5-9d8d-572070ceb25f">

**Comment by donteatfriedrice** [comment]
Sorry I could't reproduce it in the latest playground. Could you reproduce it in the latest blocksuite playground?

https://github.com/toeverything/blocksuite/assets/99816898/806015b6-5d08-4326-9612-37e4067a4046
