### ISSUE TITLE
Hold `shift` to select multiple items, then hold `alt` and drag to copy

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4938]
**Currently:** we can duplicate only **one** item by holding down `alt` and dragging to copy

https://github.com/toeverything/blocksuite/assets/40333372/d4310e8d-f848-4c4d-97d2-3a7bbcef5b96

**Should:** When we select multiple elements, we should be able to duplicate them by holding down `alt` and dragging

https://github.com/toeverything/blocksuite/assets/40333372/0920d6ac-9ded-497c-8595-102d61af88eb

**Comment by zanwei** [comment]
Probably we need to standardize the cursor for the different states both macOS and Windows in the future 

@hwangdev97

**Comment by donteatfriedrice** [comment]
We seem to have implemented holding shift to select multiple elements and holding alt to copy and paste multiple elements.


https://github.com/toeverything/blocksuite/assets/99816898/8d9242d0-bdba-494d-b48d-e6810b67b92d

**Comment by zanwei** [comment]
Going to close this issue since it has been implemented
