### ISSUE TITLE
Update kanban icon

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4946]
We would like have an update of size of '+' icon

Please refer icon button of [internal design](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%9B%9E-Design-System?type=design&node-id=750-11053&mode=design&t=jQr8qtSuaU7HCsdm-4)

<img width="538" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/8f090bc2-ceb3-4e67-b59e-3c8cbc0b92fd">

The title '+' icon requires 2 padding
<img width="1202" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/27ac2f5d-6a47-47ca-a61f-17f7112dece4">

**Comment by doodlewind** [comment]
Will be tracked in #5385
