### ISSUE TITLE
Update the default status when creating a Shape

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4960]
When selecting Shape as the element to be used in Edgeless, we need to keep it in the default `general` status, rather than the `scribbled` status

https://github.com/toeverything/blocksuite/assets/40333372/f4625d0d-0e6a-4f53-af0b-442ed8b69f7f

**Comment by donteatfriedrice** [comment]
@zanwei Do you mean set shape style to general type when using shape tool first time? I find that the latest codebase have implemented this function with pr #4877. 


https://github.com/toeverything/blocksuite/assets/99816898/e9587893-db18-4e2c-ad45-3e5987977490

**Comment by zanwei** [comment]
Correct. I'm going to close this issue since it has already been implemented
