### ISSUE TITLE
Unable to paste image cross multiple browser tabs

### ISSUE THREAD

**Issue by regischen** [toeverything/blocksuite#4967]
note: 
This is a global issue where only the ID information is included when copying and pasting images, without the actual image data. The image data itself is stored in indexdb. Since indexdb is not cross-origin, the image cannot be retrieved when pasting it across domains.

https://github.com/toeverything/blocksuite/assets/58546692/ea8601b1-c22a-43ab-b5db-14637cbffb30

**Comment by fourdim** [comment]
Closed by #5656.
