### ISSUE TITLE
Database hover animation curve

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4972]
We would like an update on the hover animation for the database

In principle, hover animations have both "**start animations**" and "**end animations**." We aim to keep them consistent here.

The parameters would be `0.42, 0, 1, 1 ` in `150ms`

![image 27](https://github.com/toeverything/blocksuite/assets/40333372/e977eb7b-384d-41c1-92a8-34f4fe6664d9)

**Use Case:**

This animation will be applied to

<img width="681" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/420da9e1-1ce9-429f-9406-901c517d76a9">

**Comment by AyushAgrawal-A2** [comment]
Hi @zanwei ,
Please clarify if animation is required on row operation icons as well ? These also show up on hover.

![scrnli_11_15_2023_1-21-44 PM](https://github.com/toeverything/blocksuite/assets/54364088/1cd05dc6-f7bf-4ef0-8699-2797ebdc6c21)

**Comment by zanwei** [comment]
Yes

**Comment by AyushAgrawal-A2** [comment]
@zanwei no problem, I have reverted hover animation on operation icons.
