### ISSUE TITLE
Issue with the z-index of Connector and Frame

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#4976]
Connector should be under the frame solid color

![image](https://github.com/toeverything/blocksuite/assets/40333372/3ef3e7a9-7bb6-47e1-bab8-23b64fcb1806)

**Comment by zanwei** [comment]
Going to close this issue since we‘ve internal discussion

**Comment by doodlewind** [comment]
@zanwei just saying that you can use the `close as not planned` button for such scenario :)
