### ISSUE TITLE
Press backspace in the start of first line

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#4984]
https://github.com/toeverything/blocksuite/assets/50035259/9e51e04d-052e-4ffc-905c-3a6c3a9b5bcb

I believe there have already been corresponding tests to verify this situation, but because there is no block related to `edgeless` in the test environment, it was not detected.

Should we perhaps raise the priority of #4952? Because later on, we may have more edgeless-related elements moved to the top layer. cc @doodlewind

**Comment by doodlewind** [comment]
> Should we perhaps raise the priority of #4952?

Makes sense, would be great if you can schedule this in your recent plan!
