### ISSUE TITLE
Copy and paste issue with bulleted list hierarchy

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4986]
When copying and pasting from one affine article into another, some content is automatically copied three times.

Original text:

![Image](https://github.com/toeverything/blocksuite/assets/142964904/93a964ee-7024-41a1-a3ce-b12ca70f2810)

After pasting: 
![Image](https://github.com/toeverything/blocksuite/assets/142964904/755fd5df-edf3-4480-bf20-0d54be3bf856)

**Comment by YanxinLu0122** [comment]
Update: 

The documents in our Insider adopt a bulleted list hierarchy (as shown in the picture), which has three levels, so after copying, there will be a problem of repeated results. This problem also exists when pasting on other platforms such as Feishu.

The current situation after copying and pasting the three hierarchical directories is as follows:
1. The content will appear twice when viewed as a whole.
2. In the second content, the third-level directory will appear twice more



https://github.com/toeverything/blocksuite/assets/144991896/d7aac653-ed86-4233-977d-375850ceae3e

**Comment by fourdim** [comment]
Depends on #5111.
