### ISSUE TITLE
After using shortcut keys to set headings, using the Enter key will clear the content

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#4987]
The following screen recording is the effect after using the setting Heading 1 in the Internal version.

https://github.com/toeverything/blocksuite/assets/22443345/bdf80e43-f7cf-4858-8c6b-c8c839d49203

**Comment by doodlewind** [comment]
Hope @lzlme can take a look while working on hotkey related improvements, thanks!
