### ISSUE TITLE
Content flickers during native selection across image

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4988]
![Image](https://github.com/toeverything/blocksuite/assets/142964904/a55295e0-25b9-4561-a5b1-cd204ebed224)

**Comment by fourdim** [comment]
Cannot select and scroll even there is no image present.

**Comment by doodlewind** [comment]
@fourdim any screen recording for reproduction? Not sure why I can't reproduce locally.

https://github.com/toeverything/blocksuite/assets/7312949/88316830-16b3-4a90-ad6b-9d2d9512a9b4

**Comment by fourdim** [comment]
https://github.com/toeverything/blocksuite/assets/59462000/b04a480c-108b-4ecd-addd-f2ea8aa74f01

**Comment by zhanghan19970306** [comment]
I also faced the same problem. There seems to be a conflict between text-selection and the autoScroll function.
