### ISSUE TITLE
Document crashes in insider & Beta when collaborating

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#4996]
When collaborating in insider and beta's Cloud workspace, I encountered two times document crashes, I don't know if it's because the collaboration time is too long or there are too many edits, but the page still can't display the content after refreshing several times.

![Image](https://github.com/toeverything/blocksuite/assets/144991896/3ce8a519-7cac-4503-b1a4-e9b7cb36a67d)

**Comment by doodlewind** [comment]
Closing as not reproduced.
