### ISSUE TITLE
When collaborating in page mode, when no one performs a select-all operation, all content is selected

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#4998]
As shown in the video, the text content appears to be all selected, and others cannot perform any operations on the text, but in fact no one operates to select all. This situation often disappears when the screen recording starts, so only the first few seconds are captured.

![Image](https://github.com/toeverything/blocksuite/assets/142964904/84bd3e13-4582-4401-aa69-877357874134)

**Comment by Flrande** [comment]
It is because `remote-selection` overlay text area which make cursor can not select text.
