### ISSUE TITLE
Performance regression in larget document

### ISSUE THREAD

**Issue by francisxihe** [toeverything/blocksuite#5001]
### What happened?

When the document content reaches 500-800 lines, affine becomes very sluggish

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by himself65** [comment]
Blocksuite issue, see demo: https://github.com/himself65/mini-affine

**Comment by fourdim** [comment]
#4381 Link it here.

**Comment by doodlewind** [comment]
This is a recent regression after `v0.8.0`, using https://blocksuite-toeverything.vercel.app/starter/?init=heavy can reproduce this, so there's no need to use new integration environment. For the `v0.8.0` tag, this performance issue doesn't exist.

**Comment by francisxihe** [comment]
The sluggishness occurs after importing a Markdown file.It doesn't sluggishness when opening it directly.
