### ISSUE TITLE
Multiple slash menu list items could be activated at the same time

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#5005]
![shot-2023-10-13-11 05 40](https://github.com/toeverything/blocksuite/assets/24713927/2c340cd8-474d-4e7d-be1b-fa0391d28c45)

When hovering over an element with the mouse, its state coexists with the state activated by keyboard up/down navigation. 

I believe a more logical solution would be that when navigating with the keyboard, only the keyboard behavior is activated.

**Comment by Flrande** [comment]
cc? @lzlme
