### ISSUE TITLE
Page crash after drag the graph in whiteboard​

### ISSUE THREAD

**Issue by Zheaoli** [toeverything/blocksuite#5007]
### What happened?

https://github.com/toeverything/AFFiNE/assets/7054676/8617a0a3-9a76-4222-a0f0-a6cdcaae2002

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Is this error page a fresh one? I can't reproduce in https://insider.affine.pro/ and latest [internal release](https://github.com/toeverything/AFFiNE-Releases/releases).

**Comment by doodlewind** [comment]
This is not reproduced in recent version, and we've also shipped https://github.com/toeverything/blocksuite/pull/5272 to optimize the behavior in content dragging on whiteboard.
