### ISSUE TITLE
Inconsistent ​database date format in editing state

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/blocksuite#5024]
### What happened?

![Screenshot_41](https://github.com/toeverything/AFFiNE/assets/117591520/d5b22f33-e635-4703-be75-84c3b6746815)

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
@zzj3720 please take a look
