### ISSUE TITLE
Edgeless zooming not work ​when hovering over database

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/blocksuite#5025]
### What happened?

If your mouse is over a database in edgeless mode, zooming in/out is not working unless you're editing a line.

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
@zzj3720 please take a look

**Comment by kemalakcc** [comment]
Yeah sorry I just missed that OS part :/
