### ISSUE TITLE
When copying several paragraphs of text and paste them, the line breaks are lost

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5051]
![Image](https://github.com/toeverything/blocksuite/assets/142964904/963a691c-473a-4538-b6fe-b09001a24da9)

Version: insider / 0.9.0 Beta

Detailed description: When copying several paragraphs of text with blank lines from other places other than affine (such as Feishu), the blank lines disappear after pasting.

The current inference is that when there is a bullet point in the first line and there is no bullet point in the second line, pasting it will become the same bullet point.

**Comment by doodlewind** [comment]
Closing as not reproduced in latest playground.

https://github.com/toeverything/blocksuite/assets/7312949/76e57890-e2ce-4f3b-80b8-4fee1bf54b65
