### ISSUE TITLE
Support doc outline

### ISSUE THREAD

**Issue by NoobJohn** [toeverything/blocksuite#5052]
<img width="303" alt="image" src="https://github.com/toeverything/blocksuite/assets/31058929/78aff858-aab3-43d6-b1f1-65eb907b3d60">

**Comment by doodlewind** [comment]
This is being implemented by @donteatfriedrice and hopefully will be landed soon :D

**Comment by doodlewind** [comment]
Closed by https://github.com/toeverything/blocksuite/pull/5539
