### ISSUE TITLE
Support selecting and deleting multiple rows in database

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#5059]

**Comment by doodlewind** [comment]
If I understand it right, currently it's indeed not very convenient to do multiple selection with row-level selection or drag handle:

<img width="875" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/d6cf1cf9-e38f-4528-85bb-dd229b30bbb8">

**Comment by zzj3720** [comment]
You can now drag and drop to select a area, then press esc to select multiple rows, then backspace to delete all rows.
like this 

https://github.com/toeverything/blocksuite/assets/17165520/22c13d47-5028-417a-87cd-38d7a0f91044

However, Currently you can't select specific rows at intervals.
![image](https://github.com/toeverything/blocksuite/assets/17165520/70a39780-b8f1-47d5-99fe-1549d6ed8e06)

We will support this in the future.

**Comment by doodlewind** [comment]
Closing since the feature range-selecting multiple rows has been landed.
