### ISSUE TITLE
Incorrect canvas text resizing ratio

### ISSUE THREAD

**Issue by kemalakcc** [toeverything/blocksuite#5061]
### What happened?

Here is a gif from text resizing

![main_large (1)](https://github.com/toeverything/blocksuite/assets/7312949/dbdc12e8-53f0-441a-a4c0-6077b3696962)

it seems it's resizing text with delta y positions, and acting weird with delta x positions

### Distribution version

Windows x64

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Require @donteatfriedrice to verify if this is already fixed in upstream 🙏

**Comment by donteatfriedrice** [comment]
> Require @donteatfriedrice to verify if this is already fixed in upstream 🙏

Is this as expected?

https://github.com/toeverything/blocksuite/assets/99816898/5f0246ae-b3b5-4b55-9425-31274517b27e

**Comment by doodlewind** [comment]
This is working as expected in playground. Closing as not reproduced - for AFFiNE updates, please kindly wait for our next release.
