### ISSUE TITLE
The check status of todo lost after indent

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#507]
https://user-images.githubusercontent.com/18554747/210180442-b2aad707-5e91-4666-839c-40a67462c9a9.mov

This issue arises because, upon indenting, not all properties were updated to the new block.

We should update the block parent instead of removing and adding a new block.

The relevant code is here
https://github.com/toeverything/blocksuite/blob/2248eb8338392e690ecf02f822044a0ec575be27/packages/blocks/src/__internal__/rich-text/rich-text-operations.ts#L123-L139

https://github.com/toeverything/blocksuite/blob/2248eb8338392e690ecf02f822044a0ec575be27/packages/blocks/src/__internal__/rich-text/rich-text-operations.ts#L198-L207

And the corresponding tests are ready
https://github.com/toeverything/blocksuite/blob/2248eb8338392e690ecf02f822044a0ec575be27/tests/list.spec.ts#L288-L337

**Comment by Flrande** [comment]
Please assign me.
