### ISSUE TITLE
Unable to view SVG images after upload

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5089]
The uploader can see the png/svg he uploaded, but the collaborator on the other side can only see the empty frame.

![Image](https://github.com/toeverything/blocksuite/assets/142964904/eae6489c-9082-4c34-a32e-6e3a3a24cb2f)

**Comment by YanxinLu0122** [comment]
No just collaborator, all of the users in the page cannot see the svg images after uploaded.



https://github.com/toeverything/blocksuite/assets/144991896/1c66cd02-176b-49c2-b0b0-1f2facd232af

**Comment by Yuhang1015** [comment]
still exist in 0.10.0 beta internal (https://github.com/toeverything/AFFiNE-Releases/releases/tag/0.0.0-internal.20231102154034-fb0aaab)


![Image](https://github.com/toeverything/blocksuite/assets/142964904/a5a7952a-e194-43dc-b85a-450bddf73b0e)

**Comment by doodlewind** [comment]
Ping @Flrande to confirm if this could be reproduced 👀

**Comment by Flrande** [comment]
I can only reproduce the issue successfully on the client, it works normally on the browser. Upon checking, I found that the indexedDB on the client has stored the svg data correctly. I suspect that the inability to display the image is related to the unique security restrictions on the client. cc @pengx17

**Comment by lawvs** [comment]
This issue is also caused by https://github.com/toeverything/AFFiNE/issues/3245

The client identifies the type of the SVG blob as `application/octet-stream`, which is causing the error.

**Comment by doodlewind** [comment]
Closed by https://github.com/toeverything/AFFiNE/pull/4845
