### ISSUE TITLE
Add block level readonly getter and override property in the BlockElement 

### ISSUE THREAD

**Issue by doouding** [toeverything/blocksuite#5090]
In the foreseeable future, there might be lots of features that require "synced blocks" ability. In such cases, a block must be rendered in read-only mode, preventing the widgets from accidentally modifying the synced block.

By default, the `BlockElement` gets its read-only status from the page:

```JavaScript
export class BlockElement {
    // omit existing part .....
    get readonly() {
        return this.page.readonly;
    }
}
```

But we can pass an `overrideReadonly` property to override read-only status even if page is editable.
```JavaScript
export class BlockElement {
    // omit existing part .....

    @property({ attribute: false })
    overrideReadonly!: boolean;

    get readonly() {
        return this.overrideReadonly || this.page.readonly;
    }
}
```

That requires some modification of `renderModel` method in `BlockSuiteRoot`:
```JavaScript
export class BlockSuitRoot {
    renderModel = (model: BaseBlockModel, overrideReadonly?: boolean) => {
        // pass overrideReadonly property to BlockElement
    }
}
```

@Saul-Mirone @doodlewind

**Comment by doodlewind** [comment]
Thanks for the design! But for #5013, the better workaround we discussed should be updating drag handle to avoid selection issues - which aligns with our widget policy. As for model layer infra, let's wait until more requirements shared this functionality.
