### ISSUE TITLE
Can not deserialize undefined when deleting blocks in edgeless.

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#5094]
![image](https://github.com/toeverything/blocksuite/assets/59462000/9445a392-74f6-4278-b3d1-0f88c2ca205a)

https://github.com/toeverything/blocksuite/blob/6efd41f2465d8b79dc895c0b23928c8005e60f56/packages/blocks/src/page-block/edgeless/components/auto-complete/edgeless-auto-complete.ts#L422

**Comment by doodlewind** [comment]
How to reproduce this? Deleting and undoing note block works well in latest playground FTM.

**Comment by fourdim** [comment]
Unable to find a way to reproduce. This error does happen in the latest playground.

**Comment by doodlewind** [comment]
Closing as not reproduced.
