### ISSUE TITLE
Perf metrics suite

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#5095]
See the great [figma post](https://www.figma.com/blog/keeping-figma-fast/) about how the perf metrics system could be maintained within a single machine that lasts for years. With playwright, it would be ideal to setup this kind of perf metrics (editing operations using heavy content as test cases) a standalone repo and get regular reports.

<img width="751" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/9d357fb5-c17e-4cfe-822a-df4ac80c3519">

**Comment by regischen** [comment]
notes:
Areas for improvement include the `points` attribute in `brush-element`; when using the native array type, the drawing process updates entirely, leading to a rapid increase in size of encodeStateAsUpdate(doc). When using the `Y.Array` type, it updates incrementally. }
However, the question remains: how significant is the impact of the size of encodeStateAsUpdate(doc) on performance?

**Comment by regischen** [comment]
note:
For the `group-element`, when the `children` field is of the `YMap` type, it can be updated incrementally. However, is a plain-object more efficient in terms of encoding?
