### ISSUE TITLE
Delete at the start of second note will jump to title

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#5100]
https://github.com/toeverything/blocksuite/assets/50035259/e0674a6d-dcd3-43e2-938c-ed12190413dc

**Comment by doodlewind** [comment]
Does this have same root cause with #5096?

**Comment by Flrande** [comment]
> Does this have same root cause with #5096?

It's a bit similar, I think their reason is that they didn't consider multiple notes logically.
