### ISSUE TITLE
Page in local workspace cannot be opened

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#5116]
https://github.com/toeverything/blocksuite/assets/144991896/76494c9c-77c2-40e1-9eef-8c6b3240d4e9

```[tasklist]
### Tasks
```

**Comment by doodlewind** [comment]
Closing as not reproduced in latest internal.

**Comment by YanxinLu0122** [comment]
still exist

https://github.com/toeverything/blocksuite/assets/144991896/2e2d40d0-ff1e-49b5-abdb-2da7deb8dbac

**Comment by joooye34** [comment]
The preloading page missing `affine:page` and `affine:surface` block, need script to fix it.
