### ISSUE TITLE
Support Ctrl + Y as a shortcut key for Redo in Windows

### ISSUE THREAD

**Issue by TuxedoCode** [toeverything/blocksuite#5120]
### Describe the bug

The Ctrl+Y shortcut is not working for undo actions in desktop client

### To Reproduce

1.  Write some text and use the Ctrl+Z shortcut
2.  Then try using Ctrl+Y shortcut

### Platform
Windows 10

### Distribution version

Windows x64

### Anything else?

Also the zoom-in shortcut is not working on the desktop client Ctrl+ +

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
The current UNDO and Redo shortcut keys are CTRL + Z and Ctrl + Shift + Z. We will consider support Ctrl + Y in the future
