### ISSUE TITLE
Improve model class for debugging

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#5128]
Currently, some block models are still based on the BaseBlockModel. When we debug the code, it becomes inconvenient to distinguish between these two different types of blocks. We have to open and check the type field, which can be cumbersome.

<img width="600" alt="image" src="https://github.com/toeverything/blocksuite/assets/50035259/3692b621-9a8d-42e7-a975-83fbd4fcf4f9">
<img width="586" alt="image" src="https://github.com/toeverything/blocksuite/assets/50035259/c5b5940a-796d-441e-8bf5-fe0f794aa998">

**Comment by lawvs** [comment]
What browser are you using? It should show the `model.flavour` in the console. Please feel free to make any necessary updates to the code.
 
<img width="834" alt="Screenshot 2023-10-26 at 16 14 00" src="https://github.com/toeverything/blocksuite/assets/18554747/b28e2670-0131-4946-89b2-c3eeb0dffba5">

https://github.com/toeverything/blocksuite/blob/e49f65cdca34fc59ee1d0961dd6e19ab854c6ac4/packages/store/src/utils/formatter.ts#L36-L51

**Comment by Flrande** [comment]
> What browser are you using? The `model.flavour` should be shown in the console. Please feel free to make any necessary updates to the code.

Edge🫣

**Comment by doodlewind** [comment]
Closing since the debug formatter has already been implemented.
