### ISSUE TITLE
affine-page-meta-data should be set as a configuration item

### ISSUE THREAD

**Issue by losingle** [toeverything/blocksuite#5145]
these should not be mandatory

https://github.com/toeverything/blocksuite/blob/f8b04fc94f24a44db581bec3883f2f785e36a704/packages/blocks/src/page-block/doc/doc-page-block.ts#L600C14-L600C14

**Comment by doodlewind** [comment]
@Flrande how about making it a widget? In this way community user should be able to compose the features via [presets](https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/_presets/index.ts). cc @zzj3720

**Comment by Flrande** [comment]
> @Flrande how about making it a widget? In this way community user should be able to compose the features via [presets](https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/_presets/index.ts). cc @zzj3720

Yes, it should be a widget.

**Comment by losingle** [comment]
I believe this should be a plugin, because as an editor, title, tag_list, and content are different fields with different logic. 
Therefore, it should be made into a plugin, allowing users to implement different interaction logic in the backend.

**Comment by doodlewind** [comment]
@losingle thanks for the advice, we are indeed working towards a comprehensive block extension system. In the draft design, the panel of page meta data should be block-specific custom UI that could be defined as "widgets" (https://blocksuite.affine.pro/block-spec-apis.html). You can compose (and even dynamically adding) blocks and there widgets, see https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/_presets/index.ts#L36-L63 for the current setup. This should be happening progressively, hope you can stay tuned!

**Comment by losingle** [comment]
My understanding is that widgets should only participate as extensions within the editor area. 
Tags and titles of the document should not fall under the editor's purview. 
However, your design seems to encompass the entire document, treating meta information as a block.
I previously misunderstood, so I couldn't grasp why you would include tags and titles.
That's awesome!
