### ISSUE TITLE
Deleting images will never trigger `storage.crud.delete`

### ISSUE THREAD

**Issue by forehalo** [toeverything/blocksuite#5170]
## Step to reproduce

open the playground and add a custom blob storage in console by:

```js
const map = new Map();

// how we know this script works
// if you delete the `get` method in crud, and paste a picture in the doc
// the pic will be shown `broken`.
workspace._storages.push({
  crud: {
    get: (k) => Promise.resolve(map.get(k)),
    set: (k, v) => { map.set(k, v); return Promise.resolve() },
    delete: (k) => { console.log('delete') },
  }
})
```

and whenever you paste/delete a picture, you will only see get/set methods get called, and no 'delete' printed in the console.

https://github.com/toeverything/blocksuite/assets/8281226/573e1213-8e85-49ce-8330-1067274291e7

**Comment by lawvs** [comment]
The image or attachment may be duplicated multiple times, so it's unreliable to directly delete the blob in storage when deleting an image.

It's recommended to implement a new resource manager to handle unused blobs.
