### ISSUE TITLE
Text highlight version2

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#5177]
Text highlight V2 increased highlight text function, V1 only supports highlight text background. 
Here we added 7 text highlight background colors,
The original text highlight colors have been designed to change the text not the background.
<img width="1244" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/1a543019-89fe-4145-bb40-6ce7b2fca143">

[Check design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%93%8C-AFFiNE-2023?type=design&node-id=8020-148018&mode=design&t=3raq7RpjuHQ6QWTr-4)

**Comment by AyushAgrawal-A2** [comment]
@Flrande @doodlewind 
The theme changes required for this issue were implmented in PR https://github.com/toeverything/design/pull/100
and got reverted back in PR https://github.com/toeverything/design/pull/104

Can we again implement the theme changes required for this issue now or the reason for PR revert still persists ?

**Comment by fourdim** [comment]
That commit is reverted because of #5267.
That is, until we have a better migration for this breaking change, we cannot introduce it back.
Of course you can reimplement it. I will merge it and release it for you.

**Comment by Flrande** [comment]
> That commit is reverted because of #5267. That is, until we have a better migration for this breaking change, we cannot introduce it back. Of course you can reimplement it. I will merge it and release it for you.

Can we make the theme forward compatible?

**Comment by fourdim** [comment]
> Can we make the theme forward compatible?

Probably not. They've changed `textHighlight`s to `textHighlightBackground`s and add new `textHighlight`s hoping that it will be used in the new feature: text color. This is definitely a breaking change in both forward and backward.

**Comment by Flrande** [comment]
I will communicate with the design team about this. It seems that this breaking change has hindered the implementation of this feature.
