### ISSUE TITLE
Image loading progress is missing​

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#5179]
### What happened?

Please [check the design](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?type=design&node-id=11663-36352&mode=design&t=y82dkj4h3XqMij20-4)
show all single loading when dragging over 1 image
<img width="831" alt="image" src="https://github.com/toeverything/AFFiNE/assets/110808979/6faf3e87-16fa-4e60-b95f-2ae2f18af839">

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by AyushAgrawal-A2** [comment]
Hi @Svaney-ssman ,
Please clarify if the task here is to have a dedicated loading and error card view for images, i.e. 

Current :-
![scrnli_11_17_2023_11-17-36 PM](https://github.com/toeverything/blocksuite/assets/54364088/a4e88f01-807b-4c95-82e4-d3c8d0198d1f)
![scrnli_11_17_2023_11-18-38 PM](https://github.com/toeverything/blocksuite/assets/54364088/0122341b-c217-44fb-bf28-6629c6a971c4)

Change to (for images) :-
![scrnli_11_17_2023_11-20-33 PM](https://github.com/toeverything/blocksuite/assets/54364088/0e58a4d8-239a-443d-bf7d-332b58cb447b)
![scrnli_11_17_2023_11-21-11 PM](https://github.com/toeverything/blocksuite/assets/54364088/8c9003e6-5343-41fd-aec2-63beb4185bb8)

I am not able to understand the meaning of `show all single loading when dragging over 1 image`
