### ISSUE TITLE
Page mode cannot wrap after inserting frame or group form whiteboard

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#5184]
especially with database below

https://github.com/toeverything/blocksuite/assets/144991896/b3e28ce0-a91a-4591-b353-7a40a2a46986

**Comment by houjoe0829** [comment]
I can also reproduce this issue, and not only is line break not possible, but it is also not possible to insert any new blocks above or below this frame using Block Hub.

**Comment by YanxinLu0122** [comment]
still exist

**Comment by doodlewind** [comment]
@YanxinLu0122 please wait for bumping BlockSuite.
