### ISSUE TITLE
Optimize edgeless performance bottlenecks

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#5190]
Before landing the perf testing suite in #5095, we already have located several major perf bottlenecks:

* Too much update size in batch dragging.
* Too much update size in shape drawing.

The optimization should be on plan.

**Comment by doouding** [comment]
To fix this issue, we need to introduce the "temporary state". When the user presses the mouse, everything they do is stored in a temporary state. Once the user releases the mouse, that temporary state will be applied to Yjs. This should significantly reduce the size of the updates.

**Comment by doouding** [comment]
Temporary state can also be applied to Yjs as needed at regular intervals.

**Comment by doodlewind** [comment]
> To fix this issue, we need to introduce the "temporary state". When the user presses the mouse, everything they do is stored in a temporary state. Once the user releases the mouse, that temporary state will be applied to Yjs. This should significantly reduce the size of the updates.

We already have a concept named `LocalRecord` to address this.
