### ISSUE TITLE
Chinese character questionmark ？will trigger the slash menu.

### ISSUE THREAD

**Issue by fourdim** [toeverything/blocksuite#5197]

**Comment by Flrande** [comment]
Which character? Can you share screen record?

**Comment by fourdim** [comment]
https://github.com/toeverything/blocksuite/assets/59462000/1f8f4b14-f235-45c5-8ad0-55aa3b75fac0

**Comment by lawvs** [comment]
It seems weird. Could you please log the keyboard event? It is `{ key: '?', code: 'Slash' }` on my machine.

Related code:

https://github.com/toeverything/blocksuite/blob/9a92e4650d734d1cf05b6d2f66f4bbbbb5411c4a/packages/blocks/src/_common/widgets/slash-menu/index.ts#L82-L103


> ## KeyboardEvent: key property
> The [KeyboardEvent](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent) interface's key read-only property returns the value of the key pressed by the user, taking into consideration the state of modifier keys such as Shift as well as the keyboard locale and layout.

> ## KeyboardEvent: code property
> The `KeyboardEvent.code` property represents a physical key on the keyboard (as opposed to the character generated by pressing the key). In other words, this property returns a value that isn't altered by keyboard layout or the state of the modifier keys.

**Comment by fourdim** [comment]
Chinese character ？:
![image](https://github.com/toeverything/blocksuite/assets/59462000/528f1595-9a3b-4f4b-92cd-c91827bf4689)
![image](https://github.com/toeverything/blocksuite/assets/59462000/5cf3c263-1d10-4e8c-8ae9-d4fec3739fc9)
English character ?:
![image](https://github.com/toeverything/blocksuite/assets/59462000/9af32291-ab17-49ee-bb8a-7b25b96dd51a)
![image](https://github.com/toeverything/blocksuite/assets/59462000/98c6c1e0-3a2a-4edc-aa67-d95642ab3237)

**Comment by lawvs** [comment]
Thank you very much for your detailed report. I believe this issue is related to the IME, and I have already submitted a fix request.
