### ISSUE TITLE
Collaboration not work in local enviroment

### ISSUE THREAD

**Issue by regischen** [toeverything/blocksuite#5201]
seems `generateRoomId` is broken
<img width="965" alt="image" src="https://github.com/toeverything/blocksuite/assets/58546692/647995ce-a791-4a1d-8f56-1939e71e946f">

**Comment by doodlewind** [comment]
@doouding I think here we should use the prod environment rather than local worker by default. But you can add a comment in code to quickly switch to using your local worker.

**Comment by doouding** [comment]
> @doouding I think here we should use the prod environment rather than local worker by default. But you can add a comment in code to quickly switch to using your local worker.

That would make sense.

**Comment by doouding** [comment]
Closed by #5229
