### ISSUE TITLE
When canvas text connected by connector and mounted, the connector would poke in text editor

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#5208]
Should we add padding between text element and connector endpoint?

https://github.com/toeverything/blocksuite/assets/99816898/1703d19a-aef2-439a-b67a-1fae97ccf512

For example, in tldraw, the connector would not connect to text directly, there is a gap:

https://github.com/toeverything/blocksuite/assets/99816898/1289e0e4-9493-481b-abdf-c684b67e1d6d

**Comment by doodlewind** [comment]
The gap looks better, cc @hwangdev97 to see if we have corresponding design.

**Comment by doodlewind** [comment]
Closing since this works as expected, and adjusting the text width horizontally greatly improves the usability. Hopefully we'll improve the usability of text resizing in the next iteration.
