### ISSUE TITLE
Add session memory for attribute settings of whiteboard objects

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#5211]
**Goal**：
Minimize the wastage of users' energy on repetitive settings when creating new objects on the whiteboard.

**Current**：
- Not all whiteboard objects have remembered attribute settings, such as Connector, Note, and Frame, which require modification every time they are used.
- The duration for recording attribute settings is too long. Objects that support attribute setting memory will still retain their settings when the page is closed and reopened.

**Expected effect**:
- Set opening and closing a page as one session.
- Within a session, the attribute settings of the previous object will be recorded. When creating new objects of the same type, the previously set attribute settings will be applied. After closing the page, the attribute settings will be restored to their default values.

In the future, we will consider adding preferential attribute settings for various objects in the Settings.

**Comment by regischen** [comment]
Edgeless is set to undergo a minor reorganization. 
There's currently a shortfall in the essential infrastructure needed for this task. As soon as these foundational elements are in place, the task will be promptly undertaken。
