### ISSUE TITLE
Copy and paste a frame in edgeless not behave as expected

### ISSUE THREAD

**Issue by CatsJuice** [toeverything/blocksuite#5228]
**Steps to reproduction:**
1. Create 2 rects `A` and `B`
2. Connect `A` with `B`
3. Create a frame from toolbar that wraps `A` and `B`
4. Copy frame with shortcut `⌘ + C`
5. Paste with shortcut `⌘ + V`
6. Drag immediately

https://github.com/toeverything/blocksuite/assets/39363750/d1f4cb2d-d7d5-459e-927d-84141051735e

**Info**
- AFFiNE `Version 0.9.0-beta.3 (0.9.0-beta.3)`

**Comment by regischen** [comment]
It's by design.
because the content of frame is dynamically calculated, when drag the frame, all elements in frame will be dragged

**Comment by doodlewind** [comment]
@regischen I think here we need to avoid the overlap with the newly pasted frame.
