### ISSUE TITLE
Optimize the snapping effect of Connectors on the whiteboard.

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#5248]
1. The default display of the snapping area dots is too small and needs to be enlarged.
2. The snapping areas and strength are hardly noticeable, and we can refer to the effects in FigJam.

https://github.com/toeverything/blocksuite/assets/22443345/36d68625-8216-4b29-8bbe-d9cdcdf66e08

**Comment by doodlewind** [comment]
Already tracked in #5183
