### ISSUE TITLE
Something wrong with the highlight color

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#5267]
Pink cannot be drawn, other colors are in dark mode

https://github.com/toeverything/blocksuite/assets/144991896/6edbc684-cc28-4452-a699-da04a532ed5b

**Comment by fourdim** [comment]
https://github.com/toeverything/design/commit/03de20ac36b651dd2187e2a5fcbbe4e5e71c9514
Pink is now replaced by red. We might need some migration here.

**Comment by fourdim** [comment]
https://github.com/toeverything/blocksuite/pull/5270 as temporary measure.

**Comment by doodlewind** [comment]
Closed by https://github.com/toeverything/AFFiNE/pull/4904
