### ISSUE TITLE
After deleting a frame, the presentation will still display the deleted frame

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5284]
version：insider /  0.10.0 beta(11.10)

In the following video, four frames are selected in sequence, and then one of them (frame3) is deleted. However, during the presentation, the deleted frame3 will still be displayed.

![Image](https://github.com/toeverything/blocksuite/assets/142964904/18dc2751-73db-4643-a4d4-e1f90fa9fc6c)

**Comment by YanxinLu0122** [comment]
still exist


https://github.com/toeverything/blocksuite/assets/144991896/834e1a3f-f28f-4b69-80eb-8335825c6cdb
