### ISSUE TITLE
Should correct the missing  image address in "package/docs"

### ISSUE THREAD

**Issue by water-in-stone** [toeverything/blocksuite#5291]
1. The picture named "unidirectional-data-flow", required in "https://github.com/toeverything/blocksuite/blob/master/packages/docs/selection-api.md", is missing correct address.
2. The picture named "unidirectional data flow", required in https://github.com/toeverything/blocksuite/blob/master/packages/docs/rich-text-orchestration.md, is missing correct address.

**Comment by doodlewind** [comment]
Closing since these are doc indeed.
