### ISSUE TITLE
Importing markdown files doesn't update the `name` in `PageMeta` and `WorkspaceMeta` correctly

### ISSUE THREAD

**Issue by hyf0** [toeverything/blocksuite#5296]
I'm digging into https://github.com/toeverything/AFFiNE/issues/4906.

And found the cause is

1.  Here create an anonymous page for importing a markdown file.

https://github.com/toeverything/blocksuite/blob/ac6d17102bd630571add91be79ec70bf8a14ff8c/packages/blocks/src/_common/widgets/linked-page/import-page/import-page.ts#L38

2. Here forgot to update `name` in `PageMeta`

https://github.com/toeverything/blocksuite/blob/ac6d17102bd630571add91be79ec70bf8a14ff8c/packages/blocks/src/_legacy/content-parser/index.ts#L640-L642

https://github.com/toeverything/blocksuite/blob/ac6d17102bd630571add91be79ec70bf8a14ff8c/packages/blocks/src/_legacy/content-parser/index.ts#L991-L999

**Comment by hyf0** [comment]
I intend to contribute and fix this issue.

I was thinking adding a line code to extract the title from the html info/`pageMetaData `.

https://github.com/toeverything/blocksuite/blob/ac6d17102bd630571add91be79ec70bf8a14ff8c/packages/blocks/src/_legacy/content-parser/index.ts#L983-L999

But I notice that, after I refresh affine, the page in the list would have a correct name. **I'm not sure weather this `name` is the same as the name I plan to get from the html info.** If not, this might cause another inconsistency.

**Comment by lawvs** [comment]
I think the reason why the page can display the correct title after refreshing lies in the following code:

https://github.com/toeverything/blocksuite/blob/4e6364e95700764ec2e68750e2308488b5a7cb98/packages/blocks/src/page-block/page-model.ts#L18-L20
