### ISSUE TITLE
Missing slot event for local `xywh` update

### ISSUE THREAD

**Issue by regischen** [toeverything/blocksuite#5305]
Due to the current updates of `xywh` being processed through local update and not updating the `YModel`, the previous implementation that relied on `yBlockupdate` slots has become ineffective.

currently found:
1. The component toolbar's position is not updating promptly.
2. The auto line's position is not updating promptly.

https://github.com/toeverything/blocksuite/assets/58546692/a8f84e1c-faca-4bb7-8145-b0bed245b405

**Comment by doouding** [comment]
The `edgeless-page-component` already has a slot called `elementSizeUpdated`; modifying the local record will also trigger the slot. This should be sufficient for most scenarios.
