### ISSUE TITLE
Unable to open link page entry from slash menu

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#5306]
The link page cannot be connected and will become @

https://github.com/toeverything/blocksuite/assets/144991896/f17eb3f6-74da-4c77-b499-4acedd5b3307

**Comment by doodlewind** [comment]
Reproduced, @YanxinLu0122 would be great if the reproduction could be as short as possible:

https://github.com/toeverything/blocksuite/assets/7312949/dcfd0698-168e-4822-a0f2-2da3b34a9b1c

cc @Flrande since this seems to related to missing widgets.

**Comment by doodlewind** [comment]
This is also reproduced in doc mode
