### ISSUE TITLE
 Images on Edgeless should support aspect ratio adjustment.

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#5309]
![shot-2023-11-13-12 28 22](https://github.com/toeverything/blocksuite/assets/24713927/5bce14c1-c465-42fc-a4b2-e81fe8e1ed62)
 After adjusting the group left and right, the aspect ratio of the image display will change, and I think this is expected. 

However, the image itself cannot be proportionally adjusted by moving it up, down, left, or right, I believe that images on Edgeless should support aspect ratio adjustment.

**Comment by doodlewind** [comment]
So I think the image resizing here should be under fixed aspect ratio?

**Comment by hwangdev97** [comment]
I believe that at this stage, **it should be consistent with the behavior within the group.**

Later, we can add preference settings for the image to cater to different image usage scenarios.

For example, when used as a frame background, I want the image to fill up the width and be cropped top and bottom. In some scenarios similar to inserting elements, I might want it to be stretched.

**Comment by hwangdev97** [comment]
After discussion, we believe that when modifying group scaling, the behavior of the image should be under fixed aspect ratio.
