### ISSUE TITLE
Edgeless Toolbar Update

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#5313]
We would like to have a feature update for Edgeless Toolbar, please refer [design](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?type=design&node-id=13008-29020&mode=design&t=si6rvpKa7FN3MaFQ-4)
<img width="986" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/f5ab22c8-0baa-401f-913e-8d3d30604188">

### Update Details

**1. Font Style**
We plan to add 6 font families to enrich the diversity of Edgeless. Additionally, the fonts of the current versions of **General** and **Scribble** will use their own names, which are **Inter(General)** and **Kalam(Scribble)**

It should be noted that when users switch fonts, the `Aa` in the Toolbar will change according to the style of the font.

<img width="709" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/e42a85ed-3ad4-4805-b083-2acfdbd9546d">

**2. Font Size**
We have decided to adopt a method of directly selecting numerical values for adjusting font size. Please note that in the current version, the font size will not change when users input a value greater than `200`. However, the value will increase with the extent of dragging. Therefore, please remove this restriction, but limit the maximum font size input by users to not exceed `9999`.
<img width="664" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/9a55c875-4fc6-45ad-a444-a5c76075ed0b">
<img width="904" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/aac9bfbc-c2e4-4dae-b3b2-07d70eb4885e">

**3. Font Weight**
In the new version, we will allow users to choose different `font-weight`. However, please note that we will limit the number of `font-weight`. Currently, each font will have a maximum of three weights and a minimum of one weight. 

- Please note that if the font has only one font-weight, the dropdown menu will be **disabled**.
- Please be aware that the names of the font-weights for each font may vary (some might be **Light, Regular, Medium**, while others could be **Regular, Medium, SemiBold**). **The specific names should be based on the font files provided by the designer.**

<img width="807" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/7e3f105f-d2b1-4857-adef-4e01419124d1">
<img width="916" alt="image" src="https://github.com/toeverything/blocksuite/assets/40333372/87b4a901-2745-4038-a2e0-f923461ed833">

[Font Resources.zip](https://github.com/toeverything/blocksuite/files/13333180/Font.Resources.zip)

**Comment by hwangdev97** [comment]
cc @Flrande and @doodlewind

**Comment by oytuntez** [comment]
If this text element could be inline formatted just like the Note block, that would be amazing.

**Comment by zanwei** [comment]
> If this text element could be inline formatted just like the Note block, that would be amazing.

Yes, we're working on it :)

**Comment by oytuntez** [comment]
That's great @zanwei! Is there a PR or branch I can test it out? 

It looks like I will need to fork to bring some fixes and features to Blocksuite, so I will already have my local environment set up for your tests etc.

**Comment by oytuntez** [comment]
@zanwei  I am currently editing the Note block to make it look like the EdgelessText element. Should I pursue this path, or will we get this inline formatting feature on EdgelessText soon?

**Comment by zanwei** [comment]
> @zanwei I am currently editing the Note block to make it look like the EdgelessText element. Should I pursue this path, or will we get this inline formatting feature on EdgelessText soon?

hi @oytuntez we actually finished the development of this feature, however we still need more time to testing. You could try when it out

**Comment by oytuntez** [comment]
Perfect @zanwei, thank you! Looking forward to testing it.
