### ISSUE TITLE
There are unwanted spaces between ordinals and dot (period) in numbered lists

### ISSUE THREAD

**Issue by andyjessop** [toeverything/blocksuite#5327]
<img width="218" alt="Screenshot 2023-11-14 at 14 23 35" src="https://github.com/toeverything/blocksuite/assets/1304307/2c461818-83e8-4672-b937-c869d94dd964">

The above screenshot is taken from usage of the `<simple-affine-editor></simple-affine-editor>` element.

There should be no space, i.e. it should be:
```
1. This is the top level.
  a. Second level
    I. Third level
    II. Third level (2)
````

Notice how, in fact there is no space on `II. Third level (2)`, but all the other items include the unwanted space.

**Comment by doodlewind** [comment]
The current list spacing should be by design, but I think it's good to make it adjustable via CSS variables. You can open the [playground](https://blocksuite-toeverything.vercel.app/starter/?init) and try in this way:

https://github.com/toeverything/blocksuite/assets/7312949/adc5740a-f82d-4d19-8c96-f2430606f518

PR welcome if you'd like to add `--affine-list-dot-spacing` :)

**Comment by andyjessop** [comment]
Can I just ask what the reason is for having the space between the number and dot? I've never seen this before, so it's really non-standard. Note that this is an actual space character in the text node, so it can't be changed by CSS.

<img width="47" alt="Screenshot 2023-11-14 at 15 06 34" src="https://github.com/toeverything/blocksuite/assets/1304307/01689278-eb02-49fc-993c-6dee7cd1fe32">

**Comment by andyjessop** [comment]
Gotcha. Ok, well I highly recommend removing that. As I said, I've never seen that before, so I can't think of a reason why it should be there.

For example, see how Notion does it:

<img width="445" alt="Screenshot 2023-11-14 at 15 34 38" src="https://github.com/toeverything/blocksuite/assets/1304307/11a43603-fc8a-434d-94cd-93fe57cf1e71">
