### ISSUE TITLE
Click at doc blank area will auto scroll to page bottom

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#5353]
Click at doc blank area will focus on last text block and auto scroll to page bottom.  It is a little confused when page is long. 

https://github.com/toeverything/blocksuite/assets/99816898/c5d4c6b1-57ea-43ac-9869-0064f8cf9dfd

**Comment by DeepakSR-12** [comment]
Hi @doodlewind  @donteatfriedrice . I'd like to work on this issue. Please update, what is the expected behaviour?

**Comment by doodlewind** [comment]
@DeepakSR-12 clicking on the blank areas on the left and right sides should not result in scrolling, thanks!
