### ISSUE TITLE
Table type "formula" for calculated fields​ or enhanced filters.

### ISSUE THREAD

**Issue by rgevrek** [toeverything/blocksuite#5374]
### Description

A new column type formula or enhanced filters possibilities.

### Use case

Filtering table or views by specific filters can be used, e.g. for managing regular tasks with varying intervals, where you can show only rows for example where a rule `prop("Last Done") > dateSubtract(now(), prop("Days Interval"), "days")` matches.

### Anything else?

Same feature is available e.g. in notion

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Tracked in #5385
