### ISSUE TITLE
Bad code block input performance

### ISSUE THREAD

**Issue by roycefanproxy** [toeverything/blocksuite#5377]
### What happened?

Overall the page edit experience was ok. But when it comes to code-block editing, the rerendering basically takes longer & longer.

especially when entering within quote section (like `"string"`)

### Distribution version

Linux

### Anything else?

![recording](https://github.com/toeverything/AFFiNE/assets/12816613/9ae29d5c-0ad2-446c-bdbe-6ad69fb1a426)

![recording2](https://github.com/toeverything/AFFiNE/assets/12816613/00da4f2d-fdc8-4ec7-8b15-2bcb1a943d6c)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Flrande** [comment]
This is related to the parsing speed of a specific theme, and a temporary solution is to use light theme.

**Comment by roycefanproxy** [comment]
Ic
I'm quite surprised that colour scheme may affect its performance.
But I guess I have to use it that way for now.
