### ISSUE TITLE
Note hover flicker when resizing

### ISSUE THREAD

**Issue by regischen** [toeverything/blocksuite#5387]
https://github.com/toeverything/blocksuite/assets/58546692/2daef142-8021-4daf-b657-7b4418a138a2

I think it's better to not have hover effect when resizing.

**Comment by doodlewind** [comment]
@regischen the hover state is supposed to be kept during dragging.

**Comment by AliceLanniste** [comment]
I dug into this bug,when the block is stretched along the x-axis, the x-coordinate of the cursor exceeds the coverage area.`getHoverState` method returns null, causing the hover state to not be sustained.

**Comment by regischen** [comment]
> I dug into this bug,when the block is stretched along the x-axis, the x-coordinate of the cursor exceeds the coverage area.`getHoverState` method returns null, causing the hover state to not be sustained.

Thanks for investigating, now we keep hover state at dragging.
And when resizing we remove hover state.

**Comment by AliceLanniste** [comment]
> Thanks for investigating, now we keep hover state at dragging. And when resizing we remove hover state.

could I give a pr

**Comment by regischen** [comment]
> > Thanks for investigating, now we keep hover state at dragging. And when resizing we remove hover state.
> 
> could I give a pr

Never mind, the issue has been solved.
