### ISSUE TITLE
Right click should only show toolbar

### ISSUE THREAD

**Issue by AryanPandeyy** [toeverything/blocksuite#5390]
![blocksuite](https://github.com/toeverything/blocksuite/assets/76730713/4c9780b2-236b-4a97-96d1-9c5e0fb92d00)

**Comment by doodlewind** [comment]
I'd consider having the context menu and format bar co-existing after righ click is expected FTM. Please feel free to clarify or discuss about it here, and we may reopen or plan corresponding improvements.
