### ISSUE TITLE
​Ability to insert pictures and files into tables

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/blocksuite#5399]
### Description

This would be useful and make data management easier

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for the feedback! Due to the recent shift of focus, we've added a collection issue for database related feature requests. This is recorded and will be scheduled afterwards. Let's track this in #5385.

**Comment by EnterMan123** [comment]
@doodlewind When will this be supported? A year has passed

**Comment by EnterMan123** [comment]
This makes it impossible for me to completely switch from Notion to Affine.

**Comment by EnterMan123** [comment]
I once saw it in the experimental features section. How long will it take for us to get this feature?
