### ISSUE TITLE
The problem of determining whether to enable 'Bookmark' in 'slash-menu'.

### ISSUE THREAD

**Issue by yangvom** [toeverything/blocksuite#5445]
![image](https://github.com/toeverything/blocksuite/assets/9628538/d14d3e3b-31a3-4462-9c03-e6aa2390882d)
The judgments at A and B are inconsistent.

**Comment by doodlewind** [comment]
The `enable_something` flag is deprecated, which should have consistent value during the whole editor lifecycle. PR welcome to correct the logic here!

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/5447
