### ISSUE TITLE
Support Shift Select

### ISSUE THREAD

**Issue by ShenQingchuan** [toeverything/blocksuite#545]
I did some competitive research.

- Notion/Wolai/Feishu support when user press Shift and use arrow keys to update selection.
- But AFFiNE (BlockSuite) doesn't support.

Notion and Wolai use the 'anchor' side of Selection to locate the float menu's position. whatever you change the selection range, the float menu stays still. 

- In Notion, if you make the selection area scrolled out of view, you will see it's fading out, and if you scroll back, it will fade in again.
- In Wolai, it has the same logic but without the fade animation
- In Feishu, it doesn't has this feature, the float menu always stay still when scrolling out of view.

<details>
  <summary> 中文 </summary>

竞品调研了一下：
- Notion/Wolai/飞书云文档   都支持了 键盘制造选区之后 呼出菜单栏
- 很遗憾 AFFiNE 还没有呢 😂  估计 BlockSuite 也有同样的问题

上述三种竞品支持的情况是
- Notion 和 Wolai 都是针对 文档的 Anchor 也就是选取不动的那一边的 绝对位置 进行浮动 Menu 的定位的，所以无论你是向上选择、向下选择，无论怎么拉大拉小选区，浮动菜单的位置都暂时是不变的。（我还特意做好事者看了一下，在 Notion 里，如果滚动页面让选区离开画面，浮动 Menu 是 Fixed 并且过 100ms 左右渐隐消失，而滚动回来又会显示 .... 体验很好，不得不说是这波非常细了。 Wolai 是有这个逻辑，但没有渐隐的动画，也差不多 ）
- 飞书好像有点傻，是每次选区变化后都重新刷新一下位置、看得出会闪一下

</details>

**Comment by doodlewind** [comment]
Thanks for your feedback! This is in the plan and should be a technically low-handing fruit to BlockSuite. We would let you know about future progress.

**Comment by Flrande** [comment]
It works fine now.
