### ISSUE TITLE
placeholder not disappear when collaborating

### ISSUE THREAD

**Issue by EYHN** [toeverything/blocksuite#5463]
https://github.com/toeverything/blocksuite/assets/13579374/fc4d4f45-80d8-4c40-81f7-d6677da85345

**Comment by lawvs** [comment]
Related to https://github.com/toeverything/blocksuite/issues/5204

**Comment by doodlewind** [comment]
@zqran seems that there is a regression for #5295, do you have time to take a look? 🤔

**Comment by EYHN** [comment]
@zqran I can't reproduce it in the latest version, it seems it has been fixed.
