### ISSUE TITLE
Inaccuracy offset when selecting text with double click then drag

### ISSUE THREAD

**Issue by coluzziandrea** [toeverything/blocksuite#5477]
### What happened?

To reproduce:

- Double click on the middle of a word (do not release the click)
- You should see the word highlighted
- Try to select the word right after the first word hovering the mouse pointer on it
- The system will remember the exact point where you firstly clicked, loosing the highlight of the first word

Expected behaviour:

As a user, I'd expect to the second word to be highlighted when the mouse pointer is on it, and not having to go through all the word lenght 

![ezgif-2-031f49c231](https://github.com/toeverything/AFFiNE/assets/12852000/374a40b1-cb68-48ff-9203-ac84971dc67e)

### Distribution version

Web (insider.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by coluzziandrea** [comment]
For reference, this is a screen record from Notion
![expected](https://github.com/toeverything/blocksuite/assets/12852000/bc09de2c-c9c7-4075-9355-7447830f8634)

**Comment by doodlewind** [comment]
Thanks for the feedback! This shouldn't be a very tricky case to fix, and @AyushAgrawal-A2 has done great work improving the selection behavior recently. So would be great if @AyushAgrawal-A2 could take a look if possible, thanks!

**Comment by coluzziandrea** [comment]
thank you all for your fast response, and congratz for the product, I've been using this for a little time, but already love it!

@doodlewind  if it is possible, I'd try to work on it

**Comment by doodlewind** [comment]
@coluzziandrea would be great if you can give it a try, thanks!

**Comment by doodlewind** [comment]
Closed by #5850
