### ISSUE TITLE
Slow PDF exporting speed

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#5501]
### What happened?

Uploading loading time.mp4…

when choose to 「export to pdf」, needs to wait for 15-20 seconds
the loading time is too long

version info: stable 0.10.2

Uploading loading time.mp4…

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Not reproduced after #5945.
