### ISSUE TITLE
Incorrect database popup position when resizing window

### ISSUE THREAD

**Issue by xiazeyu** [toeverything/blocksuite#5502]
### What happened?

When using the multi-select, and the selection box is at the edge of the window.

When the user changes the window size, the selection (pop-up box) will not change, and thus overflow.

What happened:

https://github.com/toeverything/AFFiNE/assets/10560038/1a289149-8d19-4670-ad29-189113c02073

Expected:

From notion:

https://github.com/toeverything/AFFiNE/assets/10560038/51e73480-c686-49e2-9ef9-2e01f71ccc22

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Relevant log output

```shell
N/A
```

### Anything else?

This may happens on other pop-over.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
@gauravruhela07 thanks, feel free to give it a try!

**Comment by gauravruhela07** [comment]
Hey @doodlewind, I have been trying from last one day but still I am stuck on it. Can you please provide me with any hint? Thank you.

**Comment by zzj3720** [comment]
> Hey @doodlewind, I have been trying from last one day but still I am stuck on it. Can you please provide me with any hint? Thank you.

It looks like the reason may be that the computePosition in this code doesn't support auto-update
https://github.com/toeverything/blocksuite/blob/723cee6b441eccf0383c73fa6d8840a102ce9b54/packages/blocks/src/_common/components/menu/menu.ts#L696-L732

This PR is just about to support that, but it doesn't handle unsub yet, and it doesn't look like it's been updated in a while
https://github.com/toeverything/blocksuite/pull/5457

**Comment by zzj3720** [comment]
> @zzj3720 can you please guide me how do i commit my changes?
> I tried running 
> git commit -m "popup fix
> dquote> 
> dquote> fix:database popup position fix while resizing window
> dquote> 
> dquote> "
> 
> but the error that i am getting is
> 
> fix:database popup position fix while resizing window
> ✖   subject may not be empty [subject-empty]
> ✖   type may not be empty [type-empty]
> 
> ✖   found 2 problems, 0 warnings

git commit -m "fix: database popup position fix while resizing window"

**Comment by gauravruhela07** [comment]
Thanks @zzj3720 

#5617

**Comment by doodlewind** [comment]
Should also be closed by #5457
