### ISSUE TITLE
​Multiple selection when importing

### ISSUE THREAD

**Issue by xiazeyu** [toeverything/blocksuite#5503]
### Description

Import only allows to select one at a time.
This is rediculus when multiple markdown files are needed to be imported.

### Use case

When the user import from other software, usually they have tons of markdown files as well as their attachments to import.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for your feedback! We have #4307 in plan (and should be implemented soon), will track this one there.
