### ISSUE TITLE
SVG can't be displayed after exporting to PNG

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5552]
https://github.com/toeverything/AFFiNE/assets/142964904/10cac547-9fb7-4729-9c8a-a5d6de6e6915

**Comment by doodlewind** [comment]
@donteatfriedrice this is still reproduced in current playground, PTAL

<img width="1230" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/327789d8-2cc4-4db8-adb6-6de130e62f14">

**Comment by donteatfriedrice** [comment]
I can't reproduce it on the latest master branch. Are there more recurrence conditions or processes?

https://github.com/toeverything/blocksuite/assets/99816898/1639a7a7-a418-4847-8fa2-f525b3857007

**Comment by doodlewind** [comment]
@donteatfriedrice just try the `logo.svg` in blocksuite repo 😂
