### ISSUE TITLE
Support consistent dragging behavior in edgeless mode

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#5561]
This includes following improvements to the drag handle and drag indicator:

- A. When dragging selected blocks inside the note to empty area of the edgeless canvas, dropping there would put these blocks into a new note.
- B. When dragging selected note A onto another note B, there should be the drag indicator, and dropping A should merge A into B.
- C. Dragging surface top level image over note should also show the indicator, dropping it should also merge the image into note. (This would also apply to top level bookmark afterwards.)

Case A:
<img width="800" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/ce94dbe7-100d-48f0-b0d4-3a703703f208">

Case B:
<img width="800" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/e5db42d1-d81f-40fc-95fc-78c4a397b819">

Case C: Same as B but apply to surface top level images.

We can ship this in multiple PRs.

**Comment by hwangdev97** [comment]
[update the drag image flowchart](https://www.figma.com/file/ry2HHWu5XafpuXBD2XOvKd/%F0%9F%9B%96-2023.S4?type=design&node-id=5996%3A38500&mode=design&t=myknDkx0oHPyBI9x-1)

![image](https://github.com/toeverything/blocksuite/assets/24713927/f89d6c1a-a8b3-4ca9-a20e-1f4a60a8f38c)
