### ISSUE TITLE
Incorrect format when pasted

### ISSUE THREAD

**Issue by zqran** [toeverything/blocksuite#5576]
Reproduction video:

https://github.com/toeverything/blocksuite/assets/15389209/b67abe15-d72c-4433-b0ad-f23ec7caf123

https://github.com/toeverything/blocksuite/assets/15389209/92b1ed1a-fba2-4afe-b0de-209332adfa77

**Comment by fourdim** [comment]
The first video is solved by https://github.com/toeverything/blocksuite/pull/5531/commits/0ce1717b0968896974bec365f372767cf0d1dac6 in https://github.com/toeverything/blocksuite/pull/5531.

**Comment by Saul-Mirone** [comment]
Fixed by https://github.com/toeverything/blocksuite/pull/5531
