### ISSUE TITLE
Support creating link in table

### ISSUE THREAD

**Issue by omarcostahamido** [toeverything/blocksuite#5582]
### What happened?

can't create a link on a table, but I can create a link outside of a table and then drag it in...
seems cumbersome.
<img width="404" alt="Screen Shot 2023-12-05 at 12 18 55 PM" src="https://github.com/toeverything/AFFiNE/assets/18335360/e27c9cc0-79c0-4a56-abc8-16d0c9fe36d7">

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by omarcostahamido** [comment]
@zzj3720 @EYHN @doodlewind @gauravruhela07 
I don't understand how this was just closed as completed.
There is no reference to the commit that solved this, and the current affine version does not have this fixed.
Now it is even worse, one cannot even drag a link into a table.
So, I just wanted to acknowledge that closing this issue as completed with no further information is very misleading...

**Comment by EYHN** [comment]
Maybe we need to support `/link` too? @zzj3720

**Comment by zzj3720** [comment]
> @zzj3720 @EYHN @doodlewind @gauravruhela07 
> I don't understand how this was just closed as completed.
> There is no reference to the commit that solved this, and the current affine version does not have this fixed.
> Now it is even worse, one cannot even drag a link into a table.
> So, I just wanted to acknowledge that closing this issue as completed with no further information is very misleading...

Sorry, I forgot to leave the link to pr, https://github.com/toeverything/blocksuite/pull/6572

**Comment by zzj3720** [comment]
> Maybe we need to support `/link` too? @zzj3720 

Database cells are very different from blocks, we can't support slash menus in database cells for now, most slash menu options are block-level operations and can't be used here.

**Comment by omarcostahamido** [comment]
thank you for adding some more context to this.

**Comment by omarcostahamido** [comment]
> > Maybe we need to support `/link` too? @zzj3720
> 
> Database cells are very different from blocks, we can't support slash menus in database cells for now, most slash menu options are block-level operations and can't be used here.

sorry, this sounds very confusing...

@zzj3720 @EYHN 
currently when you select some text in a cell it shows the text editing tools where linking is included.
<img width="367" alt="Screenshot 2024-03-29 at 10 42 03 PM" src="https://github.com/toeverything/blocksuite/assets/18335360/ef035475-9810-469c-85b3-6599079ed4e3">
however, if you click that and type some link in, it won't allow you to confirm it with the ✔️ and it is just stuck there.
<img width="353" alt="Screenshot 2024-03-29 at 10 42 24 PM" src="https://github.com/toeverything/blocksuite/assets/18335360/beb5b62d-dadd-4a8e-bb86-043a2e6fa59e">

now running affine 0.13.4
Editor Version 0.14.0-canary-202403250855-4171ecd
