### ISSUE TITLE
edit table view outside of reach​

### ISSUE THREAD

**Issue by omarcostahamido** [toeverything/blocksuite#5583]
### What happened?

<img width="1000" alt="Screen Shot 2023-12-05 at 12 03 28 PM" src="https://github.com/toeverything/AFFiNE/assets/18335360/c883d27b-f389-476b-8d9d-2f4aaf2a1e96">
when i click "table view" and then "edit view" it opens the panel at a weird spot.

mac os 10.15
latest official affine

### Distribution version

macOS x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
@gauravruhela07 thanks for your interest, feel free to give it a try!
