### ISSUE TITLE
Migration failed after update

### ISSUE THREAD

**Issue by luffffyz** [toeverything/blocksuite#5586]
Migration failed. Please report to https://github.com/toeverything/blocksuite/issues frame element --> frame block (page v1 --> v2) Error: val does not exist

**Comment by doodlewind** [comment]
Thanks for the report, are you using (which version of) AFFiNE that encounters this error, and could you share the workspace content for debug?

**Comment by luffffyz** [comment]
App Version
0.10.3
Editor Version
0.0.0-20231122113751-6bf81eb3-nightly

[tz-affine-workspace_a50ac718-24ba-4957-aa4b-90fb9289b9e1.zip](https://github.com/toeverything/blocksuite/files/13578826/tz-affine-workspace_a50ac718-24ba-4957-aa4b-90fb9289b9e1.zip)

**Comment by arigbs** [comment]
Same error under same circumstances, seems the migration attempt has totally messed up the workspace as I can't open anything in a previously installed version anymore and version 0.10.3 is not loading anything on account of the failed upgrade.

**Comment by joooye34** [comment]
[tz-affine-workspace_hj8SyYXG-7.affine.zip](https://github.com/toeverything/blocksuite/files/13627849/tz-affine-workspace_hj8SyYXG-7.affine.zip)
@luffffyz I tried recover your data, pls try this.

**Comment by luffffyz** [comment]
> App Version 0.10.3 Editor Version 0.0.0-20231122113751-6bf81eb3-nightly
> 
> [tz-affine-workspace_a50ac718-24ba-4957-aa4b-90fb9289b9e1.zip](https://github.com/toeverything/blocksuite/files/13578826/tz-affine-workspace_a50ac718-24ba-4957-aa4b-90fb9289b9e1.zip)

still the same error

**Comment by luffffyz** [comment]
> [tz-affine-workspace_hj8SyYXG-7.affine.zip](https://github.com/toeverything/blocksuite/files/13627849/tz-affine-workspace_hj8SyYXG-7.affine.zip) @luffffyz I tried recover your data, pls try this.

still the same error

**Comment by doodlewind** [comment]
Sorry for the inconvenience in early AFFiNE version. To minimize the risk of data lost, BlockSuite has landed the mechanism for avoiding hard migration based on https://github.com/toeverything/blocksuite/pull/6065

The legacy migration process is also deprecated. So this category of error is expected to be eliminated.
