### ISSUE TITLE
Pasting new text doesn't replace originally selected text

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#5592]
Paste a new text will not replace the original selected text

https://github.com/toeverything/blocksuite/assets/110808979/10d46a5d-0772-4cc2-bee6-30718eb7ea3f

**Comment by wfnuser** [comment]
I'm interested. May I take this one?

**Comment by doodlewind** [comment]
@wfnuser thanks, feel free to give it a try!

**Comment by zqran** [comment]
Fixed by: https://github.com/toeverything/blocksuite/pull/5531
