### ISSUE TITLE
Surface-ref block couldn't render frame inside another frame

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#5596]
https://github.com/toeverything/blocksuite/assets/99816898/1a7d99f9-6251-4392-9ae7-a0ae8255e923

Error:

<img width="395" alt="Screenshot 2023-12-06 at 17 37 56" src="https://github.com/toeverything/blocksuite/assets/99816898/af66eee7-d9fc-4fa3-a200-b989679255a0">

**Comment by doouding** [comment]
This bug has been fixed but I'm not sure in which PR.
