### ISSUE TITLE
Unable to copy & paste all the content between different workspaces

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5604]
version：0.10.3 beta
When all the contents of a page are selected from one workspace and copied and pasted into the page of another workspace, most of the contents are lost.

https://github.com/toeverything/blocksuite/assets/142964904/6d281f32-24b6-4d39-9d99-564229daf1a5

**Comment by fourdim** [comment]
All blobs are now base64 encoded inside the clipboard.
