### ISSUE TITLE
The caption input unexpectedly disappears when there is no text in the bookmark

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#5607]
Related to https://github.com/toeverything/blocksuite/pull/5544

https://github.com/toeverything/blocksuite/assets/18554747/8dec6a82-b3db-4f9c-a21a-111113583539

**Comment by doodlewind** [comment]
Auto hiding caption looks intuitive, and this behavior aligns with image.

**Comment by lawvs** [comment]
This behavior is completely contrary to ergonomics. Let's imagine the following scenarios:

- The user wants to delete all caption content and re-enter it after thinking.
- A CJK user wants to input text using an IME, but after printing a character, realizes they forgot to switch the input method. As a result, they need to delete the content and start over.

If the input box disappears when the content is empty, it will definitely confuse many users.

Furthermore, this behavior is inconsistent with the current image block.

https://github.com/toeverything/blocksuite/assets/18554747/1b56bb1a-7ff7-4c09-bfb2-42f778fac5f2

**Comment by gauravruhela07** [comment]
Hi @doodlewind, can you please assign this issue to me, I want to work on this. Thank you.

**Comment by lawvs** [comment]
This issue can be reproduced in the latest version, related to https://github.com/toeverything/blocksuite/pull/6119

**Comment by L-Sun** [comment]
It seems to have been fixed and cannot be reproduced in the current version.
