### ISSUE TITLE
Request that database can support formulas and calculations

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5618]
We have received some suggestions from users in Telegram and YouTube. They hope that the database can support formulas and calculations, and they also hope that after importing Notion tables into AFFiNE, the original formulas can be retained.

https://www.youtube.com/watch?v=1Op1qbE0R4E&lc=UgzcRnJzLe60MK1V9m14AaABAg

**Comment by doodlewind** [comment]
We've added a collection issue for database related feature requests. This is recorded and will be scheduled afterwards. Let's track this in https://github.com/toeverything/blocksuite/issues/5385.
