### ISSUE TITLE
Surface selection's path should match current selected element

### ISSUE THREAD

**Issue by Saul-Mirone** [toeverything/blocksuite#5623]
When users select a note in edgeless, the `surfaceSelection.path` should match the real path of the note, like `[pageId, noteId]`.

**Comment by doouding** [comment]
What are the best practices for representing a state in selection design where multiple elements are selected? Does each element correspond to a separate selection instance? Currently, the surface selection has an 'elements' attribute, which stores the IDs of all selected elements when multiple are chosen.
