### ISSUE TITLE
multiple-editor Uncaught Error: val does not exist

### ISSUE THREAD

**Issue by xiaofeiniuuu** [toeverything/blocksuite#5625]
When I create multiple editors
  editor's editor.mode="page"
When multiple editors are displayed on the page at the same time, one editor in the editor will report an error: Uncaught Error: val does not exist
How should I solve this problem? I have a scenario where I use multiple editors at the same time.

<img width="558" alt="image" src="https://github.com/toeverything/blocksuite/assets/29246287/1642581e-665d-450e-92c9-7a3e398d6584">

**Comment by xiaofeiniuuu** [comment]
This problem will also occur when editing one of the multiple editors in https://try-blocksuite.vercel.app/starter/?init=multiple-editor

**Comment by doodlewind** [comment]
Thanks for the feedback! This relates to legacy code pattern (that could find incorrect DOM container when multiple instances co-exists) and we have plan to refactor.

**Comment by xiaofeiniuuu** [comment]
> Thanks for the feedback! This relates to legacy code pattern (that could find incorrect DOM container when multiple instances co-exists) and we have plan to refactor.

Will this issue be resolved after the official version is released? When will the official version be released?
