### ISSUE TITLE
Canvas text font style reset

### ISSUE THREAD

**Issue by regischen** [toeverything/blocksuite#5626]
In affine, the canvas text with other font style are reset to default value.

![image](https://github.com/toeverything/blocksuite/assets/58546692/7b2a1d7d-9deb-4a22-a542-ba06c07e50c7)

**Comment by doodlewind** [comment]
The root cause is the data structure update in https://github.com/toeverything/blocksuite/pull/5339, and the styling fields are  ignored by design, so as to prevent more migration costs.
