### ISSUE TITLE
Presentation mode disruption: sidebar color change

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5638]
version: 0.10.4 beta

Before the presentation, the mouse selection mode was "select". After the presentation, the sidebar changed from white to black. It took a few seconds to recover.

https://github.com/toeverything/blocksuite/assets/142964904/930a2c48-6c10-4519-aa91-03b63ce42e6f

**Comment by regischen** [comment]
seems not reproduce in latest beta
