### ISSUE TITLE
Block cannot be cut, the scissors cannot follow the mouse

### ISSUE THREAD

**Issue by YanxinLu0122** [toeverything/blocksuite#5639]
there is an offset

https://github.com/toeverything/blocksuite/assets/144991896/e9c7331d-c528-4ab0-a674-4f79217f0d89

**Comment by Yuhang1015** [comment]
version: 0.10.4 beta

The position of the scissors is inaccurate when edgeless cuts long blocks.

As shown in the video, if you want to cut the database and the text, the default position of the scissors is in the middle of the text, but if you cut, the actual cutting position is in the middle of the database and the text. It may cause confusion to users that they cannot cut according to their original wishes.


https://github.com/toeverything/blocksuite/assets/142964904/ebd4586c-a1f7-4b84-8ed3-23b6db857062
