### ISSUE TITLE
Eraser in edgeless can erase content blocks in page mode

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5640]
version: 0.10.4 beta

The eraser can erase notes, but it is easy to lose the text content in page mode due to incorrect operation. Not sure if it is a special consideration of blocksuite, but for ordinary users, logically the eraser only wants to be used to erase traces of the pen.

https://github.com/toeverything/blocksuite/assets/142964904/33a9b9f1-85a5-47b3-9543-31d5e060c68b

**Comment by doodlewind** [comment]
Considered by design as of current implementation
