### ISSUE TITLE
Local Record and SurfaceElement Update Conflicts

### ISSUE THREAD

**Issue by regischen** [toeverything/blocksuite#5645]
Currently, there is a conflict between updating the local record and the `applyUpdate` function of the `surfaceElement`. When updates are made solely to the local record, they do not trigger certain side effects that are expected from the `applyUpdate` process.

For example, the `xywh` field not updated when `points` field of connector updated. So the connector not rendered when drawing. 

And this is the cause of #5529  and #5660

**Comment by doodlewind** [comment]
Duplicate of #5697
