### ISSUE TITLE
Table of content messed up

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5646]
version: 0.10.4 beta
TOC is messed up and the bullet point is automatically recognized as the outline. When the Heading title is changed, the outline remains unchanged.

https://github.com/toeverything/blocksuite/assets/142964904/67eb3e7e-6620-4d3b-bc4d-72405dcaf552

**Comment by donteatfriedrice** [comment]
Need to update and fix some other bugs:
https://github.com/toeverything/blocksuite/pull/5539#issuecomment-1849514870
