### ISSUE TITLE
Get closest editor container error after switching back from doc mode

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#5653]
https://github.com/toeverything/blocksuite/assets/99816898/c06e3e27-e3f2-4352-9b56-838a262c9a50

<img width="360" alt="Screenshot 2023-12-12 at 11 26 29" src="https://github.com/toeverything/blocksuite/assets/99816898/12aa15c8-8694-4785-9271-7dfcc2c4d400">

**Comment by donteatfriedrice** [comment]
And the brush wasn't rendered when moving pointer.

**Comment by doodlewind** [comment]
Not reproduced in current master
