### ISSUE TITLE
After first creating content in edgeless mode (with shape elements and note elements), then go to page mode to create content. After switching back to the whiteboard, the content in page mode will not be displayed.

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#5659]
After first creating content in edgeless mode (with shape elements and note elements), then go to page mode to create content. After switching back to the whiteboard, the content in page mode will not be displayed.
version: 12.12 0.10.4 beta.1

**Comment by Yuhang1015** [comment]
https://github.com/toeverything/blocksuite/assets/142964904/77061312-7ab8-451c-8634-a0ffefcccb08
