### ISSUE TITLE
Keep cursor to title when deleting at the start of the first block

### ISSUE THREAD

**Issue by zoulamZero** [toeverything/blocksuite#567]
Can the cursor be moved to the end of the title by pressing backspace at the beginning of the first line?（google translate）

<details>
<summary>中文</summary>
<br/>
在第一行的行头按下backspace光标能否移动到标题尾部。

</details>

# notion

https://user-images.githubusercontent.com/83949429/210953495-85e90cbd-8d65-414a-acca-a698a9953ca7.mp4

# feishu

https://user-images.githubusercontent.com/83949429/210953501-aee5ba73-b659-4d02-89e1-2847fb3cb31e.mp4

# blocksuite

https://user-images.githubusercontent.com/83949429/210953544-447317ff-78b9-48f5-9fc4-66d962e69037.mp4

**Comment by doodlewind** [comment]
Thanks for your feedback! I thought this one could be a piece of low-hanging fruit. Welcome to give it a try!

**Comment by himself65** [comment]
> I'm trying to fix

Thanks for the contribution. If you don't understand some detail, you can ask and post in this issue or new discussion.

**Comment by Flrande** [comment]
undo and redo in title is native
