### ISSUE TITLE
Unknown super impressive issue

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#5684]
https://github.com/toeverything/blocksuite/assets/110808979/6eefa8ea-b157-41d2-a32d-fafe6e8bb06c

**Comment by doouding** [comment]
Due to the lack of reproduction, I can only speculate about the cause of the BUG. This might been fixed by [#5685](https://github.com/toeverything/blocksuite/pull/5686). Feel free to reopen this issue if the problem still exists.
