### ISSUE TITLE
Quality and format confusion after exporting to pdf/png

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5685]
user feedback in discord: https://discord.com/channels/959027316334407691/1184155108699812000
version: 0.10.3 stable
 original whiteboard:

![Image](https://github.com/toeverything/blocksuite/assets/142964904/bbbb0d9f-7b19-48fd-a013-e7bbd3392811)

exporting to pdf:

![Image](https://github.com/toeverything/blocksuite/assets/142964904/0815ec73-3f94-4f09-a012-9a323b966475)

**Comment by Yuhang1015** [comment]
version: 0.10.4 beta-3

https://github.com/toeverything/blocksuite/assets/142964904/7da769a2-fb5b-4ca4-9422-04ca7e4d13a6

**Comment by doodlewind** [comment]
Should be closed by https://github.com/toeverything/blocksuite/pull/5973
