### ISSUE TITLE
Bookmark-linked page

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#5713]
[Design upgraded](https://www.figma.com/file/ry2HHWu5XafpuXBD2XOvKd/%F0%9F%9B%96-2023.S4?type=design&node-id=6755-23691&mode=design&t=zImYTax8CbHGkxX3-4)

![Image](https://github.com/toeverything/blocksuite/assets/110808979/f7dbe846-6938-4b60-8075-a3c3a2755391)

**Comment by doodlewind** [comment]
cc @hwangdev97
