### ISSUE TITLE
Roadmap 0.4.0

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#573]
Here are some first-party features that will be landed in the next minor release of `@blocksuite/editor`, a rough estimation is that most of them could be shipping (experimentally) within a month.

* New canvas-based whiteboard renderer, with `ShapeElement` and `HandwritingElement` support. Note that the handwriting contents will not be defined as “blocks”.
* New `DragHandle` UI component, used for quick block re-ordering. https://github.com/toeverything/blocksuite/issues/585
* New `SlashMenu` and `BlockHub` UI components, used for quick block inserting.
* New UI components for Edgeless mode.
* **Experimental** Database block https://github.com/toeverything/blocksuite/issues/629

This will make `@blocksuite/editor` being able to cover most usage of a typical block-based editor.

Meanwhile, we’re also working hard on improving the basic editing experience, fixing bugs on the cursor, clipboard, hotkeys, etc. For any feature requests that you are interested in, welcome to comment directly on this issue!

**Comment by fyZheng07** [comment]
- There are some bugs related to export markdowns. Underline and strikethrough markdown grammar lost in export markdown doc.
  - Mouse selection of multiple lines of text sometimes fails, or sometimes cannot be deleted after selection

https://user-images.githubusercontent.com/63830919/211485943-6675119f-5856-4c77-af2b-dd38badc9299.mov
  
  - Mouse selected text cannot be selected from front to back
  - I copied a paragraph with styles from another software to the AFFiNE editor and this paragraph is automatically indented. I want to delete the last line of content at the top of the paragraph with the mouse. The order of deletion is to delete the paragraph style first, before deleting the indentation of the paragraph, the last deletion simply loses the content.
 
https://user-images.githubusercontent.com/63830919/211486098-74be6417-1d5a-44d2-a6e4-9cf355a4d367.mov

    If the mouse is placed on the line above the insertion and you want to delete the blank line. It will happen that the inserted content is also deleted.

**Comment by doodlewind** [comment]
Closing in favor of [roadmap view](https://github.com/orgs/toeverything/projects/10/views/6) in GitHub project.
