### ISSUE TITLE
list item incorrect

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#574]
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/14026360/210996074-b4a3d531-0685-4bbd-be33-594041d9788f.png">

**Comment by himself65** [comment]
https://user-images.githubusercontent.com/14026360/210996764-004fa4ba-00f9-43af-b4c8-43e47c358ca1.mov

**Comment by lawvs** [comment]
Maybe related to https://github.com/toeverything/blocksuite/issues/199

**Comment by thorseraq** [comment]
I can't reproduce this, maybe it's an unstable behavior under collaborative circumstances.  Any suggestion to reproduce it?  

https://user-images.githubusercontent.com/20554850/211144859-01cab707-d2bb-4d24-954d-abd422b96dda.mov

**Comment by himself65** [comment]
https://user-images.githubusercontent.com/14026360/211161622-05c0f6bc-05ad-4f97-898f-616251464c85.mov

**Comment by thorseraq** [comment]
A Quick search, following line is related (Try commenting it)

https://github.com/toeverything/blocksuite/blob/f3fd73ffe8c0dc825af915cf156145b0f173598e/packages/editor/src/managers/clipboard/paste-manager.ts#L257

**Comment by himself65** [comment]
fixed in the latest version
