### ISSUE TITLE
Pasted shapes will disappear when I delete the original ones

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#5740]
Shapes in the frame are pasted from bottom right

https://github.com/toeverything/blocksuite/assets/110808979/3bd9f2c6-4c1e-46d3-896f-c402462f24cd

**Comment by Svaney-ssman** [comment]
interesting

https://github.com/toeverything/blocksuite/assets/110808979/92b06bae-a8f2-4b06-a364-abcfc10c92b8

**Comment by doouding** [comment]
I think this bug might have been fixed, it may relate to the issue of the layer manager.  If you can still reproduce this bug, feel free to reopen this.
