### ISSUE TITLE
Replace Old Twitter Icon with New Twitter Icon

### ISSUE THREAD

**Issue by antriksh-9** [toeverything/blocksuite#5751]
On the website under navbar section the twitter logo is still the old one. It needs to be updated.
Hey @doodlewind I would like to work on it.

**Comment by doodlewind** [comment]
Feel free to give it a try!

**Comment by antriksh-9** [comment]
Hey @doodlewind I have set-up the project locally but I am getting difficulty in finding the issue related file or something. 
Can you guide me a little bit?

**Comment by doodlewind** [comment]
I think we are using vitepress for the doc site. Checkout `packages/docs` for detailed configs.
