### ISSUE TITLE
Pasting will raise error.

### ISSUE THREAD

**Issue by CharlieCho2017** [toeverything/blocksuite#5753]
I use the quick start demo in my project. But when I paste some  text into the editor. It will raise error. The playground has the same error.

```
import '@blocksuite/presets/themes/affine.css';
import { createEmptyPage, DocEditor } from '@blocksuite/presets';
const page = createEmptyPage().init();
const editor = new DocEditor();
editor.page = page;
document.body.appendChild(editor);
```

# playground: https://try-blocksuite.vercel.app/starter/?init

# copied text:
Quick Start
The @blocksuite/presets package contains the prebuilt editors and opt-in additional UI components. Its nightly versions are released daily based on the master branch, which is also recommended for real world usage:

https://github.com/toeverything/blocksuite/assets/28870006/6d7bbc57-47b3-438c-853f-e4748932b5fc

**Comment by Flrande** [comment]
Is your computer Windows? If so, it is likely because the clipboard did not filter out the Windows-specific '\r' character, which is a bug in the new clipboard codebase. We should add a test for this. cc @Saul-Mirone

**Comment by CharlieCho2017** [comment]
> Is your computer Windows? If so, it is likely because the clipboard did not filter out the Windows-specific '\r' character, which is a bug in the new clipboard codebase. We should add a test for this. cc @Saul-Mirone 

Yes, my computer is WIndows. Thank you.
