### ISSUE TITLE
Console error when add a frame then switch back to doc mode

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#5787]
https://github.com/toeverything/blocksuite/assets/99816898/bb89e1fa-8466-4986-9452-05a8e1ca1a20

<img width="437" alt="Screenshot 2023-12-20 at 16 14 54" src="https://github.com/toeverything/blocksuite/assets/99816898/8e93e4c1-1471-4a4c-bb6e-a56acbb26865">

**Comment by doouding** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/5785
