### ISSUE TITLE
ContentParser Import and Export

### ISSUE THREAD

**Issue by xiaofeiniuuu** [toeverything/blocksuite#5790]
const contentParser = new ContentParser(page as Page);
  const blobMap = new Map<string, string>();
  const obj = contentParser.getSelectedBlock(root);
  const title = page.meta.title;
  const content = await contentParser.block2markdown(obj.children, blobMap);

Markdown strings exported using contentParser.block2markdown will lose blank lines when imported using contentParser.importMarkdown.

how can i solve

**Comment by doodlewind** [comment]
The `ContentParser` is a legacy module and has been deprecated. Please try the `MarkdownAdapter` instead. See https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/page-block/widgets/linked-page/import-page/import-page.ts#L30 as example.
