### ISSUE TITLE
Official quick start sandbox crash when creating a codeblock

### ISSUE THREAD

**Issue by davidliudev** [toeverything/blocksuite#5805]
I am trying to integrate blocksuite into my own project. However, I got stuck at the first step

Step to reproduce:
1. Go to the guide https://blocksuite.io/quick-start.html
2. Add a code block
3. Crash

<img width="782" alt="image" src="https://github.com/toeverything/blocksuite/assets/31893484/4847775c-7174-4ca3-a6a8-2f0cb382fa7e">

It looks like it is missing affine-editor-container  from the dom.

**Comment by fourdim** [comment]
Fixed by https://blocksuite.io/guide/quick-start.html.
