### ISSUE TITLE
Bookmark will request official url for preview image. Option to disable it?

### ISSUE THREAD

**Issue by davidliudev** [toeverything/blocksuite#5806]
When I am using the bookmark block, it tries to contact 

POST https://affine-worker.toeverything.workers.dev/api/linkPreview 404

I assume this should not be the case for other project embedding it? How do I disable this behavior or how to disable the block completely?

Actually how to disable each block types? Apparently the documentation for this project is bare minimum and I could not find it anywhere... basically these questions:

1. How to disable Blocks?
2. How to disable the Slash comamnd for that block?

Appreciate your help! Thanks

**Comment by Flrande** [comment]
> How to disable Blocks?

Remove the block you don't want from the spec.

> How to disable the Slash comamnd for that block?

https://github.com/toeverything/blocksuite/discussions/5568#discussioncomment-7774850

I suggest you carefully read [this discussion](https://github.com/toeverything/blocksuite/discussions/5568) to understand how to add custom block logic.

Regarding the bookmark, after #5811 is merged, you can override the existing function for fetching webpage information(like #5158). For example, you can refer to our [implementation](https://github.com/toeverything/affine-workers/tree/main/packages/link-preview) to deploy your own worker, so you won't need to directly remove the bookmark.

**Comment by davidliudev** [comment]
Thanks @Flrande for your quick response. Will do and check it out.

**Comment by doodlewind** [comment]
Closing since the question is replied and the option should work.
