### ISSUE TITLE
DragHandle may be positioned to parent during a same-level drag

### ISSUE THREAD

**Issue by Flrande** [toeverything/blocksuite#582]
When moving between siblings, the button will move to the upper node briefly.

blocksuite:

![20230107114117_rec_](https://user-images.githubusercontent.com/50035259/211129683-2a0d5dce-a80e-4c40-a643-b428caa3e6d5.gif)

feishu:

![20230107114156_rec_](https://user-images.githubusercontent.com/50035259/211129708-f654dc69-b985-4ce3-9a81-3dbd68d62033.gif)

**Comment by himself65** [comment]
Good catch, because the block rect box is smaller than you thought. So there's a small gap between each block

**Comment by himself65** [comment]
hot patch

```
.affine-block-children-container {
    display: flex;
    flex-direction: column;
}
```

**Comment by Flrande** [comment]
We can redesign the generating function of the button position. For example, we can determine which block-level node is in the horizontal direction by calculating getBoundingClientRect().bottom in mousemove. (Like this [function](https://github.com/toeverything/blocksuite/blob/cb27920033b719b5943fa39d4c2a786926911bc4/packages/blocks/src/__internal__/utils/selection.ts#L836)) This can also improve the user experience because users do not have to put the mouse into the node to change the button position.

blocksuite:

![20230107125133_rec_](https://user-images.githubusercontent.com/50035259/211131672-5d91a097-7048-431f-b9f4-adbded103451.gif)

feishu:

![20230107125205_rec_](https://user-images.githubusercontent.com/50035259/211131692-246622c7-b7a8-49a6-80b0-5a621d4f1a42.gif)

**Comment by himself65** [comment]
> We can redesign the generating function of the button position. For example, we can determine which block-level node is in the horizontal direction by calculating getBoundingClientRect().bottom in mousemove. (Like this [function](https://github.com/toeverything/blocksuite/blob/cb27920033b719b5943fa39d4c2a786926911bc4/packages/blocks/src/__internal__/utils/selection.ts#L836)) This can also improve the user experience because users do not have to put the mouse into the node to change the button position.
> 
> blocksuite:
> 
> ![20230107125133_rec_](https://user-images.githubusercontent.com/50035259/211131672-5d91a097-7048-431f-b9f4-adbded103451.gif) [ ![20230107125133_rec_](https://user-images.githubusercontent.com/50035259/211131672-5d91a097-7048-431f-b9f4-adbded103451.gif) ](https://user-images.githubusercontent.com/50035259/211131672-5d91a097-7048-431f-b9f4-adbded103451.gif) [ ](https://user-images.githubusercontent.com/50035259/211131672-5d91a097-7048-431f-b9f4-adbded103451.gif)
> 
> feishu:
> 
> ![20230107125205_rec_](https://user-images.githubusercontent.com/50035259/211131692-246622c7-b7a8-49a6-80b0-5a621d4f1a42.gif) [ ![20230107125205_rec_](https://user-images.githubusercontent.com/50035259/211131692-246622c7-b7a8-49a6-80b0-5a621d4f1a42.gif) ](https://user-images.githubusercontent.com/50035259/211131692-246622c7-b7a8-49a6-80b0-5a621d4f1a42.gif) [ ](https://user-images.githubusercontent.com/50035259/211131692-246622c7-b7a8-49a6-80b0-5a621d4f1a42.gif)
> 
> There may be some performance problems, but we can try some methods to solve them, such as start detect from the nearest batch of block level nodes.

I think detect by y, no x-axis could solve this

**Comment by Flrande** [comment]
> I think detect by y, no x-axis could solve this

Perhaps my statement has caused some misunderstanding, what I am trying to convey is that y.

**Comment by himself65** [comment]
This bug won't appear after the revert because the binary search algorithm solves the problem
Refs: https://github.com/toeverything/blocksuite/pull/607
