### ISSUE TITLE
Incorrect multi-line title size after undo/redo

### ISSUE THREAD

**Issue by zoulamZero** [toeverything/blocksuite#583]
Recorded on the latest [playground](https://block-suite.pages.dev/?init)

https://user-images.githubusercontent.com/83949429/211130531-8927b40a-c7b1-40fa-8ea9-79340811a29b.mp4

append `autosize.update(this._title);` at [this line](https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/page-block/default/default-page-block.ts#L296) can fix it

**Comment by doodlewind** [comment]
Good catch! Having a standalone PR fixing this would be great!
