### ISSUE TITLE
Blank note generated when rapidly duplicating note using '+' in edgeless note

### ISSUE THREAD

**Issue by Yuhang1015** [toeverything/blocksuite#5860]
version: 0.11.0 stable

When tapping the "+" icon for quick note duplication in Edgeless Note, the new note appears blank.

https://github.com/toeverything/blocksuite/assets/142964904/597e8041-a6d3-4d76-903f-c34cefdcd55c

**Comment by doodlewind** [comment]
This is by design, see https://github.com/toeverything/blocksuite/issues/5234
