### ISSUE TITLE
Image block raises error

### ISSUE THREAD

**Issue by CharlieCho2017** [toeverything/blocksuite#5863]
I use `Job.snapshotToPage`  to create page. But When page has image blocks, it will raise 'Error: val does not exist'.

https://github.com/toeverything/blocksuite/assets/28870006/59bbbe54-4cb4-4fe6-9c76-cfcaddc637fe

**Comment by fourdim** [comment]
Please follow the pattern here:
https://github.com/toeverything/blocksuite/blob/3fb9bcb6ee973a97f22d771e6a9afdc1ec05afa4/packages/blocks/src/_common/transformers/zip.ts#L39C54-L39C54
to set blobs in assetMap first.

**Comment by CharlieCho2017** [comment]
Why attachment block doesn't raise error?

**Comment by doodlewind** [comment]
Closing since importing image from snapshot should work with the pattern mentioned.
