### ISSUE TITLE
Failed to resolve entry for package "@blocksuite/presets".

### ISSUE THREAD

**Issue by Luckstarnlj** [toeverything/blocksuite#5865]
![image](https://github.com/toeverything/blocksuite/assets/87968591/7e97c76b-c5e8-4e17-b238-666d4ea68191)

![image](https://github.com/toeverything/blocksuite/assets/87968591/b0bb2a7d-2689-4b5c-873e-fafb54f3957b)

Why can't I use it according to the document? Didn't I update the document

**Comment by doodlewind** [comment]
Could you share more about your error log? One guess is that it's recommended to install this with `pnpm i @blocksuite/presets@nightly`.

**Comment by trancethehuman** [comment]
<img width="1832" alt="Screenshot 2023-12-26 at 10 37 18 PM" src="https://github.com/toeverything/blocksuite/assets/16231195/979eeab2-dcdb-4071-b812-b0edc6a3d645">

I'm facing the same issue. Here's the screenshot of the Quick Start guide.

**Comment by trancethehuman** [comment]
<img width="1106" alt="Screenshot 2023-12-26 at 11 05 21 PM" src="https://github.com/toeverything/blocksuite/assets/16231195/86ff16a9-e941-4c5e-a162-aa7c768333d2">

Can confirm it's broken when pnpm install as well

**Comment by trancethehuman** [comment]
Downgrading from 0.11.0 to 0.10.0 and got this error
<img width="758" alt="Screenshot 2023-12-26 at 11 09 21 PM" src="https://github.com/toeverything/blocksuite/assets/16231195/e2003c3f-d587-476d-a89e-b87b1e480dbc">

**Comment by fourdim** [comment]
This issue is fixed with the latest @blocksuite/presets@nightly.
Try install it by `pnpm i @blocksuite/presets@nightly`.

**Comment by trancethehuman** [comment]
🔥🔥🔥🔥
