### ISSUE TITLE
Some more TypeScript type validation errors (target: ES2020)

### ISSUE THREAD

**Issue by trancethehuman** [toeverything/blocksuite#5871]
```
./node_modules/.pnpm/@blocksuite+store@0.11.0-nightly-202312270506-f0bc780_async-call-rpc@6.3.1_lit@3.1.0_yjs@13.6.10/node_modules/@blocksuite/store/src/adapter/context.ts:90:9
Type error: The left-hand side of an 'instanceof' expression must be of type 'any', an object type or a type parameter.

  88 |       return this;
  89 |     }
> 90 |     if (parent.node[ele.prop] instanceof Array) {
     |         ^
  91 |       (parent.node[ele.prop] as Array<object>).push(ele.node);
  92 |     }
  93 |     this._stack.push(parent);
```

My tsconfig for reference:
```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "target": "ES2020",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}

```

**Comment by fourdim** [comment]
What is your TypeScript version?

**Comment by trancethehuman** [comment]
It was 5.1.3 when I got this error. Upgraded to 5.3.3 and got a different error

```
./node_modules/.pnpm/@blocksuite+store@0.11.0-nightly-202312270506-f0bc780_async-call-rpc@6.3.1_lit@3.1.0_yjs@13.6.10/node_modules/@blocksuite/store/src/index.ts:3:22
Type error: File '/Users/hainghiem/Development/cats-front/node_modules/.pnpm/@blocksuite+store@0.11.0-nightly-202312270506-f0bc780_async-call-rpc@6.3.1_lit@3.1.0_yjs@13.6.10/node_modules/@blocksuite/store/shim.d.ts' not found.

  1 | /// <reference types="@blocksuite/global" />
  2 | // eslint-disable-next-line @typescript-eslint/triple-slash-reference
> 3 | /// <reference path="../shim.d.ts" />
    |                      ^
  4 |
  5 | export type { Y };
  6 |
   Linting and checking validity of types  ... ELIFECYCLE  Command failed with exit code 1.
```

**Comment by fourdim** [comment]
> It was 5.1.3 when I got this error. Upgraded to 5.3.3 and got a different error
> 
> ```
> ./node_modules/.pnpm/@blocksuite+store@0.11.0-nightly-202312270506-f0bc780_async-call-rpc@6.3.1_lit@3.1.0_yjs@13.6.10/node_modules/@blocksuite/store/src/index.ts:3:22
> Type error: File '/Users/hainghiem/Development/cats-front/node_modules/.pnpm/@blocksuite+store@0.11.0-nightly-202312270506-f0bc780_async-call-rpc@6.3.1_lit@3.1.0_yjs@13.6.10/node_modules/@blocksuite/store/shim.d.ts' not found.
> 
>   1 | /// <reference types="@blocksuite/global" />
>   2 | // eslint-disable-next-line @typescript-eslint/triple-slash-reference
> > 3 | /// <reference path="../shim.d.ts" />
>     |                      ^
>   4 |
>   5 | export type { Y };
>   6 |
>    Linting and checking validity of types  ... ELIFECYCLE  Command failed with exit code 1.
> ```

Can confirm that it is our fault that we haven't publish the shim.d.ts to the npm registry.
However, I would say you are using blocksuite in a really really wired way.
That is, you already have dist (compiled format, out of box for you to use) under 
` ./node_modules/.pnpm/@blocksuite+store@0.11.0-nightly-202312270506-f0bc780_async-call-rpc@6.3.1_lit@3.1.0_yjs@13.6.10/node_modules/@blocksuite/store`.
Why would you still like to recompile it again?

**Comment by doodlewind** [comment]
You can refer to https://github.com/toeverything/abed as a simple environment that uses the nightly version without the build error. But the best practice here should be using BlockSuite by importing dist, we can't ensure building BlockSuite source with arbitrary TS config.

**Comment by trancethehuman** [comment]
@doodlewind @fourdim seems like `"moduleResolution": "node"` is the setting that prevented me from building. Since I'm on Next.js, it makes sense for me to keep this instead of `Bundler`, so I'll go with using the dist content directly.

**Comment by pengx17** [comment]
In the published dist files there is import like `import("@blocksuite/store/src/index")`, which might be the source of issue.
![CleanShot 2023-12-30 at 10 19 18@2x](https://github.com/toeverything/blocksuite/assets/584378/e2c471fd-5f05-48b3-bc02-3d409a04ddfc)

When the user's codebase importing this `d.ts` file, it will also try to load the type module via `import("@blocksuite/store/src/index")`, which will import the source files that are now published in `node_modules`.
If the source files contain types that are considered invalid on the user's configuration, it will throw errors.

Some more insights:
- The source files are not blacklisted by `skipLibCheck` because the source files are not suffixed with `.d.ts`.
- The error does not throw because the source files are not published in the previous versions

To fix this issue, we might:
- remove source files from the published files
- or fix the import paths in `d.ts`

**Comment by fourdim** [comment]
CC @Saul-Mirone

**Comment by Saul-Mirone** [comment]
We'll fix the import path. Leaving the src folder is helpful for users to debug.
