### ISSUE TITLE
After pasting the content, the style is lost

### ISSUE THREAD

**Issue by hwangdev97** [toeverything/blocksuite#5877]
After pasting the content, the style is lost, all content pasted as Text block. We lose h1/h6, image, code: 

Video showing the difference between pasting in affine and notion:

https://github.com/toeverything/blocksuite/assets/24713927/8c0170c3-678d-47cd-b4ad-43cbd19fa7e6

**Comment by doodlewind** [comment]
Where is the source of the copied content?

**Comment by hwangdev97** [comment]
It is https://github.com/toeverything/AFFiNE 's readme.
