### ISSUE TITLE
Cmd+Shift+V can't paste without style

### ISSUE THREAD

**Issue by EYHN** [toeverything/blocksuite#5881]
https://github.com/toeverything/blocksuite/assets/13579374/e976bdac-92b1-4214-a922-1bb500647f14

**Comment by yunnian** [comment]
This is a product logic, and there are also many styles that can be retained, such as Feishu. I don't think it's good to keep it the same as Notion.
这是一个产品逻辑，也有很多保留样式的，比如飞书，我不觉得和notion保持一样是好的

**Comment by yunnian** [comment]
> This is a product logic, and there are also many styles that can be retained, such as Feishu. I don't think it's good to keep it the same as Notion. 这是一个产品逻辑，也有很多保留样式的，比如飞书，我不觉得和notion保持一样是好的

Also consider adding a configuration option to solve this issue.
也可以考虑增加一个配置项来解决这个问题

**Comment by EYHN** [comment]
@yunnian 
I believe that Cmd+Shift+V should be designated as the shortcut for pasting text while simultaneously clearing its formatting, in keeping with the established conventions of the macOS platform.

**Comment by yunnian** [comment]
I was mistaken; I thought we were talking about cmd + V. @EYHN

**Comment by doodlewind** [comment]
Not reproduced in current playground.
