### ISSUE TITLE
Text wrap style of `Numbered List` entry in FormatBar

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#590]
### To Reproduce

1. Select text
2. `Open paragraph-panel`

### Screenshots

<img width="419" alt="Screenshot 2023-01-08 at 1 17 57 AM" src="https://user-images.githubusercontent.com/27926/211162687-0f854641-e07b-48f2-87b2-017747490c89.png">

### Platform

MacOS 13.1

### Browser

Chrome

**Comment by doodlewind** [comment]
Thanks for your feedback. Could you please help test if this is still the case in https://pathfinder.affine.pro/ (with cmd-shift-R hard refreshed) or https://blocksuite-toeverything.vercel.app/?init ? Still can't reproduce this locally 😥.

**Comment by fundon** [comment]
Sorry, my local code is a bit old.
