### ISSUE TITLE
Copying content in nested list will have unexpected content

### ISSUE THREAD

**Issue by pengx17** [toeverything/blocksuite#5901]
Please see the attached video:

<video src="https://github.com/toeverything/blocksuite/assets/584378/d57c46c1-f324-48a7-b463-6e8a838d452b"></video>

You can see in the clipboard, when copying the copied content is wrong:

<img width="832" alt="image" src="https://github.com/toeverything/blocksuite/assets/584378/384d8264-07c2-492c-9a76-097e4bfc3d78">

**Comment by fourdim** [comment]
Closed by #6630.
