### ISSUE TITLE
Redundant unremovable character appears at line start

### ISSUE THREAD

**Issue by fundon** [toeverything/blocksuite#591]
### To Reproduce

1. `Enter` tow newlines
2. `Backspace` remove them
3. Input content

### Screenshots

https://user-images.githubusercontent.com/27926/211164207-0a2f333c-7f08-4fad-ac55-9b9abc0b58db.mov

### Expected behavior

The cursor should be able to move to the end

### Platform

MacOS 13.1

### Browser

Chrome

**Comment by doodlewind** [comment]
Thanks for your feedback. This looks like a regression like #265 which should have been fixed earlier. Could you please help test if this happens in https://pathfinder.affine.pro/ (with cmd-shift-R hard refreshed) or https://blocksuite-toeverything.vercel.app/?init ? Can't reproduce this locally 😥.

**Comment by fundon** [comment]
😄, I used the old branch `pathfinder`. 

Good job. The new code works well.
