### ISSUE TITLE
Shortcuts do not work in the captions of custom blocks

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#5912]
`Ctrl+A/C/X/V` shortcuts do not work in the captions of custom blocks

https://github.com/toeverything/blocksuite/assets/18554747/e7b1dc02-b56b-4bd2-aff5-ee008cc3210b

**Comment by lawvs** [comment]
This issue can still be reproduced in the attachment/bookmark block.

**Comment by doodlewind** [comment]
Closed by #6119

https://github.com/toeverything/blocksuite/assets/7312949/ee8d2c66-6edf-41a6-aef3-095c8d80eb50
