### ISSUE TITLE
Help Needed: Detect & Initializing Blocksuite Editor

### ISSUE THREAD

**Issue by DineshCodeFlow** [toeverything/blocksuite#5925]
I'm relatively new to Blocksuite and currently working on integrating it into my project. I'm looking for assistance in a specific aspect: 
- initializing the Blocksuite editor with data from my database and 
- detecting changes made within the editor.

Stackblitz: [Blocksuite GitHub Stackblitz example](https://stackblitz.com/github/toeverything/blocksuite?file=README.md)

Specifically, I'm seeking guidance on the following:

**Detecting Changes:** Identifying the process or methods within Blocksuite in the above stackblitz exampe to detect modifications or content changes made within the editor.
**Initializing Editor with Database Data:** Understanding how to initialize the Blocksuite editor with data fetched from an external database via an API call, ensuring that the editor displays this fetched content.

Any pointers, documentation references, or code snippets illustrating these functionalities would be incredibly helpful.

**Comment by doodlewind** [comment]
Hi, you can use the `page.slots.blockUpdated` to listen to block update events, and you can refer to https://blocksuite.io/data-persistence.html how to initialize editor with existing data. If you are saving the snapshot into database, calling `snapshotToPage` when loading data should be adequate.

You can also checkout https://blocksuite.io/adapter.html to learn more about importing and exporting data in BlockSuite. Hope this could make sense to you!
