### ISSUE TITLE
The font-weight of Heading 2 is 500, but Heading 3 is 700.

### ISSUE THREAD

**Issue by CharlieCho2017** [toeverything/blocksuite#5938]
The font-weight of Heading 2 is 500, but Heading 3 is 700.  Heading2 looks different.
![image](https://github.com/toeverything/blocksuite/assets/28870006/926ead4a-4203-4071-841e-0fe3b1713b9d)

**Comment by doodlewind** [comment]
@hwangdev97 is this by design?
