### ISSUE TITLE
Selection and document update commands effect on queued commands

### ISSUE THREAD

**Issue by newlegendmedia** [toeverything/blocksuite#5948]
If commands are applied that affect the document (eg. adding or removing text), are other commands that may have been queued able to work on the modified document text and selections since they may have shifted? Do they have to adjust their offsets based on the updated document somehow?

**Comment by doodlewind** [comment]
If you return `false` in command, the following command will not be executed.

If a command that updates model is executed, the following command will receive the mutated model, but the DOM view may not have been updated.
