### ISSUE TITLE
Cursor Holds Incorrect Col Location when Navigating Through Lines with Arrow Keys

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#5976]
Cursor's column position does not preserve while navigating with arrow keys from shorter to longer lines in blocksuite.

https://github.com/toeverything/blocksuite/assets/18554747/a13eb2ce-bb03-4fca-b300-0d1c0b8fea53

**Comment by doodlewind** [comment]
Considered supported in #5850, please wait for recent AFFiNE updates.

https://github.com/toeverything/blocksuite/assets/7312949/f1285b6a-9e8a-4066-a78f-b95edbf2558a

**Comment by doodlewind** [comment]
Edge case: if the block with shorter content is empty, this fallbacks to previous behavior.
