### ISSUE TITLE
Invisible content​ that was scanned by OwlOCR 5.app

### ISSUE THREAD

**Issue by dingemann** [toeverything/blocksuite#5983]
### What happened?

When pasting text into a page it doesn't appear. Instead it only shows up in the table of content.
I get this when using the OwlOCR 5.app (https://owlocr.com) to scan **multiple lines of text**. 

I'm using Version 0.11.1 (0.11.1)
It was also present in the versions before.

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by fourdim** [comment]
Hi, the clipboard has been improved a lot in 0.11.3. Could you please check if this issue persists in the latest version? If so, I would recommend you to paste it to https://evercoder.github.io/clipboard-inspector/ and give us a screenshot which will help us to further diagnose the issue.

**Comment by doodlewind** [comment]
Reproduced in OwlOCR and the native TextEdit in macOS.

Copying the selected text in TextEdit:

<img width="478" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/bc746231-0a78-405e-a55f-abc3ee4f80a0">

The clipboard HTML content:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2487.3">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px}
</style>
</head>
<body>
<p class="p1">Hello world!</p>
<p class="p2"><br></p>
<p class="p1">123123123</p>
</body>
</html>
```

Pasted result in BlockSuite:

<img width="592" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/8bc0051e-202f-4e0b-a1fb-fdf7561e6c53">

As a workaround, pasting with cmd-shift-v or copying with the "copy to clipboard" button works well, which only use the plain text clipboard format.

<img width="588" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/0da9df19-14eb-4247-9182-3d53a2519173">

**Comment by dingemann** [comment]
Thanks for reproducing. I used OWL with the command line interface. https://owlocr.com/blog/posts/owlocr-5-command-line-interface
Inspired by your post I now created a workaround workflow.
