### ISSUE TITLE
performance improve on blocks rect detect

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#599]
We could use binary search on every code that uses for-loop in blocks, which will improve the algorithm complexity from `O(n)` to `O(log(n))`.

This could make 1000 blocks (heavy) example much faster than ever.

Example:

https://github.com/toeverything/blocksuite/blob/c9785dd905a05154cfb4c100d80d3e5ae18629ab/packages/blocks/src/page-block/default/utils.ts#L44-L85

**Comment by himself65** [comment]
Explain why logN works.

The position of the `blocks` in the array is the same as that in the editor so that we could use the binary search on this part
