### ISSUE TITLE
How to implement markdown2Block

### ISSUE THREAD

**Issue by xiaofeiniuuu** [toeverything/blocksuite#6002]
How to convert a segment of markdown into a block through markdown2Block as before? The structure of the current conversion through

` 
    const adapter = new MarkdownAdapter();
    adapter.toBlockSnapshot()
    const job = new Job({ workspace: page.workspace });
    job.snapshotToBlock()
`
 is different from before

**Comment by fourdim** [comment]
https://github.com/toeverything/blocksuite/blob/704f21cc6523d8e7c2513fa01ec6d71544500168/packages/blocks/src/_common/transformers/markdown.ts#L44-L74
