### ISSUE TITLE
Image should not be deleted when deleting in caption

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#6036]
To reproduce:

1. Select on an image with exiting caption (with selection box appeared)
2. Press backspace on editing caption

The image should not be deleted.

<img width="415" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/29bde130-ec7a-46f1-b7bc-f0f7d4084840">

**Comment by lawvs** [comment]
Also related to https://github.com/toeverything/blocksuite/issues/5912

**Comment by fourdim** [comment]
Dup #6045.
