### ISSUE TITLE
​Images can be converted to card view, but cannot be reverted back to image embed view

### ISSUE THREAD

**Issue by lengineerxixi** [toeverything/blocksuite#6041]
### What happened?

Images can be converted to card view, but cannot be reverted back to image embed view

### Distribution version

Windows x64 (Intel)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zqran** [comment]
This bug cannot be reproduced in the latest version of BlockSuite.


https://github.com/toeverything/blocksuite/assets/15389209/c3795b7a-3fd1-4c8a-bc5e-52c794500faf

**Comment by lawvs** [comment]
This issue is duplicated of https://github.com/toeverything/blocksuite/issues/5097

**Comment by doodlewind** [comment]
Closed by #6069
