### ISSUE TITLE
page doc - if a codeblock exists, we can't delete any block anymore

### ISSUE THREAD

**Issue by archywillhe** [toeverything/blocksuite#6052]
https://github.com/toeverything/blocksuite/assets/10269911/51d4dbc6-aa3f-4d1b-909c-781508d99280

I can't delete my text block anymore after a codeblock is created. 

It auto-selects to the codeblock instead

**Comment by fourdim** [comment]
What is your environment?
Are you using Angular to wrap the BlockSuite?
I cannot reproduce it in the playground. https://try-blocksuite.vercel.app/

**Comment by archywillhe** [comment]
I can produce it just fine in the starter preset: https://try-blocksuite.vercel.app/starter/?init=preset

**Comment by archywillhe** [comment]
I can produce it just fine in the starter preset: https://try-blocksuite.vercel.app/starter/?init=preset

Step 1 - create a Code block 

Step 2 - try to delete any other block, and Code block gets auto-focused 

I'm in Chrome on MacOS
