### ISSUE TITLE
add some func to deal with yaml front matter when import markdown file

### ISSUE THREAD

**Issue by zkwolf** [toeverything/blocksuite#6056]
Currently when a markdown file starts with a yaml front matter, it is treated as a ThematicBreak node when imported and is rendered.

![image](https://github.com/toeverything/blocksuite/assets/8555127/e477e967-0a29-478f-9440-6d675c342295)
![image](https://github.com/toeverything/blocksuite/assets/8555127/fca906d6-65ed-4515-a6b8-ae2353b36d87)

**Comment by fourdim** [comment]
Do you want to have it removed? Or convert it into a code block?
In my opinion, you can always delete it by yourself as some users may want to preserve the yaml front matter data when importing.

**Comment by zkwolf** [comment]
I think it might be better to just remove it as opposed to rendering it out, e.g. front matter is hidden when using vscode preview

**Comment by fourdim** [comment]
After discussion with the product side, this feature is currently not planned.
You can implement a new adapter yourself to remove the front matter.
