### ISSUE TITLE
Support importing external image URL in markdown

### ISSUE THREAD

**Issue by zkwolf** [toeverything/blocksuite#6063]
`toPageSnaptshot` get assets to write blob，but only pass file to this func, is there should pass `job.assetsManager` to assets?

https://github.com/toeverything/blocksuite/blob/f2054e2d231d7160af85683b8b81ca49365e66d4/packages/blocks/src/page-block/widgets/linked-doc/import-doc/import-doc.ts#L38

**Comment by fourdim** [comment]
Is this a question or bug report?

**Comment by zkwolf** [comment]
I think this is a bug.

**Comment by fourdim** [comment]
What's your markdown file looks like?
Does it contain any image link to the local file?
If so, it's not a bug. Import it using zip option.

**Comment by doodlewind** [comment]
Tried importing the markdown, seems that the actual issue is that we are not able to import following image in markdown:

```
![](https://artem.krylysov.com/images/2023-rocksdb/rocksdb-lookup.png)
```

**Comment by fourdim** [comment]
Thank you for your contribution!
