### ISSUE TITLE
Regression on collaborative playground entry

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#609]
#594 makes the `room` param random by default. So users should add the same `room` argument explicitly to test collaborative editing.

**Comment by doodlewind** [comment]
Currently for users willing to try collaborative mode, please add the `?room` param manually. For example, opening two https://blocksuite-toeverything.vercel.app/?room=hello tabs should do the trick!

Note that in this case, you can at most open only one tab with the `?init` param. Otherwise there will be conflicts due to redundant initialization.

**Comment by himself65** [comment]
I think we should add a input box on top of `init` button
