### ISSUE TITLE
page doc - after creating a codeblock and adding a few empty lines, pressing backspace doesn't delete line

### ISSUE THREAD

**Issue by archywillhe** [toeverything/blocksuite#6101]
tested on the latest version: [2431e2e9b32dbb81dbef4a4dfac68f90587f9851](https://github.com/toeverything/blocksuite/tree/2431e2e9b32dbb81dbef4a4dfac68f90587f9851)

<img width="390" alt="Screenshot 2024-01-24 at 14 59 17" src="https://github.com/toeverything/blocksuite/assets/10269911/e3f343ad-7262-468e-960b-a9eb0a848139">

when you have a code block with a few empty new-lines, the backspace will stop working and can't delete things

**Comment by archywillhe** [comment]
reproduce:

1. create a codeblock and add a 6 empty lines
2. go to a line in the middle, say line 4, press backspace

backspace doesn't work anymore.

**Comment by Flrande** [comment]
I can't reproduce it.

https://github.com/toeverything/blocksuite/assets/50035259/979c86ac-dda1-4485-8ba1-42d509e61d0b

**Comment by archywillhe** [comment]
oh thanks; 

I just pulled from the latest master and I can't reproduce it anymore

I think one of a recent commit also got this fixed

thanks again for the great work!
