### ISSUE TITLE
​Improving Cursor Movement across Blocks

### ISSUE THREAD

**Issue by L-Sun** [toeverything/blocksuite#6134]
### Description

Content: When using the up and down arrow keys to move the cursor, the movement within a block is as expected. However, when it comes to moving across blocks, the behavior is not consistent.

### Anything else?

move cursor with double clicking down arrow key <kbd> ↓</kbd>
![image](https://github.com/toeverything/AFFiNE/assets/20479050/bfd67b9d-4649-4c4e-99d2-c77d04b4f069)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by lawvs** [comment]
Duplicated of https://github.com/toeverything/blocksuite/issues/5976

**Comment by doodlewind** [comment]
Considered supported in #5850, please wait for recent AFFiNE updates.

https://github.com/toeverything/blocksuite/assets/7312949/f1285b6a-9e8a-4066-a78f-b95edbf2558a
