### ISSUE TITLE
Continue Numbered Lists from Previous Number​

### ISSUE THREAD

**Issue by davidmorales0722** [toeverything/blocksuite#6149]
### Description

Hello Affine.pro team,

I am a user of your platform and I am really enjoying its features. However, I have encountered an issue with the numbered lists. Currently, every time I start a new list, it begins from number 1. I am unable to continue the list from the previous number.

### Use case

This is a feature that I find very useful, especially when I am drafting long documents with multiple sections. It would be great if Affine.pro could support continuing numbered lists from the last number used, instead of always starting from 1, or set the starting number manually.

**Comment by davidmorales0722** [comment]
I've tried importing md files with the correct bullet numbering and still starts from 1 every time.

**Comment by doodlewind** [comment]
@davidmorales0722 thanks for your feedback! I think resetting the link index for every group of list is by design in markdown. We have plan to support third-party customization that could allow this, which should be part of mid or long term planning.
