### ISSUE TITLE
Code block UI redesigned

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/blocksuite#6162]
Please check [the design](https://www.figma.com/file/UTTtfVCcStw1dKUg0gCSPo/%F0%9F%93%9A-Design-System?type=design&node-id=9949-30595&mode=design&t=WJ19qxq8YtS5ptfO-4)

![Image](https://github.com/toeverything/blocksuite/assets/110808979/7c616278-66a0-4679-8708-1d69e791c236)

1. remove the current block menu

![Image](https://github.com/toeverything/blocksuite/assets/110808979/367a88e5-65a3-4a9d-b5f4-04ca558e9147)

2. upgrade background color: background: var(--light-background-backgroundCodeBlock, rgba(247, 248, 250, 1)); background: var(--dark-background-backgroundCodeBlock, rgba(31, 32, 34, 1));

3. Upgrade code font, refer this https://github.com/toeverything/blocksuite/issues/6086#issue-2095715639

**Comment by doodlewind** [comment]
Closing since we've moved internal task management to linear. For anyone interested, this should still be on our feature backlog.
