### ISSUE TITLE
Editor Text Input and Copying Errors

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#6168]
### Please refer the video

1. After quoting an article and entering text, pressing Enter results in the article being copied multiple times

https://github.com/toeverything/blocksuite/assets/40333372/cde6e883-356b-4356-9eef-06e79cb09c68

2. Copying the text in the selected block will be copied together with the quoted article.

https://github.com/toeverything/blocksuite/assets/40333372/be36cfe3-2335-43e1-b1dc-0408bf4a7140

**Comment by Flrande** [comment]
https://github.com/toeverything/blocksuite/assets/50035259/79e02a05-8413-4d05-b544-044761df6d1a

case 2 is expected because you select the reference
