### ISSUE TITLE
Please tell me how to store content,thank you

### ISSUE THREAD

**Issue by kankanai** [toeverything/blocksuite#6175]
I really like this project, it's great, but it's a bit difficult for me to understand. I hope to save all the contents of the current workplace to one location, such as the note table in sqlite3. Automatically synchronize every operation, and can read and load content based on the workplace ID when opened, but I don't know where to modify it, nor can I find the relevant interface from the document

**Comment by doodlewind** [comment]
Thanks for your feedback! The basic idea about how to persist state is described when we talk about document streaming (https://blocksuite.io/guide/data-synchronization.html#document-streaming). We'll have some basic examples to show how things are put together in real world. Hope you can stay tuned!

**Comment by kankanai** [comment]
> 感谢您的反馈意见！当我们谈论文档流时，描述了如何持久化状态的基本思想（https://blocksuite.io/guide/data-synchronization.html#document-streaming）。我们将通过一些基本示例来展示现实世界中的事物是如何组合在一起的。希望您能够继续关注！

Thank you, but when I was using
```
  window.job.pageToSnapshot(window.workspace).then((workJson) => {
        console.log(workJson);
      }).catch((err) => {
        console.log(err);
      });
``` 
I received an error message,
```
TypeError: pageMeta.tags is not iterable
    at Job._exportPageMeta (job.ts:111:26)
    at Job.pageToSnapshot (job.ts:255:23)
    at window.onmessage (main.ts:189:18

```

After modifying the   _exportPageMeta   return {
      **
      tags: [...pageMeta.tags],
    };  to  return {
      **
      tags: [],
    }; it prompted:

```
Error: Root block not found in page
    at assertExists (assert.ts:18:11)
    at Job.pageToSnapshot (job.ts:256:5)
    at window.onmessage (main.ts:189:18)
```

**Comment by zkwolf** [comment]
Should pass `page` to `pageToSnapshot` and  try `await page.load()` before `pageToSnapshot`
