### ISSUE TITLE
Unable to paste content in block-level selection state

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#620]
When the editor is under block-level selection:

* The pasted content is ignored.
* The selected blocks are not removed.

**Comment by SteinsHead** [comment]
I think the correct logic is that the selected block should be removed first, and then the pasted block should be added to the location of the removed block

**Comment by SteinsHead** [comment]
#718 This is my code for this problem

**Comment by doodlewind** [comment]
Closed by #1687
