### ISSUE TITLE
Renaming `page` to `doc`

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#6214]
We should rename the `Page` class to `Doc`, so the `page.addBlock` would be `doc.addBlock`, which would reflect the doc-based (or file-based) organization of workspace better. This also aligns the planned product feature exposing more doc types. 

Note that the scope of this PR should be limited to API surface. The `affine:page` block type in data would be kept for compatibility.

**Comment by MentalGear** [comment]
I'm wondering if this wouldn't be confusing with Y.Doc. How does Page relate to Y.Doc?
Also, if you change this, for consistence I think you should also have `affine:doc`, even though you can still keep `affine:page` for legacy users.

**Comment by doodlewind** [comment]
@MentalGear thank for your feedback! The `Page` object is exactly an one-one mapping to an `Y.Doc`, so renaming it should make things more intuitive.

In BlockSuite mindset, a document should be the source of truth of any types of editable content. The `affine:xxx` blocks are after all one implementation of block collections (that are built for AFFiNE primarily). Third party prefixed blocks can also be used for your documents.
