### ISSUE TITLE
Text breaks out of layout

### ISSUE THREAD

**Issue by MentalGear** [toeverything/blocksuite#6217]
First off: Thank you for this amazing colab editor - please keep up the good work!

Reproduction:
In the demo on your page, place the cursor before the first character of the first line, then hit arrow up and write characters.

https://github.com/toeverything/blocksuite/assets/2837147/d8038476-c7ed-465d-b28b-b3fe96c95236

**Comment by doodlewind** [comment]
Thanks for the feedback, this explains the edge case for #6218

**Comment by Flrande** [comment]
https://github.com/toeverything/blocksuite/assets/50035259/f7d2e362-1672-485b-9f2a-dcc0ba196f80

I cannot reproduce it, can you provide your specific operations and environment information (system version, browser version)?

**Comment by MentalGear** [comment]
@Flrande I used a on screen keyboard to make it more obvious. Firefox 122 Mac 10.15
Hope it helps!

https://github.com/toeverything/blocksuite/assets/2837147/b1c50179-381d-4607-a02b-08d72292f30b
