### ISSUE TITLE
Arrow key down loops back to first line

### ISSUE THREAD

**Issue by MentalGear** [toeverything/blocksuite#6218]
As a user, I would not expect that when pressing `arrow key down` on the last sentence, that the cursor would loop back to the first line.

https://github.com/toeverything/blocksuite/assets/2837147/6bfc96db-ec5a-4734-9208-0d2aaa0d8bff

(text breaking of layout in previous bug report)

**Comment by doodlewind** [comment]
Thanks for your feedback! Just wondering how did you enter the first line that is aligned to the left of the browser viewport? This may be an edge case for `contenteditable` that is not expected to be editable, cc @Flrande

**Comment by Flrande** [comment]
Need to wait for the reproduction of #6217
