### ISSUE TITLE
Text selection across lines not work on making text bold

### ISSUE THREAD

**Issue by yunnian** [toeverything/blocksuite#6220]
selection not work at latest master code:

https://github.com/toeverything/blocksuite/assets/5779513/25a800d0-c850-49ae-ba4f-4dbaafb406c8

**Comment by ununian** [comment]
I'm fine with this modification, but I don't know if there are any side effects

<img width="1214" alt="image" src="https://github.com/toeverything/blocksuite/assets/4506072/2767a5df-6838-4aee-a7ab-08738e7a784c">

**Comment by yunnian** [comment]
still errors：

https://github.com/toeverything/blocksuite/assets/5779513/79d9ce25-4e43-4d41-b1c9-03a5c5d1acca

**Comment by fourdim** [comment]
To reproduce:
| indicates selection:
```
|aaa
bbb
|
```
The button fails when an empty paragraph present in the selection area.

**Comment by yunnian** [comment]
I find another one :

https://github.com/toeverything/blocksuite/assets/5779513/1e252519-fe04-4230-b7c1-fc5833dcbaa2

**Comment by Flrande** [comment]
> I find another one :
> 
>  20240221-193729.mp4

fixed in https://github.com/toeverything/blocksuite/pull/6261
