### ISSUE TITLE
​Copy paste a group in edgeless mode doesn't not create the result expected

### ISSUE THREAD

**Issue by laurenth-personal** [toeverything/blocksuite#6242]
### What happened?

I copied and pasted a group composed of a shape with text + an image (from the monthly calendar template).
The result of the paste was not a group, it was a shape and an image separated, and their display order was incorrect ( the image was behind the shape whereas in the original group the image was in front). This make the usage of this kind of group almost unusable.

### Distribution version

macOS ARM 64 (Apple Silicon)

### Anything else?

I got the same issue on PC

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by regischen** [comment]
@laurenth-personal Do you copy by short-cut or by clicking button in more option? 
Could you take a video and tell me the version?
