### ISSUE TITLE
Inherit rich text attributes from the end of last list item

### ISSUE THREAD

**Issue by TanmayChhatbar** [toeverything/blocksuite#6246]
### Description

Text properties seem to be inherited from the text before the cursor. 

### Use case

If I have the following list
- [ ] test 1
- [ ] **test 2**
- [ ] _test 3_

and want to edit the second element to 
- [ ] **new text here - test 2**

when I start typing before **test 2**, the text is not emboldened and instead types like this, probably because there is no text before it to inherit from.
- [ ] new text here - **test 2**

It makes sense to me to allow inheritance from text after and before. 
In case typing between different text properties, there is always a space between different text properties, and the property of the new text can be inherited based on the location of the cursor.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
@Flrande this seems to be reasonable to implement if when adding a new list item, we assign the style of it using the end point of its previous sibling.
