### ISSUE TITLE
Add cross-marks for checklists

### ISSUE THREAD

**Issue by TanmayChhatbar** [toeverything/blocksuite#6247]
### Description

Would like more than binary state for a checklist. A right click could mean a cross-mark

### Use case

If I have 10 elements in the checklist, of which I cannot perform one task, I'd like to right-click on its checkbox to highlight that an explicit negative marker on the element. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for the feedback, the best practice here should be using the field in database block, which supports configurable enums as states. Also, we have plans on right click context menu, so there could be conflicts if right click is added for new operations.

<img width="1053" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/7f0015f9-7ddf-405b-915f-725a0ef9b525">
