### ISSUE TITLE
About Hidden on Pagee

### ISSUE THREAD

**Issue by kankanai** [toeverything/blocksuite#6280]
![image](https://github.com/toeverything/blocksuite/assets/142068366/94e824e7-9e0c-40c4-a067-a346ee461d3c)
May I ask what its function is? I clicked on it, but nothing happened

**Comment by doodlewind** [comment]
Hi there, this will hide this note block in page mode. The basic structure of the note block is clarified at https://blocksuite.io/components/blocks/note-block.html. Also, we plan to make it a configurable widget.
