### ISSUE TITLE
​Does the image support left alignment?

### ISSUE THREAD

**Issue by geekvee** [toeverything/blocksuite#6298]
### Description

Does the image support left alignment?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for the feedback. For now the product design doesn't involve the alignment option in image. For this customization, the better approach FTM may to start from https://blocksuite.io/guide/working-with-block-tree.html#defining-new-blocks with new custom blocks.
