### ISSUE TITLE
Caret position is incorrect when selecting list block

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#6307]
To reproduce:
1. Add a list block.
2. Select the block.
3. Click at blank area below the block.

<img width="317" alt="Screenshot 2024-02-27 at 16 26 24" src="https://github.com/toeverything/blocksuite/assets/99816898/0d4309a1-ba8c-4048-9e4c-963784a87c9f">

https://github.com/toeverything/blocksuite/assets/99816898/9b0e5db9-dd32-442b-8ea3-a8bf6e3c8869

**Comment by JunIce** [comment]
Already fixed.
