### ISSUE TITLE
In which version is adapter.fromDocSnapshot available?

### ISSUE THREAD

**Issue by kyrylolvov** [toeverything/blocksuite#6310]
I am currently using `0.12.0-canary-202402230902-f7fe5ae` and it gives me an error that this function is not defined.

**Comment by kyrylolvov** [comment]
@doodlewind Is there a way to install 0.12.0? I tried updating my packages, but it says its the latest version, and on npmjs it is also 0.11.0.

**Comment by doodlewind** [comment]
I've confirmed that `0.12.0` is published, but in this version the API should be `adapter.fromPageSnapshot`, the doc site is using the latest version after the overall API update in #6290.

**Comment by kyrylolvov** [comment]
> I've confirmed that `0.12.0` is now published, but in this version the API should be `adapter.fromPageSnapshot`, the doc site is using the latest version after the overall API update in #6290.

Is the API update going to be in the next version published?
