### ISSUE TITLE
There is only one template classification

### ISSUE THREAD

**Issue by kankanai** [toeverything/blocksuite#6320]
![image](https://uploads.linear.app/4e3f1dbd-f59e-4e5e-9633-f566045a86e7/cd6cab50-443d-4b67-9f94-74ef91c97ebf/caba1fd6-8c4d-44da-a9ac-7a509f9456fd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRlM2YxZGJkLWY1OWUtNGU1ZS05NjMzLWY1NjYwNDVhODZlNy9jZDZjYWI1MC00NDNkLTRiNjctOWY5NC03NGVmOTFjOTdlYmYvY2FiYTFmZDYtOGM0ZC00NGRhLWE5YWMtN2E1MDlmOTQ1NmZkIiwiaWF0IjoxNzEwMTU4NzI4LCJleHAiOjMzMjgwNzE4NzI4fQ.ws1hbkUh7Iu0JjZWWBM-wxt65cQqdclE-kaQSGQI59c)

**Comment by doodlewind** [comment]
The blocksuite playground only supports limited content for basic demo. If you want to extend the template, you could refer to https://github.com/toeverything/AFFiNE/blob/canary/packages/frontend/core/src/bootstrap/edgeless-template.ts and https://github.com/toeverything/AFFiNE/blob/canary/packages/frontend/templates/edgeless-templates.gen.ts about extending the built-in templates.
