### ISSUE TITLE
​Issue with Korean Typing: Korean Characters Unraveling

### ISSUE THREAD

**Issue by pppaapp** [toeverything/blocksuite#6323]
### What happened?

![CleanShot 2024-02-28 at 01 20 14](https://github.com/toeverything/AFFiNE/assets/31263588/35d752e7-ed43-4ca0-8af6-70220c751560)

I am experiencing an issue when the Korean characters unravel as I type. 

For example, when I type "밈밈밈," it appears as "ㅁㅣㅁㅁㅣㅁㅁㅣㅁ." 

This makes it difficult to input text correctly in Korean.

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by pengx17** [comment]
I am not familiar with how to type Korean. I tried install Korean language with the default IME on windows, it seems that jamo conjoining works correctly. I will try again on a Mac later.

**Comment by pengx17** [comment]
It also works on Mac:
https://github.com/toeverything/blocksuite/assets/584378/34a79c08-0c34-45a9-872f-cb9dc410fd0a

**Comment by pppaapp** [comment]
> It also works on Mac:
> 
>  Kapture.2024-04-24.at.18.24.01.mp4

The issue has been resolved. I checked today, and I'm not experiencing any problems either
