### ISSUE TITLE
Support pages in database records

### ISSUE THREAD

**Issue by hkfi** [toeverything/blocksuite#6336]
### Description

Are there any plans to support pages for database records like the way Notion does?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fourdim** [comment]
After notion import, the page reference is only visible in editing mode.
Moreover, it's now not possible to reference a page in the first column of database by entering `@` .
<img width="850" alt="image" src="https://github.com/toeverything/blocksuite/assets/59462000/16e3eecc-23b5-4d43-929e-9dd8baf84cb2">

It might be a regression.
