### ISSUE TITLE
May I ask how to listen for any content changes on a webpage?

### ISSUE THREAD

**Issue by kankanai** [toeverything/blocksuite#6339]
‌‌‌I tried adding the following code in the async push method in src/doc/impl/indexeddb.js: 
`async push(docId: string, data: Uint8Array): Promise<void> {console.log("update data")window.postMessage( { type: 'async_note_data'  }, '*');`
But the problem is that it seems to work sometimes and not others.Where should I add it in which file to ensure that it can listen to every user operation?

**Comment by doodlewind** [comment]
I think you can try [`doc.slots.blockUpdated`](https://blocksuite.io/api/@blocksuite/store/classes/Doc.html#blockupdated) or [`workspace.slots.docUpdated`](https://blocksuite.io/api/@blocksuite/store/classes/Workspace.html#docupdated)?
