### ISSUE TITLE
The text in the PDF appears as gibberish​

### ISSUE THREAD

**Issue by StudyingLover** [toeverything/blocksuite#6386]
### What happened?

The text in the PDF appears as gibberish on self-hosted affine. you can download the pdf on https://bbabenko.github.io/assets/papers/paper_gestalt.pdf

![image](https://github.com/toeverything/AFFiNE/assets/68844494/9a7dc3b0-c8fa-48b7-bc05-d22074e1e79e)

![image](https://github.com/toeverything/AFFiNE/assets/68844494/8b6a1cc8-000e-4ac9-a5b8-b0f6bbca70b3)

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by EYHN** [comment]
The pdf preview feature doesn't seem to work correctly

**Comment by zkwolf** [comment]
add the mime info that saved in IndexedDB to blob can resovle it, but it seems that desktop version save blob to sqlite and don't have mime info.

**Comment by EYHN** [comment]
We can no longer rely on blob mime information because there is too much bad data in there now.
