### ISSUE TITLE
Kanban optimization

### ISSUE THREAD

**Issue by LIHAQ** [toeverything/blocksuite#6417]
### Description

Now the Kanban function can only fill properties
![image](https://github.com/toeverything/AFFiNE/assets/57976650/96dbe742-16b8-4d35-a7ee-807fa25faa8a)

Can you, like notion, have page functionality in addition to padding attributes
![image](https://github.com/toeverything/AFFiNE/assets/57976650/5eb0ccd1-22ce-4179-b01f-31f1e84148c5)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by houjoe0829** [comment]
Just to confirm, do you mean you want to have a free editing area to freely fill in content after opening a Card in a Kanban?
