### ISSUE TITLE
Moving the cursor carriage to a new line works every second time on pressing "Enter" key in angular

### ISSUE THREAD

**Issue by anna-fedosova-hs** [toeverything/blocksuite#6431]
The project that was launched for the attached video: https://github.com/toeverything/blocksuite/tree/master/examples/angular-basic

**Current behaviour**: moving the cursor carriage to a new line works every second time on pressing "Enter" key

**Expected behaviour**: pressing "Enter" key moves the cursor carriage to a new line every time

https://github.com/toeverything/blocksuite/assets/82090596/f6ddf75e-dba7-41c2-8c18-118d921887b5

**Comment by doodlewind** [comment]
Thanks for the feedback! Seems to be an angular-only issue. We'll try and hope anyone familiar with this framework could provide some guidance about how to fix 🙏

/cc @Flrande @fourdim

**Comment by andantonyan** [comment]
@anna-fedosova-hs @doodlewind 

The main issue is related to the zone.js library. A tmp workaround is to use the Angular app without zone.js. For example, when attempting to add a numbered list, it throws an error `BlockSuiteError: RichText is not ready yet` and then the cursor carriage started not to work as expected.


```ts
// app.config.ts
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    {
      provide: NgZone,
      useClass: ɵNoopNgZone
    }
  ],
};
```

Next, remove zone.js from the polyfills section in the angular.json file:

```json
{
  "options": {
    ...
    "polyfills": [],
    ...
  }
}
```

**Comment by anna-fedosova-hs** [comment]
@doodlewind Thank you for the proposed solution! My team and I checked it out and, to our great regret, realised that the option when we have to use our Angular app without zone is completely impossible for us to implement, because our project will not be able to work properly. Is there any chance that you have plans to implement some more fundamental solution to this problem? Thank you in advance!

**Comment by fourdim** [comment]
> @doodlewind Thank you for the proposed solution! My team and I checked it out and, to our great regret, realised that the option when we have to use our Angular app without zone is completely impossible for us to implement, because our project will not be able to work properly. Is there any chance that you have plans to implement some more fundamental solution to this problem? Thank you in advance!

Will change [changeDetection?](https://angular.io/api/core/Component#changeDetection) to `OnPush` works for you?

**Comment by andantonyan** [comment]
I did some debugging and found that the issue occurs when zone.js patches the requestAnimationFrame and Promise, and it is not related to the change detection strategy. If you disable the zone.js patching for requestAnimationFrame and Promise, the issue will be resolved.

Here is an example of how you can disable the zone.js patching for requestAnimationFrame and Promise:

```json
// angular.json
{
  ...
 "polyfills": ["src/zone-flags.ts", "zone.js"],
}
```

```ts
// zone-flags.ts
window.__Zone_disable_requestAnimationFrame = true;
window.__Zone_disable_ZoneAwarePromise = true;

declare interface Window {
  __Zone_disable_requestAnimationFrame: boolean;
  __Zone_disable_ZoneAwarePromise: boolean;
}
```

```json
// tsconfig.app.json
{
  ...
 "files": ["src/zone-flags.ts", "src/main.ts"],
}
```
