### ISSUE TITLE
​Linking into any item on edgeless

### ISSUE THREAD

**Issue by kmlkcl** [toeverything/blocksuite#6439]
### Description

From my previous experience with Miro, I'm pretty sure it'll quickly become an issue to navigate in a huge whiteboard. So we put links to items which teleport us to appropriate place 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Sorry for the delay. This is supported in https://github.com/toeverything/blocksuite/pull/5013 and landed from AFFiNE 0.10.

You can see this product feature in https://affine.pro/blog/affine-0-10-0-launch-week-day-3-5-make-your-mind-flow-form-doc-to-slides
