### ISSUE TITLE
Inconsistent result between `addBlockByFlavour` and `addBlock`

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#644]
https://github.com/toeverything/blocksuite/pull/641#discussion_r1065510385

**Comment by himself65** [comment]
What is the error log

**Comment by Himself65** [comment]
What is the error log

**Comment by doodlewind** [comment]
> What is the error log

Should be able to reproduce by `test.only` on that test case.

**Comment by himself65** [comment]
I see, this not because inconsistent, because you delete the block
