### ISSUE TITLE
Assistance Needed with Implementing BlockSuite in Next.js Environment 😢

### ISSUE THREAD

**Issue by DevGlyph** [toeverything/blocksuite#6452]
Hello BlockSuite Team! 👋

First off, I want to express my profound admiration for the BlockSuite project. It's genuinely the most impressive editor project I've encountered, and I'm incredibly grateful for the open-source community's spirit and willingness to help that you exemplify. The creativity and innovation here are truly inspiring.

I'm currently embarking on integrating BlockSuite into a Next.js project and have been closely following the examples provided, specifically /example/react-basic and /examples/react-sqlite, as excellently demonstrated by @doodlewind . Unfortunately, I've encountered a stumbling block in my journey. I'm facing an error that appears to indicate BlockSuite's current incompatibility with SSR (Server-Side Rendering) mode:

```
unreachable
unreachable
unreachable
unreachable
unreachable
Error: Seems like you are importing @blocksuite/blocks in SSR mode. Which is not supported for now.
```

In an attempt to circumvent this issue, I've tried including `use client` at the top of my file and leveraging Next.js's `dynamic` import feature with `{ ssr: false }` option, aiming to import the EditorContainer component client-side only. Unfortunately, these attempts haven't resolved the error, leaving me a bit puzzled on how to proceed correctly.

```
const Editor = dynamic(
    () => import("../blocksuite/components/EditorContainer"),
    { ssr: false },
);
```

Could you kindly offer some guidance on how to properly use BlockSuite within a Next.js project, similar to how the examples are set up? Any advice or pointers to steer me in the right direction would be immensely appreciated. I'm really excited about integrating BlockSuite into my project and would love to overcome this hurdle with your expert help.

Thank you so much for your time, and once again, for your incredible work on this project. Looking forward to your response!

**Comment by doodlewind** [comment]
Thanks for your feedback! I think adding a react-next example could be adequate. Will try and investigate.
