### ISSUE TITLE
Example of customizing Copilot Panel in Format Bar

### ISSUE THREAD

**Issue by kyrylolvov** [toeverything/blocksuite#6468]
Hello! Is there any example on how to customize the "Ask AI" dropdown in Format Bar. In a way to pass custom items in it, and have custom logic of sending text and then applying it to the document.

**Comment by kyrylolvov** [comment]
@doodlewind @Flrande

**Comment by kyrylolvov** [comment]
I just saw this PR https://github.com/toeverything/blocksuite/pull/6433, I believe I can just add my own buttons with functionality there. But some of the functions used there are not available in 0.12.0. @doodlewind

**Comment by Flrande** [comment]
> I just saw this PR #6433, I believe I can just add my own buttons with functionality there. But some of the functions used there are not available in 0.12.0. @doodlewind

We will soon release version 0.13, during this period if you want to use the latest features please use the canary version.

**Comment by doodlewind** [comment]
Seems to be resolved in #6477 and 0.13 is also release. Thanks for the feedback!
