### ISSUE TITLE
Children lost after deleting at line start

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#648]
Initial state:

```
123
  456
789
```

After deleting at the beginning of `123`, its child `456` is lost.

https://user-images.githubusercontent.com/7312949/211546024-f4cfec04-13f5-4571-a9cf-254495202b72.mov

**Comment by SteinsHead** [comment]
And I found that if u try to add carriage return, the current line will change to under the children line. And I will try to figure out why dose this problem occer.


https://user-images.githubusercontent.com/50788736/212471013-a1b2d05a-3c80-4e90-b6c0-a36593cee2af.mov

**Comment by SteinsHead** [comment]
Sorry for the video so small, I will re-upload a clearer version.


https://user-images.githubusercontent.com/50788736/212471181-3decb028-eb73-4eab-bc93-c9faa28bde3e.mov

**Comment by himself65** [comment]
I've seen this bug in the database block. This need to be fixed ASAP

**Comment by himself65** [comment]
> Sorry for the video so small, I will re-upload a clearer version.
> 
>  2023-01-14.20-15-04.mov

This is an expected behavior but not correct. Because `456` is a child of the original `123`. You press enter, then `123` go to the next line which is should be top of the `789`

**Comment by himself65** [comment]
We should carry the children of a model when the user press enter or backspace

**Comment by himself65** [comment]
I think the correct logic is when you append a block, you should bring the old data into the new one, and when you delete a block, you should bring data to the father

**Comment by SteinsHead** [comment]
> I think the correct logic is when you append a block, you should bring the old data into the new one, and when you delete a block, you should bring data to the father

I tried to modify the same file in the code, but did not fix the problem. Do I need to make additional changes？

**Comment by himself65** [comment]
I'm fixing this. PR will coming soon

**Comment by SteinsHead** [comment]
Ok, thank you so much 😘

**Comment by himself65** [comment]
PR has opened, but it needs some E2E tests. Welcome everyone who wants to contribute it

**Comment by doodlewind** [comment]
I haven't noticed that this has been fixed, great work here!

Also, according to my inaccurate memory, I thought maybe this was possibly introduced by #479, so /cc @lawvs
