### ISSUE TITLE
Incorrect export hierarchy when children are lists

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#6492]
Incorrect export hierarchy when child nodes are lists

Expected

```md
# BlockSuite Playground

text1

  * child

```

but

```md
# BlockSuite Playground

text1

* child
```

<img width="623" alt="Screenshot 2024-03-16 at 12 51 55" src="https://github.com/toeverything/blocksuite/assets/18554747/1864644d-8908-4914-8f6f-486306a59f7c">

**Comment by fourdim** [comment]
Markdown paragraphs cannot have any children.
