### ISSUE TITLE
​Images that support markdown syntax

### ISSUE THREAD

**Issue by iqiuzixuan** [toeverything/blocksuite#6499]
### Description

Is there a plan for this?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by doodlewind** [comment]
Thanks for the feedback! This relates to a very early design decision in BlockSuite that we are not storaging "raw markdown" as its source of truth. In other word, the image content is not stored as the `![src](url)` string, making it complex to support this types of syntax - so we may not have resource work for first-party support for this feature recently.

But pasting with markdown image syntax is supported, and during editing, typing the `/image` with slash menu should be more intuitive.
