### ISSUE TITLE
Drag-and-drop PDF files are not working​

### ISSUE THREAD

**Issue by bigint** [toeverything/blocksuite#6513]
### What happened?

Drag-and-drop PDF files are not working​

https://github.com/toeverything/AFFiNE/assets/69431456/4bcfaf95-38ef-4895-9bd0-1d2deb5d82b9

### Distribution version

Web (insider.affine.pro)

### Are you self-hosting?

- [ ] Yes

**Comment by CatsJuice** [comment]
After testing, it seems that it's not just pdf files, this should be a bug of blocksuite.

**Comment by doodlewind** [comment]
@donteatfriedrice PTAL since this and #6386 seems to have higher impact to users.
