### ISSUE TITLE
Unable to work with editor after closing file selection model without selecting the file

### ISSUE THREAD

**Issue by RajaTheKing826** [toeverything/blocksuite#6568]
Found this bug in your playground too. 
Steps to reproduce
1. In page editor select insert image option in slashbar
2. Dont upload file just close the file selection model
3. Try to add some text now nothing will happen, you cannot add new element and you can't even enter text too

![Peek 2024-03-26 10-57](https://github.com/toeverything/blocksuite/assets/59301270/629448eb-15e1-485c-bfb6-316b4e4ae737)

**Comment by lawvs** [comment]
I can't reproduce this issue on my computer, can you provide more detailed information about this issue?

https://github.com/toeverything/blocksuite/assets/18554747/78225e9b-5760-430e-a39b-e69a8e6d2676

**Comment by zkwolf** [comment]
use `/image` can reproduce

**Comment by RajaTheKing826** [comment]
> I can't reproduce this issue on my computer, can you provide more detailed information about this issue?
> 
>  Screen.Recording.2024-03-26.at.18.22.45.mov

use /image you can reproduce it
