### ISSUE TITLE
Unable to use note block after inserting a table in Edgeless editor.

### ISSUE THREAD

**Issue by RajaTheKing826** [toeverything/blocksuite#6631]
I have created a table in a note block, and i tried to insert a new line at the end of the table but i didn't get slash popover to enter element. 

Steps to reproduce.
1. Open edgeless editor
2. Insert a note block by selecting note icon
3. insert a table view
4. Click bottom of the table view to enter new content you cant use it

Please check this.

**Comment by RajaTheKing826** [comment]
@Flrande  can you please check this

**Comment by Flrande** [comment]
We should add a new line when we click the spacing area of the blocks.

**Comment by RajaTheKing826** [comment]
@golok727  Ive missed to add a data point that this issue is coming for youtube, figma, code block, image these kind of blocks

**Comment by golok727** [comment]
> @golok727 Ive missed to add a data point that this issue is coming for youtube, figma, code block, image these kind of blocks

Will close all those in the PR
