### ISSUE TITLE
​can AFFiNE support math formula?

### ISSUE THREAD

**Issue by PiggyRan** [toeverything/blocksuite#6655]
### Description

I found that I can write math formula in AFFiNE by using form like `$$a=b$$` or `$a=b$`. So, how can I input a math formula?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CatsJuice** [comment]
Duplicated with #4826

**Comment by Flrande** [comment]
https://github.com/toeverything/blocksuite/issues/3014#issuecomment-1911551596
