### ISSUE TITLE
Database element content is not saved​

### ISSUE THREAD

**Issue by MarArMar** [toeverything/blocksuite#6667]
### What happened?

Check example

1st time user, started using Affine so the version is less than 1 hour old downloaded from the official website

I created a database, clicked an entry, edited the content, it never saves & disappears each time, this is completely unusable at the moment

![Bug missing content](https://github.com/toeverything/AFFiNE/assets/136232300/049ddc1c-a9ad-43f5-aa06-078ef411c0c5)

### Distribution version

Windows x64

**Comment by EYHN** [comment]
@zzj3720 I feel like that area should be uneditable?

**Comment by EYHN** [comment]
![CleanShot 2024-04-02 at 11 31 30](https://github.com/toeverything/blocksuite/assets/13579374/d8ff2553-8ddd-429a-80b5-5c5fb0549231)

@MarArMar  We will support link doc in the database in the next version

**Comment by zzj3720** [comment]
This place should not be editable, it's fixed in https://github.com/toeverything/blocksuite/pull/6588

**Comment by zzj3720** [comment]
> But I want to use this space to take long form notes on this ?
> 
> I am coming from Notion, I do this all the time

That feature is in the plans now.
