### ISSUE TITLE
Global types is not reachable in downstream package

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#667]
For the affine repo, we cannot read the global types https://github.com/toeverything/blocksuite/blob/6129124dcc844337f75db9cb68c002bc9a886b53/packages/global/src/index.d.ts

**Comment by himself65** [comment]
Option 1: we modify the vite build to copy the global types into bundled files
Option 2: we change the global env to an import env, and publish the package as `@blocksuite/global`
Option 3: this is not a bug, it's a feature
