### ISSUE TITLE
Updated version returning errors 

### ISSUE THREAD

**Issue by RajaTheKing826** [toeverything/blocksuite#6678]
I have updated my blocksuite packages and copied play ground related code to my react application and then i tried to render the editor 
then i got below error. Can anyone tell me what am i missing.

Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "v-element" has already been used with this registry

**Comment by doodlewind** [comment]
This error indicates that you have executed the `customElements.define("my-element", MyElement)` for multiple times. Making sure you don't install multiple versions of BlockSuite could help. You can also refer to the [BlockSuite examples](https://github.com/toeverything/blocksuite/tree/master/examples) to see the react environments that should work.

**Comment by mxy2316868975javascript** [comment]
![Uploading image.png…]()

**Comment by mxy2316868975javascript** [comment]
> I have updated my blocksuite packages and copied play ground related code to my react application and then i tried to render the editor then i got below error. Can anyone tell me what am i missing.
> 
> Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "v-element" has already been used with this registry

解决了吗

**Comment by EddiePengg** [comment]
现在轮到我遇到这个问题了

![Uploading image.png…]()
