### ISSUE TITLE
First block not reachable in drag handle

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#669]
Refs: https://github.com/toeverything/AFFiNE/pull/714

**Comment by himself65** [comment]
I think there is a bug in binary search

**Comment by himself65** [comment]
> In the following example, A also cannot be dragged behind B, but can only be made a child of it.
> 
> <img alt="Screenshot 2023-01-12 at 4 30 29 PM" width="270" src="https://user-images.githubusercontent.com/27926/212016623-cfd53d53-2731-461c-b3b4-b06eb090ea0e.png">
> 
> A dirty solution is to place non-editable blocks before and after the document to provide boundary checking.

Have you found the bug? could you please describe it because I have no time to do it

**Comment by fundon** [comment]
I want to move A after B, but not a child of B. The current move can only be a child of B.

I'd like to think of a good solution to try to fix it.

**Comment by himself65** [comment]
https://user-images.githubusercontent.com/14026360/212215775-f64e0bc9-e6cc-4439-865d-d74e4de5cf30.mov

**Comment by himself65** [comment]
I found that the data structure is incorrect, the blocks[0] is actually the blocks[1]

**Comment by himself65** [comment]
re-assigned to @thorseraq
