### ISSUE TITLE
Can we hide the icon under the title bar? 

### ISSUE THREAD

**Issue by EnterMan123** [toeverything/blocksuite#6706]
### Description

Can we hide the icon under the title bar? This makes the table look better

![Snipaste_2024-04-09_11-10-58](https://github.com/toeverything/AFFiNE/assets/107846196/56adbff7-52e0-4125-abf3-81fb24bee91b)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by CatsJuice** [comment]
@hwangdev97 cc

**Comment by hwangdev97** [comment]
We have not yet provided this feature. 🤔
