### ISSUE TITLE
let fonts in public folder pls...

### ISSUE THREAD

**Issue by jooler** [toeverything/blocksuite#6729]
use vue quick start,
but use Quasar as 9000 port

![aaa](https://github.com/toeverything/blocksuite/assets/25960405/cfe0dfdc-71e4-4be8-9e84-a46cd1f64f82)

**Comment by Flrande** [comment]
https://github.com/toeverything/blocksuite/issues/6209

Does this issue not solve your problem?

**Comment by Nagendra7509** [comment]
@Flrande @doodlewind 

any update on this issue?

**Comment by Flrande** [comment]
Closed in #7045
