### ISSUE TITLE
How to play around with toolbar?

### ISSUE THREAD

**Issue by mirtaqi07** [toeverything/blocksuite#6751]
Hi, I'm just a beginner with electron and this whole Affine project is a nightmare for me. I mean this is much more sophisticated, well structured and I find it difficult to understand it.

There's no proper documentation for editing the tools. I couldn't find. Can somebody please help me how to edit the main toolbar buttons, remove or shuffle them, where button shortcuts are being enabled and how to disable press “/” to see commands? I hope you understand what I want. I'll really appreciate if you help me more with a little guide tour.

Thanks!

![Screenshot_2024-04-14-16-56-33-511_com android chrome](https://github.com/toeverything/blocksuite/assets/88597955/714a59ad-c755-42e5-8d06-eb4b8735284a)

I've posted this already in technical discussion in Affine community, but it seems like not very active.

https://community.affine.pro/c/techincal-discussion/how-to-play-around-with-toolbar

**Comment by donteatfriedrice** [comment]
Hi, thank you for your interest in AFFiNE and BlockSuite. Currently, you can modify the UI of the whiteboard's main toolbar at https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/root-block/edgeless/components/toolbar/. You can define the specific behavior of each tool at https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/root-block/edgeless/controllers/tools/. Additionally, you can set keyboard shortcuts in the file https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts.

However, the configurability and flexibility of the main toolbar are currently limited. We may refactor this part of the code in the future to improve the configurability and flexibility of the toolbar, but it may take some time.

**Comment by golok727** [comment]
> Hi, I'm just a beginner with electron and this whole Affine project is a nightmare for me. I mean this is much more sophisticated, well structured and I find it difficult to understand it.
> 
> There's no proper documentation for editing the tools. I couldn't find. Can somebody please help me how to edit the main toolbar buttons, remove or shuffle them, where button shortcuts are being enabled and how to disable press “/” to see commands? I hope you understand what I want. I'll really appreciate if you help me more with a little guide tour.
> 
> Thanks!
> 
> ![Screenshot_2024-04-14-16-56-33-511_com android chrome](https://private-user-images.githubusercontent.com/88597955/322270974-714a59ad-c755-42e5-8d06-eb4b8735284a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTk3ODIsIm5iZiI6MTcxMzE1OTQ4MiwicGF0aCI6Ii84ODU5Nzk1NS8zMjIyNzA5NzQtNzE0YTU5YWQtYzc1NS00MmU1LThkMDYtZWI0Yjg3MzUyODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1MzgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMmUwM2E2NGIyOGQwYjM3ZDQ3YzkyYTBhMTc5MDU2ODZiZDE3ZWI2MzAzY2VkMjhjNzU4NGFmZjQ4YzUxMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mvaWjk7p0xX3BQ-t4rnHozhcHxEt4xx4JzJNw5PP5RI)
> 
> I've posted this already in technical discussion in Affine community, but it seems like not very active.
> 
> https://community.affine.pro/c/techincal-discussion/how-to-play-around-with-toolbar

## Toolbar 
https://github.com/toeverything/blocksuite/tree/master/packages/blocks/src/root-block/edgeless/components/toolbar

## Keyboard Shortcuts for edgeless 
https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts

## Slash menu
https://github.com/toeverything/blocksuite/tree/master/packages/blocks/src/root-block/widgets/slash-menu

**Comment by mirtaqi07** [comment]
@donteatfriedrice Thanks alot bro. Actually I was using affine and now I know it's built on blocksuite. Thanks for the help, that means a lot.

Can you help me how to convert this blocksuite to desktop application?

Have a wonderful day!

**Comment by donteatfriedrice** [comment]
There are currently no desktop app examples in our given examples https://github.com/toeverything/blocksuite/tree/master/examples,

but you can refer to the examples in the directory, choose a framework you are familiar with to build a todo mvc application based on blocksuite, and then combine it with some desktop development frameworks, such as electron, to build a desktop application.
