### ISSUE TITLE
Press Enter in the editor to add lines and automatically scroll to the bottom

### ISSUE THREAD

**Issue by xiaofeiniuuu** [toeverything/blocksuite#6773]
The judgment condition in the rich-text component is for window.innerHeight
How does my editor determine whether to scroll based on the parent of affine-editor-container?

![image](https://github.com/toeverything/blocksuite/assets/29246287/43005eab-f4da-4464-9794-3e1b72f4a620)

**Comment by Flrande** [comment]
fixed in #6965
