### ISSUE TITLE
​Copy Paste issue

### ISSUE THREAD

**Issue by headerloc215** [toeverything/blocksuite#6782]
### What happened?

When i try to copy a few characters on the first line, it pastes the whole bullet point and sub bullet points (see screenshot, i'm trying to hide info but still give enough for you to see possible characters affecting code). For example if i copy 1 word, or a few letters, it pastes the whole paragraph from top to bottom. I tried creating a new bullet point with jibberish text but i didn't get any copy paste issues.

![image](https://github.com/toeverything/AFFiNE/assets/121714184/fb84fad7-4746-4e33-b183-5ce7c8eed9ad)

### Distribution version

Linux

### Are you self-hosting?

- [ ] Yes

**Comment by fourdim** [comment]
Already fixed in #5901. There still needs some time to see this fix in the official release.
