### ISSUE TITLE
Unable to use editor with more notes, entire chrome tab getting stucked. 

### ISSUE THREAD

**Issue by RajaTheKing826** [toeverything/blocksuite#6793]
When i run my react app with edgeless editor, its taking nearly 1.4GB memory and my chrome getting stuck like anything, and i am unable to open that page again. 

Can anyone look into this. We are unable to do a small action if the data is more in whiteboard.
But same thing working fine in firefox.

**Comment by upender7270** [comment]
Just as I was about to hit 'send' on this pesky issue I've been wrestling with, a light bulb went off – it turns out, I'm not the only one grappling with it.

So, before I hit the panic button, I thought I'd reach out to this awesome community for some collective brainpower. If anyone's got a map to smoother seas or a toolkit for troubleshooting, please drop me a line. Let's team up and conquer this challenge together!"

**Comment by Praneetha1219** [comment]
Even I'm facing the same issue. Kindly please look into it.

Thank you

**Comment by fundon** [comment]
> When i run my react app with edgeless editor, its taking nearly 1.4GB memory and my chrome getting stuck like anything, and i am unable to open that page again. 
> 
> 
> 
> Can anyone look into this. We are unable to do a small action if the data is more in whiteboard.
> 
> But same thing working fine in firefox.
> 
> 

Can you share your app and how many elements are on the edgeless?

**Comment by RajaTheKing826** [comment]
I can't share my react app as it is confidential, instead i can share the Json data which i convert as snapshot doc.
Hope this is fine.

Here you can find the json data -> https://codesandbox.io/p/sandbox/testdata-qsgkfj?file=%2Fsrc%2Fdata.json%3A26684%2C15

**Comment by RajaTheKing826** [comment]
@fundon  I think this is fine and you are working on this

**Comment by RajaTheKing826** [comment]
@fundon  any update on this

**Comment by fundon** [comment]
> @fundon any update on this

Sorry, I'll spend some time on this in the next couple of days.

**Comment by Nagendra7509** [comment]
Could you please prioritize addressing this issue as soon as possible? It's a critical blocker for us, rendering the app unusable due to frequent freezing.

**Comment by RajaTheKing826** [comment]
@golok727  Do you have any insights in this?

**Comment by doodlewind** [comment]
Thanks for the feedback. We've observed and reproduced significant performance regression in edgeless. But since our team were mainly working on new product features in the past weeks, optimization were not actually prioritized. 

So in the incoming housekeeping stage, this would be tracked together with other usability blockers.

cc @doouding

**Comment by doouding** [comment]
@RajaTheKing826 Hi Raja, could you please export the data so I can reproduce the problem? You can remove any sensitive information as long as the issue remains.

**Comment by doouding** [comment]
Thanks, that helps a lot.

**Comment by Nagendra7509** [comment]
@doouding any update??

**Comment by doouding** [comment]
Yeah， Im working on it right now. The reason is that the editor try to render all the blocks at same time. And it would take massive time if there're too many blocks. I try to split the rendering into different parts but I'm not sure if this would work.

**Comment by doouding** [comment]
Hi, we just shipped some optimizations related to this issue. You can update your dependencies to the latest canary [0.15.0-canary-202405160654-a3008e5](https://www.npmjs.com/package/@blocksuite/blocks/v/0.15.0-canary-202405160654-a3008e5) to see if the problem has been resolved or mitigated.

**Comment by doouding** [comment]
This issue has been resolved. If you are still experiencing this problem, feel free to reopen it.

**Comment by doouding** [comment]
https://github.com/toeverything/blocksuite/pull/7068
