### ISSUE TITLE
Undo/redo not avaliable in title

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#682]

**Comment by doodlewind** [comment]
The undo/redo hotkey doesn't trigger `page.undo|redo` when editing `textarea`. Using the `undoByClick` should work but the cursor is not kept.

**Comment by lawvs** [comment]
> The undo/redo hotkey doesn't trigger `page.undo|redo` when editing `textarea`. Using the `undoByClick` should work but the cursor is not kept.

I skipped title undo/redo in https://github.com/toeverything/blocksuite/pull/548 (https://github.com/toeverything/blocksuite/pull/548/commits/01e55bee5f88e8f4b92b4a845ea50c7969db8f27) to prevent undo sometimes triggers multiple times（native textarea undo and hotkey undo occur together）

https://github.com/toeverything/blocksuite/blob/b09db146d9f282b7d095e130b6ac68f260ad74d3/packages/blocks/src/page-block/utils/bind-hotkey.ts#L28-L39

**Comment by doodlewind** [comment]
> > The undo/redo hotkey doesn't trigger `page.undo|redo` when editing `textarea`. Using the `undoByClick` should work but the cursor is not kept.
> 
> I skipped title undo/redo in #548 ([01e55be](https://github.com/toeverything/blocksuite/commit/01e55bee5f88e8f4b92b4a845ea50c7969db8f27)) to prevent undo sometimes triggers multiple times（native textarea undo and hotkey undo occur together）
> 

This should do the trick, is anyone trying for a PR?

``` ts
if (isPageTitle(e)) { 
  e.preventDefault();
} 
page.undo();
```
