### ISSUE TITLE
Pressing enter at the line start of a dragged block wrongly creates a duplicate block

### ISSUE THREAD

**Issue by jackeydou** [toeverything/blocksuite#684]
https://user-images.githubusercontent.com/95235746/212257981-b7bb9c02-4d4e-45c8-adc0-db7a1f036822.mov

**Comment by doodlewind** [comment]
Reproduced:

1. Drag paragraph A to another position.
2. Click at the line start of A.
3. Press enter, this will create a duplicated copy of A, instead of adding a new empty paragraph.

@Himself65 any quick idea about this? Perhaps we missed some cleanup?

**Comment by himself65** [comment]
Please enable debug log and see the stack

**Comment by himself65** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/14026360/213375317-ed947e0e-e065-4e2f-80cb-a06dff4a7395.png">

**Comment by himself65** [comment]
`const [left, right] = model.text.split(splitIndex, splitLength);` is 0 and 0

**Comment by himself65** [comment]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/14026360/213379304-df1104fc-2e77-4289-bfd4-0e049bdfe522.png">
<img width="136" alt="image" src="https://user-images.githubusercontent.com/14026360/213379315-e58fe416-ba53-45b6-bb45-533130035bf1.png">

The data structure is correct

**Comment by himself65** [comment]
I think the problem is quill data not updated

**Comment by himself65** [comment]
The reason is this line 
https://github.com/toeverything/blocksuite/blob/fe057391d18f674943e26de6eb48e8987f79d809/packages/blocks/src/__internal__/rich-text/rich-text.ts#L191
