### ISSUE TITLE
Read-only mode can edit

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#686]
In read-only mode, shortcut keys can still be used for editing, floating buttons will appear for pictures and code blocks, and the code type of code blocks can also be switched.

https://user-images.githubusercontent.com/102217452/212292534-18a11a40-0a15-4d99-99a4-1e6abff1ec96.mov

**Comment by himself65** [comment]
I think we should put `read-only` into workspace

how do you think? @doodlewind

**Comment by doodlewind** [comment]
> I think we should put `read-only` into workspace
> 
> how do you think? @doodlewind

Our permission model is expected to support page-wise `readonly`, and in this issue, I thought the config prop is adequate, but our UI hasn't comprehensively supported it yet.

**Comment by himself65** [comment]
I think we could use a proxy to support this feature, which set read-only props in the yMap proxy. So that downstream cannot write anything at all

**Comment by himself65** [comment]
Landed in #690
