### ISSUE TITLE
When the Edgeless editor is opened in two new tabs, an unknown text with a cursor appears in the editor

### ISSUE THREAD

**Issue by RajaTheKing826** [toeverything/blocksuite#6892]
When the Edgeless editor is opened in two new tabs, an unknown text with a cursor appears in the editor.  I don't want to see this i wanna remove this how can i do this?

![image](https://github.com/toeverything/blocksuite/assets/59301270/b6178ae1-5566-474d-a37a-f280da599381)

**Comment by doouding** [comment]
This might be a bug. Let me look into this.

**Comment by RajaTheKing826** [comment]
@doouding  any update

**Comment by doouding** [comment]
Hi Raja, did you deploy the playground packages directly? I found the doc id is set to `starter` by default. So if you don't want that unknown cursor to appear, you can generate a random ID for the doc.

**Comment by doodlewind** [comment]
Closed by #6955
