### ISSUE TITLE
How to export doc JSON and apply in the next time？

### ISSUE THREAD

**Issue by undefined-unknown** [toeverything/blocksuite#6911]

**Comment by doodlewind** [comment]
You can try the snapshot API: https://blocksuite.io/guide/data-synchronization.html#snapshot-api

**Comment by undefined-unknown** [comment]
> You can try the snapshot API: https://blocksuite.io/guide/data-synchronization.html#snapshot-api

Thanks for the answer! 
One problem here is that I am doing `const json = await job.docToSnapshot(doc);` to store json in sql. I will do it again the next time I retrieve it.
`
const schema = new Schema().register(AffineSchemas);
const collection = new DocCollection({ schema });
const job = new Job({ collection })
const doc = await job.snapshotToDoc(docSnapshot)
doc.load();
`
Such an operation is not allowed because doc.meta.tags is not in the new collection instance. In this case, should I store it twice? That is
`const collectionSnapshot = await job.collectionInfoToSnapshot();`
Do it first the next time you use it
`const schema = new Schema().register(AffineSchemas);
   const collection = new DocCollection({ schema });
  const job = new Job({ collection })
  job.snapshotToCollectionInfo(_collectionSnapshot);
const doc = await job.snapshotToDoc(docSnapshot);
doc.load()`
