### ISSUE TITLE
If the doc obtained through job.snapshotToDoc is passed to new BlockStdScope, will the created Slot of the BlockModel corresponding to flavor be triggered?

### ISSUE THREAD

**Issue by undefined-unknown** [toeverything/blocksuite#6922]
```ts
const schema = new Schema().register(xxSchemas);
const collection = new DocCollection({ schema });
const doc = job.snapshotToDoc(docSnapshot);
const std = new BlockStdScope({
      host: this.root,
      collection: collection,
      doc: doc,
});
std.spec.applySpecs(this.specs);
std.mount();
``` 
maybe you can see the file of packages/blocks/src/data-view-block/data-view-model.ts ；
I tried to implement a Konva based view layer using something like。
![image](https://github.com/toeverything/blocksuite/assets/155932361/c053599a-7826-49aa-851e-3c508522a957)

**Comment by doodlewind** [comment]
Yes, the `created` slots on block instance (or the `doc` instance) are implemented in the `@blocksuite/store` package, which is the dependency of `@blocksuite/block-std`. So the model event dispatching behavior should be consistent no matter how you design your block renderer.
