### ISSUE TITLE
move shared utilities and constant into `@blocksuite/global`

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#700]
Some types like `BlockModels`, and functions like `assertExists` are shared in all packages. We should move them into `@blocksuite/global`

/cc @doodlewind 

## Related PRs:
- https://github.com/toeverything/blocksuite/pull/699
- https://github.com/toeverything/blocksuite/pull/741

**Comment by himself65** [comment]
This is long-term progress. Don't move forward it too fast avoiding the breaking change

**Comment by doodlewind** [comment]
Are we good to close? Seems that the related PRs are landed 👀
