### ISSUE TITLE
​Bugs when importing a table from Notion

### ISSUE THREAD

**Issue by alvaniss** [toeverything/blocksuite#7026]
### What happened?

- export a table in HTML
- import it into the app
- all text fields are now hidden, you can fix this by manually clicking LMB on each of them
- all entities in the name field now have hyperlinks to their duplicates in Notion

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Other

### Are you self-hosting?

- [ ] Yes

### Anything else?

Video demonstration: https://github.com/toeverything/AFFiNE/assets/79401978/9c3ec340-61d7-4bdc-ba0a-1d97b77db6f5

**Comment by zzj3720** [comment]
The problem of the text fields fixed in #7091

**Comment by alvaniss** [comment]
> The problem of the text fields fixed in #7091

Unfortunately, the bug still persists for me

**Comment by zzj3720** [comment]
> > The problem of the text fields fixed in #7091
> 
> Unfortunately, the bug still persists for me

This is only a fix in blocksuite, it will be a while before this fix makes it into affine stable.
