### ISSUE TITLE
react-basic example: Module not found: Can't resolve 'yjs'

### ISSUE THREAD

**Issue by vincenzodomina** [toeverything/blocksuite#7117]
I took the code from the react-basic example and installed dependencies with npm.

Then running the code throws me this:

```
https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@blocksuite/inline/dist/index.js
./node_modules/@blocksuite/blocks/dist/code-block/affine-code-line.js
./node_modules/@blocksuite/blocks/dist/index.js
./node_modules/@blocksuite/presets/dist/ai/ai-spec.js
./node_modules/@blocksuite/presets/dist/ai/index.js
./node_modules/@blocksuite/presets/dist/index.js
./src/components/Editor/EditorComponent.tsx
./src/components/Editor/ReportEditor.tsx
./src/layouts/DashboardLayout/index.tsx
./src/routes.tsx
./src/App.tsx
./src/app/[[...slug]]/client.tsx
 ⨯ ./node_modules/@blocksuite/inline/dist/inline-editor.js:3:1
Module not found: Can't resolve 'yjs'
```

Installing yjs separately solved the issue.

The question is, is yjs really needed for a basic page editor implementation without collaborative features???

**Comment by Flrande** [comment]
> The question is, is yjs really needed for a basic page editor implementation without collaborative features???

This is because we are a **CRDT Native** editor (and currently the only one, as you can see in the [binding part of Yjs documentation](https://github.com/yjs/yjs?tab=readme-ov-file#overview)), using CRDT as the single data source (you can read this [blog](https://blocksuite.io/blog/crdt-native-data-flow.html)).
