### ISSUE TITLE
In the Lit component, the `accessor` field in my local code results in syntax errors during compilation. How can I resolve this?

### ISSUE THREAD

**Issue by mazhenjie233** [toeverything/blocksuite#7188]
![1717002768276](https://github.com/toeverything/blocksuite/assets/76252062/6394a6e3-d8e0-4848-ba9f-f5cc28639c20)
like this （ https://github.com/mazhenjie233/test-umi ）

**Comment by lawvs** [comment]
This error seems to be similar to [#3009](https://github.com/evanw/esbuild/issues/3009), can you check your esbuild version?

**Comment by mazhenjie233** [comment]
my esbuild is v0.21.3

**Comment by fourdim** [comment]
According to your `pnpm-lock.yaml`, umi is using esbuild `0.17.19` which does not support this feature.
https://github.com/evanw/esbuild/releases/tag/v0.17.19

**Comment by fourdim** [comment]
You can use the latest version of umi which should support this feature.
https://github.com/umijs/umi/commit/2ba325f4bec3eeee2265233c922f26bdc132ff92
