### ISSUE TITLE
[Bug Report] Unexpected behavior of moving cursor by "⬆️" arrow key between table and codeblock

### ISSUE THREAD

**Issue by ShenQingchuan** [toeverything/blocksuite#7270]
Found this bug when trying the canary playground today, reproduction is quite easy, since I didn't find any method for exporting the playground accident scene so I'd like to describe it in words.

Following these steps:
1. Insert a table
2. Insert a code block right after the table
3. Type more than 1 line contents into the code block
4. Hit ⬆️ arrow key，wherever your cursor is

The selection goes to wrap the table above.

https://try-blocksuite.vercel.app/starter?init=AAAG0OuIiAcbCAACAQEQARNMABUnAAcAKAAhACgAJwApACgBJwAoFajsA8YDbWV0YXBhZ2VzaWR0aXRsZWNyZWF0ZURhdGV0YWdzc3BhY2VzZG9jOmhvbWVkb2M6aG9tZW1ldGF3b3Jrc3BhY2VWZXJzaW9ubWV0YXBhZ2VWZXJzaW9ubWV0YWJsb2NrVmVyc2lvbnNhZmZpbmU6Y29kZWFmZmluZTpwYXJhZ3JhcGhhZmZpbmU6cGFnZWFmZmluZTpsaXN0YWZmaW5lOm5vdGVhZmZpbmU6ZGl2aWRlcmFmZmluZTppbWFnZWFmZmluZTpzdXJmYWNlYWZmaW5lOmJvb2ttYXJrYWZmaW5lOmZyYW1lYWZmaW5lOmRhdGFiYXNlYWZmaW5lOnN1cmZhY2UtcmVmYWZmaW5lOmRhdGEtdmlld2FmZmluZTphdHRhY2htZW50YWZmaW5lOmVtYmVkLXlvdXR1YmVhZmZpbmU6ZW1iZWQtZmlnbWFhZmZpbmU6ZW1iZWQtZ2l0aHViYWZmaW5lOmVtYmVkLWh0bWxhZmZpbmU6ZW1iZWQtbGlua2VkLWRvY2FmZmluZTplbWJlZC1zeW5jZWQtZG9jYWZmaW5lOmVtYmVkLWxvb21hZmZpbmU6ZWRnZWxlc3MtdGV4dAQFAgUKBAZIAAQQBAsEDQsQSwEODA4PDA8SEBEUEhMRVwARFAcBAAAEAQMABAABAAECQRoBIQB3CGRvYzpob21le0J5AuUZxjAAdgB9An0CfQF9AX0CfQF9AX0BfQF9BX0BfQF9A30BfQF9AX0BfQF9AX0BfQF9AX0BfQF3FUJsb2NrU3VpdGUgUGxheWdyb3VuZAHQtYTEAwEDAA%3D%3D

**Comment by Saul-Mirone** [comment]
Should be fixed now.
