### ISSUE TITLE
中文使用、打开块选择器-选中某个块-然后、没有消失（斜杠是消失的）​åå

### ISSUE THREAD

**Issue by hudapao888** [toeverything/blocksuite#7451]
### What happened?

应该和/一样，选中某个块样式之后、就消失，不然我还得手动删除一下再开始写东西。

### Distribution version

macOS ARM 64 (Apple Silicon)

### Are you self-hosting?

- [ ] Yes

### Anything else?

<img width="358" alt="image" src="https://github.com/toeverything/AFFiNE/assets/85144156/e45ba65b-8079-437e-bc7a-3d5373e5446e">
<img width="354" alt="image" src="https://github.com/toeverything/AFFiNE/assets/85144156/2b6a6c52-f129-4d76-a065-d3e64fe08696">

**Comment by L-Sun** [comment]
你是通过搜狗输入法使用 / 这个按键输入的 、 吗？

**Comment by hudapao888** [comment]
是的

L-Sun ***@***.***> 于2024年6月30日周日 19:03写道：

**Comment by EYHN** [comment]
It seems to be a compatibility issue with the Chinese IME. I added a video here

https://github.com/toeverything/blocksuite/assets/13579374/62c2a0bd-8d29-4d71-bab1-5ab031e2afc7

**Comment by L-Sun** [comment]
> It seems to be a compatibility issue with the Chinese IME. I added a video here

The current implementation is based on `KeyboardEvent`, which cannot detect the symbol "、" inputed by pressing Slash key <kbd>/</kbd> in Sogou IME. I will try using `inputEven`t to address this issue, though there may still be other edge cases.

![image](https://github.com/toeverything/blocksuite/assets/20479050/29525873-8ce9-449e-bfaa-e7583b0386c8)
