### ISSUE TITLE
create or edit table , always scroll to top

### ISSUE THREAD

**Issue by LYUYork** [toeverything/blocksuite#7456]
### What happened?

Poor user experience！create or edit table , always scroll to top

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [ ] Yes

**Comment by golok727** [comment]
Is this issue still occurring?

**Comment by golok727** [comment]
fixed in https://github.com/toeverything/blocksuite/pull/7463
