### ISSUE TITLE
编辑表格内容或者编辑表格状态时，滚动条会滚到顶部，并且焦点移除时没有关闭配置框，体验不好

### ISSUE THREAD

**Issue by mazhenjie233** [toeverything/blocksuite#7458]
编辑表格内容或者编辑表格状态时，滚动条会滚到顶部，并且焦点移除时没有关闭配置框，体验不好

https://github.com/toeverything/blocksuite/assets/76252062/9069c28f-aad7-4bae-9a1b-88de1366f6be

**Comment by zzj3720** [comment]
fixed in https://github.com/toeverything/blocksuite/pull/7463
