### ISSUE TITLE
Bug in DocCollection

### ISSUE THREAD

**Issue by raymonddaikon** [toeverything/blocksuite#7481]
Something broke in between  `0.15.0-canary-202406061150-5c5d6fa` and `0.15.0-canary-202406280242-21d8d15` that causes `DocCollection` to not be able to `createDoc`. I'm having trouble pinning down the exact changes between these two versions but all subsequent versions after `0.15.0-canary-202406280242-21d8d15` including the latest `0.15.0` release includes this bug.

**Comment by fourdim** [comment]
I'm sorry that the documentation is not up to date.
Add a line:
```ts
collection.meta.initialize();
```
should solve this issue.

**Comment by jizhi0v0** [comment]
> ```ts
> ```ts
> collection.meta.initialize();
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

It works!

**Comment by fourdim** [comment]
New API updates are described in https://github.com/toeverything/blocksuite/pull/7455
