### ISSUE TITLE
Directly dragging frame block throws error in edgeless mode

### ISSUE THREAD

**Issue by m1911star** [toeverything/blocksuite#749]
### To Reproduce

https://user-images.githubusercontent.com/4948120/212821245-aeb8890f-ae82-40b3-810d-8ca4a7c12d23.mov

Maybe can add a draghandler to card when hover. (like the icon below)
It's hard to verify when I can drag.

<img width="70" alt="image" src="https://user-images.githubusercontent.com/4948120/212821655-9e098ae3-230d-45ee-ace5-90a3cd9b1183.png">

**Comment by lawvs** [comment]
Introduced by https://github.com/toeverything/blocksuite/pull/588

**Comment by ShortCipher5** [comment]
I hope my previous answer helps with your feature part. 

For the bug report, as this feature is provided by BlockSuite your issue has been moved to the BlockSuite repo.

Thank you.

**Comment by m1911star** [comment]
Maybe I can help to fix, hhh

**Comment by doodlewind** [comment]
Not reproduced as of #1415
