### ISSUE TITLE
​Request for supporting mermaid graph

### ISSUE THREAD

**Issue by mazhenjie233** [toeverything/blocksuite#7568]
```[tasklist]
### Tasks
```

**Comment by raintoway** [comment]
why not use mindmap

**Comment by mazhenjie233** [comment]
Sometimes, i also need to have a flow chart in the document view without switching to edgeless.

**Comment by raintoway** [comment]
what u need is a markdown with mermaid-parser , instead of document editor like affine

**Comment by mazhenjie233** [comment]
Blocksuite supports markdown syntax. I personally feel that it would be great if blocksuite could render the mermaid flow chart through markdown syntax like milkdown.

**Comment by fourdim** [comment]
You can use embed view to embed flow charts, mind maps from edgeless to the doc mode.

![image](https://github.com/user-attachments/assets/81abbd39-00ae-4a0b-90da-e857fd00a350)
