### ISSUE TITLE
IME bug when typing at the end of inline code on Windows

### ISSUE THREAD

**Issue by donaldxdonald** [toeverything/blocksuite#761]
## Info
OS: Windows 11
Browser: Chrome 108.0.5359.126

## Record
![aTvWCDunUF](https://user-images.githubusercontent.com/29999387/212930986-e6805b37-702d-42e6-b7f3-227053a3d616.gif)

**Comment by lawvs** [comment]
I think it related to https://github.com/toeverything/blocksuite/issues/415

**Comment by himself65** [comment]
https://blocksuite-toeverything.vercel.app/?init=AAMAAxEHyJCIuBasAacBAAIBAAgBBhQBAw4BAAgBAUxiPAECSBKCAQEDwAGMAYYBAQPEAZABOgEDeIQBjgICFgIiAQLIA5IDiAEBAsYBkAGcAQIKApQHAQL8CIYJogICEgKKAQISApoBAQLwBboFmgICCgK0BAIMAhABAvoHhAisBQI6AoQDAQLsCbYJggMCjAECuAEBAsgGkgaAAQIiAtgxjAeYKgECDgECClwgCAIABEYGTBQJmgnMCJ4xHEIMswInAAcAKAAhACgAJwAoCCcAKAEnAigAJwAoAScBKAEnACgACACoACcAKAEnACgAJwAIAAQAJwAoAScAKAEnAIgABAAnACgBJwAoAScAiAAEACcAKAEnACgBJwCIAAQAhgCEAIYAhAAnACgBJwAoACcAiAAEACcAKAEnACgAJwCIAAQAhgCEAIYAhAAnACgBJwAoACcAiAAEAIYAhACGAIQAhgCEAIYAhAAnACgBJwAoACcAiAAEAIYAhACGAIQAhgCEAIYAhAAnACgBJwAoACcAiAAEAIYAhACGAIQAJwAoAScAKAAnAIgABACGAIQAhgCEACcAKAEnACgAJwCIAAQAhgCEAIYAhACoAMgAJwAoAScAKAAnAEgAJwAoAScAKAAnAEgABACoAIQCxACEAMYBqACEnRjaFnNwYWNlOm1ldGFwYWdlc2lkdGl0bGVjcmVhdGVEYXRlc3BhY2U6bWV0YXZlcnNpb25zYWZmaW5lOmNvZGVhZmZpbmU6cGFyYWdyYXBoYWZmaW5lOnBhZ2VhZmZpbmU6bGlzdGFmZmluZTpmcmFtZWFmZmluZTpkaXZpZGVyYWZmaW5lOmVtYmVkYWZmaW5lOnN1cmZhY2VhZmZpbmU6ZGF0YWJhc2VzcGFjZTpwYWdlMDMwMTE1NzY4NDA6MHN5czppZHN5czpmbGF2b3VybWV0YTp0YWdzbWV0YTp0YWdTY2hlbWFzeXM6Y2hpbGRyZW5wcm9wOnRpdGxlc3BhY2U6cGFnZTAzMDExNTc2ODQwOjFzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnNwYWNlOnBhZ2UwMzAxMTU3Njg0MDoyc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnh5d2hzcGFjZTpwYWdlMDMwMTE1NzY4NDA6M3N5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0VGhpcyBwbGF5Z3JvdW5kIGlzIGRlc2lnbmVkIHRvOnNwYWNlOnBhZ2UwMzAxMTU3Njg0MDo0c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHTwn5OdIFRlc3QgYmFzaWMgZWRpdGluZyBleHBlcmllbmNlLnNwYWNlOnBhZ2UwMzAxMTU3Njg0MDo1c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHTimpnvuI8gU2VydmUgYXMgRTJFIHRlc3QgZW50cnkuc3BhY2U6cGFnZTAzMDExNTc2ODQwOjZzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6Y2hlY2tlZHByb3A6dGV4dPCflJcgRGVtb25zdHJhdGUgaG93IEJsb2NrU3VpdGUgcmVjb25jaWxlcyByZWFsLXRpbWUgY29sbGFib3JhdGlvbiB3aXRoIGxpbmtsb2NhbC1maXJzdGxpbmsgZGF0YSBvd25lcnNoaXAuc3BhY2U6cGFnZTAzMDExNTc2ODQwOjdzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dENvbnRyb2xsaW5nIFBsYXlncm91bmQgRGF0YSBTb3VyY2VzcGFjZTpwYWdlMDMwMTE1NzY4NDA6OHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0WW91IG1pZ2h0IGluaXRpYWxseSBlbnRlciB0aGlzIHBhZ2Ugd2l0aCB0aGUgY29kZT9pbml0Y29kZSBVUkwgcGFyYW0uIFRoaXMgaXMgdGhlIGRlZmF1bHQgKG9wdC1pbikgc2V0dXAgdGhhdCBhdXRvbWF0aWNhbGx5IGxvYWRzIHRoaXMgYnVpbHQtaW4gYXJ0aWNsZS4gTWVhbndoaWxlLCB5b3UnbGwgY29ubmVjdCB0byBhIHJhbmRvbSBzaW5nbGUtdXNlciByb29tIHZpYSBhIFdlYlJUQyBwcm92aWRlciBieSBkZWZhdWx0LiBUaGlzIGlzIHRoZSAic2luZ2xlLXVzZXIgbW9kZSIgZm9yIGxvY2FsIHRlc3Rpbmcuc3BhY2U6cGFnZTAzMDExNTc2ODQwOjlzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dFRvIHRlc3QgcmVhbC10aW1lIGNvbGxhYm9yYXRpb24sIHlvdSBjYW4gc3BlY2lmeSB0aGUgcm9vbSB0byBqb2luIGJ5IGFkZGluZyB0aGUgY29kZT9yb29tPWZvb2NvZGUgY29uZmlnIC0gVHJ5IG9wZW5pbmcgdGhpcyBwYWdlIHdpdGggY29kZT9yb29tPWZvb2NvZGUgaW4gdHdvIGRpZmZlcmVudCB0YWJzIGFuZCBzZWUgd2hhdCBoYXBwZW5zIXNwYWNlOnBhZ2UwMzAxMTU3Njg0MDoxMHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0Tm90ZSB0aGF0IHRoZSBzZWNvbmQgYW5kIHN1YnNlcXVlbnQgdXNlcnMgc2hvdWxkIG5vdCBvcGVuIHRoZSBwYWdlIHdpdGggdGhlIGNvZGU%2FaW5pdGNvZGUgcGFyYW0gaW4gdGhpcyBjYXNlLiBBbHNvLCBkdWUgdG8gdGhlIFAyUCBuYXR1cmUgb2YgV2ViUlRDLCBhcyBsb25nIGFzIHRoZXJlIGlzIGF0IGxlYXN0IG9uZSB1c2VyIGNvbm5lY3RlZCB0byB0aGUgcm9vbSwgdGhlIGNvbnRlbnQgaW5zaWRlIHRoZSByb29tIHdpbGwgYm9sZGFsd2F5c2JvbGQgZXhpc3Quc3BhY2U6cGFnZTAzMDExNTc2ODQwOjExc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRJZiB5b3UgYXJlIHRoZSBvbmx5IHVzZXIgaW4gdGhlIHJvb20sIHlvdXIgY29udGVudCB3aWxsIGJlIGxvc3QgYWZ0ZXIgcmVmcmVzaC4gVGhpcyBpcyBncmVhdCBmb3IgbG9jYWwgZGVidWdnaW5nLiBCdXQgaWYgeW91IHdhbnQgbG9jYWwgcGVyc2lzdGVuY2UsIHlvdSBjYW4gb3BlbiB0aGlzIHBhZ2Ugd2l0aCB0aGUgY29kZT9wcm92aWRlcnM9aW5kZXhlZGRiJnJvb209Zm9vY29kZSBjb25maWcsIHRoZW4gY2xpY2sgdGhlIGluaXQgYnV0dG9uIGluIHRoZSBib3R0b20tbGVmdCBjb3JuZXIgdG8gaW5pdGlhbGl6ZSB0aGlzIGRlZmF1bHQgY29udGVudC5zcGFjZTpwYWdlMDMwMTE1NzY4NDA6MTJzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dEFzIGEgcHJvIHRpcCwgeW91IGNhbiBjb21iaW5lIG11bHRpcGxlIHByb3ZpZGVycyEgRm9yIGV4YW1wbGUsIGZlZWwgZnJlZSB0byBvcGVuIHRoaXMgcGFnZSB3aXRoIGNvZGU%2FcHJvdmlkZXJzPWluZGV4ZWRkYix3ZWJydGMmcm9vbT1oZWxsb2NvZGUgcGFyYW1zLCBhbmQgc2VlIGlmIGV2ZXJ5dGhpbmcgd29ya3MgYXMgZXhwZWN0ZWQuIEhhdmUgZnVuIXNwYWNlOnBhZ2UwMzAxMTU3Njg0MDoxM3N5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0Rm9yIGFueSBmZWVkYmFjaywgcGxlYXNlIHZpc2l0IGxpbmtCbG9ja1N1aXRlIGlzc3Vlc2xpbmsg8J%2BTjXNwYWNlOnBhZ2UwMzAxMTU3Njg0MDoxNHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0c3BhY2U6cGFnZTAzMDExNTc2ODQwOjE1c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRgYGAtYGAgMTIzIGNvZGVjb2RlZGFzZHNhCgUCBUoACAsQSwAMDgwODwsMBgsJDgwKCwwGCwwLDAYLDAkLDAYLDEkAHwsMBgsMCQwJIQsMBgsMCQwJGwsMBgsMCQwJhgEECwQQCwwGCwxJACILDAYLDEkALQQFBKkDCwwGCwxJAJABBAkEJQQJBCwLDQYLDEkAjAEEBQSaAgQGBAcLDQYLDEkAtQIEHQShAQsNBgsMSQCgAQQmBDsLDQYLDEkAHwQRBAMLDQYLDEkACw0GCwxJAAEDAQIDAUQABkcBAAADAQAACAEAAAUBAAACAQAABAEAAAYBAAAGAQAABgEAAAYBAAAFAQAABQEAAAUBAAAFAQAABQEAAAUBAAAFAQAABAEAAC8AQQMAAQABAAEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgEAAgJBTwG7AQB3BXBhZ2Uwe0J4YC%2FrsFAAfQF9AX0BfQF9AX0BfQF9AX0BdwwzMDExNTc2ODQwOjB3C2FmZmluZTpwYWdldyBXZWxjb21lIHRvIEJsb2NrU3VpdGUgcGxheWdyb3VuZHcMMzAxMTU3Njg0MDoxdw5hZmZpbmU6c3VyZmFjZXcMMzAxMTU3Njg0MDoydwxhZmZpbmU6ZnJhbWV3DVswLDAsNzIwLDQ4MF13DDMwMTE1NzY4NDA6MncgV2VsY29tZSB0byBCbG9ja1N1aXRlIHBsYXlncm91bmR3DDMwMTE1NzY4NDA6M3cQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcMMzAxMTU3Njg0MDozdwwzMDExNTc2ODQwOjR3C2FmZmluZTpsaXN0dwhidWxsZXRlZHl3DDMwMTE1NzY4NDA6NHcMMzAxMTU3Njg0MDo1dwthZmZpbmU6bGlzdHcIYnVsbGV0ZWR5dwwzMDExNTc2ODQwOjV3DDMwMTE1NzY4NDA6NncLYWZmaW5lOmxpc3R3CGJ1bGxldGVkeXcMMzAxMTU3Njg0MDo2dzNodHRwczovL21hcnRpbi5rbGVwcG1hbm4uY29tL3BhcGVycy9sb2NhbC1maXJzdC5wZGZ%2BdwwzMDExNTc2ODQwOjd3EGFmZmluZTpwYXJhZ3JhcGh3AmgydwwzMDExNTc2ODQwOjd3DDMwMTE1NzY4NDA6OHcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcMMzAxMTU3Njg0MDo4eH53DDMwMTE1NzY4NDA6OXcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcMMzAxMTU3Njg0MDo5eH54fncNMzAxMTU3Njg0MDoxMHcQYWZmaW5lOnBhcmFncmFwaHcFcXVvdGV3DTMwMTE1NzY4NDA6MTB4fnh%2Bdw0zMDExNTc2ODQwOjExdxBhZmZpbmU6cGFyYWdyYXBodwR0ZXh0dw0zMDExNTc2ODQwOjExeH53DTMwMTE1NzY4NDA6MTJ3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DTMwMTE1NzY4NDA6MTJ4fncNMzAxMTU3Njg0MDoxM3cQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNMzAxMTU3Njg0MDoxM3cxaHR0cHM6Ly9naXRodWIuY29tL3RvZXZlcnl0aGluZy9ibG9ja3N1aXRlL2lzc3Vlc353DVswLDAsNzIwLDgxNF13DDMwMTE1NzY4NDA6M3cNMzAxMTU3Njg0MDoxNHcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNMzAxMTU3Njg0MDoxNHcNMzAxMTU3Njg0MDoxNXcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNMzAxMTU3Njg0MDoxNXcMWzAsMCw3MjAsMzJdeH53G1swLDAsNzIwLDM0LjY2NjY2NzkzODIzMjQyXQGIiIScCwUDABoAArUMBwcDAA%3D%3D

**Comment by himself65** [comment]
![image](https://user-images.githubusercontent.com/14026360/215500451-edaeb8c7-3d8c-420c-a2f1-c41a155c7cb0.png)

**Comment by himself65** [comment]
https://github.com/toeverything/blocksuite/blob/9bca2151df336eb942b1d002f101af520e403729/packages/blocks/src/__internal__/rich-text/rich-text.ts#L177-L178
