### ISSUE TITLE
export GfxBlockElementModel from block-std package

### ISSUE THREAD

**Issue by goldsam** [toeverything/blocksuite#7739]
I'm trying to create an edgeless compatible `BlockModel` based on those from the `@blocksuite/blocks` package. I'm running into issues with the compiler failing to resolve type details of [`EdgelessBlockModel`](https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/root-block/edgeless/edgeless-block-model.ts).

The issue is that the models in `@blocksuite/blocks` extend [`EdgelessBlockModel `](https://github.com/toeverything/blocksuite/blob/master/packages/blocks/src/root-block/edgeless/edgeless-block-model.ts) which is a re-export of [`GfxBlockElementModel`](https://github.com/toeverything/blocksuite/blob/master/packages/framework/block-std/src/gfx/model.ts) from package `@blocksuite/blocks`. `GfxBlockElementModel` however is not exported from that library. The `@blocksuite/blocks` package is able to build because of the [`workspace` package dependency](https://github.com/toeverything/blocksuite/blob/bbdf12e3d70adc5d4cb846e01accf1862003ca3c/packages/blocks/package.json#L18), but no other external consumers can resolve this type:

I believe the solution is to simply export `src/gfx` from package`@blocksuite/block-std`.

**Comment by goldsam** [comment]
@doodlewind Can you please address this.

**Comment by fourdim** [comment]
gfx is indeed exported.
Check this line:
https://github.com/toeverything/blocksuite/blob/3b62f7a91e89e364342764c7f9d941ccda8ac331/packages/framework/block-std/package.json#L39

**Comment by goldsam** [comment]
@fourdim The export is broken. I have created an [MCVE repo here](https://github.com/goldsam/blocksuite-is-broken/). The [build workflow output is pretty straightforward](https://github.com/goldsam/blocksuite-is-broken/actions/runs/10154969979/job/28080949227).
