### ISSUE TITLE
Add a "toggle list" option to slash list command

### ISSUE THREAD

**Issue by byxhy** [toeverything/blocksuite#7897]
### Description

The default slash command has many useful options, such as Text, List and Pages...
There already have bulleted list, numbered list and to-do list, if it has the toggle list, it will be very helpful.

### Use case

When we have many blocks on the same page, if we can hide the details by triggering the "toggle list", it will save a lot of space on that page.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
Our list is now toggleable

https://github.com/user-attachments/assets/ec0f9ff1-b2dd-4ac8-8736-c201d3c40256
