### ISSUE TITLE
The contents of /todo cannot be displayed

### ISSUE THREAD

**Issue by zhaopengme** [toeverything/blocksuite#7961]
The contents of /todo cannot be displayed

[https://github.com/toeverything/AFFiNE/issues/7808](https://github.com/toeverything/AFFiNE/issues/7808)

**Comment by L-Sun** [comment]
If I understand correctly, "/todo" is to create a list with checkboxes. Can you provide a video to demonstrate the problem?

**Comment by Saul-Mirone** [comment]
Seems related to database?

**Comment by L-Sun** [comment]
This /todo is an experimental feature related to the database, which currently has some bugs, and there are no new updates on it.
