### ISSUE TITLE
e2e test fail while performing attachment.spec.ts in macos 13.6.6

### ISSUE THREAD

**Issue by raintoway** [toeverything/blocksuite#7967]
`Error: ENOENT: no such file or directory, stat '../packages/playground/public/test-card-1.png'` 
cause by  ``const FILE_PATH = `../packages/playground/public/${FILE_NAME}`;``

**Comment by L-Sun** [comment]
I guess you are using the wrong method to run the tests.

**Comment by Saul-Mirone** [comment]
There's no issue in our test.

<img width="970" alt="Screenshot 2024-08-15 at 10 56 28" src="https://github.com/user-attachments/assets/52695907-2b19-47be-8b08-71e6f825d3f6">
