### ISSUE TITLE
Request to Add "node" as an Alias for JavaScript in Code Block Highlighting

### ISSUE THREAD

**Issue by see-more** [toeverything/blocksuite#8008]
Currently, when using code blocks in Affine, we can specify the language to get syntax highlighting. For JavaScript, we use js or javascript. However, it would be beneficial to add node as an alias for JavaScript,
![image](https://github.com/user-attachments/assets/dbbbe57e-a2b4-4fc0-af80-8a3fce2fbd14)

**Comment by fourdim** [comment]
No, just like what antfu is mentioned in the shikijs, nodejs is a runtime rather than a language.

There can be many runtimes for a single language and there can be runtimes that can run multiple languages.
If we are following the same logic and add all of these to BlockSuite, it will be a mess.
