### ISSUE TITLE
Code sandbox for editor entry

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#816]
We have added the `SimpleAffineEditor` component in #811 and its entry has been published in #815:

https://blocksuite-toeverything.vercel.app/examples/basic/

The [source code](https://github.com/toeverything/blocksuite/blob/master/packages/editor/src/components/simple-affine-editor.ts) of this example is deadly simple. It will be great to have online code sandbox link to edit this example (or the `playground/src/main` one), showing something we can do after editor initialized (e.g., calling [`simpleAffineEditor.setTitle`](https://github.com/toeverything/blocksuite/blob/master/packages/editor/src/components/simple-affine-editor.ts#L48) or [`simpleAffineEditor.importMarkdown`](https://github.com/toeverything/blocksuite/blob/master/packages/editor/src/components/simple-affine-editor.ts#L52)).

It will be great adding the code sandbox link (or badge) to the README, we have the [resources](https://github.com/toeverything/blocksuite#resources) section for it.

**Comment by himself65** [comment]
im working on this
