### ISSUE TITLE
Hierarchial note blocks to determine header size

### ISSUE THREAD

**Issue by i12345** [toeverything/blocksuite#8170]
Hello,

I really enjoy Affine!
When writing notes, hierarchial relationship of thoughts comes to mind quickly, but when adding a new layer in hierarchy, I must manually make the headers underneath smaller.

Could header size be determined automatically? Each note block could have one header (the page root note header is the page title), and note block children could include other note blocks. When rendering a note block's header, it could be styled one size smaller than the containing note block.

Then when linking/embedding docs, the headers in subdocs would naturally appear to be appropriate for the hierarchy in the parent document.

Really appreciate Affine/blocksuite!

**Comment by fourdim** [comment]
Not possible for now.
Every blocks in our document are made to be as independent as possible for maintainability.
And the rendering is controlled by each blocks, which made extensions possible.

**Comment by doodlewind** [comment]
Thanks for the feedback. Base on current data structure, adding regular heading block inside note block instead of support nested / titled notes should be the best practice.
