### ISSUE TITLE
Migrate the React Next example into to the playground Vite environment

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#818]
We have a React hook binding with Next.js example at [packages/react/examples/next](https://github.com/toeverything/blocksuite/tree/master/packages/react/examples/next). However since #815, this kind of example can be built using the default Vite playground. Also:

* The Next example is not associated with the root level `pnpm` monorepo, so it has to be installed manually.
* The Next example doesn't follow some naming conventions (.e.g., `kebab-case.ts`).

So it will be good to migrate this example to `playground/examples/react`, this can also remove the `blocksuite-react` integration in Vercel.

/cc @Himself65

**Comment by himself65** [comment]
if we use vite to build react. There will have no SSR

**Comment by himself65** [comment]
https://vitejs.dev/guide/ssr.html

**Comment by doodlewind** [comment]
IMO for the `@blocksuite/react` example itself, enabling SSR is just something nice-to-have. But for AFFiNE, SSR may make more sense. It would be just fine to keep simplest Vite config to migrate the React example in.

**Comment by himself65** [comment]
Building the next project for each PR is necessary. In case of people import some side effect code in SSR mode. We could remove it from vercel build it at least need a build test

**Comment by doodlewind** [comment]
> Building the next project for each PR is necessary. In case of people import some side effect code in SSR mode. We could remove it from vercel build it at least need a build test

This makes sense, so how about having an `integration` package that depends on the Next environment standalone? We can have the current Next example maintained in this package, so that our root level pnpm could initialize it together. For future toolchain integration, we can also make it happen here.

In this case, we can just keep the Vercel integration, and adding the build test of this `integration` package should be trivial.

**Comment by himself65** [comment]
discussion https://github.com/toeverything/blocksuite/discussions/844

**Comment by doodlewind** [comment]
Closing in favor of #838
