### ISSUE TITLE
snapshotToDoc very slow with large snapshot

### ISSUE THREAD

**Issue by kerituni12** [toeverything/blocksuite#8380]
The performance is slower due to the use of nextTick in the _snapshotToBlock method. Specifically, I see the following code:

```js 
await new Promise(resolve => nextTick(() => resolve(undefined)));
```

While nextTick is useful for handling large content during pasting, it can slow down operations when used in snapshotToDoc. It would be beneficial to add a parameter like usingNextTick to snapshotToDoc or explore other approaches to mitigate this issue.

**Comment by R151831** [comment]
@doodlewind  

We are encountering the same issue. Can we proceed with removing the nextTick line? 
Please let us know if there are any potential consequences of doing so.

**Comment by RajaTheKing826** [comment]
I'm also facing this issue from recent days. Don't we have any fix for this.

**Comment by EddiePengg** [comment]
我也遇到了这个问题，希望在json的处理上能够更优秀，这样就有更通用的语言，可以被更多项目使用
