### ISSUE TITLE
Redundant parents are selected during drag selection

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#839]
![Screenshot from 2023-01-24 16-57-13](https://user-images.githubusercontent.com/14026360/214439752-59037731-8f56-4b40-99a3-51a42c544d3d.png)

**Comment by doodlewind** [comment]
Can we ensure in this state, this only selected block is `1` here?

**Comment by doodlewind** [comment]
I found that for actual use case, the problem is that we can't select a sub-tree at any level for now. If I only want to select `3` here, it will include the `2` and `1` parents, which is not working as intended.

**Comment by himself65** [comment]
code spec:

1. mouse start a drag, save `mouse.pageX` `mouse.pageY` to the `startMouseInfo`
2. when the user drag to the end, collect all blocks inside the drag area
3. filter the blocks based on
    1. tag the first block that `block.x` and `block.y` > `startMouseInfo.pageX` and `startMouseInfo.pageY` as `firstBlock`
    2. track the following block if there are any blocks that are the same level as `firstBlock`, if so, return these blocks(including `firstBlock`)
    3. if there is no child block, return `firstBlock`
    4. else, treat the first child block inside the `firstBlock` as `firstBlock`, goto `3.1`

**Comment by himself65** [comment]
I would be happy if someone would keep working on https://github.com/toeverything/blocksuite/pull/840 because I don't have much time on this one

**Comment by fundon** [comment]
Is this the correct behavior?
1. Focus `3`
2. `ctrl-a` select `3`
3. `ctrl-a` select `2`
4. `ctrl-a` select `1`

**Comment by doodlewind** [comment]
This is acceptable, but the best expectation would be that the second cmd-A selects all blocks in the page, which aligns better with popular products.

**Comment by fundon** [comment]
If I understand correctly, the expectation is to show only one rect in the nested structure.

**Comment by doodlewind** [comment]
> If I understand correctly, the expectation is to show only one rect in the nested structure.

Exactly! If I click on `3`, only `3` itself should be selected, instead of bringing all of its parents in.

For now, this behavior make it annoying if you are using the block level selection to only pick one nested paragraph inside a page.

**Comment by fundon** [comment]
When I click on `4` and execute the shortcut `cmd-A`, Is it just `.ql-editor` of 4 that is selected, including `sub-tree`?

**Comment by doodlewind** [comment]
> When I click on `4` and execute the shortcut `cmd-A`, Is it just `.ql-editor` of 4 that is selected, or including `sub-tree`?
> 
>  Screen.Recording.2023-01-30.at.6.44.16.PM.mov

I think the expectation here will be select `4` with its sub-tree, which could be easier to implement, and can make the behavior of `DragHandle` much more intuitive. However if one user only wants to select `4` without its children, this may not be what their want - this could be an acceptable tradeoff, since native range selection should work fine here.

**Comment by joebeijing** [comment]
> When I click on `4` and execute the shortcut `cmd-A`, Is it just `.ql-editor` of 4 that is selected, or including `sub-tree`?
> 
>  Screen.Recording.2023-01-30.at.6.44.16.PM.mov

I have tried the effect that has been made, so far it is as expected.
Very awesome.
The basic rule is that selecting a Block will automatically include the selected Block and all its nested sub-level Blocks

And there are three common ways to select a Block
1. long press outside the editing area to start a cross-block selection
2. Cmd + A shortcut key
3. click Drag Handle

Finally, it is true that for the time being we are not considering selecting higher-level blocks one by one each time we use the Cmd + A shortcut to select all, although it is more flexible, but this will make the path of using Cmd + A to select the full text longer, we prefer to keep it simple, although it will cause tradeoff.

**Comment by himself65** [comment]
I think the fix has landed in https://github.com/toeverything/blocksuite/pull/904
