### ISSUE TITLE
Bump to TypeScript 5.0

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#843]
Refs: https://github.com/microsoft/TypeScript/issues/51362#issuecomment-1402896010

**Comment by doodlewind** [comment]
Added to good first issue in the [Kanban](https://github.com/orgs/toeverything/projects/10/views/14)

**Comment by suica** [comment]
Tried to fix this in https://github.com/toeverything/blocksuite/pull/1662.
