### ISSUE TITLE
What is the reason for switching the packageManager from pnpm to yarn?

### ISSUE THREAD

**Issue by awehook** [toeverything/blocksuite#8440]
What is the reason for switching the packageManager from pnpm to yarn?

**Comment by doodlewind** [comment]
Hi, pnpm is great (and even faster in my device)! But since the main downstream project [AFFiNE](https://github.com/toeverything/AFFiNE) is using yarn, switching to yarn makes it easier to debug these two projects together.

For community developers, there shouldn't be noticeable difference.
