### ISSUE TITLE
Uncaught TypeError: Illegal constructor (version: ^0.17.0)

### ISSUE THREAD

**Issue by yhua98** [toeverything/blocksuite#8448]
In version 0.17.0 and above, the "Uncaught TypeError: Illegal constructor" error occurs.

vue basic project created using vite

- error case
<img width="395" alt="image" src="https://github.com/user-attachments/assets/33964f33-c618-4692-b9b0-ef6cead15b75">

- dependencies
<img width="386" alt="image" src="https://github.com/user-attachments/assets/a5ce8d63-7db2-4206-b359-0692ca24e017">

**Comment by doodlewind** [comment]
Call this before initializing editors:

```
import { effects as blocksEffects } from '@blocksuite/blocks/effects';
import { effects as presetsEffects } from '@blocksuite/presets/effects';

blocksEffects();
presetsEffects();
```

**Comment by yhua98** [comment]
> Call this before initializing editors:
> 
> ```
> import { effects as blocksEffects } from '@blocksuite/blocks/effects';
> import { effects as presetsEffects } from '@blocksuite/presets/effects';
> 
> blocksEffects();
> presetsEffects();
> ```

有用,解决了
is worked,thanks
