### ISSUE TITLE
affine.css not found

### ISSUE THREAD

**Issue by mjp0** [toeverything/blocksuite#8451]
I'm trying out the nextjs starter and there's a line `import '@blocksuite/presets/themes/affine.css'` but build crashes because `affine.css` is not there. I mean I literally can't find the file anywhere. I can see `@blocksuite/presets` installed normally and the editor loads fine but that style file doesn't exist, so styling is off. I tried to find the file manually and went through sources but I'm guessing it's compiled, so couldn't find it.

I must be doing something wrong here 🤣 

If it matters, I'm using `pnpm` as a package manager.

**Comment by mjp0** [comment]
Turns out, I'm not insane because apparently something got f'ed it themes folder got dropped after 0.17.13 - https://www.npmjs.com/package/@blocksuite/presets/v/0.17.13?activeTab=code

**Comment by xiaogonggong-w** [comment]
I found style.css in @toeverything/theme

**Comment by mjp0** [comment]
> I found style.css in @toeverything/theme.

I'm using it too now but had to find that affine.css to know to look for @toeverything/theme ;)
