### ISSUE TITLE
How do I update a block or add a block with content?

### ISSUE THREAD

**Issue by mjp0** [toeverything/blocksuite#8455]
I have a simple question: how do I update a block, or even how do I add a block with text?

The API docs don't explain the logic behind methods and guides seem to be outdated, so I can't seem to find the right combination.

Here's one of the ways I tried. Guides use `doc.getBlockById` but that's deprecated and replaced by `getBlock`, so I guess `paragraph.model` is the right way because updateBlock expects `BlockModel` instead of `Block` that `getBlock` returns? In any case, this way doesn't work either.
```ts
const pageBlockId = doc.addBlock('affine:page', {});
doc.addBlock('affine:surface', {}, pageBlockId);
const noteId = doc.addBlock('affine:note', {}, pageBlockId);
const paragraphId = doc.addBlock('affine:paragraph', {}, noteId);
const paragraph = doc.getBlock(paragraphId);
doc.updateBlock(paragraph?.model, {
  text: 'some text',
});
```

This particular way crashes with `rich-text need yText to init.` error but since typings aren't giving me any errors and `updateBlock` is asking for `text: string`  🤷‍♂️

**Comment by doodlewind** [comment]
Try this:

``` ts
import { Text } from '@blocksuite/store';

doc.updateBlock(myBlock, {
  text: new Text('some text'),
})
```

This is designed since inline rich text is also supported.
