### ISSUE TITLE
How to pass handleDoubleClick or handleClick to an embed-linked-doc?

### ISSUE THREAD

**Issue by xiaogonggong-w** [toeverything/blocksuite#8465]
I looked at the embed-linked-doc source code, which includes **handleDoubleClick** and **handleClick**, They come from **this.std.getConfig('affine:embed-linked-doc')**, and my question is whether there is a function like **setConfig** that allows me to pass functions

**Comment by L-Sun** [comment]
We use a extension architecture with dependency injection, and we provide a simple config extension implement in `packages/affine/block-embed/src/embed-linked-doc-block/embed-linked-doc-config.ts`. Here is a example:
```ts
import { EmbedLinkedDocBlockConfigExtension } from '@blocksuite/affine-block-embed';

editor.specs = [
    ...editor.specs, 
    EmbedLinkedDocBlockConfigExtension(yourConfig)
]
```
