### ISSUE TITLE
codesandbox preview is unavaliable for public

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#847]

**Comment by himself65** [comment]
Refs: https://codesandbox.io/docs/learn/integrations/github-app#privacy-and-permissions

**Comment by doodlewind** [comment]
I think it's working as intended for now. Take #858 as an example, the CodeSandbox link in this PR ( https://codesandbox.io/p/github/toeverything/blocksuite/0126/build?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D ) works in incognito tab. Not sure if I am misunderstanding the "public preview" here, could you elaborate?

**Comment by himself65** [comment]
<img width="753" alt="image" src="https://user-images.githubusercontent.com/14026360/214883520-5ddeeb8d-9bfa-4201-93aa-15698e8709bc.png">

**Comment by lawvs** [comment]
The URL https://codesandbox.io/p/github/toeverything/blocksuite/0126/build?file=%2FREADME.md works on my machine.

<img width="945" alt="Screenshot 2023-01-26 at 11 57 40 PM" src="https://user-images.githubusercontent.com/18554747/214884447-a96c7431-27be-45d3-80f1-7d8370f472e5.png">

But the actual code sandbox link in PR such as   https://github.com/toeverything/blocksuite/pull/851 not work.

https://codesandbox.io/p/github/toeverything/blocksuite/20230125-tsc?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D

<img width="805" alt="Screenshot 2023-01-26 at 11 59 54 PM" src="https://user-images.githubusercontent.com/18554747/214885017-94d806c6-d057-456d-85cd-78ff76ff88e6.png">
