### ISSUE TITLE
​Images are not loading after importing from Notion

### ISSUE THREAD

**Issue by andkulikov** [toeverything/blocksuite#8486]
### What happened?

Hello and thanks for working on this project!
I tried to start using it by exporting my notes from Notion, and noticed that some of the notes are exported without their inline images being correctly displayed. It stuck with displaying "Loading image", see the screenshot
<img width="581" alt="Screenshot 2024-09-03 163523" src="https://github.com/user-attachments/assets/5b8db0a8-c78a-4838-9ced-e5ecebad5cd2">.
I uploaded the file I've got from Notion which I am trying to import (it only contains one page repoducing the issue):
[df4b697c-b8be-4de0-a40f-85e21b037685_Export-a5d2b0ea-d24f-4285-8dfc-1cd15b754cab.zip](https://github.com/user-attachments/files/16851162/df4b697c-b8be-4de0-a40f-85e21b037685_Export-a5d2b0ea-d24f-4285-8dfc-1cd15b754cab.zip)
Thanks!

### Distribution version

Web (app.affine.pro)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Firefox

### Are you self-hosting?

- [ ] yes

**Comment by fourdim** [comment]
> I can reproduce this issue in the blocksuite.

What's your environment? Did you see any error in the console?

![image](https://github.com/user-attachments/assets/439329ad-fccf-42f2-9073-ab9214b3b939)

I cannot reproduce from my side.

**Comment by fourdim** [comment]
I just need some logs from you guys to debug the root cause.
Could you please go to https://try-blocksuite.vercel.app/
import your zip files there and send me the console logs?
Console log can be accessed from the developer tools `F12` or `CTRL/CMD+Shift+I`.

**Comment by lawvs** [comment]
My bad, I used the HTML import instead of Notion.

Did you use the correct import method? Make sure you select the zip file when you import it. @andkulikov 

https://github.com/user-attachments/assets/6bbeb4b8-5301-4357-9c83-0f2b7c7f708a

**Comment by andkulikov** [comment]
It seems like it was fixed already while this bug was waiting for the triage. I had 0.16.3 version of the Affine Windows client and there images are not loading after the import. Now I updated to the latest 0.17.2 and the page is being imported correctly. Thanks
