### ISSUE TITLE
The Drag Handle is not shown in the documentation?

### ISSUE THREAD

**Issue by xiaogonggong-w** [toeverything/blocksuite#8521]
# The Drag Handle is not shown in the documentation.
<img width="671" alt="image" src="https://github.com/user-attachments/assets/2c121f2c-806b-4b8c-bab1-0bee1ee6168d">

When I hover my mouse over the content, the Drag Handle disappears.

import './App.css'
import { useEffect } from "react"
import { useRef } from "react"
import { Schema } from '@blocksuite/store';
import { DocCollection } from '@blocksuite/store';
import { AffineSchemas } from '@blocksuite/blocks';
import { PageEditor, AffineEditorContainer, EdgelessEditor, DocTitle } from "@blocksuite/presets";
import { effects } from '@blocksuite/presets/effects'
import { effects as blockEffects } from '@blocksuite/blocks/effects'
effects()
blockEffects()
const editor = new AffineEditorContainer()
function App() {
  const editorRef = useRef(null)

  useEffect(() => {
    const schema = new Schema().register(AffineSchemas);
    const collection = new DocCollection({ schema });
    collection.meta.initialize();
    const doc = collection.createDoc({ id: 'page1' });

    doc.load(() => {
      const pageBlockId = doc.addBlock('affine:page', {});
      doc.addBlock('affine:surface', {}, pageBlockId);
      const noteId = doc.addBlock('affine:note', {}, pageBlockId);
      doc.addBlock('affine:paragraph', {}, noteId);
    });

    

    // title.doc = doc
    // titleRef.current.appendChild(title)

   
    editor.doc = doc
    editorRef.current.appendChild(editor)
  }, [])
  return (
    <>
      <div ref={editorRef} style={{
        marginInline: 300
      }}>
      </div>
    </>

  )
}

export default App

"@blocksuite/blocks": "^0.17.14",
    "@blocksuite/global": "^0.17.14",
    "@blocksuite/lit": "^0.13.0",
    "@blocksuite/presets": "0.17.14",
    "@blocksuite/store": "^0.17.14",

**Comment by miro-ku** [comment]
I've encountered same issues after updating from v0.16 to v0.19. After some reverse-engineering and debugging found out that it doesn't work because of the default `DocModeProvider`. So I've ended up with this solution:

```typescript
import {
  AffineEditorContainer,
  OutlineViewer,
  PageEditor,
} from '@blocksuite/presets';
import {
  EdgelessEditorBlockSpecs,
  PageEditorBlockSpecs,
  RefNodeSlotsExtension,
  RefNodeSlotsProvider,
  DocModeProvider,
  DocMode,
} from '@blocksuite/blocks';
import type { ExtensionType } from '@blocksuite/block-std';

export const docModeStorage = useStorage(
  'affine-doc-mode',
  {} as Record<string, DocMode>,
);

export const DEFAULT_DOC_MODE = 'page';

export function dockModeService(editor: AffineEditorContainer | PageEditor) {
  const getEditorModeCallback: () => DocMode = () => {
    if (editor instanceof AffineEditorContainer) {
      return editor.mode;
    }
    return DEFAULT_DOC_MODE;
  };
  const setEditorModeCallback: (mode: DocMode) => void = (mode) => {
    if (editor instanceof AffineEditorContainer) {
      editor.switchEditor(mode);
    } else {
      throw new Error('Set editor mode is not supported for PageEditor');
    }
  };

  const docModeService: DocModeProvider = {
    getPrimaryMode: (docId: string) => {
      try {
        // YOUR GETTER HERE
        return; 
      } catch {
        return DEFAULT_DOC_MODE;
      }
    },
    onPrimaryModeChange: (handler: (mode: DocMode) => void, docId: string) => {
      return {
        dispose:  ...,
      };
    },
    getEditorMode: () => {
      return getEditorModeCallback();
    },
    setEditorMode: (mode: DocMode) => {
      setEditorModeCallback(mode);
    },
    setPrimaryMode: (mode: DocMode, docId: string) => {
      docModeStorage.value[docId] = mode;
    },
    togglePrimaryMode: (docId: string) => {
      const mode =
        docModeService.getPrimaryMode(docId) === 'page' ? 'edgeless' : 'page';
      docModeService.setPrimaryMode(mode, docId);
      return mode;
    },
  };

  return docModeService;
}

export function docModeExtension(editor: AffineEditorContainer | PageEditor) {
  return {
    setup: (di) => {
      di.override(DocModeProvider, dockModeService(editor));
    },
  } as ExtensionType;
}

const initEditor = () => {
  const editor =
    props.mode === 'doc'
      ? document.createElement('affine-editor-container')
      : new PageEditor();

  let outline: OutlineViewer | undefined;

  if (editor instanceof PageEditor) {
    editor.hasViewport = false;
  }

  editor.dataset.theme = useConfigStore().theme;
  editor.doc = props.entity.Description.doc;

  const commonSpecs = [
       // HERE
       docModeExtension(editor),
       RefNodeSlotsExtension()
  ];

  if (editor instanceof AffineEditorContainer) {
    editor.pageSpecs = [...PageEditorBlockSpecs, ...commonSpecs];
    editor.edgelessSpecs = [...EdgelessEditorBlockSpecs, ...commonSpecs];

    editor.std.get(RefNodeSlotsProvider).docLinkClicked.on(({ pageId }) => {
      const doc = useChatsStore().one(pageId);
      if (doc) {
        navigateTo({
          name: 'space_uid-docs-doc_uid',
          params: {
            doc_uid: pageId,
          },
        });
      }
    });

    outline = new OutlineViewer();

    outline.editor = editor;
  } else {
    editor.specs = [...PageEditorBlockSpecs, ...commonSpecs];
  }

  return { editor, outline };
};
```
