### ISSUE TITLE
​Properties in Kanban can't be hide except status

### ISSUE THREAD

**Issue by Himlol** [toeverything/blocksuite#8654]
### What happened?

Any properties in kanban view can't be hide. When I press "Hide all" it's hide only status properties.
"Eyes" bottoms looks like presseble, but it didn't. 

![image](https://github.com/user-attachments/assets/d106e903-c879-4a08-8f55-261e0b9e00b0)

### Distribution version

Linux

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you self-hosting?

- [X] Yes

### Relevant log output

```shell
Nothing interesting in browser logs or affine pod logs.
```

**Comment by OlegDev1** [comment]
It was probably fixed, could you please check it again? Works perfectly fine for me

**Comment by Himlol** [comment]
Hello,

In which version did this work correctly for you?
I just checked in version 0.18.0 with editor 0.17.33 and the problem still exists.
![image](https://github.com/user-attachments/assets/d42e5b28-5a0c-453a-98ef-6e75bbaf123a)
![image](https://github.com/user-attachments/assets/28012f37-f62c-4932-9a8f-0ff28cadc668)

**Comment by OlegDev1** [comment]
I am using the latest version from https://try-blocksuite.vercel.app/, everything works as expected. Try to pull new commits and test it again
![Screenshot 2024-12-10 at 18 01 58](https://github.com/user-attachments/assets/b114ef45-d8f3-465d-acaf-4fa91d5bb733)
