### ISSUE TITLE
reference-node external configuration

### ISSUE THREAD

**Issue by xiaofeiniuuu** [toeverything/blocksuite#8765]
How to update the config value of
const config = provider.getOptional(ReferenceNodeConfigIdentifier) ​​?? {}; after upgrading
Do I need to use ReferenceNodeConfigExtension? How to use it?
I see that affine-paragraph no longer has referenceNodeConfig

**Comment by xiaofeiniuuu** [comment]
![image](https://github.com/user-attachments/assets/fda8cb90-4b00-401d-8ee9-65fd1566705a)
How to update this value externally

**Comment by xiaofeiniuuu** [comment]
![image](https://github.com/user-attachments/assets/d71f0801-6fbe-4be5-bc4a-f6a9a9d7497a)

This is what I'm doing now. Is this correct?

**Comment by L-Sun** [comment]
You can add a `ConfigExtension` to `editor.pageSpecs` and `editor.edgelessSpecs`. For example, in the setup stage of playground editor:
- Before
https://github.com/toeverything/blocksuite/blob/bfb0c7fa5e746bdec4e5cd7c165efcbc4e0d88e7/packages/playground/apps/default/utils/editor.ts#L58-L66
- After
  ```ts
  const referenceNodeConfigExtension : ExtensionType = {
  } 

  editor.pageSpecs = patchPageRootSpec([
    refNodeSlotsExtension,
    ...specs.pageModeSpecs,
    configs,
  ]);
  editor.edgelessSpecs = patchPageRootSpec([
    refNodeSlotsExtension,
    ...specs.edgelessModeSpecs,
   configs,
  ]);
  ```
