### ISSUE TITLE
some modules not compatable with tsconfig `moduleResolution: 'Node'`

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#8832]
Some modules don't support for example:

- @blocksuite/block-std/gfx 

Some modules do support like `@blocksuite/global/utils`

**Comment by himself65** [comment]
https://arethetypeswrong.github.io/?p=%40blocksuite%2Fstore%400.18.1

https://arethetypeswrong.github.io/?p=%40blocksuite%2Fblock-std%400.18.1

https://arethetypeswrong.github.io/?p=%40blocksuite%2Fblocks%400.18.1

**Comment by doodlewind** [comment]
Closed by #8834
