### ISSUE TITLE
Incorrect indent beahvior

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#893]
test with [blocksuite](https://blocksuite-toeverything.vercel.app/?init=AAMAAw8H8cOD8R25AbUBAAIBAAgBBhQBAw4BAAgBAUxiPAECSBKCAQEDwAGMAYYBAQPEAZABOgEDeIQBjgICFgIiAQLIA5IDiAEBAsYBkAGcAQIKApQHAQL8CIYJogICEgKKAQISApoBAQLwBboFmgICCgK0BAIMAhABAvoHhAisBQI6AoQDAQLsCbYJggMCjAECuAEBAsgGkgaAAQIiAtgxojEBAkIMEgECUAIUxjKSMmgsTCABAlJKIlombDAEAQJCDAOOAQDVAicABwAoACEAKAAnACgIJwAoAScCKAAnACgBJwEoAScAKAAIAKgAJwAoAScAKAAnAAgABAAnACgBJwAoAScAiAAEACcAKAEnACgBJwCIAAQAJwAoAScAKAEnAIgABACGAIQAhgCEACcAKAEnACgAJwCIAAQAJwAoAScAKAAnAIgABACGAIQAhgCEACcAKAEnACgAJwCIAAQAhgCEAIYAhACGAIQAhgCEACcAKAEnACgAJwCIAAQAhgCEAIYAhACGAIQAhgCEACcAKAEnACgAJwCIAAQAhgCEAIYAhAAnACgBJwAoACcAiAAEAIYAhACGAIQAJwAoAScAKAAnAIgABACGAIQAhgCEAKgAJwAoAScAKAAnAEgAqAAEACcAKAEnACgAJwDIAKgApwEIAKcACAAEACcAKAEnACgAJwCIAKgApwEIAKcACAAnACgBJwAoACcAiAAEsBnlF3NwYWNlOm1ldGFwYWdlc2lkdGl0bGVjcmVhdGVEYXRlc3BhY2U6bWV0YXZlcnNpb25zYWZmaW5lOmNvZGVhZmZpbmU6cGFyYWdyYXBoYWZmaW5lOnBhZ2VhZmZpbmU6bGlzdGFmZmluZTpmcmFtZWFmZmluZTpkaXZpZGVyYWZmaW5lOmVtYmVkYWZmaW5lOnN1cmZhY2VhZmZpbmU6ZGF0YWJhc2VzcGFjZTpwYWdlMDQwMTA4MzIxMTM6MHN5czppZHN5czpmbGF2b3VybWV0YTp0YWdzbWV0YTp0YWdTY2hlbWFzeXM6Y2hpbGRyZW5wcm9wOnRpdGxlc3BhY2U6cGFnZTA0MDEwODMyMTEzOjFzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnNwYWNlOnBhZ2UwNDAxMDgzMjExMzoyc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnh5d2hzcGFjZTpwYWdlMDQwMTA4MzIxMTM6M3N5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0VGhpcyBwbGF5Z3JvdW5kIGlzIGRlc2lnbmVkIHRvOnNwYWNlOnBhZ2UwNDAxMDgzMjExMzo0c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHTwn5OdIFRlc3QgYmFzaWMgZWRpdGluZyBleHBlcmllbmNlLnNwYWNlOnBhZ2UwNDAxMDgzMjExMzo1c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHTimpnvuI8gU2VydmUgYXMgRTJFIHRlc3QgZW50cnkuc3BhY2U6cGFnZTA0MDEwODMyMTEzOjZzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6Y2hlY2tlZHByb3A6dGV4dPCflJcgRGVtb25zdHJhdGUgaG93IEJsb2NrU3VpdGUgcmVjb25jaWxlcyByZWFsLXRpbWUgY29sbGFib3JhdGlvbiB3aXRoIGxpbmtsb2NhbC1maXJzdGxpbmsgZGF0YSBvd25lcnNoaXAuc3BhY2U6cGFnZTA0MDEwODMyMTEzOjdzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dENvbnRyb2xsaW5nIFBsYXlncm91bmQgRGF0YSBTb3VyY2VzcGFjZTpwYWdlMDQwMTA4MzIxMTM6OHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0WW91IG1pZ2h0IGluaXRpYWxseSBlbnRlciB0aGlzIHBhZ2Ugd2l0aCB0aGUgY29kZT9pbml0Y29kZSBVUkwgcGFyYW0uIFRoaXMgaXMgdGhlIGRlZmF1bHQgKG9wdC1pbikgc2V0dXAgdGhhdCBhdXRvbWF0aWNhbGx5IGxvYWRzIHRoaXMgYnVpbHQtaW4gYXJ0aWNsZS4gTWVhbndoaWxlLCB5b3UnbGwgY29ubmVjdCB0byBhIHJhbmRvbSBzaW5nbGUtdXNlciByb29tIHZpYSBhIFdlYlJUQyBwcm92aWRlciBieSBkZWZhdWx0LiBUaGlzIGlzIHRoZSAic2luZ2xlLXVzZXIgbW9kZSIgZm9yIGxvY2FsIHRlc3Rpbmcuc3BhY2U6cGFnZTA0MDEwODMyMTEzOjlzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dFRvIHRlc3QgcmVhbC10aW1lIGNvbGxhYm9yYXRpb24sIHlvdSBjYW4gc3BlY2lmeSB0aGUgcm9vbSB0byBqb2luIGJ5IGFkZGluZyB0aGUgY29kZT9yb29tPWZvb2NvZGUgY29uZmlnIC0gVHJ5IG9wZW5pbmcgdGhpcyBwYWdlIHdpdGggY29kZT9yb29tPWZvb2NvZGUgaW4gdHdvIGRpZmZlcmVudCB0YWJzIGFuZCBzZWUgd2hhdCBoYXBwZW5zIXNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxMHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0Tm90ZSB0aGF0IHRoZSBzZWNvbmQgYW5kIHN1YnNlcXVlbnQgdXNlcnMgc2hvdWxkIG5vdCBvcGVuIHRoZSBwYWdlIHdpdGggdGhlIGNvZGU%2FaW5pdGNvZGUgcGFyYW0gaW4gdGhpcyBjYXNlLiBBbHNvLCBkdWUgdG8gdGhlIFAyUCBuYXR1cmUgb2YgV2ViUlRDLCBhcyBsb25nIGFzIHRoZXJlIGlzIGF0IGxlYXN0IG9uZSB1c2VyIGNvbm5lY3RlZCB0byB0aGUgcm9vbSwgdGhlIGNvbnRlbnQgaW5zaWRlIHRoZSByb29tIHdpbGwgYm9sZGFsd2F5c2JvbGQgZXhpc3Quc3BhY2U6cGFnZTA0MDEwODMyMTEzOjExc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRJZiB5b3UgYXJlIHRoZSBvbmx5IHVzZXIgaW4gdGhlIHJvb20sIHlvdXIgY29udGVudCB3aWxsIGJlIGxvc3QgYWZ0ZXIgcmVmcmVzaC4gVGhpcyBpcyBncmVhdCBmb3IgbG9jYWwgZGVidWdnaW5nLiBCdXQgaWYgeW91IHdhbnQgbG9jYWwgcGVyc2lzdGVuY2UsIHlvdSBjYW4gb3BlbiB0aGlzIHBhZ2Ugd2l0aCB0aGUgY29kZT9wcm92aWRlcnM9aW5kZXhlZGRiJnJvb209Zm9vY29kZSBjb25maWcsIHRoZW4gY2xpY2sgdGhlIGluaXQgYnV0dG9uIGluIHRoZSBib3R0b20tbGVmdCBjb3JuZXIgdG8gaW5pdGlhbGl6ZSB0aGlzIGRlZmF1bHQgY29udGVudC5zcGFjZTpwYWdlMDQwMTA4MzIxMTM6MTJzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnByb3A6dHlwZXByb3A6dGV4dEFzIGEgcHJvIHRpcCwgeW91IGNhbiBjb21iaW5lIG11bHRpcGxlIHByb3ZpZGVycyEgRm9yIGV4YW1wbGUsIGZlZWwgZnJlZSB0byBvcGVuIHRoaXMgcGFnZSB3aXRoIGNvZGU%2FcHJvdmlkZXJzPWluZGV4ZWRkYix3ZWJydGMmcm9vbT1oZWxsb2NvZGUgcGFyYW1zLCBhbmQgc2VlIGlmIGV2ZXJ5dGhpbmcgd29ya3MgYXMgZXhwZWN0ZWQuIEhhdmUgZnVuIXNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxM3N5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0Rm9yIGFueSBmZWVkYmFjaywgcGxlYXNlIHZpc2l0IGxpbmtCbG9ja1N1aXRlIGlzc3Vlc2xpbmsg8J%2BTjXNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxNHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0cGFyZW50c3BhY2U6cGFnZTA0MDEwODMyMTEzOjE1c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRjaGlsZHJlbnNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxNnN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0c3BhY2U6cGFnZTA0MDEwODMyMTEzOjE3c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRncmFuZHNvbgoFAgVKAAgLEEsADA4MDg8LDAYLCQ4MCgsMBgsMCwwGCwwJCwwGCwxJAB8LDAYLDAkMCSELDAYLDAkMCRsLDAYLDAkMCYYBBAsEEAsMBgsMSQAiCwwGCwxJAC0EBQSpAwsMBgsMSQCQAQQJBCUECQQsCw0GCwxJAIwBBAUEmgIEBgQHCw0GCwxJALUCBB0EoQELDQYLDEkAoAEEJgQ7Cw0GCwxJAB8EEQQDCw0GCwxJAAYLDQYLDEkACAsNBgsMSQALDQYLDEkACE8BAAADAQAACAEAAAUBAAACAQAABAEAAAYBAAAGAQAABgEAAAYBAAAFAQAABQEAAAUBAAAFAQAABQEAAAUBAAAFAQAABQEAAAcBAAAGAQAAOQBBAwABAAEAAQACAQACAQACAQACAQACAQACAQACAQACAQACAQACAQACAQACAQACQAEBAAJAAQEAAgJBWwHNAQB3BXBhZ2Uwe0J4X%2B3gOHAAfQF9AX0BfQF9AX0BfQF9AX0Bdww0MDEwODMyMTEzOjB3C2FmZmluZTpwYWdldyBXZWxjb21lIHRvIEJsb2NrU3VpdGUgcGxheWdyb3VuZHcMNDAxMDgzMjExMzoxdw5hZmZpbmU6c3VyZmFjZXcMNDAxMDgzMjExMzoydwxhZmZpbmU6ZnJhbWV3DVswLDAsNzIwLDQ4MF13DDQwMTA4MzIxMTM6MncgV2VsY29tZSB0byBCbG9ja1N1aXRlIHBsYXlncm91bmR3DDQwMTA4MzIxMTM6M3cQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcMNDAxMDgzMjExMzozdww0MDEwODMyMTEzOjR3C2FmZmluZTpsaXN0dwhidWxsZXRlZHl3DDQwMTA4MzIxMTM6NHcMNDAxMDgzMjExMzo1dwthZmZpbmU6bGlzdHcIYnVsbGV0ZWR5dww0MDEwODMyMTEzOjV3DDQwMTA4MzIxMTM6NncLYWZmaW5lOmxpc3R3CGJ1bGxldGVkeXcMNDAxMDgzMjExMzo2dzNodHRwczovL21hcnRpbi5rbGVwcG1hbm4uY29tL3BhcGVycy9sb2NhbC1maXJzdC5wZGZ%2Bdww0MDEwODMyMTEzOjd3EGFmZmluZTpwYXJhZ3JhcGh3Amgydww0MDEwODMyMTEzOjd3DDQwMTA4MzIxMTM6OHcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcMNDAxMDgzMjExMzo4eH53DDQwMTA4MzIxMTM6OXcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcMNDAxMDgzMjExMzo5eH54fncNNDAxMDgzMjExMzoxMHcQYWZmaW5lOnBhcmFncmFwaHcFcXVvdGV3DTQwMTA4MzIxMTM6MTB4fnh%2Bdw00MDEwODMyMTEzOjExdxBhZmZpbmU6cGFyYWdyYXBodwR0ZXh0dw00MDEwODMyMTEzOjExeH53DTQwMTA4MzIxMTM6MTJ3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DTQwMTA4MzIxMTM6MTJ4fncNNDAxMDgzMjExMzoxM3cQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNNDAxMDgzMjExMzoxM3cxaHR0cHM6Ly9naXRodWIuY29tL3RvZXZlcnl0aGluZy9ibG9ja3N1aXRlL2lzc3Vlc353DVswLDAsNzIwLDgzMV13DTQwMTA4MzIxMTM6MTR3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DTQwMTA4MzIxMTM6MTR3DFswLDAsNzIwLDMyXXcNNDAxMDgzMjExMzoxNXcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNNDAxMDgzMjExMzoxNXcMWzAsMCw3MjAsNzJddw00MDEwODMyMTEzOjE0dw00MDEwODMyMTEzOjE1dw00MDEwODMyMTEzOjE2dxBhZmZpbmU6cGFyYWdyYXBodwR0ZXh0dw00MDEwODMyMTEzOjE2dw1bMCwwLDcyMCwxMTJddw00MDEwODMyMTEzOjE1dw00MDEwODMyMTEzOjE2dw00MDEwODMyMTEzOjE3dxBhZmZpbmU6cGFyYWdyYXBodwR0ZXh0dw00MDEwODMyMTEzOjE3AfHhwfgOCwMAGQECrQwDAAIBCQACAgIBCAYBAAMA) 

https://user-images.githubusercontent.com/18554747/215348853-a638e9ed-1e3f-4896-b70a-072ec7703e89.mov

test in [blocksuite](https://blocksuite-toeverything.vercel.app/?init=AABl8cOD8R06oZOJ7wvxw4PxHQChk4nvC%2FHDg%2FEdAOGTie8LFLHDg%2FEd4ZOJ7wsHscOD8R3hk4nvCwHxw4PxHQDhk4nvCwPxw4PxHQChk4nvC7HDg%2FEd4ZOJ7wsEscOD8R3hk4nvCzydAQACAQAIAQYUAQMOAQAIAQFMYjaiMQECQgwSAQJOFMYykjJoIAQIJmwwBAECQgxW8jMIAQAGRgEADgJWKAEDDE4SAqIx2DECRAZEAQAIyAGAAR5YsjLEMgECgjL4MbYx%2BjFcOAAGSLIw5DBQcDoMRg5EQuIBtgEBAwwCEAEDQghyPmouejAGCEQWXCICSA5KDlBEKgEDVAIYXCpwNEwQrjIAIMgzCr4yBjb0MqIBAN8CJwAHACgAIQAoACcAKAgnACgBJwIoACcAKAEnASgBIQEIAKgAIQAAACEAAAAhAAAAIQAAACEAAAAhAAAAIQAAACEAAAAhAAAAIQAAACEAAAChACcAKAEhACgAJwAAAKEABAAnACgBIQAoACcAAAChAacACAChAAAABAAhAAAAqAAAAKcACACnAAEAJwAoAScAKAAnAIgABABEAKgAxABIACcAKAEnAAgAKAEnAKcABABIAKgAJwAoAScAKAEnAEgABACoAIQAqACnACcABACoAIQAKAKEAMgAJwAIAKgARACnACgBJwAoACcAyAAEAKcCCACnAAgApwEIAKcAqACnAggApwCoAMQAJwAoAScAKAEnAKcABABIACcAKAEnACgBJwDIAKcBCACnAAgAqAAEAKcAqACnAAgApwCIAKcBCACnAAgAqACEACcAKAEnACgBJwCIAKgApwEIAKcACAAEwgysC3NwYWNlOm1ldGFwYWdlc2lkdGl0bGVjcmVhdGVEYXRlc3BhY2U6bWV0YXZlcnNpb25zYWZmaW5lOmNvZGVhZmZpbmU6cGFyYWdyYXBoYWZmaW5lOnBhZ2VhZmZpbmU6bGlzdGFmZmluZTpmcmFtZWFmZmluZTpkaXZpZGVyYWZmaW5lOmVtYmVkYWZmaW5lOnN1cmZhY2VhZmZpbmU6ZGF0YWJhc2VzcGFjZTpwYWdlMDQwMTA4MzIxMTM6MHN5czppZHN5czpmbGF2b3VybWV0YTp0YWdzbWV0YTp0YWdTY2hlbWFzeXM6Y2hpbGRyZW5wcm9wOnRpdGxlc3BhY2U6cGFnZTA0MDEwODMyMTEzOjFzeXM6aWRzeXM6Zmxhdm91cnN5czpjaGlsZHJlbnNwYWNlOnBhZ2UwNDAxMDgzMjExMzoyc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnh5d2hzcGFjZTpwYWdlMDQwMTA4MzIxMTM6M3NwYWNlOnBhZ2UwNDAxMDgzMjExMzo0c3BhY2U6cGFnZTA0MDEwODMyMTEzOjVzcGFjZTpwYWdlMDQwMTA4MzIxMTM6NnNwYWNlOnBhZ2UwNDAxMDgzMjExMzo3c3BhY2U6cGFnZTA0MDEwODMyMTEzOjhzcGFjZTpwYWdlMDQwMTA4MzIxMTM6OXNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxMHNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxMXNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxMnNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxM3NwYWNlOnBhZ2UwNDAxMDgzMjExMzoxNHN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0cGFyZW50c3BhY2U6cGFnZTA0MDEwODMyMTEzOjE1c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOnRleHRjaGlsZHJlbnNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxNnNwYWNlOnBhZ2UwNDAxMDgzMjExMzoxN3N5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0Z3JhbmRzb24tIHNwYWNlOnBhZ2UwMTU5Mjg2MTkyMTowc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHRwYXJlbnRzcGFjZTpwYWdlMDE1OTI4NjE5MjE6MXN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDpjaGVja2VkcHJvcDp0ZXh0Y2hpbHByb3A6dGV4dC0gc3lzOmlkc3lzOmZsYXZvdXJwcm9wOnR5cGVwYXJlbnRzeXM6Y2hpbGRyZW5jaGlsZHJlbnN5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDp0ZXh0Z3JhbmRzb24tIHNwYWNlOnBhZ2UwMTU5Mjg2MTkyMToyc3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHRwYXJlbnRzcGFjZTpwYWdlMDE1OTI4NjE5MjE6M3N5czppZHN5czpmbGF2b3Vyc3lzOmNoaWxkcmVucHJvcDp0eXBlcHJvcDpjaGVja2VkcHJvcDp0ZXh0Z3JhbmRzb25jaGlsZHJlbnNwYWNlOnBhZ2UwMTU5Mjg2MTkyMTo0c3lzOmlkc3lzOmZsYXZvdXJzeXM6Y2hpbGRyZW5wcm9wOnR5cGVwcm9wOmNoZWNrZWRwcm9wOnRleHRncmFuZHNvbgoFAgVKAAgLEEsADA4MDg8LDAYLCQ4MCgsMBgsMCwwGCwwJCwwLDAsMCwwLDAsMCwwLDQsNCw0LDQsNBgsMSQAGCw0GCwxJAAgLDQsNBgsMSQAIQQALDAYLDAkMCQYLDAYLDAkMCQEDCUEABgsJBgwIBgsMSQAIAgsMBgsMCQwJBgsMBgsMCQwJSAALDAYLDAkMCQg3AQAAAwEAAAgBAAAFAQAAAgEAAAQBCwAFAQAABgEAAAEBAAAFAQAABwEAABcBAAAGAQAACwEAAC0AQQMAAQBBAAIBAkABAQACAQBCAAEAAgECAAEAAkAJAQBCAAEAAkAHAQACQAEpQRYlASgBIgGqAQEoAaMEAb0CAYIEAbsEAYkDATtBEAZBIQIBAgECQRoCXwB3BXBhZ2Uwe0J4X%2B3gOHAAfQF9AX0BfQF9AX0BfQF9AX0Bdww0MDEwODMyMTEzOjB3C2FmZmluZTpwYWdldyBXZWxjb21lIHRvIEJsb2NrU3VpdGUgcGxheWdyb3VuZHcMNDAxMDgzMjExMzoxdw5hZmZpbmU6c3VyZmFjZXcMNDAxMDgzMjExMzoydwxhZmZpbmU6ZnJhbWV3DDQwMTA4MzIxMTM6MncgV2VsY29tZSB0byBCbG9ja1N1aXRlIHBsYXlncm91bmR3DTQwMTA4MzIxMTM6MTR3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DTQwMTA4MzIxMTM6MTV3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DTQwMTA4MzIxMTM6MTR3DVswLDAsNzIwLDExMl13DTQwMTA4MzIxMTM6MTV3DTQwMTA4MzIxMTM6MTd3EGFmZmluZTpwYXJhZ3JhcGh3BHRleHR3DTQwMTA4MzIxMTM6MTd5AHcMWzAsMCw3MjAsNzJddw00MDEwODMyMTEzOjE1dwwxNTkyODYxOTIxOjB3C2FmZmluZTpsaXN0dw00MDEwODMyMTEzOjE1dwhidWxsZXRlZHl3DDE1OTI4NjE5MjE6MHcNWzAsMCw3MjAsMTEyXXcMMTU5Mjg2MTkyMToxdwthZmZpbmU6bGlzdHcIYnVsbGV0ZWR5dwwxNTkyODYxOTIxOjF3DVswLDAsNzIwLDE0NF13DVswLDAsNzIwLDExMl13DFswLDAsNzIwLDcyXXcNNDAxMDgzMjExMzoxNHcQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNNDAxMDgzMjExMzoxNHcNNDAxMDgzMjExMzoxNXcNWzAsMCw3MjAsMTEyXXcNNDAxMDgzMjExMzoxN3cQYWZmaW5lOnBhcmFncmFwaHcEdGV4dHcNNDAxMDgzMjExMzoxN3cNNDAxMDgzMjExMzoxNXcNNDAxMDgzMjExMzoxN3cNNDAxMDgzMjExMzoxNXcNNDAxMDgzMjExMzoxNHcNNDAxMDgzMjExMzoxN3cMWzAsMCw3MjAsNzJddw00MDEwODMyMTEzOjE0dw00MDEwODMyMTEzOjE1dwxbMCwwLDcyMCwzMl13DDE1OTI4NjE5MjE6MncLYWZmaW5lOmxpc3R3CGJ1bGxldGVkeXcMMTU5Mjg2MTkyMToydwwxNTkyODYxOTIxOjN3C2FmZmluZTpsaXN0dwhidWxsZXRlZHl3DDE1OTI4NjE5MjE6M3cMMTU5Mjg2MTkyMToydwwxNTkyODYxOTIxOjN3DFswLDAsNzIwLDY0XXcMWzAsMCw3MjAsMzJddwwxNTkyODYxOTIxOjJ3DDE1OTI4NjE5MjE6M3cMMTU5Mjg2MTkyMToydwwxNTkyODYxOTIxOjN3DFswLDAsNzIwLDY0XXcMMTU5Mjg2MTkyMTo0dwthZmZpbmU6bGlzdHcIYnVsbGV0ZWR5dwwxNTkyODYxOTIxOjR3DFswLDAsNzIwLDk2XXcMMTU5Mjg2MTkyMTozdwwxNTkyODYxOTIxOjQC8eHB%2BA4DAwAZAQLsDOHJxPcFCQBhAwACAAcAAwADFQICCwADAA%3D%3D)

https://user-images.githubusercontent.com/18554747/215348929-8f89a4ae-d3b0-4f62-9b70-0d1c523f7b66.mov

**Comment by himself65** [comment]
must relate with `bringChildrenTo`
