### ISSUE TITLE
Inconsistent frame block height on WebKit

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#902]
On WebKit (Safari), the `xywh` field of frame block has different value with Chromium and Firefox. Since we serialize and compare this field for testing model state, this breaks most of the test cases on Safari 🥵.

See #881 for more information about testing on compatibility.

**Comment by lawvs** [comment]
In most JSX snapshots, we do not care about the `affine:frame` block, so I plan to split `assertStoreMatchJSX` into `assertPaperMatchJSX`(ignore `affine:frame`) and `assertEdgelessMatchJSX`(same as `assertStoreMatchJSX`)

**Comment by fundon** [comment]
When I tested the selection feature in Safari, I found that the height of the block would include the `margin-top` of the first child element.

**Comment by doodlewind** [comment]
This can be closed by #3424 since we are not blocked by related compatibility issue under the hood now. Different height of note (was named frame before) should be acceptable.
