### ISSUE TITLE
Unable to move cursor with `↓` and `↑` in edgeless mode

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#926]
Moving native cursor using ArrowKeys in paragraph and list works fine in page mode, but this breaks edgeless mode at the moment.

**Comment by lawvs** [comment]
The main reason for this problem is the `edgeless-page-block` does not bind ArrowDown and ArrowUp handlers.

Related code can be found in

https://github.com/toeverything/blocksuite/blob/bc20157ed661fc3547b31545b5a0bd02edfeab1d/packages/blocks/src/page-block/utils/bind-hotkey.ts#L9-L39

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/1122
