### ISSUE TITLE
Counter-intuitive select-all behavior

### ISSUE THREAD

**Issue by donaldxdonald** [toeverything/blocksuite#933]
## Expected Behavior
If I press Ctrl/Cmd + A more than three times, I expect all the blocks to still be selected.

## Current Behavior
Pressing Ctrl/Cmd + A three times seems to clear the selection. But when I then press Backspace, all the blocks are deleted.

## Record
![select_all](https://user-images.githubusercontent.com/29999387/216094684-a295b7dd-5230-453c-8a12-0734dc6873ed.gif)

## Solution?
Not sure if this is a feature or bug, but it seems to work for me after removing these codes.
https://github.com/toeverything/blocksuite/blob/892d2f1d6121d401908d44721d45569e20a55c4f/packages/blocks/src/page-block/default/selection-manager.ts#L613-L614

**Comment by himself65** [comment]
I think this is the expected behavior, and I don't feel the counter-intuitive

**Comment by pingren** [comment]
@Himself65 This is unexpected since it unselect all blocks, but the blocks can still be deleted by backspace.

So Either:
1. Press Cmd + A more than two times, all blocks still are selected, and can be deleted by backspace
Or:
2. Fix backspace deletion after all blocks unselected. 

I suggested the first one since it is the most popular editor behavior (Notion, Feishu, etc…)

**Comment by doodlewind** [comment]
> @Himself65 This is unexpected since it unselect all blocks, but the blocks can still be deleted by backspace.
> 
> So Either:
> 
> 1. Press Cmd + A more than two times, all blocks still are selected, and can be deleted by backspace
>    Or:
> 2. Fix backspace deletion after all blocks unselected.
> 
> I suggested the first one since it is the most popular editor behavior (Notion, Feishu, etc…)

See https://github.com/toeverything/blocksuite/issues/839#issuecomment-1411742112 for the thought on product design.

/cc @joebeijing

**Comment by joebeijing** [comment]
@doodlewind Vote for option 1
