### ISSUE TITLE
Stale selection rect after inserting from BlockHub

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#938]
After a block was selected by clicking the block handle and the light-blue selection rectangle showed up, this rect's position will not be correctly updated while inserting new block from the block hub by drag-and-dropping. 

Please see the attached screencast. At the 00:00:05 you will find a glitch: the z-index of selection rect was wrong as it appeared above the block hub menu.

https://user-images.githubusercontent.com/132558/216217505-72bf0583-3415-4ef0-8b71-15e3beedc9f2.mp4

However, inserting new block by clicking the edit area will not bring about this problem because the click action will firstly deselect any existed selection.

**Comment by xell** [comment]
After discussing with @thorseraq we realized that a quick fix would be to cancel the selection **right before** the drag action so you don't have to worry about the new position of the selection rect, which is meaningless while a new bock was being inserted.

**Comment by himself65** [comment]
in our code, we don't have the information that bind a blue rect with a block
