### ISSUE TITLE
Redundant block hub instances exist after editor disposed

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#939]
https://user-images.githubusercontent.com/14026360/216226409-fce7089d-849c-44e8-bfb9-c92c84dfffa3.mp4

**Comment by himself65** [comment]
![img_v2_4e029ede-e923-4a33-aa29-e1477301630g](https://user-images.githubusercontent.com/14026360/216226529-a8b2e599-4b37-43dc-9897-017cfd73adae.jpg)
