### ISSUE TITLE
Press UP / DOWN cursor is lost and throws error

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#968]
When I keep holding the up/down keys, the cursor gets lost and the console throws a bunch of errors.

https://user-images.githubusercontent.com/102217452/216530064-36daf8d0-7df7-4c47-a77b-98dc90d5d22c.mov

**Comment by lawvs** [comment]
Fixed in https://github.com/toeverything/blocksuite/pull/1710

Thanks @Saul-Mirone
