### ISSUE TITLE
Unable to indent multiple blocks under native range selection

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#976]
Pressing Tab to indent fails when I use native range select to select multiple lists.

https://user-images.githubusercontent.com/102217452/216560164-c3817cb9-04a8-4677-be84-b23aa2eee9a2.mov

**Comment by lzlme** [comment]
I want to try to fix this bug.

**Comment by lawvs** [comment]
Thank you very much. If you have any questions about the code or architecture, feel free to ask at any time. @lzlme

**Comment by lzlme** [comment]
I noticed that #1064 has fixed this bug.

**Comment by himself65** [comment]
> I noticed that #1064 has fixed this bug.

Also #1056
