### ISSUE TITLE
Unexpected cursor after indenting multiple list blocks

### ISSUE THREAD

**Issue by JimmFly** [toeverything/blocksuite#978]
When multiple List blocks are selected, pressing the Tab key fails to indent, the cursor moves to the first line and can be edited, the selected area does not disappear, and the selected area can be operated.

https://user-images.githubusercontent.com/102217452/216568113-b946967c-a69c-4021-9de5-53f8f8732ace.mov

**Comment by lawvs** [comment]
I believe this issue has been fixed.
