### ISSUE TITLE
Block selection disappear after scrolling

### ISSUE THREAD

**Issue by pingren** [toeverything/blocksuite#989]
Block selection disappear after scrolling, and it is a temp fix in https://github.com/toeverything/blocksuite/blob/3e6dd8281b9c706448c57ec5e21cfca4f24daadd/packages/blocks/src/page-block/default/default-page-block.ts#L438-L439 to prevent it become misplaced.

The root issue is that block selections are `position:fixed` and will misplace if default viewport width changes or scrolling

https://user-images.githubusercontent.com/5123601/216752351-8c398ab5-0ca0-4094-92aa-c63f14be4cad.mp4

**Comment by fundon** [comment]
In block selection mode, the rects of the selected blocks need to be re-read when the window is resized

**Comment by himself65** [comment]
duplicated, https://github.com/toeverything/blocksuite/issues/330
