### ISSUE TITLE
Pressing escape doesn't cancel current selection state

### ISSUE THREAD

**Issue by gotjoshua** [toeverything/blocksuite#990]
Reproduce:

1. Open playground
2. single click anywhere
3. notice that the selection is following you
4. try to press escape key
5. notice it doesn't work as expected (to stop the selection process)

also:
1. make a selection by dragging over text
2. try to press escape key
3. notice it doesn't work as expected (to remove the selection)

**Comment by doodlewind** [comment]
Closed by #993
