### ISSUE TITLE
Unexpected behavior when create divider in quote

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#995]
https://user-images.githubusercontent.com/18554747/216778779-a101da8c-b819-4054-840f-167bbbd90e39.mov

**Comment by co-decode** [comment]
I'd like to have a crack at this.

In: packages > blocks > src > __internal__ > utils > common-operations.ts > convertToDivider
I've fixed the behavior by:
- changing the model.text.insert index parameter from prefix.length to the length of the text
- changing the model.text?.delete index parameter from 0 to the length of the text minus the length of the prefix + 1

`model.text?.insert(' ', model.text?.length);`
`model.text?.delete(
      model.text?.length - (prefix.length + 1),
      prefix.length + 1
    );`

I'm looking into whether I can add anything to your tests.

I'm new to this, so any pointers would be appreciated.

**Comment by himself65** [comment]
> I'd like to have a crack at this.
> 
> In: packages > blocks > src > **internal** > utils > common-operations.ts > convertToDivider I've fixed the behavior by:
> 
> * changing the model.text.insert index parameter from prefix.length to the length of the text
> * changing the model.text?.delete index parameter from 0 to the length of the text minus the length of the prefix + 1
> 
> `model.text?.insert(' ', model.text?.length);` `model.text?.delete( model.text?.length - (prefix.length + 1), prefix.length + 1 );`
> 
> I'm looking into whether I can add anything to your tests.
> 
> I'm new to this, so any pointers would be appreciated.

I think adding a divider in a quote should be prohibited? Not sure. /cc @doodlewind 

If you want to add a test, please see the `/tests` folder and https://github.com/toeverything/blocksuite/blob/master/BUILDING.md#testing

**Comment by co-decode** [comment]
Yes that would make things simpler.
It is also possible to create a newline in the middle of a quote, and my suggestion above would fail in that case.

Perhaps adding to the conditional like this is enough:
`if (matchFlavours(model, ['affine:divider']) || model.type === 'quote')`

I've also created a new file in the tests folder with a single test called quote.spec.test

`'prohibit creating divider within quote'

**Comment by himself65** [comment]
> Yes that would make things simpler. It is also possible to create a newline in the middle of a quote, and my suggestion above would fail in that case.
> 
> Perhaps adding to the conditional like this is enough: `if (matchFlavours(model, ['affine:divider']) || model.type === 'quote')`
> 
> I've also created a new file in the tests folder with a single test called quote.spec.test
> 
> `'prohibit creating divider within quote'`

you can open a PR first, then we can give a response quickly
