### ISSUE TITLE
Test coverage improvement

### ISSUE THREAD

**Issue by Himself65** [toeverything/blocksuite#999]
There is currently some code that is clearly not covered by the e2e tests.

- [ ] many blocks that in total larger than one window's height
  - [ ] scroll editor
  - [ ] range selection
- [ ] complex interactions between different types of blocks
  - [ ] block selection in embed block with paragraph
- [ ] database block

## Code Coverage CI

- https://github.com/toeverything/blocksuite/issues/1000

**Comment by himself65** [comment]
## Test uncovered PRs

- https://github.com/toeverything/blocksuite/pull/1095
- https://github.com/toeverything/blocksuite/pull/1065
- https://github.com/toeverything/blocksuite/pull/1051

**Comment by doodlewind** [comment]
We've added coverage since #1000 and things turn out to be fine after months of experiment. I'd close this as resolved and track new test coverage related affairs in upcoming issues.
